/* Oliver Kullmann, 4.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Quasigroups/include.mac
  \brief Inclusion of Maxima quasigroup-related functionality

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Quasigroups/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Quasigroups/tests/Basics.mac")$

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Quasigroups/Basics.mac")$


/*!
\endhtmlonly
*/
