#!/bin/bash
# Matthew Gwynne, 11.1.2011 (Swansea)
# Copyright 2011 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.

list_programs="${bin_dir}/QuineMcCluskeySubsumptionHypergraph-n4*"


case ${test_level} in
basic) list_test_cases="$(find app_tests/test_cases/basic/QuineMcCluskeySubsumptionHypergraph/ -name '*.cnf')"
    ;;
full) list_test_cases="$(find app_tests/test_cases/basic/QuineMcCluskeySubsumptionHypergraph/ -name '*.cnf') $(find app_tests/test_cases/full/QuineMcCluskeySubsumptionHypergraph/ -name '*.cnf')"
      list_programs="${list_programs} ${bin_dir}/QuineMcCluskeySubsumptionHypergraph-n16*"
    ;;
extensive) list_test_cases="$(find app_tests/test_cases/basic/QuineMcCluskeySubsumptionHypergraph/ -name '*.cnf') $(find app_tests/test_cases/full/QuineMcCluskeySubsumptionHypergraph/ -name '*.cnf') $(find app_tests/test_cases/extensive/QuineMcCluskeySubsumptionHypergraph/ -name '*.cnf')"
	   list_programs="${list_programs} ${bin_dir}/QuineMcCluskeySubsumptionHypergraph-n16*"
    ;;
esac

echo "PROGRAMS FOUND:"
for P in ${list_programs}; do echo ${P}; done

echo "TEST FORMULAS FOUND:" 
for T in ${list_test_cases}; do echo ${T}; done

echo "EXECUTION OF PROGRAMS:"

match_tool=${bin_dir}/MatchFiles-O3-DNDEBUG

for S in ${list_programs}; do
  echo
  for P in ${list_test_cases}; do
    echo ${S} ${P}
    tmp_primes=$(mktemp)
    output="$(${S} ${P} ${tmp_primes})"
    template="$(dirname ${P})/dimacs_output/$(basename ${P} .cnf)"
    template_primes="$(dirname ${P})/dimacs_output/$(basename ${P} .cnf)_primes"
    echo "${output}" | ${match_tool} "${template}"
    result=$?
    if [[ ${result} != 0 ]]; then
      echo -e "ERROR: OUTPUT of solver is\n${output}\n, while TEMPLATE is"
      cat ${template}; echo; exit 1
    fi
    cat ${tmp_primes} | ${match_tool} "${template_primes}"
    result=$?
    if [[ ${result} != 0 ]]; then
      echo -e "ERROR: AUXILLIARY OUTPUT of solver is\n$(cat ${tmp_primes})\n, while TEMPLATE is"
      cat ${template_primes}; echo; exit 1
    fi
    rm -f ${tmp_primes}
  done
done


exit 0

