#!/bin/bash
# Matthew Gwynne, 11.1.2011 (Swansea)
# Copyright 2011 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.

list_programs="${bin_dir}/QuineMcCluskeySubsumptionHypergraphWithFullStatistics-n4*"


case ${test_level} in
basic) list_test_cases="$(find app_tests/test_cases/basic/QuineMcCluskeySubsumptionHypergraphWithFullStatistics/ -name '*.cnf')"
    ;;
full) list_test_cases="$(find app_tests/test_cases/basic/QuineMcCluskeySubsumptionHypergraphWithFullStatistics/ -name '*.cnf') $(find app_tests/test_cases/full/QuineMcCluskeySubsumptionHypergraphWithFullStatistics/ -name '*.cnf')"
      list_programs="${list_programs} ${bin_dir}/QuineMcCluskeySubsumptionHypergraphWithFullStatistics-n16*"
    ;;
extensive) list_test_cases="$(find app_tests/test_cases/basic/QuineMcCluskeySubsumptionHypergraphWithFullStatistics/ -name '*.cnf') $(find app_tests/test_cases/full/QuineMcCluskeySubsumptionHypergraphWithFullStatistics/ -name '*.cnf') $(find app_tests/test_cases/extensive/QuineMcCluskeySubsumptionHypergraphWithFullStatistics/ -name '*.cnf')"
	   list_programs="${list_programs} ${bin_dir}/QuineMcCluskeySubsumptionHypergraphWithFullStatistics-n16*"
    ;;
esac

echo "PROGRAMS FOUND:"
for P in ${list_programs}; do echo ${P}; done

echo "TEST FORMULAS FOUND:" 
for T in ${list_test_cases}; do echo ${T}; done

echo "EXECUTION OF PROGRAMS:"

match_tool=${bin_dir}/MatchFiles-O3-DNDEBUG

for S in ${list_programs}; do
  echo
  for P in ${list_test_cases}; do
    echo ${S} ${P}
    output="$(${S} ${P})"
    template="$(dirname ${P})/dimacs_output/$(basename ${P} .cnf)"
    template_primes="$(dirname ${P})/dimacs_output/$(basename ${P})_primes"
    template_primes_stats="$(dirname ${P})/dimacs_output/$(basename ${P})_primes_stats"
    template_shg_stats="$(dirname ${P})/dimacs_output/$(basename ${P})_shg_stats"
    echo "${output}" | ${match_tool} "${template}"
    result=$?
    if [[ ${result} != 0 ]]; then
      echo -e "ERROR: OUTPUT of solver is\n${output}\n, while TEMPLATE is"
      cat ${template}; echo; exit 1
    fi
    cat $(basename ${P})_primes | ${match_tool} "${template_primes}"
    result=$?
    if [[ ${result} != 0 ]]; then
      echo -e "ERROR: AUXILLIARY OUTPUT of solver is\n$(cat $(basename ${P})_primes)\n, while TEMPLATE is"
      cat ${template_primes}; echo; exit 1
    fi
    rm -f $(basename ${P})_primes
    cat $(basename ${P})_primes_stats | ${match_tool} "${template_primes_stats}"
    result=$?
    if [[ ${result} != 0 ]]; then
      echo -e "ERROR: AUXILLIARY OUTPUT of solver is\n$(cat $(basename ${P})_primes_stats)\n, while TEMPLATE is"
      cat ${template_primes_stats}; echo; exit 1
    fi
    rm -f $(basename ${P})_primes_stats
    cat $(basename ${P})_shg_stats | ${match_tool} "${template_shg_stats}"
    result=$?
    if [[ ${result} != 0 ]]; then
      echo -e "ERROR: AUXILLIARY OUTPUT of solver is\n$(cat $(basename ${P})_shg_stats)\n, while TEMPLATE is"
      cat ${template_shg_stats}; echo; exit 1
    fi
    rm -f $(basename ${P})_shg_stats
  done
done


exit 0

