/* Oliver Kullmann, 21.11.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Backtracking/testobjects/Learning.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Backtracking/testobjects/ConstraintSatisfaction.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Backtracking/ConstraintSatisfaction.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Backtracking/tests/ConstraintSatisfaction.mac")$


/* ***************
   * Propagators *
   ***************
*/

okltest_constraint_backtracking(constraint_backtracking);

/* ***********
   * Solvers *
   ***********
*/



/* **************
   * Heuristics *
   **************
*/

okltest_test_propagator(test_propagator);

okltest_variable_heuristics_tau(variable_heuristics_tau);


/*!
\endhtmlonly
*/
