/* Oliver Kullmann, 17.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Backtracking/testobjects/DLL_solvers.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Backtracking/testobjects/DLL_solvers.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Backtracking/DLL_solvers.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Backtracking/tests/DLL_solvers.mac")$

/* **********************************
   * Backtracking without reduction *
   **********************************
*/

okltest_dll_simplest(dll_simplest);
okltest_dll_simplest_spa(dll_simplest_spa);

/* ***********************************
   * Backtracking with r_k-reduction *
   ***********************************
*/


/* *****************************************
   * Backtracking with arbitrary reduction *
   *****************************************
*/


/* *******************************
   * Simple heuristics for DLL   *
   *******************************
*/

okltest_choose_most_sat_literal_h(choose_most_sat_literal_h);

okltest_johnson_heuristic(johnson_heuristic);

okltest_dll_heuristics_max_lit_tb(dll_heuristics_max_lit_tb);

/* ****************************
   * Heuristics via distances *
   ****************************
*/


/* *************
   * Distances *    
   *************
*/


/* ***************
   * Projections *
   ***************
*/


/* *********************************
   * Satisfiability approximations *
   *********************************
*/

okltest_locallemma_satapprox(locallemma_satapprox);
okltest_locallemmasum_satapprox(locallemmasum_satapprox);

/*!
\endhtmlonly
*/
