/* Oliver Kullmann, 8.6.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Backtracking/testobjects/Learning.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Backtracking/testobjects/Learning.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Backtracking/Learning.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Backtracking/tests/Learning.mac")$


okltest_basic_learning(basic_learning);

/*!
\endhtmlonly
*/
