/* Oliver Kullmann, 31.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Backtracking/testobjects/SplittingTrees.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Backtracking/testobjects/SplittingTrees.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Backtracking/SplittingTrees.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Backtracking/tests/SplittingTrees.mac")$

okltest_negate_st(negate_st);
okltest_condense_st(condense_st);

okltest_optimal_splitting_tree(optimal_splitting_tree);
okltest_optimal_r_splitting_tree(optimal_r_splitting_tree);

okltest_sat_pass_st(sat_pass_st);
okltest_usat_clauses_st(usat_clauses_st);

/*!
\endhtmlonly
*/
