/* Oliver Kullmann, 26.5.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Matroids/Lisp/Greedoids/Basics.mac
  \brief Basic functionality related to greedoids

Use by

oklib_load("OKlib/ComputerAlgebra/Matroids/Lisp/Greedoids/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$
oklib_include("OKlib/ComputerAlgebra/Matroids/Lisp/Basics.mac")$


/* ***********************
   * Fundamental notions *
   ***********************
*/

/* Checking whether G is a greedoid given by the independent sets: */
grdins_p(M) := hg_p(M) and not emptyp(second(M)) and
 accessible_ss_p(second(M)) and augmentation_ss_p(second(M))$

/*!
\endhtmlonly
*/
