/* Oliver Kullmann, 26.5.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Matroids/Lisp/Greedoids/include.mac
  \brief Inclusion file for Maxima functions related to greedoids

Use by

oklib_load("OKlib/ComputerAlgebra/Matroids/Lisp/Greedoids/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Matroids/Lisp/Greedoids/Basics.mac")$

oklib_include("OKlib/ComputerAlgebra/Matroids/Lisp/Greedoids/tests/Basics.mac")$

/*!
\endhtmlonly
*/
