/* Oliver Kullmann, 23.10.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/testobjects/Constructions.mac

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/testobjects/Constructions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/Constructions.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/tests/Constructions.mac")$

/* *******************
   * Rabung's method *
   *******************
*/

okltest_rabung_valid_param(rabung_valid_param);

okltest_rabung_derived_parameters(rabung_derived_parameters);

okltest_rabung_colouring_map(rabung_colouring_map);

okltest_rabung_attempted_certificate(rabung_attempted_certificate);

okltest_rabung_checkdirect_certificate(rabung_checkdirect_certificate);

okltest_rabung_checkcriterion(rabung_checkcriterion);

okltest_rabung_next_candidates(rabung_next_candidates);

okltest_rabung_search(rabung_search);

okltest_rabung_search_next(rabung_search_next);

/*!
\endhtmlonly
*/
