/* Oliver Kullmann, 12.4.2009 (Swansea) */
/* Copyright 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/testobjects/Numbers.mac

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/testobjects/Numbers.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/Numbers.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/tests/Numbers.mac")$

/* ***************************
   * Van der Waerden numbers *
   ***************************
*/

okltest_vanderwaerden(vanderwaerden);
okltest_vanderwaerden_p(vanderwaerden_p);

/* ************************
   * The transversal case *
   ************************
*/

okltest_vanderwaerdent_a(vanderwaerdent_a);

/* *******************************************************
   * The formula from [Landman, Robertson, Culver, 2005] *
   *******************************************************
*/

okltest_lrc_j(lrc_j);
okltest_lrc_l0p(lrc_l0p);
okltest_lrc_l1p(lrc_l1p);

/* ********************************
   * Generalised transversal case *
   ********************************
*/

okltest_vanderwaerdents_a(vanderwaerdents_a);

/* ******************************************************************
   * Transversal numbers of hypergraphs of arithmetic progresssions *
   ******************************************************************
*/

okltest_alpha_steplist_arithprog_seq(alpha_steplist_arithprog_seq);

/* *********************************
   * Analysing transversal numbers *
   *********************************
*/

okltest_alpha_arithprog(alpha_arithprog);
okltest_alphal_arithprog(alphal_arithprog);

okltest_bestgamma_vdWt(bestgamma_vdWt);
okltest_condition_kl_vdWt(condition_kl_vdWt);

/* ****************************************
   * Checking the consistency of the data *
   ****************************************
*/

if oklib_test_level >= 1 then okltest_consistency_check_1() else true;

/*!
\endhtmlonly
*/
