/* Oliver Kullmann, 7.5.2009 (Swansea) */
/* Copyright 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/GreenTao/include.mac
  \brief Inclusion file for functions related to Green-Tao numbers

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/Asymptotics.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/Numbers.mac")$

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/tests/Numbers.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/tests/Asymptotics.mac")$

/*!
\endhtmlonly
*/
