/* Oliver Kullmann, 15.7.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/Schur/Numbers.mac
  \brief Handling of Schur numbers

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Schur/Numbers.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Ramsey/Numbers.mac")$


/* *****************
   * Schur numbers *
   *****************
*/

/* r is natural numbers >= 1: */
schur(r) := if r <= 4 then [2,5,14,45][r]
 elseif r=5 then [161,306]
 elseif r=6 then [537,1837]
 elseif r=7 then [1681,12860]
 else block([lb : (3^r+1)/2, ub : 3*r!-1,
             rub : ramsey([2,create_list(3,i,1,r)])],
   if rub#unknown then ub : min(ub, rub),
   [lb, ub])$
/* Remarks:
 - This is A030126 in the OEIS (http://oeis.org/A030126).
 - For the general bounds see Theorems 8.8, 8.9 in [Ramsey Theory on the
   Integers; Landman, Robertson].
 - By Corollary 8.6 there we have
     schur(r) <= ramsey([2,create_list(3,i,1,r)]) - 1.
 - For r = 5:
    - For the lower bound see certificates in
      Investigations/RamseyTheory/SchurProblems/plans/general.hpp.
    - The upper bound comes from ramsey([2,[3,3,3,3,3]]) <= 307
      ([Small Ramsey Numbers; Radziszowski, The Electronic Journal of
      Combinatorics, August 22, 2011], Page 34
      http://www.combinatorics.org/ojs/index.php/eljc/article/view/ds1/html).
 - For r = 6:
    - The upper bound comes from ramsey([2,[3,3,3,3,3,3]]) <= 1838
      ([Small Ramsey Numbers; Radziszowski, The Electronic Journal of
      Combinatorics, August 22, 2011].
 - For r = 7:
    - The upper bound comes from ramsey([2,[3,3,3,3,3,3,3]]) <= 12861
      ([Small Ramsey Numbers; Radziszowski, The Electronic Journal of
      Combinatorics, August 22, 2011].

*/


/* *****************************
   * Palindromic Schur numbers *
   *****************************
*/

/* r is natural numbers >= 1: */
pdschur(r) := unknown$



/*!
\endhtmlonly
*/
