/* Oliver Kullmann, 15.7.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/Schur/Numbers.mac
  \brief Handling of Schur numbers

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Schur/Numbers.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Ramsey/Numbers.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$


/* *****************
   * Schur numbers *
   *****************
*/

/* r is natural numbers >= 0: */
schur(r) := if r <= 4 then [1,2,5,14,45][r+1]
 elseif r=5 then [161,306]
 elseif r=6 then [537,1837]
 elseif r=7 then [1681,12860]
 else block([lb : max(3^(r-7)*(1681-1/2)+1/2,ceiling(44/89*89^(r/4))),
             ub : floor(r!*%e),
             rub : ramsey([2,create_list(3,i,1,r)])],
   if rub#unknown then ub : min(ub, rub-1),
   [lb, ub])$
/* Remarks:
 - This is A030126 in the OEIS (http://oeis.org/A030126).
 - For the general bounds see Theorems 8.8, 8.9 and Corollary 8.6 in
   [Ramsey Theory on the Integers; Landman, Robertson].
 - Schur showed that schur(r) >= 3*schur(r-1)-1 for r >= 1.
   The sequence s(r) := 3*s(r-1)-1 has the law s(r) = 3^r*(s(0)-1/2)+1/2.
   Since for r=7 we have the last concrete bound, we set s(0) = 1681.
 - For r = 5:
    - For the lower bound see certificates in
      Investigations/RamseyTheory/SchurProblems/plans/general.hpp.
    - The upper bound comes from ramsey([2,[3,3,3,3,3]]) <= 307
      ([Small Ramsey Numbers; Radziszowski, The Electronic Journal of
      Combinatorics, August 22, 2011], Page 34
      http://www.combinatorics.org/ojs/index.php/eljc/article/view/ds1/html).
 - For r = 6:
    - The upper bound comes from ramsey([2,[3,3,3,3,3,3]]) <= 1838
      ([Small Ramsey Numbers; Radziszowski, The Electronic Journal of
      Combinatorics, August 22, 2011]).
 - For r = 7:
    - The upper bound comes from ramsey([2,[3,3,3,3,3,3,3]]) <= 12861
      ([Small Ramsey Numbers; Radziszowski, The Electronic Journal of
      Combinatorics, August 22, 2011]).

*/


/* **********************
   * Weak Schur numbers *
   **********************
*/

/* r is natural numbers >= 0: */
wschur(r) := if r <= 4 then [1,3,9,24,67][r+1]
 elseif r=5 then [190,1631]
 elseif r=6 then [573,11743]
 else block([lb : firste(schur(r)), ub : floor(r!*r*%e)+1,
             rub : ramsey([2,create_list(4,i,1,r)])],
   if rub#unknown then ub : min(ub, rub-1),
   rub : ramsey([2,create_list(3,i,1,2*r)]),
   if rub#unknown then ub : min(ub, rub-1),
   [lb, ub])$


/* *****************************
   * Palindromic Schur numbers *
   *****************************
*/

/* r is natural numbers >= 0: */
pdschur(r) := if r <= 4 then [[{},1],[{},2],[{},5],[{},14],[{},45]][r+1]
 elseif r=5 then [{[158]},[161,306]]
 else unknown$


/* r is natural numbers >= 0: */
pdwschur(r) := if r <= 4 then [[{},1],[{},3],[{},6],[{},14],[{45,46},48]][r+1]
 elseif r=5 then [{[158]},[161,1631]]
 else unknown$
/* Note that if a palindromic (ordinary) Schur-instance is known to be
   satisfiable for n mod 3 # 2, then also the weak palindromic Schur-instance
   for that n is satisfiable.
*/

/*!
\endhtmlonly
*/
