/* Oliver Kullmann, 29.5.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/tests/Numbers.mac
  \brief Tests for general functions regarding Ramsey-type numbers

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/tests/Numbers.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

/* We use the following properties of inf: */
okltest_inf_properties() := block([x],
  assert(inf-1 < inf),
  assert(10 < inf-1),
  assert(x < inf-1),
  true)$


/*!
\endhtmlonly
*/
