/* Oliver Kullmann, 23.4.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/tests/Sequences.mac
  \brief Tests for functions handling sequences

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/tests/Sequences.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

/* ****************
   * Transformers *
   ****************
*/

okltest_transform_threshold_l(f) := (
  assert(f([]) = []),
  assert(f([0]) = [1]),
  assert(f([0,1]) = [1,2]),
  assert(f([1,3]) = [0,1,1,2]),
  assert(f([1,3,6]) = [0,1,1,2,2,2,3]),
  assert(f([1,3,6,[],[1]]) = [0,1,1,2,2,2,3]),
  assert(f([[],1]) = []),
  for m : 0 thru 6 do
    assert(f([m]) = endcons(1,create_list(0,i,1,m))),
  for m : 0 thru 6 do
    assert(f(create_list(i,i,0,m-1)) = create_list(i,i,1,m)),
  for m : 1 thru 6 do
    assert(f(create_list(i,i,1,m)) = create_list(i,i,0,m)),
  true)$

okltest_transform_steps_l(f) := block([LT],
  assert(f([]) = []),
  assert(f([0]) = []),
  assert(f([0,0]) = []),
  assert(f([1,1,1]) = []),
  assert(f([0,0,0,1,1,2]) = [3,5]),
  assert(f([1,1,1,2,2,3]) = [3,5]),
  LT : [[],[1],[2],[3],[1,2],[1,3],[1,4],[1,4,6,8,11]],
  for L in LT do
    assert(f(transform_threshold_l(L)) = L),
  LT = [[],[0,1],[0,0,1],[0,0,1,1],[0,1,2,2,2,3],[0,1,2,2,3,3,3,4]],
  for L in LT do
    assert(f(transform_threshold_l(L)) = L),
  true)$

okltest_alphastep2tau(f) := (
  assert(f([1]) = [0]),
  assert(f([2]) = [1,1]),
  assert(f([3]) = [1,2,2]),
  assert(f([1,2]) = [0,0]),
  assert(f([1,3]) = [0,1,1]),
  /* XXX */
  true)$

okltest_tau2alphastep(f) := (
  assert(f([0]) = [1]),
  assert(f([0,1,2]) = [1]),
  /* XXX */
  true)$


/* ************
   * Analysis *
   ************
*/



/*!
\endhtmlonly
*/
