/* Oliver Kullmann, 12.7.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators/Hindman.mac
  \brief Maxima functions for generating hypergraphs

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Hindman.mac");

*/

/*!
\htmlonly
*/


/* *****************
   * Hindman quads *
   *****************
*/

hindmanquads_degenerated_ohg(n) := 
 [create_list(i,i,1,n),
  append(create_list({1,y,1+y},y,1,n-1),
    create_list({x,y,x+y,x*y}, x,2,floor(sqrt(n)), y,x,floor(n/x)))]$

hindmanquads_ohg(n) := 
 [create_list(i,i,1,n),
  append(create_list({1,y,1+y},y,2,n-1),
    create_list({x,y,x+y,x*y}, x,2,floor(sqrt(n)), y,x+1,floor(n/x)))]$

/* Prerequisite: a >= 1 */
hindmanquadsgen_degenerated_ohg(a,n) := [create_list(i,i,a,n),
 block([M : create_list({x,y,x+y,x*y}, x,max(a,2),floor(sqrt(n)), y,x,floor(n/x))],
  if a >= 2 then M else
   append(create_list({1,y,1+y},y,1,n-1),M))]$

hindmanquadsgen_ohg(a,n) := [create_list(i,i,a,n),
 block([M : create_list({x,y,x+y,x*y}, x,max(a,2),floor(sqrt(n)), y,x+1,floor(n/x))],
  if a >= 2 then M else
   append(create_list({1,y,1+y},y,2,n-1),M))]$



hindman_ohg(k,n) := block([])$
hindmani_ohg(k,n) := block([])$
genhindman_ohg(a,k,n) := block([])$
genhindmani_ohg(a,k,n) := block([])$

/*!
\endhtmlonly
*/

