/* Oliver Kullmann, 12.7.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators/Rado.mac
  \brief Maxima functions for generating hypergraphs

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Rado.mac");

*/

/*!
\htmlonly
*/

/* Vertices are {1,...,n}, hyperedges are the underlying sets of p-tuples
   x with A * x = 0.
*/
/* Prerequisites: A is an integer r x p matrix, n a natural number >= 0. */
rado_ohg(A,n) := []$
/* The variation where all components of x must be distinct (i.e., all
   hyperedges have length (exactly) p):
*/
radoi_ohg(A,n) := []$


/*!
\endhtmlonly
*/

