/* Oliver Kullmann, 6.7.2008 (Swansea) */
/* Copyright 2008, 2009, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Groups/CyclicGroups.mac
  \brief Implementing cyclic groups

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Groups/CyclicGroups.mac");

*/

/*!
\htmlonly
*/

/* The residue class rings ZZ_n are defined as "residues_rng(n)" in
   ComputerAlgebra/Algebra/Lisp/Ringframes/Rings/ResidueClasses.mac.
*/

oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Ringframes/Rings/ResidueClasses.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Ringframes/BasicNotions.mac")$

/* Cyclic groups of order n (n >= 1), where the operation also allows as
   inputs arbitrary integers (which are interpreted as representing their
   congruence classes):
*/
cyclic_ugrp(n) := rngfrm2egrd_add(residues_rng(n))$
cyclic_ougrp(n) := [create_list(i,i,0,n-1), mod_add(n), 0]$


/*!
\endhtmlonly
*/
