/* Oliver Kullmann, 6.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Groups/CyclicGroups.mac
  \brief Implementing cyclic groups

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Groups/CyclicGroups.mac");

*/

/*!
\htmlonly
*/

/* The residule class rings ZZ_n are defined as "residues_rng(n)" in
   ComputerAlgebra/Algebra/Lisp/Ringframes/Rings/ResidueClasses.mac.
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Ringframes/Rings/ResidueClasses.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Ringframes/BasicNotions.mac")$


cyclic_grpn(n) := rngfrm2egrd_add(residues_rng(n))$


/*!
\endhtmlonly
*/
