/* Oliver Kullmann, 5.12.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Groups/LinearGroups.mac
  \brief Functions regarding linear groups

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Groups/LinearGroups.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$


/* The order of the linear group GL(n,q) of dimension n over a field with q
   elements (n >= 0, q a prime-power):
*/
order_gl(n,q) := prod_l(create_list(q^n - q^(k-1), k,1,n))$
/* Remarks: This is the number of invertible square matrices of order n
   over a field with q elements. The function can be applied to arbitrary
   integral n and arbitrary terms q.
*/

/*!
\endhtmlonly
*/
