/* Oliver Kullmann, 6.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/tests/BasicNotions.mac
  \brief Tests for the basic groupoid-notions

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/BasicExamples.mac");
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Constructions.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/LatinSquares.mac")$

kill(f)$

/* ************************************
   * Checking the defining properties *
   ************************************
*/

okltest_compo_p(f) := (
  assert(f(identity,{}) = true),
  assert(f("+",{0}) = true),
  assert(f("+",{0,1}) = false),
  assert(f("*",{0,1,-1}) = true),
  assert(f("*",{0,1,-1,x}) = false),
  assert(f(0,{1}) = false),
  assert(f({},{1}) = false),
  assert(f(lambda([x,y],[1]),{[1]}) = true),
  true)$


okltest_grd_p(f) := (
  assert(f(0) = false),
  assert(f({}) = false),
  assert(f([]) = false),
  assert(f([{}]) = false),
  assert(f([{},{}]) = true),
  assert(f([{1},{}]) = false),
  assert(f(empty_sgr) = true),
  assert(f(singleton_sgr) = true),
  assert(f(non_assoc_2_grd) = true),
  true)$

okltest_ugrd_p(f) := (
  /* XXX */
  true)$

okltest_cgrd_p(f) := (
  /* XXX */
  true)$

okltest_cugrd_p(f) := (
  /* XXX */
  true)$


okltest_sgr_p(f) := (
  assert(f(0) = false),
  assert(f({}) = false),
  assert(f([]) = false),
  assert(f([{}]) = false),
  assert(f([{},{}]) = true),
  assert(f([{1},{}]) = false),
  assert(f(empty_sgr) = true),
  assert(f(singleton_sgr) = true),
  assert(f(non_assoc_2_grd) = false),
  assert(f(null_sgr({1,2},1)) = true),
  assert(f(leftnull_sgr({1,2,3})) = true),
  assert(f(rightnull_sgr({-1,2,-3})) = true),
  true)$

okltest_csgr_p(f) := (
  /* XXX */
  true)$

okltest_mon_p(f) := (
  /* XXX */
  true)$

okltest_cmon_p(f) := (
  /* XXX */
  true)$


/* Remark: The semantics of okltest_qgrp_p is identical with that of
   okltest_ls_p. Currently all tests are handled by okltest_ls_p.
*/
okltest_qgrp_p(f) := (
  assert(okltest_ls_p(f)),
  true)$

okltest_cqgrp_p(f) := (
  /* XXX */
  true)$

okltest_lop_p(f) := (
  /* XXX */
  true)$

okltest_clop_p(f) := (
  /* XXX */
  true)$


okltest_grp_p(f) := (
  /* XXX */
  true)$

okltest_cgrp_p(f) := (
  /* XXX */
  true)$

okltest_grpn_p(f) := (
  /* XXX */
  true)$

okltest_cgrpn_p(f) := (
  /* XXX */
  true)$

okltest_grpni_p(f) := (
  /* XXX */
  true)$

okltest_cgrpni_p(f) := (
  /* XXX */
  true)$


/* *********************
   * Checking equality *
   *********************
*/

okltest_grd_equalp(f) := (
  assert(f(empty_sgr,empty_sgr) = true),
  assert(f(empty_sgr,singleton_sgr) = false),
  assert(f(singleton_sgr,empty_sgr) = false),
  assert(f(singleton_sgr,singleton_sgr) = true),
  assert(f(null_sgr({1},1),null_sgr({1},1)) = true),
  assert(f(null_sgr({1},1),null_sgr({2},2)) = false),
  assert(f(null_sgr({1,2},2),null_sgr({2},2)) = false),
  assert(f(leftnull_sgr({1}),rightnull_sgr({1})) = true),
  assert(f(leftnull_sgr({1}),rightnull_sgr({2})) = false),
  assert(f(leftnull_sgr({1,2}),rightnull_sgr({1,2})) = false),
  true)$

okltest_ugrd_equalp(f) := (
  /* XXX */
  true)$


/* *************
   * Downcasts *
   *************
*/

okltest_ugrd2grd(f) := (
  /* XXX */
  true)$

okltest_grpni2grpn(f) := (
  /* XXX */
  true)$

okltest_grpni2grp(f) := (
  /* XXX */
  true)$

okltest_grpn2grp(f) := (
  /* XXX */
  true)$


/* **************
   * Promotions *
   **************
*/


/*!
\endhtmlonly
*/
