/* Oliver Kullmann, 7.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Closures.mac
  \brief Tests for the basic groupoid-notions

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Closures.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/TransformationMonoids.mac")$

kill(f)$

/* Testing whether f(compo,S) computes the closure of set S under the
   law of composition compo: */
okltest_closure_grd(f) := (
  assert(f(0,{}) = {}),
  assert(f(transformation_l_compo,{}) = {}),
  assert(f(transformation_l_compo,{[]}) = {[]}),
  assert(f(transformation_l_compo,{[2,3,1]}) = {[1,2,3],[2,3,1],[3,1,2]}),
  true)$

/*!
\endhtmlonly
*/
