/* Oliver Kullmann, 19.9.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Commutativity.mac
  \brief Tests for the functions related to commutativity in groupoids

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Commutativity.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/BasicExamples.mac")$

kill(f)$


/* *********
   * Tests *
   *********
*/



/* ********************
   * Central elements *
   ********************
*/

okltest_central_grd_p(f) := block([G],
  assert(f(singleton_mon[3],singleton_mon[1],singleton_mon[2]) = true),
  G : null_sgr({0,1},0),
  assert(f(0,G[1],G[2]) = true),
  assert(f(1,G[1],G[2]) = true),
  G : leftnull_sgr({0,1}),
  assert(f(0,G[1],G[2]) = false),
  assert(f(1,G[1],G[2]) = false),
  /* XXX */
  true)$


/*!
\endhtmlonly
*/
