/* Oliver Kullmann, 7.7.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Constructions.mac
  \brief Tests for the basic groupoid-notions

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Constructions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/TransformationMonoids.mac")$

kill(f)$

/* ***********************
   * Complex composition *
   ***********************
*/

okltest_complex_compo(f) := block([C],
  C : f("+"),
  assert(C({},{}) = {}),
  assert(C({},{0}) = {}),
  assert(C({0},{}) = {}),
  assert(C({0},{1,2}) = {1,2}),
  assert(C({1,2},{0}) = {1,2}),
  assert(C({1,2,3},{-1,0,1}) = {1,2,3,0,4}),
  C : f("["),
  assert(C({},{}) = {}),
  assert(C({},{0}) = {}),
  assert(C({0},{}) = {}),
  assert(C({0},{1,2}) = {[0,1],[0,2]}),
  assert(C({1,2},{0}) = {[1,0],[2,0]}),
  assert(C({1,2},{3,4}) = {[1,3],[1,4],[2,3],[2,4]}),
  C : f(transformation_l_compo),
  assert(C({},{}) = {}),
  assert(C({},{[]}) = {}),
  assert(C({[]},{[]}) = {[]}),
  assert(C({[1,3,2],[2,1,3]},{[2,1,3],[1,3,2]}) = {[3,1,2],[1,2,3],[2,3,1]}),
  true)$

okltest_complex_grd(f) := (
  /* XXX */
  true)$


/* *********************
   * Product groupoids *
   *********************
*/

okltest_product_compo(f) := (
  /* XXX */
  true)$

okltest_product_grd(f) := (
  /* XXX */
  true)$


/* *****************
   * Transposition *
   *****************
*/

okltest_transposed_compo(f) := (
  /* XXX */
  true)$

okltest_transposed_grd(f) := (
  /* XXX */
  true)$

okltest_transposed_ugrd(f) := (
  /* XXX */
  true)$


/*!
\endhtmlonly
*/
