/* Oliver Kullmann, 14.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Idempotency.mac
  \brief Tests regarding idempotent elements in groupoids

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Idempotency.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/BasicExamples.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/BasicNotions.mac")$

kill(f)$


okltest_idempotent_el_grd(f) := (
  assert(f(singleton_sgr,1) = true),
  for x in {1,2,3} do block([V : leftnull_sgr({1,2,3})],
    assert(f(V,x) = true)),
  for x in {1,2,3} do block([V : rightnull_sgr({1,2,3})],
    assert(f(V,x) = true)),
  true)$

okltest_has_idempotent_el_grd(f) := (
  assert(f(empty_sgr) = false),
  assert(f(singleton_sgr) = true),
  assert(f(leftnull_sgr({1,2,3})) = true),
  assert(f(rightnull_sgr({1,2,3})) = true),
  assert(f(null_sgr({1,2,3},1)) = true),
  assert(f(scom2grd(m2scom(matrix([2,1],[2,1])))) = false),
  true)$

okltest_idempotent_bydef_grd(f) := (
  assert(f(empty_sgr) = true),
  assert(f(singleton_sgr) = true),
  assert(f(leftnull_sgr({1,2,3})) = true),
  assert(f(rightnull_sgr({1,2,3})) = true),
  assert(f(null_sgr({1,2,3},1)) = false),
  assert(f(scom2grd(m2scom(matrix([2,1],[2,1])))) = false),
  true)$

okltest_idempotents_grd(f) := (
  okltest_idempotent_el_grd(buildq([f], lambda([V,x], elementp(x,f(V))))),
  okltest_has_idempotent_el_grd(buildq([f], lambda([V], not emptyp(f(V))))),
  okltest_idempotent_bydef_grd(buildq([f], lambda([V], is(f(V) = V[1])))),
  assert(f(null_sgr({1,2,3},2)) = {2}),
  true)$

/*!
\endhtmlonly
*/
