#!/bin/bash
# Oliver Kullmann, 25.8.2012 (Swansea)
# Copyright 2012, 2013, 2021 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version.

set -o errexit
set -o nounset

script_name="SelectExtractionTool"
version_number=0.0.8

if ([ $# -ne 1 ]) then
  echo -e "ERROR[${script_name}]: Exactly one parameter is needed,"\
    "the string with the solver-call."
  exit 1
fi

solver_call=$1

if [[ ${solver_call} =~ ^minisat ]]; then
  echo "ExtractMinisat"
elif [[ ${solver_call} =~ ^OKsolver ]]; then
  echo "ExtractOKsolver"
elif [[ ${solver_call} =~ ^glucose ]]; then
  echo "ExtractGlucose"
elif [[ ${solver_call} =~ ^satz ]]; then
  echo "ExtractSatz"
elif [[ ${solver_call} =~ ^tawSolver ]] ||\
     [[ ${solver_call} =~ ^ctawSolver ]] ||\
     [[ ${solver_call} =~ ^mtawSolver ]] ||\
     [[ ${solver_call} =~ ^ttawSolver ]] ||\
     [[ ${solver_call} =~ ^cttawSolver ]] ||\
     [[ ${solver_call} =~ ^mttawSolver ]]; then
  echo "ExtractTawSolver"
elif [[ ${solver_call} =~ ^march_pl ]]; then
  echo "ExtractMarchpl"
elif [[ ${solver_call} =~ ^precosat ]]; then
  echo "ExtractPrecosat570"
elif [[ ${solver_call} =~ ^picosat ]]; then
  echo "ExtractPicosat"
elif [[ ${solver_call} =~ ^cryptominisat ]]; then
  echo "ExtractCryptominisat"
elif [[ ${solver_call} =~ ^lingeling ]]; then
  echo "ExtractLingeling"
elif [[ ${solver_call} =~ ^MapleLCMDistChrBtDLv3 ]]; then
  echo "ExtractMapleLCMDistChrBtDLv3"
else
  echo "UNKNOWN"
fi

exit 0
