/* Oliver Kullmann, 26.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/tests/Colouring.mac
  \brief Tests for graph-colouring functions

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/tests/Colouring.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Basic.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Generators.mac")$
oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$


kill(f)$

okltest_chromatic_number_gr(f) := block(
  assert(f([{},{}]) = 0),
  assert(f([{1},{}]) = 1),
  assert(f([{1,2},{}]) = 1),
  assert(f([{1,2},{{1,2}}]) = 2),
  for n : 0 thru 3 do
    assert(f(complete_g(setn(n))) = n),
  for n : 3 thru 6 do
   for m : 2 thru (n+1)/2 do
    assert(f(knesergraph_g(n,m)) = n - 2 * m + 2),
  true);

/*!
\endhtmlonly
*/
