/* Oliver Kullmann, 27.11.2011 (Swansea) */
/* Copyright 2011, 2018 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/tests/Basic.mac
  \brief Tests for basic graph functionality

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/tests/Connectedness.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

okltest_concom_g(f) := (
  assert(f([{},{}]) = {}),
  assert(f([{1},{}]) = {{1}}),
  assert(f([{1,2},{}]) = {{1},{2}}),
  assert(f([{1,2},{{1,2}}]) = {{1,2}}),
  assert(f([{1,2,3,4},{{1,2},{3,4}}]) = {{1,2},{3,4}}),
  assert(f([{{1},{2},{3},{4}}, {{{1},{2}},{{1},{3}}}]) = {{{1},{2},{3}},{{4}}}),
  true)$

okltest_allpaths_dg(f) := (
  assert(f([{1,2},{}],1,2) = {}),
  assert(f([{1},{}],1,1) = {{}}),
  assert(f([{1,2},{[1,2]}],1,2) = {{[1,2]}}),
  assert(f([{1,2},{[2,1]}],1,2) = {}),
  assert(f([{1,2,3,4},{[1,2],[1,3],[2,4],[3,4]}],1,4) = {{[1,2],[2,4]},{[1,3],[3,4]}}),
  true)$

okltest_allcycles_dg(f) := (
  assert(f([{},{}]) = {}),
  assert(f([{1,2},{[1,2],[2,1]}]) = {{[1,2],[2,1]}}),
  assert(f([{1,2,3,4}, {[1,2],[2,1],[2,3],[3,1]}]) = {{[1,2],[2,1]}, {[1,2],[2,3],[3,1]}}),
  true)$

okltest_chordless_dg_p(f) := (
  assert(f({},[{},{}]) = true),
  assert(f({[1,2],[2,3],[3,1]}, [{1,2,3},{[1,2],[2,3],[3,1]}]) = true),
  assert(f({[1,2],[2,3],[3,1]}, [{1,2,3},{[1,2],[2,3],[3,1],[1,3]}]) = false),
  true)$

okltest_all_chordless_cycles_dg(f) := (
  assert(f([{},{}]) = {}),
  assert(f([{1,2,3,4,5,6}, {[1,2],[2,3],[3,4],[4,1],[3,6],[6,1]}]) = {{[1,2],[2,3],[3,4],[4,1]},{[1,2],[2,3],[3,6],[6,1]}}),
  true)$

/*!
\endhtmlonly
*/
