/* Oliver Kullmann, 27.11.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/tests/Basic.mac
  \brief Tests for basic graph functionality

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/tests/Connectedness.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

okltest_concom_g(f) := (
  assert(f([{},{}]) = {}),
  assert(f([{1},{}]) = {{1}}),
  assert(f([{1,2},{}]) = {{1},{2}}),
  assert(f([{1,2},{{1,2}}]) = {{1,2}}),
  assert(f([{1,2,3,4},{{1,2},{3,4}}]) = {{1,2},{3,4}}),
  assert(f([{{1},{2},{3},{4}}, {{{1},{2}},{{1},{3}}}]) = {{{1},{2},{3}},{{4}}}),
  true)$

/*!
\endhtmlonly
*/
