/* Matthew Gwynne, 24.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/tests/Statistics.mac
  \brief Tests for graph statistics

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/tests/Statistics.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Basic.mac")$

kill(f)$

okltest_vertex_degrees_g(f) := block(
  assert(hm2sm(f([{},{}])) = {}),
  assert(hm2sm(f([{1},{}])) = {[1,0]}),
  assert(hm2sm(f([{1,2},{}])) = {[1,0],[2,0]}),
  assert(hm2sm(f([{1,2},{{1,2}}])) = {[1,1],[2,1]}),
  assert(hm2sm(f([{1,2,3,4,5,6},{{1,2},{3,2},{2,4},{4,5},{4,6}}])) =
    {[1,1],[3,1],[2,3],[4,3],[5,1],[6,1]}),
  true)$

okltest_vertex_degrees_og(f) := block(
  assert(hm2sm(f([[],[]])) = {}),
  assert(hm2sm(f([[1],[]])) = {[1,0]}),
  assert(hm2sm(f([[1,2],[]])) = {[1,0],[2,0]}),
  assert(hm2sm(f([[1,2],[[1,2]]])) = {[1,1],[2,1]}),
  assert(hm2sm(f([[1,2,3,4,5,6],[[1,2],[3,2],[2,4],[4,5],[4,6]]])) =
    {[1,1],[3,1],[2,3],[4,3],[5,1],[6,1]}),
  true)$

okltest_min_vertex_degree_v_og(f) := block(
  assert(f([[],[]]) = [inf]),
  assert(f([[1],[]]) = [0,1]),
  assert(f([[1,2],[]]) = [0,1]),
  assert(f([[2,1],[]]) = [0,2]),
  assert(f([[1,2],[{1,2}]]) = [1,1]),
  assert(f([[2,1],[{1,2}]]) = [1,2]),
  assert(f([[1,2,3,4,5,6],[{1,2},{3,2},{2,4},{4,5},{4,6}]]) =
    [1,1]),
  assert(f([[1,2,3,4,5,6],[{1,2},{3,1},{1,4},{4,5},{4,6}]]) =
    [1,2]),
  assert(f([[3,2,1,4,5,6],[{1,2},{3,1},{1,4},{4,5},{4,6}]]) =
    [1,3]),
  assert(f([[1,2,3,4,5,6,7],[{1,2},{3,2},{2,4},{4,5},{4,6}]]) =
    [0,7]),
  true)$

okltest_vertex_degrees_hm_g(f) := block(
  assert(hm2sm(f([{},{}])) = {}),
  assert(hm2sm(f([{1},{}])) = {[0,1]}),
  assert(hm2sm(f([{1,2},{}])) = {[0,2]}),
  assert(hm2sm(f([{1,2},{{1,2}}])) = {[1,2]}),
  assert(hm2sm(f([{1,2,3,4,5,6},{{1,2},{3,2},{2,4},{4,5},{4,6}}])) =
    {[1,4],[3,2]}),
  true)$



/*!
\endhtmlonly
*/
