/* Oliver Kullmann, 27.1.2008 (Swansea) */
/* Copyright 2008, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Resolution/include.mac
  \brief Inclusion file for Maxima resolution-related functions

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/Graphs.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/Proofs.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/Search.mac")$

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/tests/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/tests/Graphs.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/tests/Proofs.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/tests/Search.mac")$

/*!
\endhtmlonly
*/
