/* Oliver Kullmann, 3.2.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Transversals/testobjects/Basics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/tests/Basics.mac")$


okltest_transversal_p(transversal_p);
okltest_etransversal_p(etransversal_p);

/* ************************
   * Greedy approximation *
   ************************
*/

okltest_greedy_transversal_ohg(greedy_transversal_ohg);
okltest_greedy_transversal_(greedy_transversal_);

/*!
\endhtmlonly
*/
