/* Oliver Kullmann, 3.2.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Transversals/testobjects/Transversals.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/testobjects/Transversals.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/Transversals.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/tests/Transversals.mac")$


okltest_transversal_p(transversal_p);
okltest_etransversal_p(etransversal_p);

/* ************************************
   * Finding all minimal transversals *
   ************************************
*/

okltest_transversal_hyp(transversal_hyp_rs);

/* *************************************
   * Finding size-bounded transversals *
   *************************************
*/

okltest_transversals_be(transversals_be);
okltest_transversals_be(transversals_bes);

okltest_minimum_transversals_mongen(minimum_transversals_mongen);

okltest_minimum_transversals_lbbvs_hg(minimum_transversals_lbbvs_hg);
okltest_minimum_transversals_bvs_hg(minimum_transversals_bvs_hg);

/*!
\endhtmlonly
*/
