/* Oliver Kullmann, 7.6.2008 (Swansea) */
/* Copyright 2008, 2009, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/NumberTheory/Lisp/include.mac
  \brief Inclusion file for Maxima number theory functions

Use by

oklib_load("OKlib/ComputerAlgebra/NumberTheory/Lisp/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/Auxiliary.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/CalkinWilf.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/ModularArithmetic.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/PrimeNumbers.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/Quadratics.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/SurrealNumbers.mac")$

oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/Auxiliary.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/CalkinWilf.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/ModularArithmetic.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/PrimeNumbers.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/Quadratics.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/SurrealNumbers.mac")$


/*!
\endhtmlonly
*/

