/* Oliver Kullmann, 20.6.2009 (Swansea) */
/* Copyright 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Transversals/Bounded/testobjects/MaintainingBound.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/Bounded/testobjects/MaintainingBound.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/Bounded/MaintainingBound.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/Bounded/tests/MaintainingBound.mac")$

/* *************************************
   * Finding size-bounded transversals *
   *************************************
*/

okltest_transversals_be(transversals_be);
okltest_transversals_be(transversals_bes);

okltest_minimum_transversals_lbbvs_hg(minimum_transversals_lbbvs_hg);
okltest_minimum_transversals_bvs_hg(minimum_transversals_bvs_hg);

/* *********************************
   * Monotone hypergraph sequences *
   *********************************
*/

okltest_minimum_transversals_mongen(minimum_transversals_mongen);

/* *********************************
   * Stratification of hypergraphs *
   *********************************
*/


/*!
\endhtmlonly
*/
