/* Oliver Kullmann, 16.5.2019 (Swansea) */
/* Copyright 2019 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Quantification/include.mac
  \brief Inclusion file for Maxima functions related to QBF

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Quantification/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Quantification/DQCNF.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Quantification/RandomQCNF.mac")$


/*
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Quantification/tests/DQCNF.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Quantification/tests/RandomQCNF.mac")$
*/

/*!
\endhtmlonly
*/
