#!/bin/bash
# Matthew Gwynne, 24.1.2012 (Swansea)
# Copyright 2012 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version.

# set -o errexit # currently "find" creates an error due to non-existing directories, and also the match-program might fail
set -o nounset

list_programs="${public_bin_dir_okl}/RandomDESTotalAssignment"
app_test_dir=${OKlib}/Experimentation/Investigations/Cryptography/DataEncryptionStandard/app_tests/

echo "PROGRAMS FOUND:"
for P in ${list_programs}; do echo ${P}; done

cd ${app_test_dir}

case ${test_level} in
basic) list_test_cases="$(find test_cases/basic/RandomDESTotalAssignment/input/ -maxdepth 1 -mindepth 1 -type d)"
    ;;
full) list_test_cases="$(find test_cases/basic/RandomDESTotalAssignment/input/ -maxdepth 1 -mindepth 1 -type d) $(find test_cases/full/RandomDESTotalAssignment/input/ -maxdepth 1 -mindepth 1 -type d)"
    ;;
extensive) list_test_cases="$(find test_cases/basic/RandomDESTotalAssignment/input/ -maxdepth 1 -mindepth 1 -type d) $(find test_cases/full/RandomDESTotalAssignment/input/ -maxdepth 1 -mindepth 1 -type d) $(find test_cases/extensive/RandomDESTotalAssignment/input/ -maxdepth 1 -mindepth 1 -type d)"
    ;;
esac


# Each test is a directory with a "generate" script to generate the DES instance, and a file "params"
# containing the parameters (instance filename, seed, and number of rounds) for RandomDESTotalAssignment.
# The generate script is expected to delete all temporary files, except the instance file.


echo
echo
echo "TEST SCRIPT: $0"

echo "TEST FORMULAS FOUND:"
for T in ${list_test_cases}; do echo ${T}; done
echo "MATCHING: PROGRAM OUTPUT against app_tests/test_cases/TEST_LEVEL/RandomDESTotalAssignment/dimacs_output/FORMULA_BASENAME."
echo "EXECUTION OF PROGRAMS:"

match_tool=${bin_dir}/MatchFiles-O3-DNDEBUG

for S in ${list_programs}; do
  echo
  for P in ${list_test_cases}; do
    echo "  $(basename ${S}) ${P}/*"

    generate_script="${P}/generate"
    params_file="${P}/params"
    instance_name=$(cat ${params_file} | awk ' { print $1; }')

    # Generate the instance file
    bash ${generate_script}

    output="$(cat ${P}/params | xargs ${S})"
    template="$(dirname ${P})/../output/$(basename ${P})"
    echo "${output}" | ${match_tool} "${template}"
    result=$?
    if [[ ${result} != 0 ]]; then
      echo -e "ERROR: OUTPUT of solver is\n${output}\n, while TEMPLATE is"
      cat ${template}; echo;
      rm ${instance_name}
      exit 1
    fi

    rm ${instance_name}
  done
done

exit 0

