#!/bin/bash
# Oliver Kullmann, 26.11.2010 (Swansea)
# Copyright 2010, 2011 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.

# "RunPdVdW3k k alg runs cutoff" creates a directory
# "Exp_PdVanderWaerden_2-3-k_alg-runs-cutoff_date", where the SAT instances
# VanDerWaerden_pd_2-3-k_n.cnf for n = k, k+1, ... are created
# and ubcsat-okl with parameters alg, runs, cutoff is executed on
# these instances, storing the output in VanDerWaerden_pd_2-3-k_n.cnf_OUT.
# If a solution was found, then it is stored in
# VanDerWaerden_pd_2-3-k_n.cnf_sol.

# A solution found for n-2 is used as the initial ubcsat-assignment for n.
# Once the first phase is finised, that is, the first unsatisfiable
# instance was found (that is, heuristically determined as unsat),
# the second phase is entered, where in steps of +2 the search advances
# to the next potentially satisfiable instance, skipping the unsatisfiable
# instance inbetween. The third phase is entered once the second unsatisfiable
# instance is found in this way.
# The results are two n-values n1, n2: n1 is maximal such that for all n <= n1
# the instances are satisfiable, while n2 is minimal such that for all n >= n2
# the instances are unsatisfiable (always heuristically).

# The parameters of the script can be found in file "Parameters" within the
# experiment-directory, and the results are in file "Results".

set -o errexit
set -o nounset

script_name="RunPdVdW3k"
version_number="0.2.2"

if [[ $# != 4 ]]; then
  echo "ERROR[${script_name}]: Four parameters k, alg, runs, cutoff
  are needed: The progression-length k, the ubcsat-algorithm,
  the number of runs, and the cutoff."
  exit 1
fi

k=$1
alg=$2
runs=$3
cutoff=$4

repeats_prevassign=3

timestamp=$(date +"%Y-%m-%d-%H%M%S")

ExpDir="Exp_PdVanderWaerden_2-3-${k}_${alg}-${runs}-${cutoff}_${timestamp}"
echo -e "Running \"${script_name}\" in version ${version_number}."
echo -e "Creating directory ${ExpDir}.\n"
mkdir ${ExpDir}
cd ${ExpDir}

result_file=Results

echo -e "${script_name}:\n k=${k}\n alg=${alg}\n runs=${runs}\n cutoff=${cutoff}\n" > Parameters

generator="PdVanderWaerdenCNF-O3-DNDEBUG"
shifter="SolutionShift-O3-DNDEBUG"

phase=1 
# first phase is "all sat", second phase is "alternating", third phase is "all unsat"

for ((n=k; n<=k+1; ++n)); do
  SATinstance="VanDerWaerden_pd_2-3-${k}_${n}.cnf"
  ${generator} 3 ${k} ${n} > ${SATinstance}
  Output="${SATinstance}_OUT"
  Solution="${SATinstance}_sol"
  parameter_line="-alg ${alg} -runs ${runs} -cutoff ${cutoff} -i ${SATinstance} -solve"
  ubcsat-okl ${parameter_line} | tee ${Output}
  cat ${Output} | extract_solution_ubcsat > ${Solution}
done

n0=${k}

for ((n=k+2; phase<=2; ++n, ++n0)); do

  initial_assignment_orig="VanDerWaerden_pd_2-3-${k}_${n0}.cnf_sol"
  initial_assignment="${initial_assignment_orig}_shifted"
  cat ${initial_assignment_orig} | ${shifter} > ${initial_assignment}

  SATinstance="VanDerWaerden_pd_2-3-${k}_${n}.cnf"
  # Creating the Dimacs-file:
  ${generator} 3 ${k} ${n} > ${SATinstance}

  Output="${SATinstance}_OUT"
  Solution="${SATinstance}_sol"

  # Using the assignment two steps before as initial assignment:
  Output_init="${Output}_init"
  parameter_line="-alg ${alg} -runs ${repeats_prevassign} -cutoff ${cutoff} -i ${SATinstance} -solve -varinitfile ${initial_assignment}"
  ubcsat-okl ${parameter_line} | tee ${Output_init}
  # Finding out whether a satisfying assignment was found (searching for
  # the line "PercentSuccess = x" and determining whether x > 0):
  success=$(awk "/^PercentSuccess = .*/ {if (\$3 > 0) print 1; else print 0;}" ${Output_init})
  if [[ ${success} == 1 ]]; then
    Output=${Output_init}
  fi

  # Using random initial assignments:
  if [[ ${success} != 1 ]]; then
    parameter_line="-alg ${alg} -runs ${runs} -cutoff ${cutoff} -i ${SATinstance} -solve"
    ubcsat-okl ${parameter_line} | tee ${Output}
    # Finding out whether a satisfying assignment was found:
    success=$(awk "/^PercentSuccess = .*/ {if (\$3 > 0) print 1; else print 0;}" ${Output})
  fi

  if [[ ${success} == 1 ]]; then

    # Extracting the solution
    cat ${Output} | extract_solution_ubcsat > ${Solution}
    # Printing the solution
    echo "Solution ubcsat-parameters are:"
    awk '/^  +[0-9]+ 1/ {\
      print " run=",$1, "osteps=",$4, "msteps=",$5, "seed=",$6}' ${Output}
    echo "Certificate (the vertices for k=3) for n = ${n} : "
    ExtractCertificate_vdW2 ${Output}
    if [[ ${phase} == 2 ]]; then
      let n+=1
      let n0+=1
    fi

  else
    echo "Break point ${phase}: $((n-1))" >> ${result_file}
    echo "UNSAT for n=${n}"
    let phase+=1
  fi
  echo

done

echo "Final result:"
cat ${result_file}

exit 0

