/* Oliver Kullmann, 11.7.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/BicliquePartitions/testobjects/BasicNotions.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/BicliquePartitions/testobjects/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/BicliquePartitions/BasicNotions.mac")$
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/BicliquePartitions/tests/BasicNotions.mac")$

/* ***********************
   * Fundamental notions *
   ***********************
*/

okltest_ebcp_gg_p(ebcp_gg_p);

okltest_greedy_bcp_gl(greedy_bcp_gl);

/*!
\endhtmlonly
*/
