/* Oliver Kullmann, 11.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/BicliquePartitions/testobjects/Bicliques.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/BicliquePartitions/testobjects/Bicliques.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/BicliquePartitions/Bicliques.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/BicliquePartitions/tests/Bicliques.mac")$

/* ************************************
   * Fundamental notions of bicliques *
   ************************************
*/

okltest_vbc_gl_p(vbc_gl_p);
okltest_vbc_mugl_p(vbc_mugl_p);
okltest_vbc_gg_p(vbc_gg_p);

okltest_vbc_dgl_p(vbc_dgl_p);

okltest_ebc_gg_p(ebc_gg_p);

/* **********************************************
   * Fundamental notions of biclique partitions *
   **********************************************
*/

okltest_ebcp_gg_p(ebcp_gg_p);

/*!
\endhtmlonly
*/
