/* Oliver Kullmann, 20.5.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/BicliquePartitions/testobjects/Heuristics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/BicliquePartitions/testobjects/Heuristics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/BicliquePartitions/Heuristics.mac")$
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/BicliquePartitions/tests/Heuristics.mac")$

/* *********************
   * Greedy approaches *
   *********************
*/

okltest_greedy_bcp_gl(greedy_bcp_gl);

/*!
\endhtmlonly
*/
