/* Oliver Kullmann, 10.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/PropositionalLogic/testobjects/Backtracking.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/PropositionalLogic/testobjects/Backtracking.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/PropositionalLogic/Backtracking.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/PropositionalLogic/tests/Backtracking.mac")$

okltest_satisfiability_ft(sat_backtracking_trivh_bft);
okltest_satisfiability_ft(sat_backtracking_firstlh_bft);

/*!
\endhtmlonly
*/
