/* Oliver Kullmann, 9.2.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/PropositionalLogic/testobjects/Formulas.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/PropositionalLogic/testobjects/Formulas.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/PropositionalLogic/Formulas.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/PropositionalLogic/tests/Formulas.mac")$

/* ***********************************
   * Representation of formulas      *
   ***********************************
*/

okltest_var_prpl(var_prpl);
okltest_var_ft(var_ft);

/* ******************************************
   * Basic transformations of formula trees *
   ******************************************
*/

okltest_elimination_constants_ft(elimination_constants_ft);

/* ***********************
   * Partial assignments *
   ***********************
*/

okltest_apply_pa_prpl(apply_pa_prpl);

/* ******************
   * Measures       *
   ******************
*/

/* ******************
   * Translations   *
   ******************
*/



/* ****************************
   * Tseitin translation      *
   ****************************
*/

okltest_tseitin_trans_basic(tseitin_trans_basic);

/*!
\endhtmlonly
*/
