#!/bin/bash
# Copyright 2011 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.


# Script which given an exponent e and a 32-bit integer seed, computes a 
# random permutation, and then a boolean function which is true if and only if
# for every total assignment to the variables, the standard evaluation of the 
# variables 1 to e, as an integer, is mapped to the standard evaluation of the 
# variables e+2 to 2*e by the permutation.
#
# The statistics for the prime implicates and subsumption hypergraph for
# this boolean function are then computed.
#
# Files are output to 
#   random_perm_${set_size}_${seed}/Permutation_full.cnf
#     The CNF file for the generated permutation
#   random_perm_${set_size}_${seed}/Permutation_full.cnf_primes_stats
#     The prime implicate statistics for the generated CNF file.
#   random_perm_${set_size}_${seed}/Permutation_full.cnf_shg_stats
#     The subsumption hypergraph statistics for the generated CNF file.
#
# This process continues picking random permutations until it is quit
# manually. The seed is incremented by one each iteration.
# 

set -o errexit
set -o nounset

script_name="analyse_random_permutations"
version_number="0.1.3"

err="Error[analyse_random_permutations]:"
qmc_scriptname="QuineMcCluskeySubsumptionHypergraphFullStatistics-n"
cnf_filename=Permutation_full.cnf
exp_dir_prefix=random_perm_

if [[ $# -ne 2 ]]; then
  echo "${err} Takes two arguments, the size of the set and the 32-bit seed."
  exit 1;
fi

exp_power=$1
num_vars=$(expr ${exp_power} "*" 2)
seed=$2

if ! type -P ${qmc_scriptname}${num_vars}-O3-DNDEBUG; then
    echo "${err} ${qmc_scriptname}${num_vars}-O3-DNDEBUG doesn't exist."
    echo "Please compile this executable and rerun the script."
    exit 1
fi

while true; do

exp_dir=${exp_dir_prefix}${exp_power}_${seed}
if [[ -e ${exp_dir} ]]; then 
  echo "Skipping seed=" ${seed} ". It already exists!"
  echo "If this is not the case, please delete '${exp_dir}'."
fi
mkdir ${exp_dir} && cd ${exp_dir}

# Generate random permutation as CNF file.
oklib --maxima --batch-string='"oklib_load(\"OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/Permutations.mac\"); set_random('${seed}'); P : random_permutation(create_list(i,i,1,2^'${exp_power}')); output_perm_fullcnf_stdname(P);"'

# Compute statistics
${qmc_scriptname}${num_vars}-O3-DNDEBUG ${cnf_filename}

seed=$(expr ${seed} + 1)
cd ../

done