/* Oliver Kullmann, 29.11.2007 (Swansea) */
/* Copyright 2007 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators.mac
  \brief Maxima functions for generating hypergraphs

Use by

oklib_load("Transitional/ComputerAlgebra/Hypergraphs/Lisp/Generators.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$


/* *****************
   * Ramsey Theory *
   *****************
*/

/* The hypergraph of all arithmetic progressions of size k in {1,...,n}. */
/* Prerequisites: n,k are integers. */
ArithmeticProgressions(k,n) := block([V : setn(n)],
  if elementp(k,{0,1,2}) then return([V,powerset(V,k)]) 
  elseif n < k or k < 0 then return([V,{}]) 
  elseif k = n then return([V,{V}]) else
  return([V, 
    union(ArithmeticProgressions(k,n-1)[2], 
    setify(create_list(setify(
      create_list(n-d*i,i,0,k-1)), d,1,floor((n-1)/(k-1)))))]))$

/*!
\endhtmlonly
*/
