/* Oliver Kullmann, 9.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/IndependentSets.mac
  \brief Functions for independent sets in hypergraphs

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/IndependentSets.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Basics.mac");
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals.mac")$

/* The hypergraph of maximal independent sets of a hypergraph G, via
   hypergraph-transversals */
independence_hyp_tr(G, Tr) := ecomp_hyp(Tr(G))$
independence_hyp_trrs(G) := independence_hyp_tr(G, transversal_hyp_rs)$

/*!
\endhtmlonly
*/
