/* Oliver Kullmann, 30.5.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Statistics.mac
  \brief Statistics for hypergraphs

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Statistics.mac");

*/

/*!
\htmlonly
*/

/* ******************
   * Basic measures *
   ******************
*/

/* Counting the number of vertices: */

nver_hg(G) := length(G[1])$
nver_ohg(G) := length(G[1])$
nver_ghg(G) := length(G[1])$
nver_oghg(G) := length(G[1])$

/* Counting the number of hyperedges: */

nhyp_hg(G) := length(G[2])$
nhyp_ohg(G) := length(G[2])$
nhyp_ghg(G) := length(G[2])$
nhyp_oghg(G) := length(G[2])$


/*!
\endhtmlonly
*/
