/* Oliver Kullmann, 5.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/include.mac
  \brief Inclusion file for Maxima functions related to branching tuples

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/Basic.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/Trees.mac")$

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/tests/Trees.mac")$

/*!
\endhtmlonly
*/
