/* Oliver Kullmann, 27.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/include.mac
  \brief Inclusion file for Maxima autarky functions

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/AutarkyMonoid.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/LargestAutarky.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/MatchingAutarkies.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/Translations.mac")$

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/LargestAutarky.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/MatchingAutarkies.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/Translations.mac")$

/*!
\endhtmlonly
*/
