/* Matthew Lewsey, 17.5.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/LargestAutarky.mac
  \brief Functions related to the largest autarky in partial assignments

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/LargestAutarky.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$

/* Given a partial assignment phi and clause-set F, compute the largest
   autarky for F which is contained in phi. */
largest_aut_cs(phi,F) := if emptyp(phi) then {} else block(
 [analyse_phi, FC],
  F : disjoin({},F),
  analyse_phi : analyse_pa(phi,F),
  FC : union(analyse_phi[2], analyse_phi[4]),
  if not emptyp(FC) then
    return(largest_aut_cs(restr_c_pa(phi,var_cs(FC)),F))
  else return(phi))$

/*!
\endhtmlonly
*/

