/* Oliver Kullmann, 29.7.2008 (Swansea) */
/* Copyright 2008, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/LeanKernel.mac
  \brief Functions for computing lean kernels

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/LeanKernel.mac");

*/

/*!
\htmlonly
*/

/* ***********************************
   * Computing the lean kernel bydef *
   ***********************************
*/

/* Computing the lean kernel w.r.t. some autarky system by a given function,
   which returns a non-trivial autarky iff possible: */
lean_kernel_autfind_fcs(FF,autfind) := block([phi : autfind(FF)],
  unless emptyp(phi) do (
    FF : apply_pa_fcs(phi,FF),
    phi : autfind(FF)
  ),
  return(FF))$

/*!
\endhtmlonly
*/
