/* Oliver Kullmann, 28.3.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011, 2012, 2017 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/Basics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Basics.mac")$


/* *************************
   * Deciding irredundancy *
   *************************
*/

okltest_impliesp_fcs(impliesp_fcs);
okltest_impliesp_cs(impliesp_cs);

okltest_min_unsat_bydef(min_unsat_bydef);
okltest_irredundant_bydef(irredundant_bydef);

/* *****************************
   * Classification of clauses *
   *****************************
*/

okltest_all_irrcl_bydef(all_irrcl_bydef);

/* **************************************
   * Saturated minimal unsatisfiability *
   **************************************
*/

okltest_saturated_min_unsat_bydef(saturated_min_unsat_bydef);
okltest_non_saturating_pas_bydef(non_saturating_pas_bydef);

/* *************************************
   * Marginal minimal unsatisfiability *
   *************************************
*/

okltest_marginal_min_unsat_bydef_fcs(marginal_min_unsat_bydef_fcs);
okltest_marginal_min_unsat_bydef_cs(marginal_min_unsat_bydef_cs);

/*!
\endhtmlonly
*/
