/* Oliver Kullmann, 16.6.2018 (Swansea) */
/* Copyright 2018 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/Binary.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/Binary.mac");

(or use oklib_batch to see the test-executions).

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/Binary.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Binary.mac")$

/* ****************************
   * All 2-MUs by brute force *
   ****************************
*/

okltest_all_ubmu(all_ubmu);
okltest_all_ubmue(all_ubmue);
okltest_all_bmu(all_bmu);
okltest_all_bmue(all_bmue);

/* ******************************
   * Some small auxiliary 2-CNF *
   ******************************
*/

okltest_impl_cl(impl_cl);
okltest_impl_cs(impl_cs);

/* ***********************
   * The nonsingular B_n *
   ***********************
*/

okltest_nonsing_bmu_fcl(nonsing_bmu_fcl);
okltest_nonsing_bmu_cl(nonsing_bmu_cl);
okltest_nonsing_bmu_fcs(nonsing_bmu_fcs);
okltest_nonsing_bmu_cs(nonsing_bmu_cs);

/* **********************
   * Cycle descriptions *
   **********************
*/

okltest_valid_triple_bmu(valid_triple_bmu);
okltest_valid_cycledesc_bmu(valid_cycledesc_bmu);

okltest_deficiency_cycledesc(deficiency_cycledesc);
okltest_ncl_cycledesc(ncl_cycledesc);
okltest_nlitocc_cycledesc(nlitocc_cycledesc);

okltest_cycledesc2bmu_cs(cycledesc2bmu_cs);
okltest_cycledesc2bmu_fcl(cycledesc2bmu_fcl);

/*!
\endhtmlonly
*/
