/* Oliver Kullmann, 8.4.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/Cores.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/Cores.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/Cores.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Cores.mac")$


okltest_min_size_mus(min_size_mus_bydef);

okltest_contains_us(contains_us_bydef);

okltest_first_irr_fcs(first_irr_fcs);

okltest_all_irr_cores(all_irr_cores_bydef);
okltest_all_forced_irr_cores(all_forced_irr_cores_bydef);
okltest_all_min_usat_cores(all_min_usat_cores_bydef);

okltest_sample_irr_cores(sample_irr_cores);

okltest_all_max_noneq_scs(all_max_noneq_scs_bydef);
okltest_all_max_sat_scs(all_max_sat_scs_bydef);
okltest_equivalence_checker_scl(equivalence_checker_scl_bydef);
okltest_all_max_neq_scs(all_max_neq_scs_bydef);

/*!
\endhtmlonly
*/
