/* Oliver Kullmann, 20.2.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/DeficiencyOne.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/DeficiencyOne.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/DeficiencyOne.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/DeficiencyOne.mac")$

/* ************************
   * Tree representations *
   ************************
*/

/* ****************************
   * Generating all instances *
   ****************************
*/

okltest_all_smusat1_cs(all_smusat1_cs);
okltest_num_all_smusat1(num_all_smusat1);

/* ******************************************************
   * Heuristical approach: removing literal occurrences *
   * to achieve a given maximal variable degree         *
   ******************************************************
*/

okltest_remlitocc_greedy(remlitocc_greedy);

okltest_marginal_musat1(marginal_musat1);

/*!
\endhtmlonly
*/
