/* Oliver Kullmann, 31.5.2008 (Swansea) */
/* Copyright 2008, 2009, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/Deficiency2.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/Deficiency2.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/Deficiency2.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Deficiency2.mac")$

/* *********************************************************************
   * The saturated minimally unsatisfiable clause-sets of deficiency 2 *
   *********************************************************************
*/

okltest_charprop_nsmusatd2(charprop_nsmusatd2);

okltest_musatd2_cl(musatd2_cl);
okltest_musatd2_fcs(musatd2_fcs);

okltest_nvar_musatd2(nvar_musatd2);
okltest_ncl_musatd2(ncl_musatd2);
okltest_ncl_list_musatd2(ncl_list_musatd2);
okltest_nlitocc_musatd2(nlitocc_musatd2);

/* *****************************************************
   * Unsatisfiable hitting clause-sets of deficiency 2 *
   *****************************************************
*/

okltest_hittingtype_d2_cs(hittingtype_d2_cs);

okltest_all_reps_uhitd2_t_fcs(all_reps_uhitd2_t_fcs);
okltest_all_reps_uhitd2_fcs(all_reps_uhitd2_fcs);
okltest_all_uhitd2_fcs(all_uhitd2_fcs);

/*!
\endhtmlonly
*/
