/* Oliver Kullmann, 14.6.2008 (Swansea) */
/* Copyright 2008, 2009, 2013 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/InverseSingularDP.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/InverseSingularDP.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/InverseSingularDP.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/InverseSingularDP.mac")$

/* ********************************
   * Performing single extensions *
   ********************************
*/

okltest_new_var_fcs(new_var_fcs);

okltest_random_sublist(random_sublist);

okltest_basic_inverse_singulardp_fcs(basic_inverse_singulardp_fcs);

okltest_pre_hitting_extension_fcs_p(pre_hitting_extension_fcs_p);
okltest_hitting_extension_fcs_p(hitting_extension_fcs_p);

okltest_all_pre_hitting_extensions_fcs(all_pre_hitting_extensions_fcs);

okltest_hittingdivisor_extension_cs(hittingdivisor_extension_cs);

/* ********************************
   * Performing random extensions *
   ********************************
*/

okltest_random_subset_si(random_subset_si);

okltest_si_inverse_singulardp_fcs(si_inverse_singulardp_fcs);

okltest_it_si_inverse_singulardp_fcs(it_si_inverse_singulardp_fcs);

/*!
\endhtmlonly
*/
