/* Oliver Kullmann, 16.4.2011 (Guangzhou) */
/* Copyright 2011, 2013 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/MinVarDegrees.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/MinVarDegrees.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/MinVarDegrees.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/MinVarDegrees.mac")$

/* **************************
   * Number of full clauses *
   **************************
*/

okltest_index_Sma_S2_rec(index_Sma_S2_rec);
okltest_fullclauses_dmu_lb1_gen(fullclauses_dmu_lb1_gen);

okltest_Sma_S2_list(lambda([n], if n=0 then [] else cons(1,create_list(fullclauses_dmu_lb1[k],k,1,n-1))));
okltest_Sma_S2_list(lambda([n], create_list(Sma_S2_bydef(k),k,0,n-1)));
okltest_Sma_S2_list(Sma_S2_list);

okltest_Sma_bydef(Sma_bydef);
okltest_Sma_start(Sma_start);
okltest_Sma_list(Sma_list);

/* ***************************
   * Maximal min-var-degrees *
   ***************************
*/

okltest_order_deficiency(order_deficiency);

/* **************************************
   * (Generalised) non-Mersenne numbers *
   **************************************
*/

okltest_nonmersenne_rec(nonmersenne_rec);
okltest_nonmersenne_law(nonmersenne_law);
okltest_nonmersenne_lb(nonmersenne_lb);
okltest_nonmersenne_ub(nonmersenne_ub);

okltest_nonmersenne_dary_jump(nonmersenne_dary_jump);

okltest_analyse_nonmersenne_rec(analyse_nonmersenne_rec);

okltest_index_nonmersenne_rec(index_nonmersenne_rec);
okltest_nonmersenne_law(nonmersenne_rec2);

okltest_step_nonmersenne_rec(step_nonmersenne_rec);

okltest_nonmersenne_rec(nonmersenne_rec3);

okltest_possible_degree_pairs_nm(possible_degree_pairs_nm);
okltest_possible_degree_pairs_gen(possible_degree_pairs_gen);

okltest_nonmersenne_op(nonmersenne_op);

okltest_nonmersenne_gen_rec(nonmersenne_gen_rec);

okltest_epoche_nonmersenne_gen(epoche_nonmersenne_gen);

okltest_nonmersenne_inf_rec(nonmersenne_inf_rec);

okltest_nonmersenne_level(nonmersenne_level);

okltest_nonmersenne_law(nonmersenne_law2);

okltest_nonmersenne_inf_rec(nonmersenne_inf_law);

/*!
\endhtmlonly
*/
