/* Oliver Kullmann, 1.5.2008 (Guangzhou) */
/* Copyright 2008, 2009, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/uhit_def.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/testobjects/uhit_def.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/data/uhit_def.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/uhit_def.mac")$

okltest_uhit_def(uhit_def);

/* *************************************
   * Bounds on the deficiency and on n *
   *************************************
*/

okltest_max_def_uhit_n(max_def_uhit_n);
okltest_min_n_uhit_def(min_n_uhit_def_i);
okltest_min_n_uhit_def(min_n_uhit_def_l);

/* ***************************
   * Accessing the catalogue *
   ***************************
*/

okltest_all_uhit_def(all_uhit_def);

okltest_collect_uhit_n(collect_uhit_n);

okltest_uhit_n(uhit_n);

/* ****************************
   * Evaluating the catalogue *
   ****************************
*/

okltest_classify_candidates_uhit_def(classify_candidates_uhit_def);

okltest_analyse_isorepo_defset_mvd(analyse_isorepo_defset_mvd);

/* ****************************
   * Completing the catalogue *
   ****************************
*/


/*!
\endhtmlonly
*/
