/* Oliver Kullmann, 30.4.2008 (Guangzhou) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/testobjects/Basic.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/testobjects/Basic.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Basic.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/tests/Basic.mac")$

/* ************************************
   * Checking the defining properties *
   ************************************
*/

okltest_g_p(g_p);
okltest_gl_p(gl_p);
okltest_dg_p(dg_p);
okltest_dgl_p(dgl_p);
okltest_mug_p(mug_p);
okltest_mugl_p(mugl_p);
okltest_mudg_p(mudg_p);
okltest_mudgl_p(mudgl_p);
okltest_gg_p(gg_p);
okltest_gdg_p(gdg_p);

okltest_og_p(og_p);
okltest_ogl_p(ogl_p);
okltest_odg_p(odg_p);
okltest_odgl_p(odgl_p);
okltest_omug_p(omug_p);
okltest_omugl_p(omugl_p);
okltest_omudg_p(omudg_p);
okltest_omudgl_p(omudgl_p);
okltest_ogg_p(ogg_p);
okltest_ogdg_p(ogdg_p);

/* *********************
   * Checking equality *
   *********************
*/

okltest_gr_equalp(gr_equalp);

/* **************
   * Promotions *
   **************
*/

okltest_gl2mugl(gl2mugl);
okltest_gl2gg(gl2gg);
okltest_mugl2gg(mugl2gg);

okltest_ogl2omugl(ogl2omugl);
okltest_ogl2ogg(ogl2ogg);
okltest_omugl2ogg(omugl2ogg);

okltest_gl2ogl(gl2ogl);
okltest_mugl2omugl(mugl2omugl);
okltest_gg2ogg(gg2ogg);

okltest_dgl2mudgl(dgl2mudgl);
okltest_dgl2gdg(dgl2gdg);
okltest_mudgl2gdg(mudgl2gdg);

okltest_odgl2omudgl(odgl2omudgl);
okltest_odgl2ogdg(odgl2ogdg);
okltest_omudgl2ogdg(omudgl2ogdg);

okltest_dgl2odgl(dgl2odgl);
okltest_mudgl2omudgl(mudgl2omudgl);
okltest_gdg2ogdg(gdg2ogdg);

/* *************
   * Downcasts *
   *************
*/


/* ***************
   * Conversions *
   ***************
*/

okltest_g2dg(g2dg);
okltest_gl2dgl(gl2dgl);


/* **************************
   * Basic graph operations *
   **************************
*/

okltest_expand_edge(expand_edge);

okltest_neighbours_g(neighbours_g);
okltest_neighbours_gl(neighbours_gl);

/* *****************************
   * Basic graph constructions *
   *****************************
*/


/* **********
   * Tests  *
   **********
*/

okltest_dominating_vertex_g_p(dominating_vertex_g_p);
okltest_dominating_vertex_gl_p(dominating_vertex_gl_p);

okltest_has_dominating_vertex_g(has_dominating_vertex_g);
okltest_has_dominating_vertex_gl(has_dominating_vertex_gl);

/* ********************************
   * Connections to Maxima-graphs *
   ********************************
*/

okltest_g2mg(g2mg);
okltest_mg2og(mg2og);
okltest_mg2g(mg2g);

okltest_dg2mdg(dg2mdg);

/*!
\endhtmlonly
*/
