/* Oliver Kullmann, 26.2.2008 (Swansea) */
/* Copyright 2008, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/testobjects/Colouring.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/testobjects/Colouring.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Colouring.mac");
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/tests/Colouring.mac");

/* ***************************
   * Using Maxima facilities *
   ***************************
*/

okltest_chromatic_number_gr(chromatic_number_gr_m);

/* ********************
   * Greedy colouring *
   ********************
*/

okltest_greedy_colouring_og(greedy_colouring_og);

/*!
\endhtmlonly
*/
