/* Oliver Kullmann, 24.6.2008 (Swansea) */
/* Copyright 2008, 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/testobjects/Generators.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/testobjects/Generators.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Generators.mac")$
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/tests/Generators.mac")$

/* *******************
   * Complete graphs *
   *******************
*/

okltest_complete_g(complete_g);
okltest_complete_stdg(complete_stdg);

/* ********************
   * Paths and cycles *
   ********************
*/

okltest_pathgraph_og(pathgraph_og);
okltest_cyclegraph_ogl(cyclegraph_ogl);
okltest_cyclegraph_ogg(cyclegraph_ogg);

/* **********
   * Dipols *
   **********
*/

okltest_dipole_ogg(dipole_ogg);

/* ************
   * Bouquets *
   ************
*/

okltest_bouquet_ogg(bouquet_ogg);

/* *****************
   * Kneser graphs *
   *****************
*/

okltest_kneser_g(kneser_g);

/*!
\endhtmlonly
*/
