/* Oliver Kullmann, 24.6.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/testobjects/Generators.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/testobjects/Generators.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Generators.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/tests/Generators.mac")$

/* *****************
   * Kneser graphs *
   *****************
*/

okltest_knesergraph_g(knesergraph_g);

/* ********************
   * Paths and cycles *
   ********************
*/

okltest_pathgraph_og(pathgraph_og);
okltest_cyclegraph_ogl(cyclegraph_ogl);
okltest_cyclegraph_ogg(cyclegraph_ogg);

/*!
\endhtmlonly
*/
