/* Oliver Kullmann, 24.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/testobjects/IndependentSets.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/testobjects/IndependentSets.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/IndependentSets.mac");
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/tests/IndependentSets.mac");


okltest_independence_number_gr_m(independence_number_gr_m);

okltest_partition_number_gr_m(partition_number_gr_m);

/*!
\endhtmlonly
*/
