/* Matthew Gwynne, 24.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/testobjects/Statistics.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/testobjects/Statistics.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Statistics.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/tests/Statistics.mac")$


okltest_vertex_degrees_g(vertex_degrees_g);
okltest_vertex_degrees_og(vertex_degrees_og);

okltest_min_vertex_degree_v_og(min_vertex_degree_v_og);

okltest_vertex_degrees_hm_g(vertex_degrees_hm_g);

/*!
\endhtmlonly
*/

