/* Oliver Kullmann, 1.2.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/Generators.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/Generators.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/Generators.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/Generators.mac")$

/* ********************
   * Full clause-sets *
   ********************
*/

okltest_full_fcs_v(full_fcs_v);
okltest_full_cs_v(full_cs_v);
okltest_full_fcl_v(full_fcl_v);
okltest_full_cl_v(full_cl_v);

okltest_full_fcs(full_fcs);
okltest_full_cs(full_cs);
okltest_full_fcl(full_fcl);
okltest_full_cl(full_cl);

okltest_nvar_full_fcs(nvar_full_fcs);

okltest_ncl_list_full_fcs(ncl_list_full_fcs);

okltest_ncl_full_fcs(ncl_full_fcs);

okltest_deficiency_full_fcs(deficiency_full_fcs);

/* ***********************
   * Pigeonhole formulas *
   ***********************
*/

/* Measures */

okltest_nvar_php(nvar_php);
okltest_ncl_list_weak_php(ncl_list_weak_php);
okltest_ncl_weak_php(ncl_weak_php);
okltest_deficiency_weak_php(deficiency_weak_php);

/* Extended Resolution */

okltest_php_induction_step_cl(php_induction_step_cl)$
okltest_php_induction_cl(php_induction_cl)$
okltest_weak_php_unsat_ext_fcs(weak_php_unsat_ext_fcs)$


/* ************************
   * Parity formulas      *
   ************************
*/

okltest_even_parity_cl(even_parity_cl);
okltest_odd_parity_cl(odd_parity_cl);
okltest_boolm_mul2cnf_fcl(boolm_mul2cnf_fcl);
okltest_boolm_mul2cnf_wv_fcl(boolm_mul2cnf_wv_fcl);

/*!
\endhtmlonly
*/
