/* Oliver Kullmann, 8.8.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/HindmanProblems.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/HindmanProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/HindmanProblems.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/HindmanProblems.mac")$

/* ********************
   * Hindman problems *
   ********************
*/

okltest_hindmani_a1k2_nbfcsud(hindmani_a1k2_nbfcsud);
okltest_hindman_a1k2_nbfcsud(hindman_a1k2_nbfcsud);


/*!
\endhtmlonly
*/
