/* Oliver Kullmann, 11.5.2013 (Swansea) */
/* Copyright 2013 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/LinearEquations.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/LinearEquations.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/LinearEquations.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/LinearEquations.mac")$

/* *********************
   * Parity conditions *
   *********************
*/

okltest_even_parity_cl(even_parity_cl);
okltest_even_parity_wv_cl(even_parity_wv_cl);
okltest_even_parity_fcl(even_parity_fcl);
okltest_odd_parity_cl(odd_parity_cl);
okltest_odd_parity_wv_cl(odd_parity_wv_cl);
okltest_odd_parity_fcl(odd_parity_fcl);

/* **********************
   * Parity constraints *
   **********************
*/

okltest_gprt2prt(gprt2prt);

/* **********************************
   * Translating parity constraints *
   **********************************
*/

okltest_prt2cl_0(prt2cl_0);
okltest_prt2cl_aux_1(prt2cl_aux_1);

okltest_gen_2xor_fcl(gen_2xor_fcl);

okltest_gprt2s2cl_aux_2(gprt2s2cl_aux_2);

okltest_gprt2s2cl_aux_s(gprt2s2cl_aux_s);

okltest_sprt2cl_0(sprt2cl_0);

okltest_sprt2cl_aux_1(sprt2cl_aux_1);

/*!
\endhtmlonly
*/
