/* Matthew Gwynne, 27.5.2009 (Swansea) */
/* Copyright 2009, 2010, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/NonBooleanTranslations.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/NonBooleanTranslations.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/NonBooleanTranslations.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/NonBooleanTranslations.mac")$

/* ******************************
   * The "direct" translation *
   ******************************
*/

okltest_nbfclfd2fcl_core(nbfclfd2fcl_core);
okltest_nbfclud2fcl_core(nbfclud2fcl_core);
okltest_nbfcsfd2fcs_core(nbfcsfd2fcs_core);

okltest_nbfclud2fcl_alo(nbfclud2fcl_alo);
okltest_nbfcsfd2fcs_alo(nbfcsfd2fcs_alo);

okltest_nbfclud2fcl_aloamo(nbfclud2fcl_aloamo);
okltest_nbfcsfd2fcs_aloamo(nbfcsfd2fcs_aloamo);

okltest_snbfclfd2fcl_core(snbfclfd2fcl_core);
okltest_snbfclud2fcl_core(snbfclud2fcl_core);
okltest_snbfcsfd2fcs_core(snbfcsfd2fcs_core);

okltest_snbfclfd2fcl_aloamo(snbfclfd2fcl_aloamo);
okltest_snbfclud2fcl_aloamo(snbfclud2fcl_aloamo);
okltest_snbfcsfd2fcs_aloamo(snbfcsfd2fcs_aloamo);

okltest_extract_partition(extract_partition);

/* **************************************
   * The generalised nested translation *
   **************************************
*/

okltest_gennest_clause_trans(gennest_clause_trans);
okltest_gennest_nbfcl2fcl(gennest_nbfcl2fcl);

okltest_standtrans_T(standtrans_T);
okltest_standtrans_fd_weak_TR(standtrans_fd_weak_TR);
okltest_standtrans_ud_weak_TR(standtrans_fd_weak_TR);
okltest_standtrans_fd_TV(standtrans_fd_TV);
okltest_standtrans_ud_TV(standtrans_ud_TV);
/* okltest_nbfclfd2fcl_alo(nbfclfd2fcl_alo_2); */
okltest_nbfclud2fcl_alo(nbfclud2fcl_alo_2);

okltest_standnest_T(standnest_T);
okltest_standnest_TR(standnest_TR);
okltest_standnest_strong_TR(standnest_strong_TR);
okltest_standnest_TV(standnest_TV);
okltest_nbfclud2fcl_standnest(nbfclud2fcl_standnest);
okltest_nbfclud2fcl_standnest_strong(nbfclud2fcl_standnest_strong);

okltest_logarithmic_T(logarithmic_T);
okltest_logarithmic_TR(logarithmic_TR);
okltest_logarithmic_TV(logarithmic_TV);
okltest_nbfclud2fcl_logarithmic(nbfclud2fcl_logarithmic);

okltest_reduced_T(reduced_T);
okltest_reduced_TR(reduced_TR);
okltest_reduced_strong_TR(reduced_strong_TR);
okltest_reduced_TV(reduced_TV);
okltest_nbfclud2fcl_reduced(nbfclud2fcl_reduced);
okltest_nbfclud2fcl_reduced_strong(nbfclud2fcl_reduced_strong);

/* ************************************************
   * Tools for the generalised nested translation *
   ************************************************
*/

okltest_gennest_nbfcl2fcl_p(gennest_nbfcl2fcl_p);

okltest_add_bincl_nec(add_bincl_nec);

/*!
\endhtmlonly
*/
