/* Matthew Gwynne, 27.5.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/NonBooleanTranslations.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/NonBooleanTranslations.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/NonBooleanTranslations.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/NonBooleanTranslations.mac")$

/* ******************************
   * The "standard" translation *
   ******************************
*/

okltest_nbfclud2fcl_core(nbfclud2fcl_core);
okltest_nbfcsfd2fcs_core(nbfcsfd2fcs_core);
okltest_nbfclud2fcl_alo(nbfclud2fcl_alo);
okltest_nbfcsfd2fcs_alo(nbfcsfd2fcs_alo);
okltest_nbfclud2fcl_aloamo(nbfclud2fcl_aloamo);
okltest_nbfcsfd2fcs_aloamo(nbfcsfd2fcs_aloamo);


/*!
\endhtmlonly
*/
