/* Matthew Gwynne, 26.8.2011 (Swansea) */
/* Copyright 2011, 2012, 2013 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/Pigeonhole.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/Pigeonhole.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/Pigeonhole.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/Pigeonhole.mac")$


/* ***********************
   * Pigeonhole formulas *
   ***********************
*/

okltest_var_php_l(var_php_l);
okltest_pigeons_different_holes_cl(pigeons_different_holes_cl);

/* Measures */

okltest_nvar_php(nvar_php);
okltest_ncl_list_weak_php(ncl_list_weak_php);
okltest_ncl_weak_php(ncl_weak_php);
okltest_deficiency_weak_php(deficiency_weak_php);


/* *********************************
   * Extended pigeon-hole formulas *
   *********************************
*/

okltest_php_induction_step_cl(php_induction_step_cl);
okltest_php_induction_cl(php_induction_cl);
okltest_weak_php_unsat_ext_fcs(weak_php_unsat_ext_fcs);
okltest_weak_php_unsat_ext_uni_fcs(weak_php_unsat_ext_uni_fcs);
okltest_standardise_weak_php_unsat_ext_uni(standardise_weak_php_unsat_ext_uni);
okltest_invstandardise_weak_php_unsat_ext_uni(invstandardise_weak_php_unsat_ext_uni);
okltest_weak_php_unsat_ext_stdfcs(weak_php_unsat_ext_stdfcs);
okltest_var_php2ephp_sm(var_php2ephp_sm);
okltest_var_ephp2php_sm(var_ephp2php_sm);
okltest_nvar_weak_php_unsat_ext(nvar_weak_php_unsat_ext);
okltest_ncl_weak_php_unsat_ext(ncl_weak_php_unsat_ext);


/*!
\endhtmlonly
*/
