/* Oliver Kullmann, 4.9.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/RamseyProblems.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/RamseyProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyProblems.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/RamseyProblems.mac")$

okltest_ramsey2_ofcs(ramsey2_ofcs);
okltest_ramsey2_sym_break_rec(ramsey2_sym_break_rec);

/*!
\endhtmlonly
*/
