/* Oliver Kullmann, 6.7.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/RandomClauseSets.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/RandomClauseSets.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RandomClauseSets.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/RandomClauseSets.mac")$

/* *********************************
   * The fixed-clause-length model *
   *********************************
*/

okltest_random_sublist_l(random_sublist_l);
okltest_random_full_fcs(random_full_fcs);
okltest_random_bal_full_fcs(random_bal_full_fcs);

okltest_random_k_sublist_l(random_k_sublist_l);

okltest_random_fcl(random_fcl);

/* **********************************
   * The random clause-length model *
   **********************************
*/

okltest_random_rcl_fcl(random_rcl_fcl);

/* **********************************
   * The OKgenerator (based on AES) *
   **********************************
*/

okltest_OKlitgenerator_l(OKlitgenerator_l);
okltest_OKlitgenerator_l_p(OKlitgenerator_l_p);
okltest_OKgenerator_fcl(OKgenerator_fcl);

/*!
\endhtmlonly
*/
