/* Oliver Kullmann, 7.10.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/Sudoku.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/Sudoku.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/Sudoku.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/Sudoku.mac")$

/* *************************
   * The basic translation *
   *************************
*/

okltest_var_sdk(var_sdk);

okltest_sdk_different_rows(sdk_different_rows);

okltest_sdk_different_columns(sdk_different_columns);

okltest_sdk_positions_box(sdk_positions_box);

okltest_sdk_different_boxes(sdk_different_boxes);

okltest_sdk_all_fields(sdk_all_fields);

okltest_weak_sdk(weak_sdk);

/* **************************
   * Additional constraints *
   **************************
*/

okltest_sdk_all_rows(sdk_all_rows);

okltest_sdk_all_columns(sdk_all_columns);

okltest_sdk_all_boxes(sdk_all_boxes);

okltest_dual_weak_sdk(dual_weak_sdk);

okltest_strong_sdk(strong_sdk);

/* ************
   * Measures *
   ************
*/

okltest_nvar_sdk(nvar_sdk);

okltest_ncl_list_weak_sdk(ncl_list_weak_sdk);
okltest_ncl_list_dual_weak_sdk(ncl_list_dual_weak_sdk);
okltest_ncl_list_strong_sdk(ncl_list_strong_sdk);

okltest_ncl_weak_sdk(ncl_weak_sdk);
okltest_ncl_dual_weak_sdk(ncl_dual_weak_sdk);
okltest_ncl_strong_sdk(ncl_strong_sdk);

okltest_nlitocc_weak_sdk(nlitocc_weak_sdk);
okltest_nlitocc_dual_weak_sdk(nlitocc_dual_weak_sdk);
okltest_nlitocc_strong_sdk(nlitocc_strong_sdk);

/*!
\endhtmlonly
*/
