/* Oliver Kullmann, 7.10.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/Sudoku.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/Sudoku.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/Sudoku.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/Sudoku.mac")$

/* *************
   * Variables *
   *************
*/

okltest_var_sdk(var_sdk);

okltest_standardise_sdk(standardise_sdk);
okltest_invstandardise_sdk(invstandardise_sdk);

/* *************************
   * The basic translation *
   *************************
*/

okltest_sdk_different_rows_cl(sdk_different_rows_cl);

okltest_sdk_different_columns_cl(sdk_different_columns_cl);

okltest_sdk_positions_box(sdk_positions_box);

okltest_sdk_different_boxes_cl(sdk_different_boxes_cl);

okltest_sdk_all_fields_cl(sdk_all_fields_cl);

okltest_weak_sdk_fcl(weak_sdk_fcl);

/* **************************
   * Additional constraints *
   **************************
*/

okltest_sdk_all_rows(sdk_all_rows);

okltest_sdk_all_columns(sdk_all_columns);

okltest_sdk_all_boxes(sdk_all_boxes);

okltest_dual_weak_sdk(dual_weak_sdk);

okltest_strong_sdk(strong_sdk);

/* ************
   * Measures *
   ************
*/

okltest_nvar_sdk(nvar_sdk);

okltest_ncl_list_weak_sdk_fcl(ncl_list_weak_sdk_fcl);
okltest_ncl_list_weak_sdk_fcs(ncl_list_weak_sdk_fcs);
okltest_ncl_list_dual_weak_sdk_fcl(ncl_list_dual_weak_sdk_fcl);
okltest_ncl_list_dual_weak_sdk_fcs(ncl_list_dual_weak_sdk_fcs);
okltest_ncl_list_strong_sdk_fcl(ncl_list_strong_sdk_fcl);
okltest_ncl_list_strong_sdk_fcs(ncl_list_strong_sdk_fcs);

okltest_ncl_weak_sdk_fcl(ncl_weak_sdk_fcl);
okltest_ncl_weak_sdk_fcs(ncl_weak_sdk_fcs);
okltest_ncl_dual_weak_sdk_fcl(ncl_dual_weak_sdk_fcl);
okltest_ncl_dual_weak_sdk_fcs(ncl_dual_weak_sdk_fcs);
okltest_ncl_strong_sdk_fcl(ncl_strong_sdk_fcl);
okltest_ncl_strong_sdk_fcs(ncl_strong_sdk_fcs);

okltest_nlitocc_weak_sdk_fcl(nlitocc_weak_sdk_fcl);
okltest_nlitocc_weak_sdk_fcs(nlitocc_weak_sdk_fcs);
okltest_nlitocc_dual_weak_sdk_fcl(nlitocc_dual_weak_sdk_fcl);
okltest_nlitocc_dual_weak_sdk_fcs(nlitocc_dual_weak_sdk_fcs);
okltest_nlitocc_strong_sdk_fcl(nlitocc_strong_sdk_fcl);
okltest_nlitocc_strong_sdk_fcs(nlitocc_strong_sdk_fcs);

/* ********************
   * Creating puzzles *
   ********************
*/

okltest_sdk_fields_stdcl(sdk_fields_stdcl);


/*!
\endhtmlonly
*/
