/* Oliver Kullmann, 20.9.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/VanderWaerdenProblems.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/testobjects/VanderWaerdenProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/VanderWaerdenProblems.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/VanderWaerdenProblems.mac")$

/* **************************************************
   * Arithmetic progressions in the natural numbers *
   **************************************************
*/

okltest_vanderwaerden2_fcs(vanderwaerden2_fcs);
okltest_vanderwaerden2nd_fcs(vanderwaerden2nd_fcs);

/* *****************************************
   * Arithmetic progressions in the primes *
   *****************************************
*/

okltest_greentao2_fcs(greentao2_fcs);
okltest_greentao2nd_fcs(greentao2nd_fcs);

/*!
\endhtmlonly
*/
