/* Oliver Kullmann, 10.12.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/NumberTheory/Lisp/tests/Collatz.mac
  \brief Tests for auxiliary number theory functions

Use by

oklib_load("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/Collatz.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

okltest_collatz_reduction(f) := (
  assert(f(2) = 1),
  assert(f(3) = 10),
  assert(f(4) = 2),
  assert(f(5) = 16),
  true)$

okltest_collatz_redseq(f) := (
  assert(f(1) = [1]),
  assert(f(2) = [2,1]),
  assert(f(3) = [3,10,5,16,8,4,2,1]),
  assert(f(4) = [4,2,1]),
  assert(f(5) = [5,16,8,4,2,1]),
  assert(f(6) = [6,3,10,5,16,8,4,2,1]),
  assert(f(11) = [11,34,17,52,26,13,40,20,10,5,16,8,4,2,1]),
  assert(length(f(63728127)) = 950),
  true)$

okltest_collatz_switch_p(f) := (
  assert(f(1) = false),
  assert(f(2) = false),
  assert(f(3) = false),
  assert(f(4) = true),
  true)$

okltest_collatz_prevswitch(f) := (
  assert(f(4) = [16]),
  assert(f(10) = [40]),
  assert(f(16) = [64,10]),
  assert(f(22) = [88, 28]),
  assert(f(28) = [112]),
  true)$

okltest_collatz_prevswitch_lrt_g(f) := block([n],
  assert(f(0,n) = [n]),
  assert(f(1, 106) = [106, [424], [70]]),
  true)$

okltest_collatz_prevswitch_lrt(f) := (
  assert(f(0) = [4]),
  assert(f(1) = [4, [16]]),
  assert(f(2) = [4, [16, [64], [10]]]),
  assert(f(3) = [4, [16, [64, [256]], [10, [40]]]]),
  assert(f(4) = [4, [16, [64, [256, [1024], [340]]], [10, [40, [160], [52]]]]]),
  true)$

okltest_collatz_prevswitch_l(f) := (
  assert(f(0) = [4]),
  assert(f(1) = [4,16]),
  assert(f(2) = [4,16,64,10]),
  assert(f(3) = [4,16,64,10,256,40]),
  true)$

okltest_collatz_redswitch(f) := (
  assert(f(4) = 1),
  assert(f(10) = 2),
  true)$

okltest_collatz_prevswitchred_lrt(f) := (
  assert(f(0) = [1]),
  assert(f(1) = [1, [3]]),
  assert(f(2) = [1, [3, [11], [2]]]),
  assert(f(3) = [1, [3, [11, [43]], [2, [7]]]]),
  assert(f(4) = [1, [3, [11, [43, [171], [57]]], [2, [7, [27], [9]]]]]),
  true)$

okltest_collatz_prevswitchred_l(f) := (
  assert(f(0) = [1]),
  assert(f(1) = [1,3]),
  assert(f(2) = [1,3,11,2]),
  assert(f(3) = [1,3,11,2,43,7]),
  true)$

okltest_collatz_prevswitch_rm(f) := (
  assert(f(0) = [4]),
  assert(f(1) = [4,16]),
  assert(f(2) = [4,16,10]),
  assert(f(3) = [4,16,10,40]),
  assert(f(4) = [4,16,10,40,52]),
  true)$

okltest_collatz_prevswitchred_rm(f) := (
  assert(f(0) = [1]),
  assert(f(1) = [1,3]),
  assert(f(2) = [1,3,2]),
  assert(f(3) = [1,3,2,7]),
  assert(f(4) = [1,3,2,7,9]),
  true)$


/*!
\endhtmlonly
*/
