/* Oliver Kullmann, 20.9.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/NumberTheory/Lisp/tests/PrimeNumbers.mac
  \brief Tests for auxiliary number theory functions

Use by

oklib_load("Transitional/ComputerAlgebra/NumberTheory/Lisp/tests/PrimeNumbers.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$


okltest_primes_interval(f) := (
  assert(f(0,0) = []),
  assert(f(0,1) = []),
  assert(f(3,2) = []),
  assert(f(2,-1) = []),
  assert(f(-10,2) = [2]),
  assert(f(2,2) = [2]),
  assert(f(2,10) = [2,3,5,7]),
  assert(length(f(1,1000)) = 168),
  true)$

okltest_primes_first(f) := (
  assert(f(0) = []),
  assert(f(-1) = []),
  assert(f(1) = [2]),
  assert(f(2) = [2,3]),
  assert(f(5) = [2,3,5,7,11]),
  assert(length(f(66)) = 66),
  true)$


/*!
\endhtmlonly
*/
