/* Oliver Kullmann, 5.8.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/NumberTheory/Lisp/tests/Quadratics.mac
  \brief Tests for auxiliary number theory functions

Use by

oklib_load("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/Quadratics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

/* ******************************
   * Counting integer equations *
   ******************************
*/

okltest_count_quadintsol(f) := block(
  assert(f(0,0) = 1),
  assert(f(0,-1) = 0),
  assert(f(0,1) = 2),
  assert(create_list(f(1,n),n,0,9) = [0,0,1,2,4,5,7,8,10,12]),
  /* XXX */
  if oklib_test_level = 0 then return(true),
  assert(create_list(f(1,n),n,10,20) = [14,15,18,19,21,23,26,27,30,31,34]),
  true)$


/*!
\endhtmlonly
*/
