/* Oliver Kullmann, 11.8.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Groups/tests/CyclicGroups.mac
  \brief Tests regarding cyclic groups

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Groups/tests/CyclicGroups.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/BasicNotions.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Groups/CyclicGroups.mac")$

kill(f)$

okltest_cyclic_ugrpi(f) := (
  assert(f(1) = [{0},mod_add(1), 0,mod_add_inv(1)]),
  for n : 1 thru cokltl(6,12) do block([Z : f(n)],
    assert(ugrpi_p(Z) = true),
    assert(ugrpi2ugrp(Z) = cyclic_ugrp(n))
  ),
  true)$

okltest_cyclic_ougrp(f) := (
  assert(f(1) = [[0],mod_add(1), 0]),
  for n : 1 thru cokltl(6,12) do block([Z : f(n)],
    assert(ougrp_p(Z) = true),
    assert(ougrp2ugrp(Z) = cyclic_ugrp(n))
  ),
  true)$


/*!
\endhtmlonly
*/
