#!/usr/bin/env bash
# Oliver Kullmann, 23.11.2019 (Swansea)
# Copyright 2019 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# USAGE:

# ./RSolsQueens N
# compiles programs SolsQueens with the given N, and runs it, with timing.

# pversion="_debug" ./RSolsQueens N
# compiles the debug-version.

set -o errexit
set -o nounset

program="RunTime"
version="0.0.2"

N=$1
: ${pversion:=""}

program="./SolsQueens${pversion}"

make -B CPPFLAGS=-DNQUEENS=${N} ${program}
time ${program} ${N}
