#!/usr/bin/env bash
# Oliver Kullmann, 23.11.2019 (Swansea)
# Copyright 2019 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# USAGE:

# ./RSolsQueens N [option]

# compiles programs SolsQueens with the given N, and runs it as
# ./SolsQueens option N
# with timing in seconds, and max-resident-memory in KB.
# Note: input N is ignored by SolsQueens, but is useful for (h)top.
# The debug-version is used by

# pversion="_debug" ./RSolsQueens N [option]


set -o errexit
set -o nounset

program="RunTime"
version="0.1.0"

N=$1
shift
: ${pversion:=""}

program="./SolsQueens${pversion}"

make -B CPPFLAGS=-DNQUEENS=${N} ${program}
/usr/bin/time -f"  %e %M" ${program} "$@" ${N}
