#!/usr/bin/env bash

set -o errexit
set -o nounset

program="Run"
version="0.3.4"

scriptdir="$(dirname "$0")"
fullscriptdir=${PWD##*/}
executable=${executable:-"${scriptdir}/ExpQueensRC"}

numargs=$#
if (( numargs == 0 )); then
  echo -e "USAGE:\n ${program} N [...]\n further parameters \"...\" passed to $executable"
  exit 0
fi

N=$1
maxheur=7
maxcache=2

timestamp=$(date "+%F_%H-%M-%S")
logfile="${program}_${timestamp}"
timingtool="/usr/bin/time"

echo -e "${fullscriptdir}/${program} in version ${version}, logfile = \"${logfile}\", pid=$$"

echo -e "# Produced by program \"${fullscriptdir}/${program}\", version ${version}, pid=$$, with arguments" > ${logfile}
echo "# $@" >> ${logfile}
echo -e "# Version information of executable \"${executable}\":" >> ${logfile}

shift

${executable} $N 0 0 "$@" rh >> ${logfile}

for ((heur=0; heur<=maxheur; ++heur)); do
  for ((cache=0; cache<=maxcache; ++cache)); do
    for ((i=4; i<=N; ++i)); do
      ${timingtool} -f " %e" ${executable} $i $heur $cache "$@" rd >> ${logfile} 2>&1
    done
  done
done

timestamp2=$(date "+%F_%H-%M-%S")
echo "Completed $timestamp2"

exit 0
