#!/bin/bash
set -o errexit
set -o nounset

program="RunTests"
version="0.1.3"

error="ERROR[${program}]: "

maxN=8

# program1="valgrind -q --exit-on-first-error=yes ./SimTaw_debug"
program1="./SimTaw"
program2="valgrind -q ./SimTaw_debug"
declare -a programs=("${program1}" "${program2}")

declare -a outcomes=(0 1 0 0 2 10 4 40 92)

for S in "${programs[@]}"; do
  for (( N=1; N<=maxN; ++N )); do
    echo "Testcase: ${S} ${N}"
    result=$(${S} ${N} | cut -d " " -f1)
    expected=${outcomes[$N]}
    if (( result != expected )); then
      echo -e "${error}\"${S} ${N}\" yields \"${result}\", but should yield ${expected}."
      exit $N
    fi
  done

done
