/* Oliver Kullmann, 12.11.2010 (Swansea) */
/* Copyright 2010, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/Certificates.mac
  \brief Functions for investigating certificates of vdW-lower-bounds

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/Certificates.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/VanderWaerden.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$


/* *****************
   * Basic notions *
   *****************
*/

/* Tests whether P is a palindromic vdW-certificate for parameter tuple L
   and n vertices. It is assumed that L is an extended vdW-parameter-tuple,
   n a natural number, and P a list of sets. A valid certificate can have
   empty parts, but overlaps between the parts and additional elements are
   not allowed.
*/
certificate_vdw_p(L,n,P) := block([N : setn(n)],
  length(L) = length(P) and lunion(P) = N and
    sum_l(map(length,P)) = n and
    every(lambda([k,b], not has_arithprog(b,k)), L, P))$
/* See "The notion of a certificate" in 
   ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/plans/Certificates.hpp.
*/

/* For a list of subsets of {1,...,n} check whether P is "palindromic",
   that is, whether for every element (subset) p of P it is true that
   v is in p iff n+1-v is in p:
*/
palindromic_subsets_p(n,P) := if n <= 1 then true else
 block([palin : true],
  for p in P while palin do
    for x in p while palin do
      if not elementp(n+1-x,p) then palin : false,
  return(palin))$

/* Check whether P is a palindromic vdW-certificate for L and n: */
certificate_pdvdw_p(L,n,P) := palindromic_subsets_p(n,P) and
 certificate_vdw_p(L,n,P)$


/* *******************
   * Transformations *
   *******************
*/

/* Creates a certificate from a list of elements constituting one part
   of a binary partitioning:
*/
create_certificate2_vdw(S,n) := block([s : setify(S)],
  [s, setdifference(setn(n),s)])$

/* Translates a vdw-certificate P (as a block-partitioning of {1,...,n})
   into a sequence "i^k", where i = 0,...,length(P)-1 is the colour,
   and k is the occurrence numbers, representing "i^k" as [i,k] for the
   list-form, while using "i" for "i^1" in the string-form:
*/
certificatevdw2list(P) := block([N : lunion(P), n, seq],
 if emptyp(N) then return([]),
 n : lmax(N),
 seq : create_list(
        block([j:0], for b in P do if elementp(i,b) then return(j) else j:j+1),
        i,1,n),
 block([current:first(seq), compressed:[], count:1],
   for x in rest(seq) do
     if x=current then count:count+1
     else (compressed:cons([current,count],compressed), count:1, current:x),
   if count>0 then compressed:cons([current,count],compressed),
   return(reverse(compressed))))$
certificatevdw2string(P) := block([distribute_over:false, x,y], 
  ssubst("1","y",ssubst("0","x", apply(sconcat,
    map(lambda([p], block([a,b], [a,b]:p, if a=0 then a:x elseif a=1 then a:y, 
                          if b=1 then a else a^{b})),
        certificatevdw2list(P))))))$

/* The compression of a palindromic partition of {1,...,n}, restricting to
   the elements <= (n+1)/2:
*/
compress_palindromic_subsets(P) := 
block([n : lmax(map(lmax,P)), H],
  if n = minf then return(P),
  H : setn(ceiling(n/2)),
  map(lambda([p], intersection(p,H)), P))$

/* Unfolding a compressed palindromic partition: */
uncompresss_palindromic_subsets(n,P) := block([m : lambda([v], {v,n+1-v})],
  map(lambda([p], lunion(map(m,listify(p)))), P))$

/* For a "half compressed palindromic certificate" S, that is, a sublist of
   {1,...,m} with m = ceiling(n/2), which specifies the elements of the
   first part of the partition, create a full palindromic certificate:
*/
create_certificate2c_pdvdw(S,n) := block([m : ceiling(n/2), P],
  P : create_certificate2_vdw(S,m),
  uncompresss_palindromic_subsets(n,P))$

/*!
\endhtmlonly
*/
