/* Oliver Kullmann, 20.9.2008 (Swansea) */
/* Copyright 2008, 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/Hypergraphs.mac
  \brief Basic functions for investigating Van der Waerden hypergraphs

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/Hypergraphs.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Generators.mac")$

/* Van der Waerden hypergraphs are computed by

   arithprog_(o)hg(k,n)

   (from Hypergraphs/Lisp/Generators.mac).
*/

/* The satisfiability problems for diagonal resp. mixed problems with 2 parts
   are created by

   vanderwaerden2_fcs(k,n) 
   vanderwaerden2nd_fcs(k1,k2,n)

   and the general mixed problems by

   vanderwaerden_nbfclud(L,n)

   (from
   ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/VanderWaerdenProblems.mac).
*/


/*!
\endhtmlonly
*/
