/* Matthew Gwynne, 25.3.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/CryptoSystems/DataEncryptionStandard/tests/Cipher.mac
  \brief Tests regarding the DES cipher.

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/DataEncryptionStandard/tests/Cipher.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

okltest_des_template(f) := block(
  /* Trivial keys (computed using des_encryption_hex): */
  assert(
    f(hexstr2binv("0000000000000000"),
      des_round_keys(hexstr2binv("0000000000000000"))) =
      hexstr2binv("8CA64DE9C1B123A7")),
  assert(
    f(hexstr2binv("FFFFFFFFFFFFFFFF"),
      des_round_keys(hexstr2binv("FFFFFFFFFFFFFFFF"))) =
      hexstr2binv("7359B2163E4EDC58")),
  /* Test vector from SAT09 desgen benchmark (see "DES generator" in
     Buildsystem/ExternalSources/SpecialBuilds/plans/SAT.hpp):
  */
  assert(
    f(hexstr2binv("038E596D4841D03B"),
      des_round_keys(hexstr2binv("15FBC08D31B0D521"))) =
      hexstr2binv("A2FB6032638EC79D")),
  true)$

okltest_des_encryption(f) := block(
  assert(
    okltest_des_encryption_hex(
      buildq([f],
        lambda([plain,key],
          binv2hexstr(f(hexstr2binv(plain),hexstr2binv(key))))))),
  true)$

okltest_des_decryption(f) := block(
  assert(
    okltest_des_decryption_hex(
      buildq([f],
        lambda([plain,key],
          binv2hexstr(f(hexstr2binv(plain),hexstr2binv(key))))))),
  true)$

okltest_des_encryption_reduced(f) := block(
  assert(
    okltest_des_encryption(
      buildq([f],lambda([plain,key],f(16,plain,key))))),
  true)$

okltest_des_decryption_reduced(f) := block(
  assert(
    okltest_des_decryption(
      buildq([f],lambda([plain,key],f(16,plain,key))))),
  true)$

okltest_des_encryption_hex(f) := block(
  /* Trivial keys (computed using des_encryption_hex): */
  assert(
    f("0000000000000000","0000000000000000") = "8CA64DE9C1B123A7"),
  assert(
    f("FFFFFFFFFFFFFFFF","FFFFFFFFFFFFFFFF") = "7359B2163E4EDC58"),
  /* Test vector from SAT09 desgen benchmark (see "DES generator" in
     Buildsystem/ExternalSources/SpecialBuilds/plans/SAT.hpp):
  */
  assert(
    f("038E596D4841D03B","15FBC08D31B0D521") = "A2FB6032638EC79D"),
  true)$

okltest_des_decryption_hex(f) := block(
  /* Trivial keys (computed using des_decryption_hex): */
  assert(
    f("8CA64DE9C1B123A7","0000000000000000") = "0000000000000000"),
  assert(
    f("7359B2163E4EDC58","FFFFFFFFFFFFFFFF") = "FFFFFFFFFFFFFFFF"),
  /* Test vector from SAT09 desgen benchmark (see "DES generator" in
     Buildsystem/ExternalSources/SpecialBuilds/plans/SAT.hpp):
  */
  assert(
    f("A2FB6032638EC79D","15FBC08D31B0D521") = "038E596D4841D03B"),
  true)$




/*!
\endhtmlonly
*/
