#!/usr/bin/env bash
# Oliver Kullmann, 25.4.2020 (Swansea)
# Copyright 2020 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# USAGE:

# Call_QueensRUCPct [N=16]

# compiles progr=Queens_RUCP_ct in both versions, via "make -B",
# setting -DNN=N, then runs the program, and appends data on the run to the
# output-line:
#  - elapsed real time e (in seconds)
#  - total number U of CPU-seconds that the process spent in user mode
#  - total number S of CPU-seconds that the process spent in kernel mode
#  - percentage of the CPU that this job got, computed as (U + S) / e
#  - maximum resident set size of the process during its lifetime, in Kbytes.

# Call_QueensRUCPct N progr

# compiles and runs progr as above, without arguments (for arguments use
# variable progargs).

# Call_QueensRUCPct -header

# prints the R-header (for Queens_RUCP_ct).


set -o errexit
set -o nounset

program="Call_QueensRUCPct"
version="0.2.0"

if [[ $# == 1 && $1 == "-header" ]]; then
  echo "N sol nds ut wt st pp mm"
  exit 0
fi

N="${1:-16}"
progr="${2:-Queens_RUCP_ct}"

: ${progargs:=""}

make -B SETN="-DNN=$N" $progr ${progr}_debug > /dev/null

/usr/bin/time -f" %e %U %S %P %M" -o"/dev/stdout" -a ./${progr} ${progargs} | tr -d "\n"
echo
