/* Oliver Kullmann, 21.5.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/LargestAutarky.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/LargestAutarky.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/LargestAutarky.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/LargestAutarky.mac")$

okltest_largest_aut_cs(largest_aut_cs);

/*!
\endhtmlonly
*/
