/* Oliver Kullmann, 29.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/LeanKernel.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/LeanKernel.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/LeanKernel.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/LeanKernel.mac")$

okltest_lean_kernel_autfind_fcs(lean_kernel_autfind_fcs);

/*!
\endhtmlonly
*/
