/* Oliver Kullmann, 19.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/LinearAutarkies.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/LinearAutarkies.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/LinearAutarkies.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/LinearAutarkies.mac")$

/* ********************
   * Basic operations *
   ********************
*/

okltest_laut_paocs_p(laut_paocs_p);

okltest_all_laut_ocs(all_laut_ocs);
okltest_lautmon_ocs(lautmon_ocs);

okltest_extlaut_paocs_p(extlaut_paocs_p);

okltest_find_linearautarky_ocs(find_linearautarky_ocs);

/*!
\endhtmlonly
*/
