/* Oliver Kullmann, 1.6.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/MatchingAutarkies.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/MatchingAutarkies.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/MatchingAutarkies.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/MatchingAutarkies.mac")$

/* ********************
   * Basic operations *
   ********************
*/

okltest_cllit_aut_odg(cllit_aut_odg);
okltest_maut_paocs_p(maut_paocs_p);
okltest_all_maut_ocs(all_maut_ocs);
okltest_mautmon_ocs(mautmon_ocs);

/* *****************************
   * Matching-lean clause-sets *
   *****************************
*/

okltest_matchinglean_p(matchinglean_smax_p);

okltest_clawfree_mlean_def1(clawfree_mlean_def1);

/*!
\endhtmlonly
*/
