/* Oliver Kullmann, 1.6.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/MatchingAutarkies.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/MatchingAutarkies.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/MatchingAutarkies.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/MatchingAutarkies.mac")$

okltest_matchinglean_smax_p(matchinglean_smax_p);

okltest_clawfree_mlean_def1(clawfree_mlean_def1);

/*!
\endhtmlonly
*/
