/* Oliver Kullmann, 21.5.2011 (London) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/MinVarDegrees.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/MinVarDegrees.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/MinVarDegrees.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/MinVarDegrees.mac")$

okltest_extremal_lean_mvdd_fcs(extremal_lean_mvdd_fcs);

/*!
\endhtmlonly
*/
