/* Oliver Kullmann, 30.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/TableauAlgorithm.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/TableauAlgorithm.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/TableauAlgorithm.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/TableauAlgorithm.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/LeanKernel.mac")$

/* ***********************
   * The basic algorithm *
   ***********************
*/

okltest_find_aut_cl_tableau_cl(find_aut_cl_tableau_cl);

/* ************************************
   * Finding some non-trivial autarky *
   ************************************
*/

okltest_find_autarky_cs(lambda([F],find_aut_tableau_fs_cl(cs2cl(F))[1]));
okltest_find_autarky_cs(lambda([F],find_aut_tableau_cl(cs2cl(F),lambda([],last(obligations)))[1]));

/* *****************************
   * Computing the lean kernel *
   *****************************
*/

okltest_lean_kernel_fcs(lambda([FF],cs2fcs(cl2cs(lean_kernel_tableau_fs_cl(cs2cl(FF[2]))[1]))));

/*!
\endhtmlonly
*/
