/* Oliver Kullmann, 14.5.2008 (Guangzhou) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/Translations.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/testobjects/Translations.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/Translations.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/Translations.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/LeanKernel.mac")$

okltest_aut_sat_ls(aut_sat_ls);
okltest_lean_usat_ls(lean_usat_ls);
okltest_trans_aut_sat_ls(trans_aut_sat_ls);
okltest_itransc_aut_sat_ls(itransc_aut_sat_ls);
okltest_itrans_aut_sat_ls(itrans_aut_sat_ls);
okltest_find_autarky_fcs(lambda([FF],find_autarky_ls_fcs(FF,dll_simplest_spa_trivial2)));

/*!
\endhtmlonly
*/
