/* Oliver Kullmann, 12.7.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Hindman.mac
  \brief Tests for hypergraph generators related to Hindman's theorem

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Hindman.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

/* *****************
   * Hindman quads *
   *****************
*/

okltest_hindmanquads_degenerated_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2],[{1,2}]]),
  assert(f(3) = [[1,2,3],[{1,2},{1,2,3}]]),
  assert(f(4) = [[1,2,3,4],[{1,2},{1,2,3},{1,3,4},{2,4}]]),
  assert(f(5) = [[1,2,3,4,5],[{1,2},{1,2,3},{1,3,4},{1,4,5},{2,4}]]),
  assert(f(6) = [[1,2,3,4,5,6],[{1,2},{1,2,3},{1,3,4},{1,4,5},{1,5,6},{2,4},{2,3,5,6}]]),
  /* XXX */
  true)$

okltest_hindmanquads_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2],[]]),
  assert(f(3) = [[1,2,3],[{1,2,3}]]),
  assert(f(4) = [[1,2,3,4],[{1,2,3},{1,3,4}]]),
  assert(f(5) = [[1,2,3,4,5],[{1,2,3},{1,3,4},{1,4,5}]]),
  assert(f(6) = [[1,2,3,4,5,6],[{1,2,3},{1,3,4},{1,4,5},{1,5,6},{2,3,5,6}]]),
  /* XXX */
  true)$

okltest_hindmanquadsgen_degenerated_ohg(f) := (
  assert(okltest_hindmanquads_degenerated_ohg(buildq([f],lambda([n],f(1,n)))) = true),
  assert(f(2,3) = [[2,3],[]]),
  assert(f(2,4) = [[2,3,4],[{2,4}]]),
  assert(f(3,4) = [[3,4],[]]),
  assert(f(2,5) = [[2,3,4,5],[{2,4}]]),
  assert(f(2,6) = [[2,3,4,5,6],[{2,4},{2,3,5,6}]]),
  assert(f(3,6) = [[3,4,5,6],[]]),
  /* XXX */
  true)$

okltest_hindmanquadsgen_ohg(f) := (
  assert(okltest_hindmanquads_ohg(buildq([f],lambda([n],f(1,n)))) = true),
  assert(f(2,3) = [[2,3],[]]),
  assert(f(2,4) = [[2,3,4],[]]),
  assert(f(3,4) = [[3,4],[]]),
  assert(f(2,5) = [[2,3,4,5],[]]),
  assert(f(2,6) = [[2,3,4,5,6],[{2,3,5,6}]]),
  assert(f(3,6) = [[3,4,5,6],[]]),
  true)$

/*!
\endhtmlonly
*/
