/* Oliver Kullmann, 12.7.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Hindman.mac
  \brief Tests for hypergraph generators related to Hindman's theorem

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Hindman.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Hindman.mac")$


/* *****************
   * Hindman quads *
   *****************
*/

okltest_hindman_a1k2_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2],[{1,2}]]),
  assert(f(3) = [[1,2,3],[{1,2},{1,2,3}]]),
  assert(f(4) = [[1,2,3,4],[{1,2},{1,2,3},{1,3,4},{2,4}]]),
  assert(f(5) = [[1,2,3,4,5],[{1,2},{1,2,3},{1,3,4},{1,4,5},{2,4}]]),
  assert(f(6) = [[1,2,3,4,5,6],[{1,2},{1,2,3},{1,3,4},{1,4,5},{1,5,6},{2,4},{2,3,5,6}]]),
  /* XXX */
  true)$

okltest_nver_hindman_a1k2_ohg(f) := (
  for n : 0 thru 10 do
    assert(f(n) = length(hindman_a1k2_ohg(n)[1])),
  true)$

okltest_nhyp_hindman_a1k2_ohg(f) := (
  for n : 0 thru 10 do
    assert(f(n) = length(hindman_a1k2_ohg(n)[2])),
  true)$


okltest_hindmani_a1k2_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2],[]]),
  assert(f(3) = [[1,2,3],[{1,2,3}]]),
  assert(f(4) = [[1,2,3,4],[{1,2,3},{1,3,4}]]),
  assert(f(5) = [[1,2,3,4,5],[{1,2,3},{1,3,4},{1,4,5}]]),
  assert(f(6) = [[1,2,3,4,5,6],[{1,2,3},{1,3,4},{1,4,5},{1,5,6},{2,3,5,6}]]),
  /* XXX */
  true)$

okltest_nver_hindmani_a1k2_ohg(f) := (
  for n : 0 thru 10 do
    assert(f(n) = length(hindman_a1k2_ohg(n)[1])),
  true)$

okltest_nhyp_hindmani_a1k2_ohg(f) := (
  for n : 0 thru 10 do 
    assert(f(n) = length(hindmani_a1k2_ohg(n)[2])),
  true)$


okltest_hindman_k2_ohg(f) := (
  assert(okltest_hindman_a1k2_ohg(buildq([f],lambda([n],f(1,n)))) = true),
  assert(f(2,3) = [[2,3],[]]),
  assert(f(2,4) = [[2,3,4],[{2,4}]]),
  assert(f(3,4) = [[3,4],[]]),
  assert(f(2,5) = [[2,3,4,5],[{2,4}]]),
  assert(f(2,6) = [[2,3,4,5,6],[{2,4},{2,3,5,6}]]),
  assert(f(3,6) = [[3,4,5,6],[]]),
  /* XXX */
  true)$

okltest_hindmani_k2_ohg(f) := (
  assert(okltest_hindmani_a1k2_ohg(buildq([f],lambda([n],f(1,n)))) = true),
  assert(f(2,3) = [[2,3],[]]),
  assert(f(2,4) = [[2,3,4],[]]),
  assert(f(3,4) = [[3,4],[]]),
  assert(f(2,5) = [[2,3,4,5],[]]),
  assert(f(2,6) = [[2,3,4,5,6],[{2,3,5,6}]]),
  assert(f(3,6) = [[3,4,5,6],[]]),
  true)$


/* ********************
   * The general case *
   ********************
*/

okltest_hindman_ohg(f) := (
  assert(f(1,0,0) = [[],[{}]]),
  assert(f(1,0,1) = [[1],[{}]]),
  assert(f(1,1,0) = [[],[]]),
  assert(f(1,1,1) = [[1],[{1}]]),
  assert(f(2,1,1) = [[],[]]),
  assert(f(2,1,2) = [[2],[{2}]]),
  assert(f(1,2,0) = [[],[]]),
  assert(f(1,2,1) = [[1],[]]),
  assert(f(1,2,2) = [[1,2],[{1,2}]]),
  assert(f(1,3,0) = [[],[]]),
  assert(f(1,3,1) = [[1],[]]),
  assert(f(1,3,2) = [[1,2],[]]),
  assert(f(1,3,3) = [[1,2,3],[{1,2,3}]]),
  assert(f(1,3,4) = [[1,2,3,4],[{1,2,3},{1,2,3,4}]]),
  assert(f(1,3,5) = [[1,2,3,4,5],[{1,2,3},{1,2,3,4},{1,2,3,4,5}]]),
  assert(f(2,3,0) = [[],[]]),
  assert(f(2,3,1) = [[],[]]),
  assert(f(2,3,2) = [[2],[]]),
  assert(f(2,3,3) = [[2,3],[]]),
  assert(f(2,3,4) = [[2,3,4],[]]),
  assert(f(2,3,5) = [[2,3,4,5],[]]),
  assert(f(2,3,6) = [[2,3,4,5,6],[]]),
  assert(f(2,3,7) = [[2,3,4,5,6,7],[]]),
  assert(f(2,3,8) = [[2,3,4,5,6,7,8],[{2,4,6,8}]]),
  assert(okltest_hindman_k2_ohg(buildq([f], lambda([a,n], f(a,2,n)))) = true),
  true)$

okltest_hindmani_ohg(f) := block(
  assert(f(1,0,0) = [[],[{}]]),
  assert(f(1,0,1) = [[1],[{}]]),
  assert(f(1,1,0) = [[],[]]),
  assert(f(1,1,1) = [[1],[{1}]]),
  assert(f(2,1,1) = [[],[]]),
  assert(f(2,1,2) = [[2],[{2}]]),
  assert(f(1,2,0) = [[],[]]),
  assert(f(1,2,1) = [[1],[]]),
  assert(f(1,2,2) = [[1,2],[]]),
  assert(f(1,3,0) = [[],[]]),
  assert(f(1,3,1) = [[1],[]]),
  assert(f(1,3,2) = [[1,2],[]]),
  assert(f(1,3,3) = [[1,2,3],[]]),
  assert(f(1,3,4) = [[1,2,3,4],[]]),
  assert(f(1,3,5) = [[1,2,3,4,5],[]]),
  assert(f(1,3,6) = [[1,2,3,4,5,6],[{1,2,3,4,5,6}]]),
  assert(f(2,3,0) = [[],[]]),
  assert(f(2,3,1) = [[],[]]),
  assert(f(2,3,2) = [[2],[]]),
  assert(f(2,3,3) = [[2,3],[]]),
  assert(f(2,3,4) = [[2,3,4],[]]),
  assert(f(2,3,5) = [[2,3,4,5],[]]),
  assert(f(2,3,6) = [[2,3,4,5,6],[]]),
  assert(f(2,3,7) = [[2,3,4,5,6,7],[]]),
  assert(f(2,3,8) = [[2,3,4,5,6,7,8],[]]),
  assert(okltest_hindmani_k2_ohg(buildq([f], lambda([a,n], f(a,2,n)))) = true),
  if oklib_test_level=0 then return(true),
  assert(f(2,3,24) = [create_list(i,i,2,24),[{2,3,4,5,6,7,9,8,12,24}]]),
  true)$


/*!
\endhtmlonly
*/
