/* Oliver Kullmann, 15.7.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Schur.mac
  \brief Tests for Schur-hypergraph generators

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Schur.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Schur.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Statistics.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Groups/CyclicGroups.mac")$

kill(f)$


/* *******************
   * Schur's theorem *
   *******************
*/

okltest_schurtriples_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2], [{1,1,2}]]),
  assert(f(3) = [[1,2,3], [{1,2},{1,2,3}]]),
  assert(f(4) = [[1,2,3,4], [{1,2},{1,2,3},{1,3,4},{2,2,4}]]),
  assert(f(5) = [[1,2,3,4,5],[{1,2},{1,2,3},{1,3,4},{2,2,4},{1,4,5},{2,3,5}]]),
  assert(f(6) = [[1,2,3,4,5,6],[{1,2},{1,2,3},{1,3,4},{2,2,4},{1,4,5},{2,3,5},{1,5,6},{2,4,6},{3,6}]]),
  true)$

okltest_schurtriples_hg(f) := (
  assert(f(0) = [{},{}]),
  assert(f(1) = [{1},{}]),
  assert(f(2) = [{1,2}, {{1,1,2}}]),
  assert(f(3) = [{1,2,3}, {{1,2},{1,2,3}}]),
  assert(f(4) = [{1,2,3,4}, {{1,2},{1,2,3},{1,3,4},{2,2,4}}]),
  true)$

okltest_schurtriples_me_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2], [{1,1,2}]]),
  assert(f(3) = [[1,2,3], [{1,2}]]),
  assert(f(4) = [[1,2,3,4], [{1,2},{1,3,4},{2,2,4}]]),
  assert(f(5) = [[1,2,3,4,5],[{1,2},{1,3,4},{2,2,4},{1,4,5},{2,3,5}]]),
  assert(f(6) = [[1,2,3,4,5,6],[{1,2},{1,3,4},{2,2,4},{1,4,5},{2,3,5},{1,5,6},{3,6}]]),
  true)$

okltest_schurtriples_me_hg(f) := (
  for n : 0 thru if oklib_test_level=0 then 10 else 50 do
   block([G : schurtriples_hg(n)],
    assert(f(n) = [G[1], min_elements(G[2])])
  ),
  true)$

okltest_wschurtriples_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2],[]]),
  assert(f(3) = [[1,2,3],[{1,2,3}]]),
  assert(f(4) = [[1,2,3,4],[{1,2,3},{1,3,4}]]),
  assert(f(5) = [[1,2,3,4,5],[{1,2,3},{1,3,4},{1,4,5},{2,3,5}]]),
  assert(f(6) = [[1,2,3,4,5,6],[{1,2,3},{1,3,4},{1,4,5},{2,3,5},{1,5,6},{2,4,6}]]),
  assert(f(7) = [[1,2,3,4,5,6,7],[{1,2,3},{1,3,4},{1,4,5},{2,3,5},{1,5,6},{2,4,6},{1,6,7},{2,5,7},{3,4,7}]]),
  assert(f(8) = [[1,2,3,4,5,6,7,8],[{1,2,3},{1,3,4},{1,4,5},{2,3,5},{1,5,6},{2,4,6},{1,6,7},{2,5,7},{3,4,7},{1,7,8},{2,6,8},{3,5,8}]]),
  for n : 0 thru 15 do block([G : schurtriples_ohg(n)],
    assert(f(n) = [G[1], sublist(G[2], lambda([H], is(length(H)=3)))])
  ),
  true)$

okltest_nhyp_list_schurtriples_ohg(f) := (
  for n : 0 thru 10 do
    assert(f(n) = nhyp_list_ohg(schurtriples_ohg(n))),
  true)$

okltest_nhyp_list_schurtriples_me_ohg(f) := (
  for n : 0 thru 20 do
    assert(f(n) = nhyp_list_ohg(schurtriples_me_ohg(n))),
  true)$

okltest_nhyp_list_wschurtriples_ohg(f) := (
  for n : 0 thru 10 do
    assert(f(n) = nhyp_list_ohg(wschurtriples_ohg(n))),
  true)$

okltest_nhyp_schurtriples_ohg(f) := (
  for n : 0 thru 10 do
    assert(f(n) = nhyp_ohg(schurtriples_ohg(n))),
  true)$

okltest_nhyp_schurtriples_me_ohg(f) := (
  for n : 0 thru 10 do
    assert(f(n) = nhyp_ohg(schurtriples_me_ohg(n))),
  true)$

okltest_nhyp_wschurtriples_ohg(f) := (
  for n : 0 thru 10 do
    assert(f(n) = nhyp_ohg(wschurtriples_ohg(n))),
  true)$

okltest_has_schurtriple(f) := (
  assert(f({}) = false),
  assert(f({0}) = true),
  assert(f({1}) = false),
  assert(f({1,2}) = true),
  assert(f({1,3}) = false),
  assert(f({2,3}) = false),
  assert(f({2,4}) = true),
  assert(f({1,2,3}) = true),
  assert(f({-1,2,3}) = true),
  assert(f({-1,2,4}) = true),
  assert(f({-1,2,5}) = false),
  assert(f({2,4,6,12}) = true),
  assert(f({2,4,7,12}) = true),
  assert(f({2,5,7,12}) = true),
  assert(f({2,6,7,12}) = true),
  assert(f({2,6,7,15}) = false),
  assert(f({4,5,15,16,22,28,29,39,40,41,42,48,49,59}) = false),
  assert(f({1,4,7,10,30}) = false),
  assert(f({1,4,7,10,30,37}) = true),
  true)$

okltest_has_wschurtriple(f) := (
  assert(f({}) = false),
  assert(f({0}) = false),
  assert(f({1}) = false),
  assert(f({1,2}) = false),
  assert(f({1,3}) = false),
  assert(f({2,3}) = false),
  assert(f({2,4}) = false),
  assert(f({1,2,3}) = true),
  assert(f({-1,2,3}) = true),
  assert(f({-1,2,4}) = false),
  assert(f({-1,2,5}) = false),
  assert(f({2,4,6,12}) = true),
  assert(f({2,4,7,12}) = false),
  assert(f({2,5,7,12}) = true),
  assert(f({2,6,7,12}) = false),
  assert(f({2,6,7,15}) = false),
  assert(f({4,5,15,16,22,28,29,39,40,41,42,48,49,59}) = false),
  assert(f({1,4,7,10,30}) = false),
  assert(f({1,4,7,10,30,37}) = true),
  true)$


/* ************
   * Symmetry *
   ************
*/

okltest_schurtriples_pd_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2],[{1,2}]]),
  assert(f(3) = [[1,2],[{1,2}]]),
  assert(f(4) = [[1,2],[{1,2}]]),
  assert(f(5) = [[1,2,3,4],[{1,2},{1,4},{2,4}]]),
  assert(f(6) = [[1,2,3],[{1,2},{1,3},{2,3}]]),
  assert(f(7) = [[1,2,3,4],[{1,2},{2,3},{2,4},{1,3,4}]]),
  assert(f(8) = [[1,2,3,4,6],[{1,2},{1,4},{2,4},{3,6}]]),
  true)$

okltest_wschurtriples_pd_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1],[]]),
  assert(f(3) = [[1,2],[{1,2}]]),
  assert(f(4) = [[1,2],[{1,2}]]),
  assert(f(5) = [[1,2,3],[{1,2}]]),
  assert(f(6) = [[1,2,3],[{1,2},{1,3},{2,3}]]),
  assert(f(7) = [[1,2,3,4],[{1,2},{2,3},{2,4},{1,3,4}]]),
  assert(f(8) = [[1,2,3,4],[{1,2},{1,4},{2,4}]]),
  true)$

okltest_nver_schurtriples_pd_ohg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nver_ohg(schurtriples_pd_ohg(n))),
  true)$

okltest_nver_wschurtriples_pd_ohg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nver_ohg(wschurtriples_pd_ohg(n))),
  true)$


/* *****************
   * Group triples *
   *****************
*/

okltest_grouptriples_ougrp2ohg(f) := (
  assert(f(cyclic_ougrp(1)) = [[],[]]),
  /* XXX */
  true)$

okltest_grouptriples_ugrp2hg(f) := (
  assert(f(cyclic_ugrp(1)) = [{},{}]),
  /* XXX */
  true)$

okltest_grouptriples_me_ougrp2ohg(f) := (
  assert(f(cyclic_ougrp(1)) = [[],[]]),
  /* XXX */
  true)$

okltest_grouptriples_me_ugrp2hg(f) := (
  assert(f(cyclic_ugrp(1)) = [{},{}]),
  /* XXX */
  true)$

okltest_wgrouptriples_ougrp2ohg(f) := (
  assert(f(cyclic_ougrp(1)) = [[],[]]),
  /* XXX */
  true)$

okltest_wgrouptriples_ugrp2hg(f) := (
  assert(f(cyclic_ugrp(1)) = [{},{}]),
  /* XXX */
  true)$

okltest_nver_grouptriples_ougrp2ohg(f) := block([C],
  assert(f([[0],C]) = 0),
  assert(f([[0,1],C]) = 1),
  assert(f([[0,1,3],C]) = 2),
  true)$

okltest_nver_grouptriples_ugrp2hg(f) := block([C],
  assert(f([{0},C]) = 0),
  assert(f([{0,1},C]) = 1),
  assert(f([{0,1,3},C]) = 2),
  true)$

okltest_nver_grouptriples_me_ougrp2ohg(f) := block([C],
  assert(f([[0],C]) = 0),
  assert(f([[0,1],C]) = 1),
  assert(f([[0,1,3],C]) = 2),
  true)$

okltest_nver_grouptriples_me_ugrp2hg(f) := block([C],
  assert(f([{0},C]) = 0),
  assert(f([{0,1},C]) = 1),
  assert(f([{0,1,3},C]) = 2),
  true)$

okltest_nver_wgrouptriples_ougrp2ohg(f) := block([C],
  assert(f([[0],C]) = 0),
  assert(f([[0,1],C]) = 1),
  assert(f([[0,1,3],C]) = 2),
  true)$

okltest_nver_wgrouptriples_ugrp2hg(f) := block([C],
  assert(f([{0},C]) = 0),
  assert(f([{0,1},C]) = 1),
  assert(f([{0,1,3},C]) = 2),
  true)$

okltest_nhyp_grouptriples_ougrp2ohg(f) := (
  for G in append(create_list(cyclic_ougrp(n),n,1,cokltl(5,20)), create_list(sym_l_ougrp(n),n,1,cokltl(4,5))) do
    assert(f(G) = nhyp_ohg(grouptriples_ougrp2ohg(G))),
  true)$

okltest_nhyp_wgrouptriples_ougrp2ohg(f) := (
  for G in append(create_list(cyclic_ougrp(n),n,1,cokltl(5,20)), create_list(sym_l_ougrp(n),n,1,cokltl(4,5))) do
    assert(f(G) = nhyp_ohg(wgrouptriples_ougrp2ohg(G))),
  true)$

okltest_mschurtriples_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2],[{1,2},{1,2}]]),
  assert(f(3) = [[1,2,3],[{1,2},{1,2,3},{1,2,3},{1,2,3},{1,2,3},{2,3}]]),
  assert(f(4) = [[1,2,3,4],[{1,2},{1,2,3},{1,3,4},{1,2,3},{2,4},{1,2,4},{1,3,4},{1,3},{2,3,4},{1,2,4},{2,3,4},{3,4}]]),
  true)$

okltest_mschurtriples_hg(f) := (
  assert(f(0) = [{},{}]),
  assert(f(1) = [{1},{}]),
  assert(f(2) = [{1,2},{{1,2}}]),
  assert(f(3) = [{1,2,3},{{1,2},{1,2,3},{2,3}}]),
  assert(f(4) = [{1,2,3,4},{{1,2},{1,2,3},{1,3,4},{2,4},{1,2,4},{1,3},{2,3,4},{1,2,4},{3,4}}]),
  true)$

okltest_mschurtriples_me_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2],[{1,2}]]),
  assert(f(3) = [[1,2,3],[{1,2},{2,3}]]),
  assert(f(4) = [[1,2,3,4],[{1,2},{2,4},{1,3},{3,4}]]),
  true)$

okltest_mschurtriples_me_hg(f) := (
  assert(f(0) = [{},{}]),
  assert(f(1) = [{1},{}]),
  assert(f(2) = [{1,2},{{1,2}}]),
  assert(f(3) = [{1,2,3},{{1,2},{2,3}}]),
  assert(f(4) = [{1,2,3,4},{{1,2},{2,4},{1,3},{3,4}}]),
  true)$

okltest_wmschurtriples_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2],[]]),
  assert(f(3) = [[1,2,3],[{1,2,3},{1,2,3},{1,2,3},{1,2,3}]]),
  assert(f(4) = [[1,2,3,4],[{1,2,3},{1,3,4},{1,2,3},{1,2,4},{1,3,4},{2,3,4},{1,2,4},{2,3,4}]]),
  true)$

okltest_wmschurtriples_hg(f) := (
  assert(f(0) = [{},{}]),
  assert(f(1) = [{1},{}]),
  assert(f(2) = [{1,2},{}]),
  assert(f(3) = [{1,2,3},{{1,2,3}}]),
  assert(f(4) = [{1,2,3,4},{{1,2,3},{1,3,4},{1,2,4},{2,3,4},{1,2,4}}]),
  true)$

okltest_nver_mschurtriples_ohg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nver_ohg(mschurtriples_ohg(n))),
  true)$

okltest_nver_mschurtriples_hg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nver_hg(mschurtriples_hg(n))),
  true)$

okltest_nver_mschurtriples_me_ohg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nver_ohg(mschurtriples_me_ohg(n))),
  true)$

okltest_nver_mschurtriples_me_hg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nver_hg(mschurtriples_me_hg(n))),
  true)$

okltest_nver_wmschurtriples_ohg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nver_ohg(wmschurtriples_ohg(n))),
  true)$

okltest_nver_wmschurtriples_hg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nver_hg(wmschurtriples_hg(n))),
  true)$

okltest_nhyp_mschurtriples_ohg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nhyp_ohg(mschurtriples_ohg(n))),
  true)$

/*
okltest_nhyp_mschurtriples_hg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nhyp_hg(mschurtriples_hg(n))),
  true)$
*/

/*
okltest_nhyp_mschurtriples_me_ohg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nhyp_ohg(mschurtriples_me_ohg(n))),
  true)$
*/

/*
okltest_nhyp_mschurtriples_me_hg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nhyp_hg(mschurtriples_me_hg(n))),
  true)$
*/

okltest_nhyp_wmschurtriples_ohg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nhyp_ohg(wmschurtriples_ohg(n))),
  true)$

/*
okltest_nhyp_wmschurtriples_hg(f) := (
  for n : 0 thru cokltl(10,20) do
    assert(f(n) = nhyp_ohg(wmschurtriples_hg(n))),
  true)$
*/

okltest_symmetrictriples_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[],[]]),
  assert(f(2) = [[[2,1]],[]]),
  assert(f(3)[1] = [[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]),
  /* XXX */
  true)$

okltest_symmetrictriples_hg(f) := (
  assert(f(0) = [{},{}]),
  assert(f(1) = [{},{}]),
  assert(f(2) = [{[2,1]},{}]),
  assert(f(3)[1] = {[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]}),
  /* XXX */
  true)$

okltest_symmetrictriples_me_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[],[]]),
  assert(f(2) = [[[2,1]],[]]),
  assert(f(3)[1] = [[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]),
  /* XXX */
  true)$

okltest_symmetrictriples_me_hg(f) := (
  assert(f(0) = [{},{}]),
  assert(f(1) = [{},{}]),
  assert(f(2) = [{[2,1]},{}]),
  assert(f(3)[1] = {[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]}),
  /* XXX */
  true)$

okltest_wsymmetrictriples_ohg(f) := (
  assert(f(0) = [[],[]]),
  assert(f(1) = [[],[]]),
  assert(f(2) = [[[2,1]],[]]),
  assert(f(3)[1] = [[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]),
  /* XXX */
  true)$

okltest_wsymmetrictriples_hg(f) := (
  assert(f(0) = [{},{}]),
  assert(f(1) = [{},{}]),
  assert(f(2) = [{[2,1]},{}]),
  assert(f(3)[1] = {[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]}),
  /* XXX */
  true)$

okltest_nver_symmetrictriples_ohg(f) := (
  for n : 0 thru cokltl(3,4,5) do
    assert(f(n) = nver_ohg(symmetrictriples_ohg(n))),
  true)$

okltest_nver_symmetrictriples_hg(f) := (
  for n : 0 thru cokltl(3,4,5) do
    assert(f(n) = nver_hg(symmetrictriples_hg(n))),
  true)$

okltest_nver_symmetrictriples_me_ohg(f) := (
  for n : 0 thru cokltl(3,4,5) do
    assert(f(n) = nver_ohg(symmetrictriples_me_ohg(n))),
  true)$

okltest_nver_symmetrictriples_me_hg(f) := (
  for n : 0 thru cokltl(3,4,5) do
    assert(f(n) = nver_hg(symmetrictriples_me_hg(n))),
  true)$

okltest_nver_wsymmetrictriples_ohg(f) := (
  for n : 0 thru cokltl(3,4,5) do
    assert(f(n) = nver_ohg(wsymmetrictriples_ohg(n))),
  true)$

okltest_nver_wsymmetrictriples_hg(f) := (
  for n : 0 thru cokltl(3,4,5) do
    assert(f(n) = nver_hg(wsymmetrictriples_hg(n))),
  true)$

okltest_nhyp_symmetrictriples_ohg(f) := (
  for n : 0 thru cokltl(3,4,5) do
    assert(f(n) = nhyp_ohg(symmetrictriples_ohg(n))),
  true)$

okltest_nhyp_wsymmetrictriples_ohg(f) := (
  for n : 0 thru cokltl(3,4,5) do
    assert(f(n) = nhyp_ohg(wsymmetrictriples_ohg(n))),
  true)$


/*!
\endhtmlonly
*/
