/* Oliver Kullmann, 18.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Numerical/Lisp/tests/LinearProgramming.mac
  \brief Tests for list-processing functions

Use by

oklib_load("OKlib/ComputerAlgebra/Numerical/Lisp/tests/LinearProgramming.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$


kill(f)$


/* ******************************************
   * Solving systems of linear inequalities *
   ******************************************
*/

okltest_solve_lineq(f) := block([A, special_symbol : "x", x1,x2],
  x1 : 777, x2 : -9999,
  assert(f(matrix(),[],[],[]) = []),
  assert(f(matrix([0]),[],[],[]) = [0]),
  assert(f(matrix([0]),[1],[],[]) = [1]),
  assert(f(matrix([0]),[],[1],[]) = [-1]),
  assert(f(matrix([0]),[],[],[1]) = [0]),
  assert(f(matrix([0]),[1],[1],[]) = false),
  assert(f(matrix([1]),[],[],[]) = [0]),
  assert(f(matrix([1]),[1],[],[]) = [1]),
  assert(f(matrix([1]),[],[1],[]) = false),
  assert(f(matrix([1]),[],[],[1]) = [0]),
  A : matrix([0,0],[0,0]),
  assert(f(A,[],[],[]) = [0,0]),
  assert(f(A,[1,2],[],[]) = [1,1]),
  assert(f(A,[1],[2],[]) = [1,-1]),
  assert(f(A,[],[2],[1]) = [0,-1]),
  assert(f(A,[],[],[1]) = [0,0]),
  A : matrix([1,1],[-1,-1]),
  assert(f(A,[],[],[]) = [0,0]),
  assert(f(A,[1],[],[]) = [1,-1]),
  assert(f(A,[],[1],[]) = [-1,1]),
  assert(f(A,[1],[2],[]) = [1,-1]),
  assert(f(A,[1],[1],[]) = false),
  true)$

/*!
\endhtmlonly
*/
