/* Matthew Gwynne, 4.6.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file Transitional/ComputerAlgebra/Algebra/Lisp/testobjects/FiniteFields.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/testobjects/FiniteFields.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/FiniteFields.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/tests/FiniteFields.mac")$

/* ***************************************
   * Finite Field Wrapper Functions      *
   ***************************************
*/

okltest_egf_add(egf_add);

okltest_egf_mul(egf_mul);

okltest_egf_matmul(egf_matmul);
okltest_egf_matinv(egf_matinv);

okltest_egf_inv(egf_inv);

/* ****************************
   * Standard representations *
   ****************************
*/

okltest_gf_stand(gf_stand);
okltest_egf_stand(egf_stand);

okltest_gf_equalp(gf_equalp);
okltest_egf_equalp(egf_equalp);

/*!
\endhtmlonly
*/
