/* Matthew Gwynne, 4.6.2008 (Swansea) */
/* Copyright 2008, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file OKlib/ComputerAlgebra/Algebra/Lisp/testobjects/FiniteFields.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/testobjects/FiniteFields.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/FiniteFields.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/tests/FiniteFields.mac")$

/* ***************************************
   * Finite Field Wrapper Functions      *
   ***************************************
*/

okltest_egf_add(egf_add);
okltest_egf_sub(egf_sub);

okltest_egf_mul(egf_mul);
okltest_egf_div(egf_div);

okltest_egf_matmul(egf_matmul);
okltest_egf_matinv(egf_matinv);

okltest_egf_inv(egf_inv);

okltest_egf_exp(egf_exp);
okltest_egf_findprim(egf_findprim);
okltest_egf_ind(egf_ind);

okltest_egf_primep(egf_primep);

okltest_egf_poly2num(egf_poly2num);
okltest_egf_num2poly(egf_num2poly);

okltest_egf_coeffs(egf_coeffs);

/* ****************************
   * Standard representations *
   ****************************
*/

okltest_gf_stand(gf_stand);
okltest_egf_stand(egf_stand);

okltest_gf_equalp(gf_equalp);
okltest_egf_equalp(egf_equalp);

/*!
\endhtmlonly
*/
