/* Matthew Gwynne, 25.11.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/Ramsey/tests/Numbers.mac
  \brief Tests for functions computing Ramsey-numbers

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Ramsey/tests/Numbers.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

okltest_ramsey(f) := block(
  for i : 1 thru 5 do
    assert(f(2,[1,i]) = 1),
  assert(f(2,[3,3]) = 6),
  assert(f(2,[4,4]) = 18),
  assert(f(2,[3,3,3]) = 17),
  assert(f(2,[-1,-1]) = [0,inf]),
  true)$

/*!
\endhtmlonly
*/
