/* Oliver Kullmann, 3.7.2018 (Swansea) */
/* Copyright 2018 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/ChessGraphs/BasicNotions.mac
  \brief Functions regarding chess-related notions

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/ChessGraphs/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Constructions.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/LinearEquations.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/Numbering.mac")$


/* The N-Queens graph and SAT-representation */

kill(qv)$
declare(qv, noun)$
declare(qv, posfun)$
qv_var([x]) := apply(nounify(qv),x)$

/* Whether there is some N >= 0 such that S is a partial solution of the
   N-queens problem for N, using pairs [i,j] for queens-positions:
*/
partialsol_nqueens_p(S) := setp(S) and every_s(lambda([p], listp(p) and
  length(p)=2 and naturalp(first(p)) and naturalp(second(p))), S) and
  every_s(lambda([P], block([p1:first(P),p2:second(P)], first(p1)#first(p2)
    and second(p1)#second(p2) and
    abs(first(p1)-first(p2))#abs(second(p1)-second(p2)))), powerset(S,2))$
/*
partialsol_nqueens_p({[1,1],[3,2]});
  true
partialsol_nqueens_p({[1,1],[3,3]});
  false
partialsol_nqueens_p({[1,2],[2,4],[3,1],[4,3]});
  true
*/

/* Translate a set of pairs [i,j] into variables qv(i,j): */
qvmap(SP) := map(lambda([p], apply(qv_var,p)), SP)$

/* Transform a set V of variables qv(i,j) in the corresponding set of pairs [i,j]: */
nqueens_extrpairs(V) := map(lambda([v], [first(v),second(v)]), V)$

/* Translate a solution as a set of pairs into a DNF-clause: */
extendsol_nqueens(S) := block([N:lmax(map(first,S)),D],
  D : setdifference(all_tuples(setn(N),2),S), union(qvmap(S), comp_sl(qvmap(D))))$
/*
extendsol_nqueens({[1,2],[2,4],[3,1],[4,3]});
  {-qv(1,1),qv(1,2),-qv(1,3),-qv(1,4),-qv(2,1),-qv(2,2),-qv(2,3),qv(2,4),
   qv(3,1),-qv(3,2),-qv(3,3),-qv(3,4),-qv(4,1),-qv(4,2),qv(4,3),-qv(4,4)}
*/
/* The inverse, just keeping the positive literals (but as variables qv(i,j),
   not as pairs [i,j]): */
shrinksol_nqueens(S) := pospart_c(S)$
/*
shrinksol_nqueens(extendsol_nqueens({[1,2],[2,4],[3,1],[4,3]}));
  {qv(1,2),qv(2,4),qv(3,1),qv(4,3)}
*/

/* For a set V of variables, the clause expressing "at most one (AMO) of them":
*/
amo_cs(V) := comp_cs(powerset(V,2))$
/*
amo_cs({});
  {}
amo_cs({1,2});
  {{-2,-1}}
amo_cs({1,2,3});
  {{-3,-2},{-3,-1},{-2,-1}}
*/

/* For a lset V of variables the clauses expressing "all or none of them": */
allequal_cs(V) := if length(V) <= 1 then {} else block([res:[], L:listify(V)],
  for i : 1 thru length(L)-1 do res:cons({-L[i],L[i+1]},res),
  res:cons({-last(L),first(L)},res), setify(res))$
/* This can be established by an SD (strong digraph) between
   the elements of V. The cycle uses the minimal number of arcs.
*/

/* The equivalence relations on the pairs [i,j] as well as on variables
   qv(i,j) as fundamental for the Queens-graph and Queens-constraints:
*/
samerow_p(p1,p2) := is(first(p1) = first(p2))$
samecolumn_p(p1,p2) := is(second(p1) = second(p2))$
samediag_p(p1,p2) := is(second(p1)-first(p1) = second(p2)-first(p2))$
sameantidiag_p(p1,p2) := is(second(p1)+first(p1) = second(p2)+first(p2))$

queens_g(N,M) :=  block([SQ : cartesian_product(setn(N),setn(M))],
  [SQ, union(
     lunion(map(lambda([K],powerset(K,2)),equiv_classes(SQ, samerow_p))),
     lunion(map(lambda([K],powerset(K,2)),equiv_classes(SQ, samecolumn_p))),
     lunion(map(lambda([K],powerset(K,2)),equiv_classes(SQ, samediag_p))),
     lunion(map(lambda([K],powerset(K,2)),equiv_classes(SQ, sameantidiag_p))))])$

nqueens_fcs(N,M) := block([SQ : qvmap(cartesian_product(setn(N),setn(M)))],
  [SQ, union(
     lunion(map(amo_cs, equiv_classes(SQ, samerow_p))),
     lunion(map(amo_cs, equiv_classes(SQ, samecolumn_p))),
     lunion(map(amo_cs, equiv_classes(SQ, samediag_p))),
     lunion(map(amo_cs, equiv_classes(SQ, sameantidiag_p))),
     if N<=M then equiv_classes(SQ, samerow_p) else {},
     if M<=N then equiv_classes(SQ, samecolumn_p) else {}
   )])$
nqueens_cs(N,M) := fcs2cs(nqueens_fcs(N,M))$

standardise_qv(T) := block(
 ev(T, qv(i,j) := rank_squarenumbering(i,j), qv))$
invstandardise_qv(n) := enum_squarenumbering(n)$

/* For N#M we allow gaps: */
nqueens_stdfcs(N,M) := standardise_qv(nqueens_fcs(N,M))$

/* Output the direct translation to a file (now without gaps for the
   variable-numbering): */
output_nqueens(N,M,filename) := block(
 [FF : standardise_fcs(nqueens_stdfcs(N,M))[1]],
  output_fcs_v(
    sconcat("N-Queens SAT with N = ", N, " and M = ", M, ".", newline, "c ", "Created by output_nqueens(", N, ",", M, ",\"", filename, "\").", newline, "c ", created_by_OKlib()),
    FF,
    filename,
    []))$
/* Providing a standard name: "NQueens_N_M.cnf": */
output_nqueens_stdname(N,M) := output_nqueens(N,M,
  sconcat("NQueens_",N,"_",M,".cnf"))$


/* Now forcing the rotational resp. just the point-symmetries: */
nqueens_rot_fcs(N) := block([F : nqueens_fcs(N,N),
  SQ : cartesian_product(setn(N),setn(N))],
  SQ : equiv_classes(SQ, lambda([x,y],nqueens_rot_p(x,y,N))),
  SQ : map(qvmap, SQ),
 [first(F), union(second(F), lunion(map(allequal_cs, SQ)))])$
nqueens_psym_fcs(N) := block([F : nqueens_fcs(N,N),
  SQ : cartesian_product(setn(N),setn(N))],
  SQ : equiv_classes(SQ, lambda([x,y],nqueens_psym_p(x,y,N))),
  SQ : map(qvmap, SQ),
 [first(F), union(second(F), lunion(map(allequal_cs, SQ)))])$

nqueens_rot_stdfcs(N) := standardise_qv(nqueens_rot_fcs(N))$
nqueens_psym_stdfcs(N) := standardise_qv(nqueens_psym_fcs(N))$

/* Output the direct translation to a file: */
output_nqueens_rot(N,filename) := block(
 [FF : nqueens_rot_stdfcs(N)],
  output_fcs_v(
    sconcat("N-Queens SAT with rotational symmetry and N = ", N, ".", newline, "c ", "Created by output_nqueens_rot(", N, ",\"", filename, "\").", newline, "c ", created_by_OKlib()),
    FF,
    filename,
    []))$
/* Providing a standard name: "NQueens_rot_N.cnf": */
output_nqueens_rot_stdname(N) := output_nqueens_rot(N,
  sconcat("NQueens_rot_",N,".cnf"))$
output_nqueens_psym(N,filename) := block(
 [FF : nqueens_psym_stdfcs(N)],
  output_fcs_v(
    sconcat("N-Queens SAT with point-symmetry and N = ", N, ".", newline, "c ", "Created by output_nqueens_psym(", N, ",\"", filename, "\").", newline, "c ", created_by_OKlib()),
    FF,
    filename,
    []))$
/* Providing a standard name: "NQueens_psym_N.cnf": */
output_nqueens_psym_stdname(N) := output_nqueens_psym(N,
  sconcat("NQueens_psym_",N,".cnf"))$



/* Transforming an N-queens-clause C into a square combinatorial matrix: */
queenscl2scom(C,N) := [setn(N), lambda([i,j], if elementp(qv_var(i,j),C) then +1 elseif elementp(-qv_var(i,j),C) then -1 else 0)]$
/* Now into a Maxima matrix: */
queenscl2m(C,N) := scom2m(queenscl2scom(C,N))$

/* Checking whether a clause lies completely in some row or column: */
isrowcolumn_p(C) := block([V:var_c(C)], is(length(map(first,V))=1) or
  is(length(map(second,V))=1))$
isnotrowcolumn_p(C) := not isrowcolumn_p(C)$

/* The eight standard symmetries: */
/* First the two generating symmetries: */
nqueens_rotate(i,j,N) := [N-j+1,i]$
/* For a point p: */
nqueens_rotate_p(p,N) := nqueens_rotate(first(p),second(p),N)$
nqueens_hmirror(i,j,N) := [N-i+1,j]$
nqueens_hmirror_p(p,N) := nqueens_hmirror(first(p),second(p),N)$
/* Now the m-times rotated versions ("iterated"): */
/* Rotation by m*90 degrees: */
nqueens_irotate(i,j,N,m) := block([p:[i,j]], thru mod(m,4) do p : nqueens_rotate(first(p),second(p),N), p)$
nqueens_irotate_p(p,N,m) := (thru mod(m,4) do p : nqueens_rotate_p(p,N), p)$
/* Mirroring at horizontal midline, antidiagonal, vertical midline, diagonal: */
nqueens_ihmirror(i,j,N,m) := block([p:nqueens_hmirror(i,j,N)],
  nqueens_irotate(first(p),second(p),N,m))$
nqueens_ihmirror_p(p,N,m) := (p:nqueens_hmirror_p(p,N), nqueens_irotate_p(p,N,m))$
/* Versions for sets S of points: */
nqueens_rotate_s(S,N) := map(lambda([p],nqueens_rotate_p(p,N)), S)$
nqueens_irotate_s(S,N,m) := map(lambda([p],nqueens_irotate_p(p,N,m)), S)$
nqueens_hmirror_s(S,N) := map(lambda([p],nqueens_hmirror_p(p,N)), S)$
nqueens_ihmirror_s(S,N,m) := map(lambda([p],nqueens_ihmirror_p(p,N,m)), S)$

/* The orbit of point [i,j]: */
nqueens_orbit(i,j,N) := setify(append(
  create_list(nqueens_irotate(i,j,N,m),m,0,3),
  create_list(nqueens_ihmirror(i,j,N,m),m,0,3)))$
nqueens_orbit_p(p,N) := setify(append(
  create_list(nqueens_irotate_p(p,N,m),m,0,3),
  create_list(nqueens_ihmirror_p(p,N,m),m,0,3)))$
/* The orbit under the four rotations: */
nqueens_orbit_rot(i,j,N) := setify(
  create_list(nqueens_irotate(i,j,N,m),m,0,3))$
nqueens_orbit_rot_p(p,N) := setify(
  create_list(nqueens_irotate_p(p,N,m),m,0,3))$
/* The orbit under the rotation by 180 degrees ("point-symmetry"): */
nqueens_orbit_psym(i,j,N) := setify(
  create_list(nqueens_irotate(i,j,N,m),m,[0,2]))$
nqueens_orbit_psym_p(p,N) := setify(
  create_list(nqueens_irotate_p(p,N,m),m,[0,2]))$
/* The orbit of a set S of points: */
nqueens_orbit_s(S,N) := setify(append(
  create_list(nqueens_irotate_s(S,N,m),m,0,3),
  create_list(nqueens_ihmirror_s(S,N,m),m,0,3)))$

/* Extend map f_(i,j), implicitly defined on variables qv(i,j), to literals: */
nqueens_extvarlit(f_,x) := block([i,j,p], if posp(x) then (i:first(x),j:second(x),p:f_(i,j),qv_var(first(p),second(p))) else (i:first(-x),j:seccond(-x),p:f_(i,j),-qv_var(first(p),second(p))))$

/* Testing whether points p1, p2 are equivalent due to point-symmetry: */
nqueens_psym_p(p1,p2,N) := p1=p2 or nqueens_irotate_p(p1,N,2)=p2$
/* Now under rotational symmetry: */
nqueens_rot_p(p1,p2,N) := elementp(p2, nqueens_orbit_rot_p(p1,N))$

/* Testing whether clauses C, D are isomorphic (there is a symmetry mapping, which transforms C to D): */
nqueens_isoc_p(C,D,N) := block(
 [PC:nqueens_extrpairs(pospart_c(C)), NC:nqueens_extrpairs(comp_sl(negpart_c(C))),
  PD:nqueens_extrpairs(pospart_c(D)), ND:nqueens_extrpairs(comp_sl(negpart_c(D))),
  solved:false],
  if length(PC)#length(PD) or length(NC)#length(ND) then return(false),
  thru 4 do (PC:nqueens_rotate_s(PC,N), NC:nqueens_rotate_s(NC,N),
    if PC=PD and NC=ND then (solved:true, return(true))),
  if solved then return(true),
  PC:nqueens_hmirror_s(PC,N), NC:nqueens_hmirror_s(NC,N),
  thru 4 do (PC:nqueens_rotate_s(PC,N), NC:nqueens_rotate_s(NC,N),
    if PC=PD and NC=ND then (solved:true, return(true))),
  if solved then return(true) else return(false))$

/* White and black squares (vertices/variables): */
blacksq_p(p) := evenp(first(p) + second(p))$
whitesq_p(p) := oddp(first(p) + second(p))$

/* The constraint that the number of white queens is odd/even, using variables
   max(N,M)^2+1, ..., as auxiliary variables:
*/
oddwhitequeens_fcs(N,M) := if N*M <= 1 then [{},{{}}] else block(
 [n : max(N,M)^2,
  W : qvmap(cartesian_product(setn(N), setn(M))), X, s, V],
  W : subset(W, whitesq_p),
  s : first(W), X : disjoin(s,W), X : adjoin(-s,X),
  V : create_list(n+i,i,1,length(W)-2),
  [union(W,setify(V)), setify(prt2cl_aux_1(listify(X), V))])$
evenwhitequeens_fcs(N,M) := if N*M <= 1 then [{},{}] else block(
 [n : max(N,M)^2,
  W : qvmap(cartesian_product(setn(N), setn(M))), V],
  W : subset(W, whitesq_p),
  V : create_list(n+i,i,1,length(W)-2),
  [union(W,setify(V)), setify(prt2cl_aux_1(listify(W), V))])$
oddblackqueens_fcs(N,M,offset) := if N*M = 0 then [{},{{}}] else block(
 [B : qvmap(cartesian_product(setn(N), setn(M))), X, s, V],
  B : subset(B, blacksq_p),
  s : first(B), X : disjoin(s,B), X : adjoin(-s,X),
  V : create_list(offset+i,i,1,length(B)-2),
  [union(B,setify(V)), setify(prt2cl_aux_1(listify(X), V))])$
evenblackqueens_fcs(N,M,offset) := if N*M = 0 then [{},{}] else block(
 [B : qvmap(cartesian_product(setn(N), setn(M))), V],
  B : subset(B, blacksq_p),
  V : create_list(offset+i,i,1,length(B)-2),
  [union(B,setify(V)), setify(prt2cl_aux_1(listify(B), V))])$

nqueens_oddwhite_stdfcs(N,M) := block(
 [F1 : nqueens_stdfcs(N,M), F2 : standardise_qv(oddwhitequeens_fcs(N,M))],
 [union(first(F1), first(F2)), union(second(F1), second(F2))])$
nqueens_evenwhite_stdfcs(N,M) := block(
 [F1 : nqueens_stdfcs(N,M), F2 : standardise_qv(evenwhitequeens_fcs(N,M))],
 [union(first(F1), first(F2)), union(second(F1), second(F2))])$
/* The derived number of black queens also required: */
nqueens_oddwhiteplus_stdfcs(N,M) := block(
 [F1 : nqueens_stdfcs(N,M), F2 : standardise_qv(oddwhitequeens_fcs(N,M)),
  V, F3, n],
  V : union(first(F1), first(F2)), n : lmax(V),
  F3 : standardise_qv(if oddp(min(N,M)) then evenblackqueens_fcs(N,M,n)
       else oddblackqueens_fcs(N,M,n)),
 [union(V,first(F3)), union(second(F1),second(F2),second(F3))])$
nqueens_evenwhiteplus_stdfcs(N,M) := block(
 [F1 : nqueens_stdfcs(N,M), F2 : standardise_qv(evenwhitequeens_fcs(N,M)),
  V, F3, n],
  V : union(first(F1), first(F2)), n : lmax(V),
  F3 : standardise_qv(if evenp(min(N,M)) then evenblackqueens_fcs(N,M,n)
       else oddblackqueens_fcs(N,M,n)),
 [union(V,first(F3)), union(second(F1),second(F2),second(F3))])$


/* Output the direct translation to a file (now without gaps for the
   variable-numbering): */
output_nqueens_oddwhite(N,M,filename) := block(
 [FF : standardise_fcs(nqueens_oddwhite_stdfcs(N,M))[1]],
  output_fcs_v(
    sconcat("N-Queens SAT, odd number of white queens, with N = ", N, " and M = ", M, ".", newline, "c ", "Created by output_nqueens_oddwhite(", N, ",", M, ",\"", filename, "\").", newline, "c ", created_by_OKlib()),
    FF,
    filename,
    []))$
/* Providing a standard name: "NQueens_oddwhite_N_M.cnf": */
output_nqueens_oddwhite_stdname(N,M) := output_nqueens_oddwhite(N,M,
  sconcat("NQueens_oddwhite_",N,"_",M,".cnf"))$

output_nqueens_oddwhiteplus(N,M,filename) := block(
 [FF : standardise_fcs(nqueens_oddwhiteplus_stdfcs(N,M))[1]],
  output_fcs_v(
    sconcat("N-Queens SAT, odd number of white queens, even/odd number of black queens, with N = ", N, " and M = ", M, ".", newline, "c ", "Created by output_nqueens_oddwhiteplus(", N, ",", M, ",\"", filename, "\").", newline, "c ", created_by_OKlib()),
    FF,
    filename,
    []))$
/* Providing a standard name: "NQueens_oddwhiteplus_N_M.cnf": */
output_nqueens_oddwhiteplus_stdname(N,M) :=
 output_nqueens_oddwhiteplus(N,M,
   sconcat("NQueens_oddwhiteplus_",N,"_",M,".cnf"))$

/* Output the direct translation to a file (now without gaps for the
   variable-numbering): */
output_nqueens_evenwhite(N,M,filename) := block(
 [FF : standardise_fcs(nqueens_evenwhite_stdfcs(N,M))[1]],
  output_fcs_v(
    sconcat("N-Queens SAT, even number of white queens, with N = ", N, " and M = ", M, ".", newline, "c ", "Created by output_nqueens_evenwhite(", N, ",", M, ",\"", filename, "\").", newline, "c ", created_by_OKlib()),
    FF,
    filename,
    []))$
/* Providing a standard name: "NQueens_evenwhite_N_M.cnf": */
output_nqueens_evenwhite_stdname(N,M) := output_nqueens_evenwhite(N,M,
  sconcat("NQueens_evenwhite_",N,"_",M,".cnf"))$

output_nqueens_evenwhiteplus(N,M,filename) := block(
 [FF : standardise_fcs(nqueens_evenwhiteplus_stdfcs(N,M))[1]],
  output_fcs_v(
    sconcat("N-Queens SAT, even number of white queens, even/odd number of black queens, with N = ", N, " and M = ", M, ".", newline, "c ", "Created by output_nqueens_evenwhiteplus(", N, ",", M, ",\"", filename, "\").", newline, "c ", created_by_OKlib()),
    FF,
    filename,
    []))$
/* Providing a standard name: "NQueens_evenwhiteplus_N_M.cnf": */
output_nqueens_evenwhiteplus_stdname(N,M) :=
 output_nqueens_evenwhiteplus(N,M,
   sconcat("NQueens_evenwhiteplus_",N,"_",M,".cnf"))$


/* The total number of solutions for 1 <= N <= 27: */
nqueens_counts : [1,0,0,2,10,4,40,92,352,724,
 2680,14200,73712,365596,2279184,14772512,95815104,666090624,4968057848,39029188884,
 314666222712,2691008701644,24233937684440,227514171973736,2207893435808352,22317699616364044,234907967154122528]$
/* https://oeis.org/A000170 */
/* The maximal entry is ~ 2.35*10^17. */
/* Approximation formula (according to https://oeis.org/A000170): */
nqueens_approx_count(N) := N! / 2.54^N$

/* The number of isomorphism classes of solutions (classes of symmetric solutions) for 1 <= N <= 27: */
iso_nqueens_counts : [1,0,0,1,2,1,6,12,46,92,
 341,1787,9233,45752,285053,1846955,11977939,83263591,621012754,4878666808,
 39333324973,336376244042,3029242658210,28439272956934,275986683743434,2789712466510289,29363495934315694]$
/* https://oeis.org/A002562 */

/* The number of rotational-symmetry solutions for 1 <= N <= 63: */
rot_nqueens_counts : [1,0,0,2,2,0,0,0,0,0,
 0,8,8,0,0,64,128,0,0,480,
 704,0,0,3328,3264,0,0,32896,43776,0,
 0,406784,667904,0,0,5845504,8650752,0,0,77184000,
 101492736,0,0,1261588480,1795233792,0,0,21517426688,35028172800,0,
 0,406875119616,652044443648,0,0,8613581094912,12530550128640,0,0,194409626533888,
 291826098503680,0,0]$
/* https://oeis.org/A033148 */
/* According to there: count = 0 for mod(N,4) in {2,3}.
   In case of mod(N,4) = 1, the count is a multiple of 2^((N-1)/4).
*/

/* The number of point-symmetric solutions for 1 <= N <= 40: */
psym_nqueens_counts : [1,0,0,2,2,4,8,4,16,12,
 48,80,136,420,1240,3000,8152,18104,44184,144620,
 375664,1250692,3581240,11675080,34132592,115718268,320403024,1250901440,3600075088,14589438024,
43266334696,181254386312,533869114600,2419751731604,6905549827664,33686204023352,97762487422768,496654774712700,1472761266426976,7715290606371500]$
/* https://oeis.org/A032522 */

/* The number of independent vertex sets in the N-Queens graph for 1<=N<=16:
*/
partial_nqueens_counts : [2,5,18,87,462,2635,16870,118969,915442,7535369,
 66807234,633443407,6354135838,67480769839,754734433310,8870886701401]$
/* https://oeis.org/A287227 for N <= 10. */
/* N > 10 computed in OKlibrary. */


/* ******************
   * Knight's graph *
   ******************
*/

/*

  https://en.wikipedia.org/wiki/Knight's_graph

*/

/*!
\endhtmlonly
*/
