/* Oliver Kullmann, 4.7.2018 (Swansea) */
/* Copyright 2018 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/ChessGraphs/include.mac
  \brief Inclusion file for functions related to chess-type graphs

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/ChessGraphs/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/ChessGraphs/BasicNotions.mac")$
/*oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/ChessGraphs/tests/BasicNotions.mac")$
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/ChessGraphs/Consensus.mac")$*/

/*!
\endhtmlonly
*/
