
/* Oliver Kullmann, 16.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Bicliques/include.mac
  \brief Inclusion file for functions related to bicliques

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/Bicliques/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Bicliques/BasicNotions.mac")$
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Bicliques/tests/BasicNotions.mac")$
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Bicliques/Consensus.mac")$
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Bicliques/tests/Consensus.mac")$

/*!
\endhtmlonly
*/
