/* Oliver Kullmann, 21.5.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Primality/testobjects/Basics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Primality/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Primality/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Primality/tests/Basics.mac")$

okltest_prime_clause_p(prime_clause_p);

okltest_dual_prime_clause_p(dual_prime_clause_p);

okltest_prime_cs_p(prime_cs_p);

okltest_maximal_prime_cs_p(maximal_prime_cs_p);

/*!
\endhtmlonly
*/
