/* Oliver Kullmann, 27.3.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Resolution/testobjects/PrimeImplicatesImplicants.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/testobjects/PrimeImplicatesImplicants.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/PrimeImplicatesImplicants.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/tests/PrimeImplicatesImplicants.mac")$

/* ****************************
   * The Quine/McCluskey case *
   ****************************
*/

okltest_min_2resolution_closure_cs(min_2resolution_closure_cs);

okltest_subsumption_hg_full_cs(subsumption_hg_full_cs);
okltest_minequiv_cs(lambda([F],setify(all_minequiv_bvs_cs(F))));
okltest_rsubsumption_hg_full_cs(rsubsumption_hg_full_cs);
okltest_minequiv_cs(lambda([F],setify(all_minequiv_bvsr_cs(F))));

okltest_dual_min_2resolution_closure_cs(dual_min_2resolution_closure_cs);
okltest_dual_minequiv_cs(dual_all_minequiv_bvs_cs);

/* **************************************************
   * Finding contained prime-clauses by SAT solvers *
   **************************************************
*/

okltest_contained_prime_implicate(contained_prime_implicate);

okltest_replace_by_prime_implicates_hitting(replace_by_prime_implicates_hitting);


/*!
\endhtmlonly
*/
