/* Oliver Kullmann, 16.3.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/CombinatorialMatrices/Lisp/testobjects/Basics.mac

Use by

oklib_load("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/Basics.mac");
oklib_include("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/tests/Basics.mac");


okltest_com2ghyp(com2ghyp);

okltest_comequalp(comequalp);
okltest_scomequalp(scomequalp);

okltest_abs_com(abs_com);
okltest_abs_scom(abs_scom);

/*!
\endhtmlonly
*/
