/* Oliver Kullmann, 9.8.2008 (Swansea) */
/* Copyright 2008, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/CombinatorialMatrices/Lisp/testobjects/Isomorphisms.mac

Use by

oklib_load("OKlib/ComputerAlgebra/CombinatorialMatrices/Lisp/testobjects/Isomorphisms.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/CombinatorialMatrices/Lisp/Isomorphisms.mac")$
oklib_include("OKlib/ComputerAlgebra/CombinatorialMatrices/Lisp/tests/Isomorphisms.mac")$

/* ********************************
   * Incomplete isomorphism tests *
   ********************************
*/

okltest_is_isomorphic_incl0_com(is_isomorphic_incl0_com);
okltest_is_isomorphic_incl1_com(is_isomorphic_incl1_com);
okltest_is_isomorphic_incl2_com(is_isomorphic_incl2_com);

/* ******************************
   * Complete isomorphism tests *
   ******************************
*/

okltest_is_isomorphic_com_p(is_isomorphic_rowperm0_com_p);
okltest_is_isomorphic_com_p(is_isomorphic_rowperm1_com_p);
okltest_is_isomorphic_com_p(is_isomorphic_rowperm2_com_p);

/* ************************
   * Duality and polarity *
   ************************
*/

okltest_selfpolar_bydef_m_p(selfpolar_bydef_m_p);

okltest_selfdual_bydef_m_p(selfdual_bydef_m_p);

/*!
\endhtmlonly
*/
