/* Oliver Kullmann, 9.8.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/CombinatorialMatrices/Lisp/testobjects/Isomorphisms.mac

Use by

oklib_load("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/testobjects/Isomorphisms.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/Isomorphisms.mac")$
oklib_include("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/tests/Isomorphisms.mac")$

/* ***********************
   * Isomorphic matrices *
   ***********************
*/

okltest_is_isomorphic_rowperm_com(is_isomorphic_rowperm_com);

/* ************************
   * Duality and polarity *
   ************************
*/

okltest_selfpolar_bydef_m_p(selfpolar_bydef_m_p);

okltest_selfdual_bydef_m_p(selfdual_bydef_m_p);

/*!
\endhtmlonly
*/
