/* Oliver Kullmann, 16.6.2018 (Swansea) */
/* Copyright 2018 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Binary.mac
  \brief Tests for functions related to 2-MU

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Binary.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

/* **********************
   * Cycle descriptions *
   **********************
*/

okltest_valid_triple_2mu(f) := (
  assert(f(0) = false),
  assert(f([]) = false),
  assert(f([0,0,0]) = false),
  assert(f([1,0,1]) = true),
  true)$

okltest_valid_cycledesc_2mu(f) := (
  assert(f(0) = false),
  assert(f([[1,0,1]]) = false),
  assert(f([[1,0,1],[1,0,1]]) = true),
  true)$

/*!
\endhtmlonly
*/
