/* Oliver Kullmann, 31.5.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Deficiency2.mac
  \brief Tests for functions related to MUSAT(2)

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Deficiency2.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Basics.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Backtracking/DLL_solvers.mac")$
oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/Generators.mac")$


/* Testing the characteristic properties of non-singular minimally 
   unsatisfiable clause-sets of deficiency 2. */
charprop_nsmusatd2(FF,n) := 
  nvar_f(FF) = n and
  FF[1] = setn(n) and
  deficiency_fcs(FF) = 2 and
  min_unsat_bydef(FF,lambda([GG],dll_rk_trivial1(GG,1))) and
  literal_degrees_list_fcs(FF) = [[2,2*n]]$

okltest_charprop_nsmusatd2(f) := (
  assert(f([{},{}],0) = false),
  assert(f([{},{{}}],1) = false),
  assert(f([{1,2},{{},{1},{2},{-1,-2}}],2) = false),
  assert(f([{1,2,3},{{-1,2},{-1,-2},{1,2,-3},{1,2,3},{1,-2}}],3) = false),
  assert(f(full_fcs(2),2) = true),
  assert(f(full_fcs(2),3) = false),
  assert(f([{1,2,3},{{-1,-2,-3},{1,2,3},{-1,2},{-2,3},{-3,1}}],3) = true),
  true)$

okltest_musatd2(f) := (
  for n : 2 thru 5 do
    assert(charprop_nsmusatd2(musatd2(n),n) = true),
  true)$

/*!
\endhtmlonly
*/
