/* Oliver Kullmann, 31.5.2008 (Swansea) */
/* Copyright 2008, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Deficiency3.mac
  \brief Tests for functions related to MUSAT(1)

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Deficiency3.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Backtracking/DLL_solvers.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Statistics.mac")$

kill(f)$


/* Testing the characteristic properties of the special clause-sets showing
   the sharpness of the min-var-degree bound. */
charprop_minvdegdef3(FF,n) := (
  assert(nvar_f(FF) = n+1),
  assert(FF[1] = setn(n+1)),
  assert(deficiency_fcs(FF) = 3),
  assert(min_unsat_bydef(FF,lambda([GG],dll_rk_trivial1(GG,1)))),
  assert(literal_degrees_list_fcs(FF) = [[2,n],[3,n+2]]),
  assert(variable_degrees_list_cs(FF[2]) = [[5,n],[6,1]])
)$

okltest_minvdegdef3(f) := (
  for n : 2 thru if oklib_test_level=0 then 3 else 5 do
    charprop_minvdegdef3(f(n),n),
  true)$

/*!
\endhtmlonly
*/
