/* Oliver Kullmann, 20.8.2009 (Swansea) */
/* Copyright 2009, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/testobjects/Basic.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/testobjects/Basic.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/Basic.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/tests/Basic.mac")$

/* ************************
   * Elementary functions *
   ************************
*/

okltest_bt_apply_permutation(bt_apply_permutation);

okltest_int_seq_bt(int_seq_bt);

/* ***************
   * Power means *
   ***************
*/

okltest_meann(meann);

okltest_gmean(gmean);
okltest_gmeann(gmeann);

/* ***********************************************
   * Lower and upper bounds for the tau-function *
   ***********************************************
*/

/* ****************************
   * Comparison of tau-values *
   ****************************
*/

/* ********************************
   *   Computing the tau-function *
   ********************************
*/


/* ********************
   * Higher precision *
   ********************
*/

/* ************************
   * Symbolic computation *
   ************************
*/

/* *************************************
   *   Derivatives of the tau-function *
   *************************************
*/


/* ******************************************
   *   The induced probability distribution *
   ******************************************
*/

okltest_tauprob(tauprob);
okltest_tauprob_hp(tauprob_hp);
okltest_tauprob_symbolical(tauprob_symbolical);

/* ****************
   * The tau-mean *
   ****************
*/

okltest_taumean(taumean);
okltest_taumean_inf(taumean_inf);

/* *********************************************
   *   Convexity considerations: line versions *
   *********************************************
*/


/* ************************************
   * Investigations on approximations *
   ************************************
*/

/*!
\endhtmlonly
*/
