/* Oliver Kullmann, 20.8.2009 (Swansea) */
/* Copyright 2009, 2011, 2019 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/testobjects/Basic.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/testobjects/Basic.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/Basic.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/tests/Basic.mac")$

/* ************************
   * Elementary functions *
   ************************
*/

okltest_bt_apply_permutation(bt_apply_permutation);

okltest_int_seq_bt(int_seq_bt);

/* ***************
   * Power means *
   ***************
*/

okltest_meann(meann);

okltest_gmean(gmean);
okltest_gmeann(gmeann);

okltest_hmean(hmean);
okltest_hmeann(hmeann);

/* ***********************************************
   * Lower and upper bounds for the tau-function *
   ***********************************************
*/

okltest_tau_lo(tau_lo);
okltest_tau_lon(tau_lon);

okltest_tau_up(tau_up);
okltest_tau_upn(tau_upn);


/* ****************************
   * Comparison of tau-values *
   ****************************
*/

okltest_bt_comparison(bt_comparison);

/* ********************************
   *   Computing the tau-function *
   ********************************
*/

okltest_chi(chi);
okltest_chi_newtonstep(chi_newtonstep);

okltest_tau_eps(tau_eps);

okltest_tau(tau);
okltest_taun(taun);
okltest_tau2(tau2);
okltest_tau3(tau3);

okltest_lchi(lchi);
okltest_lchi_newtonstep(lchi_newtonstep);


/* ********************
   * Higher precision *
   ********************
*/

okltest_tau_hp(tau_hp);

/* ************************
   * Symbolic computation *
   ************************
*/

okltest_tau_symbolical(tau_symbolical);

/* *************************************
   *   Derivatives of the tau-function *
   *************************************
*/


/* ******************************************
   *   The induced probability distribution *
   ******************************************
*/

okltest_tauprob(tauprob);
okltest_tauprob_hp(tauprob_hp);
okltest_tauprob_symbolical(tauprob_symbolical);

/* ****************
   * The tau-mean *
   ****************
*/

okltest_taumean(taumean);
okltest_taumean_inf(taumean_inf);

/* *********************************************
   *   Convexity considerations: line versions *
   *********************************************
*/


/* ************************************
   * Investigations on approximations *
   ************************************
*/

/*!
\endhtmlonly
*/
