/* Oliver Kullmann, 7.5.2008 (Guangzhou) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/testobjects/Trees.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/testobjects/Trees.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/Trees.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/tests/Trees.mac")$

/* *******************************************
   * Analysing unlabelled rooted trees       *
   *******************************************
*/

okltest_canonical_tpd(canonical_tpd);
okltest_uniform_tpd(uniform_tpd);

/* **************************************************
   * Rooted trees labelled with branching tuples    *
   **************************************************
*/

okltest_tbtp(tbtp);

okltest_min_sum_tbt(min_sum_tbt);
okltest_max_sum_tbt(max_sum_tbt);

okltest_delta_tm(delta_tm);

okltest_tauprob_tbt(tauprob_tbt);
okltest_tauprob_hp_tbt(tauprob_hp_tbt);
okltest_tauprob_symbolical_tbt(tauprob_symbolical_tbt);

/* **********************************************************
   * Rooted trees labelled with probability distributions   *
   **********************************************************
*/

okltest_ipd_rp(ipd_rp);

okltest_maxtau_tbt(maxtau_tbt);
okltest_mintau_tbt(mintau_tbt);

/*!
\endhtmlonly
*/
