/* Matthew Gwynne, 5.4.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/testobjects/Conversions.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/testobjects/Conversions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Conversions.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/tests/Conversions.mac")$

okltest_lpad(lpad);

okltest_int2poly(int2poly);
okltest_poly2int(poly2int);

/*!
\endhtmlonly
*/
