/* Matthew Gwynne, 5.4.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/testobjects/Conversions.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Cryptology/Lisp/testobjects/Conversions.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Cryptology/Lisp/Conversions.mac")$
oklib_include("Transitional/ComputerAlgebra/Cryptology/Lisp/tests/Conversions.mac")$

okltest_lpad(lpad);

okltest_digitToInt(digitToInt);
okltest_intToDigit(intToDigit);

okltest_baseNToInt(baseNToInt);
okltest_intToBaseN(intToBaseN);

okltest_intToPoly(intToPoly);
okltest_polyToInt(polyToInt);

/*!
\endhtmlonly
*/
