/* Oliver Kullmann, 15.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Trees/testobjects/Generators.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/Trees/testobjects/Generators.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Trees/Generators.mac")$
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Trees/tests/Generators.mac")$

/* ****************
   * Random trees *
   ****************
*/

okltest_randomtree_pr1_og(randomtree_pr1_og);

okltest_uniform_randomtree_og(uniform_randomtree_og);

/*!
\endhtmlonly
*/
