/* Matthew Gwynne, 23.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Trees/testobjects/Representations.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/Trees/testobjects/Representations.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Trees/Representations.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Trees/tests/Representations.mac")$

/* ****************
   * Prufer Codes *
   ****************
*/

okltest_tree2prufer_code_og(tree2prufer_code_og);
okltest_prufer_code2tree_og(prufer_code2tree_og);

/*!
\endhtmlonly
*/

