#!/bin/bash
# Oliver Kullmann, 15.3.2009 (Swansea)
# Copyright 2009 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.

# "VdWTransversalsInc k n t file1 file 2" starts computing the transversal
# number of the hypergraph of arithmetic progressions of size k over 
# {1,...n}, where t is the transversal number over {1,...,n-1} (thus the 
# transversal number for n is either t or t+1), and continues with n+1 and so
# on.
# The method is by adding the inequality "transversal size <= t" to
# the clauses representing the hyperedges, thus obtaining a SAT problem,
# solved then by Minisat (which seems to be strongest on these problems).

script_name="VdWTransversalsInc"

if [[ $# != 5 ]]; then
  echo "ERROR[${script_name}]: 
  Exactly five parameters k, n, t, file1, file2 are needed:
  The progression-length k, the starting number n of vertices, the 
  transversal number t for n-1 vertices, the output filename for the
  transversal numbers, and the filename for output of the SAT solver."
  exit 1
fi

K=$1
T=$3
output=$4
output_solver=$5

solver="minisat1"
generator="VdWTransversals"

echo "k n tau" >> ${output}
for ((N=${2}; 1; ++N)); do
  ${generator} ${K} ${N} ${T}
  file="vdw_trans_${K}_${N}_${T}.cnf"
  echo ${file} >> ${output_solver}
  ${solver} ${file} >> ${output_solver}
  res=$(echo $?)
  if [[ ${res} != 10 && ${res} != 20 ]]; then
    echo "ERROR[${script_name}]:
    Unexpected return value ${res} from the SAT solver."
    exit 1
  fi
  if [[ ${res} == 20 ]]; then T=$(expr ${T} + 1); fi
  echo "${K} ${N} ${T}" >> ${output}
  echo -e "${K} ${N} ${T}\n" >> ${output_solver}
  rm ${file}
done

exit 0
