#!/bin/bash
# Oliver Kullmann, 17.3.2009 (Swansea)
# Copyright 2009 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.

# "VdWTransversalsPB k n b" computes the pseudo-boolean problem expressing the
# existence of a transversal of size exactly b of the hypergraph of 
# arithmetic progressions of size k for the vertex set {1, ..., n}.

script_name="VdWTransversalsPB"

if [[ $# != 3 ]]; then
  echo "ERROR[${script_name}]: Exactly three parameters k, n, b are needed:
  The progression-length k, the number n of vertices, and the precise length b
  of the envisaged transversal."
  exit 1
fi

K=$1
N=$2
B=$3

maxima_call="oklib --maxima"
translator="BoundOnes"

auxfile="vdw_$$"
resultfile="vdw_trans_${K}_${N}_${B}.opb"

# Creating the Dimacs-file representing the hypergraph as positive clause-set:
${maxima_call} --batch-string="\"oklib_load(\\\"OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac\\\"); oklib_load(\\\"OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators.mac\\\"); output_fcs(\\\"Hypergraph of arithmetic progressions, k=${K}, n=${N}, bound=${B}\\\",arithprog_hg(${K},${N}),\\\"${auxfile}\\\");\""

${translator} "= ${B}" ${N} ${auxfile} ${resultfile}

# Removing the auxiliary files:
rm ${auxfile}

exit 0
