/* Oliver Kullmann, 5.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/include.mac
  \brief Inclusion file for Maxima clause-set functions

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/Generators.mac")$

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/Generators.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/Sudoku.mac")$

/*!
\endhtmlonly
*/
