/* Matthew Gwynne, 26.8.2011 (Swansea) */
/* Copyright 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/Pigeonhole.mac
  \brief Generators for the pigeonhole formulas

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/Pigeonhole.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/HashMaps.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Substitutions.mac")$



/* ************************
   * Pigeon-hole formulas *
   ************************
*/

/* TODO: The following needs to be updated, so that the list-forms
   are the basic forms, and the set-forms are derived. See todo
   "Update the php-functions" in the plans-file.
*/

/* Encoding all injective maps from {1,...,m} to {1,...,n}
   (putting pigeon i in {1,...,m} into hole in {1,...,n}).
*/

/* Variables are "php(i,j)", meaning that pigeon i is in hole j: */
kill(php)$
declare(php, noun)$
declare(php, posfun)$
php_var(i,j) := nounify(php)(i,j)$

/* The set of variables for the pigeonhole formulas with m pigeons and
   n holes:
*/
var_php(m,n) := setify(create_list(php_var(i,j), i,1,m, j,1,n))$

/* In the following m denotes the number of pigeons, n the number of holes */

/* No two pigeon in the same hole: */
pigeons_different_holes(m,n) := setify(create_list({- php_var(i,k), - php_var(j,k)},
  i,1,m-1, j,i+1,m, k,1,n))$

/* Every pigeon in one hole: */
pigeons_in_holes(m,n) := setify(
  create_list(setify(create_list(php_var(i,j), j, 1, n)), i,1,m))$

/* The weak pigeon formula as formal clause-set: */
/* RENAME: weak_php_fcs */
weak_php(m,n) := [var_php(m,n),
 union(pigeons_different_holes(m,n), pigeons_in_holes(m,n))]$
weak_php_fcs(m,n) := weak_php(m,n)$
weak_php_cs(m,n) := fcs2cs(weak_php_fcs(m,n))$

output_weak_php(m,n,filename) := block([FF : standardise_fcs(weak_php(m,n))],
  output_fcs_v(
    sconcat("The pigeonhole principle (weak form): ", m, " pigeons, ", n, " holes."),
    FF[1], filename, FF[2]))$
output_weak_php_stdname(m,n) := output_weak_php(m,n,
  sconcat("PHP_weak_",m,"_",n,".cnf"))$


/* No pigeon in more than one hole: */
pigeon_unique_hole(m,n) := setify(create_list({-php_var(i,k1), -php_var(i,k2)},
  i,1,m, k1,1,n-1, k2,k1+1,n))$

/* Every hole carries a pigeon: */
holes_occupied(m,n) := if m < n then {} else
  setify(create_list(setify(create_list(php_var(i,j), i, 1, m)), j,1,n))$

/* The strong pigeonhole formula as formal clause-set: */
/* RENAME: strong_php_fcs */
strong_php(m,n) := block([FF : weak_php(m,n)],
  [FF[1], union(FF[2], pigeon_unique_hole(m,n), holes_occupied(m,n))])$
strong_php_fcs(m,n) := strong_php(m,n)$
strong_php_cs(m,n) := fcs2cs(strong_php_fcs(m,n))$

output_strong_php(m,n,filename) := block([FF : standardise_fcs(strong_php(m,n))],
  output_fcs_v(
    sconcat("The pigeonhole principle (strong form): ", m, " pigeons, ", n, " holes."),
    FF[1], filename, FF[2]))$
output_strong_php_stdname(m,n) := output_strong_php(m,n,
  sconcat("PHP_weak_",m,"_",n,".cnf"))$


/* Measures */

nvar_php(m,n) := m * n$

/* List of clause-counts for weak_php as with ncl_list_fcs: */
ncl_list_weak_php(m,n) :=
  if m = 0 then []
  elseif n = 0 then [[0,1]]
  elseif m = 1 then [[n,m]]
  elseif n = 1 then [[n,m], [2,n*binomial(m,2)]]
  elseif n = 2 then [[2,n*binomial(m,2)+m]]
  else [[2,n*binomial(m,2)], [n,m]]$
ncl_weak_php(m,n) := block([L : ncl_list_weak_php(m,n)],
 return(sum(L[i][2], i, 1, length(L))))$

deficiency_weak_php(m,n) := ncl_weak_php(m,n) - nvar_php(m,n)$

/* The probability that a random assignment is satisfiable: */
satprob_weak_php(m,n) := sum(binomial(n,i) * stirling2(i,m) * m! ,i,m,n) / 2^nvar_php(m,n)$


/* Extended Resolution refutation
   Additional clauses, using new variables, allow polynomial size
   resolution proofs.
*/

/* Variables are "php_ext(n,i,j)", meaning that pigeon i is in hole j in the
   map from {1,...,n} to {1,...,n-1}.  */
kill(php_ext)$
declare(php_ext, noun)$
declare(php_ext, posfun)$
php_ext_var(n,i,j) := nounify(php_ext)(n,i,j)$

/* Renaming the standard pigeon hole variables to their counter-parts in
   the extended-pigeon-hole clause-set weak_php_unsat_ext_uni_fcs(m): */
rename_php_var2ephp_var_cs(F,m) :=
  substitute_cl(
    F,
    sm2hm(lappend(
        create_list(
          if l = m then
            [[ php_var(i,j), php_ext_var(m,i,j)  ],
            [ -php_var(i,j), -php_ext_var(m,i,j) ]]
          else
            [[ php_ext(l,i,j), php_ext_var(l,i,j) ],
            [ -php_ext(l,i,j), -php_ext_var(l,i,j) ]],
          l, 1, m,i,1,l+1,j,1,l))))$
/* Renaming the extended-pigeon-hole variables to their counter-parts in
   the original pigeon-hole clause-set: */
rename_ephp_var2php_var_cs(F,m) :=
  substitute_cl(
    F,
    sm2hm(lappend(
        create_list(
          if l = m then
            [[ php_ext_var(m,i,j), php_var(i,j)  ],
            [ -php_ext_var(m,i,j), -php_var(i,j) ]]
          else
            [[ php_ext(l,i,j), php_ext_var(l,i,j) ],
            [ -php_ext(l,i,j), -php_ext_var(l,i,j) ]],
          l, 1, m,i,1,l+1,j,1,l))))$

/* Clauses enforcing that if the variables
     php_ext_var(mp+1,i,j) for i in {1,...,mp+1}, j in {1,...,mp}
   represent an injective map phi : {1,...,mp+1} -> {1,...,mp} then variables
     php_ext_var(mp,i,j) for i in {1,...,mp}, j in {1,...,mp-1}
   represent the map phi_mp :  {1,...,mp} -> {1,...,mp-1}:
     phi_n(i) = phi(i) if phi(i) # n
                phi(n+1) if phi(i) = n.
*/
php_induction_step_cl(mp) :=
    lappend(create_list(
      [{php_ext_var(mp,i,j), -php_ext_var(mp+1,i,j)},
       {php_ext_var(mp,i,j), -php_ext_var(mp+1,i,mp+1), -php_ext_var(mp+1,mp+2,j)},
       {-php_ext_var(mp,i,j), php_ext_var(mp+1,i,j), php_ext_var(mp+1,i,mp+1)},
       {-php_ext_var(mp,i,j), php_ext_var(mp+1,i,j), php_ext_var(mp+1,mp+2,j)}],
      i,1,mp+1,j,1,mp))$
/* Extended pigeon-hole induction clauses (using uniform variable names): */
php_induction_uni_cl(m) :=
  lappend(
    create_list(php_induction_step_cl(mp), mp,1,m-1))$
php_induction_cl(m) := rename_ephp_var2php_var_cs(php_induction_uni_cl(m),m)$
/* union(weak_php(m,m-1), setify(weak_php_induction_cl(m)) has a polynomial
   size resolution proof. */

/* For m >= 0, yields weak_php_fcs(m+1,m) with Extended Resolution clauses
   as given in
   [A short proof of the pigeon hole principle using extended resolution";
   Stephen Cook]: */
weak_php_unsat_ext_fcs(m) := block([F : weak_php_unsat_ext_uni_fcs(m)],
  [listify(rename_ephp_var2php_var_cs({F[1]},m))[1],
   rename_ephp_var2php_var_cs(F[2],m)])$
/* Using now php_ext_var(m+1,i,j) for php_var(i,j) for uniformity: */
weak_php_unsat_ext_uni_fcs(m) := block([F : weak_php_fcs(m+1,m)],
  [setify(create_list(php_ext_var(mp,i,j), mp, 1, m, i, 1, mp+1, j, 1, mp)),
   union(setify(php_induction_uni_cl(m)),
         rename_php_var2ephp_var_cs(F[2],m))])$
nvar_weak_php_unsat_ext(m) := (m+1) * m + sum((l+1) * l, l, 1, m-1)$
ncl_weak_php_unsat_ext(m) := (m+1) + binomial(m+1,2) * m + sum(4*l*(l-1),l,1,m)$


/*!
\endhtmlonly
*/
