/* Oliver Kullmann, 1.11.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/PlantedSolutions.hpp
  \brief Plans for Maxima-generators for satisfiable instances with given solution

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/PlantedSolutions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$

/* *******************************************
   * Minimally uniquely satisfiable problems *
   *******************************************
*/

/* For given formal clause-set FF and partial assignment phi, compute, by
   repeated randomised removal of literals from phi, a minimal
   phi' <= phi such that in phi' * FF all assignments from phi - phi'
   are enforced.
*/
/* Prerequisite: var(phi) <= var(FF). */
minUNISAT(FF,phi,solver) := block(
 [minimal : false, FFA : [FF[1],union(FF[2],{comp_sl(phi)})]],
  while not minimal do (
    minimal : true,
    for x in random_permutation(phi) unless not minimal do
     block([nphi : disjoin(x,phi)],
      if solver(apply_pa_fcs(nphi,FFA)) = false then (
        phi : nphi, minimal : false))
  ),
  return(phi))$
/* A main application is the situation where phi is a total satisfying
   assignment for FF, and one wants to find a minimal phi' such that
   phi' * FF has phi as its unique solution.
   If on the other hand phi * FF is unsatisfiable, then phi' is a minimal
   sub-assignment of phi such that phi' * FF is still unsatisfiable.
*/

/*!
\endhtmlonly
*/
