/* Oliver Kullmann, 5.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/RandomClauseSets.mac
  \brief Functions for basic operations with clause-sets

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/RandomClauseSets.mac");

*/

/*!
\htmlonly
*/

/* *********************************
   * The fixed clause-length model *
   *********************************
*/

/* Computing a random repetition-free sublist of a given length k;
   V is a list, repetitions determine the chance of being elected, but the
   result is repetition-free. */
/* Prerequisites: 0 <= k <= length(unique(V)). */
random_sublist_l(V,k) := block([res : []],
  thru k do block([x : V[random(length(V))+1]],
    res : endcons(x,res),
    V : delete(x,V)),
  return(res))$

/* Using the Maxima pseudo-random generator, compute random clause-lists
   with n variables, clause-length k and c clauses: */
/* Prerequisites: n,k,c >= 0, k <= n. */
random_fcl(n,k,c) := block([V : create_list(i,i,1,n), F : []],
  thru c do block([C : random_sublist_l(V,k)],
    for i : 1 thru k do
      if random(2) = 1 then C[i] : -C[i],
    F : endcons(setify(C),F)),
  return([V,F]))$


/* **********************************
   * The random clause-length model *
   **********************************
*/

/* Creating random clause-sets in the "random clause-length" model,
   where a parameter p governs the probability of inclusion of
   a variable (so with probability 1-p the variable is not included).
*/
/* For p=1 every clause is full, for p=0 every clause is empty,
   and for p=2/3 every clause has the same probability. */
/* The average clause-length is p * n (thus if the average shall be k,
   then set p = k/n). */
/* Prerequisites: n,c >= 0, 0 <= p <= 1. */
random_rcl_fcl(n,p,c) := 
 block([V : create_list(i,i,1,n), F : []],
  thru c do block([C : create_list(i,i,1,n)],
    for i : 1 thru n do
      if random(1.0) >= p then C[i] : 0
      else
        if random(2) = 1 then C[i] : -C[i],
    F : endcons(setdifference(setify(C),{0}),F)),
  return([V,F]))$

/*!
\endhtmlonly
*/
