/* Oliver Kullmann, 20.9.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/VanderWaerdenProblems.mac
  \brief Generators for clause-sets related to Van der Waerden problems

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/VanderWaerdenProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Colouring.mac")$


/* **************************************************
   * Arithmetic progressions in the natural numbers *
   **************************************************
*/

/* Boolean formal clause-sets, whose solutions are the partitionings of 
   {1,...,n} into two parts such that none of them contains an arithmetic 
   progression of size k. */
/* (We are using "trivially generalised partitionings here, where the
    parts can be empty.) */
vanderwaerden2_fcs(k,n) := tcol2sat_stdhg2stdfcs(ArithmeticProgressions(k,n))$

output_vanderwaerden2(k,n,filename) := 
  output_fcs(
    sconcat("Van der Waerden problem: 2 parts, arithmetic progressions of size ", k, ", and ", n, " elements."), 
    vanderwaerden2_fcs(k,n),
    filename)$
/* Providing a standard name: "VanDerWaerden_2-k-k_n.cnf": */
output_vanderwaerden2_stdname(k,n) := output_vanderwaerden2(k,n,
  sconcat("VanDerWaerden_2-",k,"-",k,"_",n,".cnf"))$


/* *****************************************
   * Arithmetic progressions in the primes *
   *****************************************
*/

/* Boolean formal clause-sets, whose solutions are the partitionings of 
   the set of the first n prime numbers into two parts such that none of them 
   contains an arithmetic progression of size k.
   The variables are the first n prime numbers.
*/
greentao2_fcs(k,n) := tcol2sat_stdhg2stdfcs(arithprog_primes_hg(k,n))$

/* More generally, create boolean formal clause-sets encoding the 
   partitionings of the first n prime numbers into two parts such that the
   first part (value 0) does not contain an arithmetic progression of size k1,
   whiel the second part (value 1) does not contain an arithmetic progression
   of size k2 ("nd" for "non-diagonal"):
*/
greentao2nd_fcs(k1,k2,n) := block(
 [G1 : arithprog_primes_hg(k1,n), G2 : arithprog_primes_hg(k2,n)],
  [G1[1], union(G1[2], comp_cs(G2[2]))])$

/* Output in Dimacs format (together with statistics and variable meanings):
*/

output_greentao2(k,n,filename) := block(
 [FFGT : standardise_fcs(greentao2_fcs(k,n))],
  output_fcs_v(
    sconcat("Green-Tao problem (diagonal form), 
c created by the OKlibrary at ", timedate(),":
c 2 parts, arithmetic progressions of size ", k, ", and ", n, " prime numbers.
", standard_statistics_fcs(FFGT[1]), "
c Variables and associated prime numbers:"), 
    FFGT[1],
    filename,
    FFGT[2]))$
/* Providing a standard name: "GreenTao_2-k-k_n.cnf": */
output_greentao2_stdname(k,n) := output_greentao2(k,n,
  sconcat("GreenTao_2-",k,"-",k,"_",n,".cnf"))$

output_greentao2nd(k1,k2,n,filename) := block(
 [FFGT : standardise_fcs(greentao2nd_fcs(k1,k2,n))],
  output_fcs_v(
    sconcat("Green-Tao problem (non-diagonal form),
c created by the OKlibrary at ", timedate(),": 
c 2 parts, arithmetic progressions of size ", k1, " and ", k2, ", and ", n, " prime numbers.
", standard_statistics_fcs(FFGT[1]), "
c Variables and associated prime numbers:"), 
    FFGT[1],
    filename,
    FFGT[2]))$
/* Providing a standard name: "GreenTao_2-k1-k2_n.cnf": */
output_greentao2nd_stdname(k1,k2,n) := output_greentao2nd(k1,k2,n,
  sconcat("GreenTao_2-",k1,"-",k2,"_",n,".cnf"))$


/*!
\endhtmlonly
*/
