/* Oliver Kullmann, 20.9.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/VanderWaerdenProblems.mac
  \brief Generators for clause-sets related to Van der Waerden problems

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/VanderWaerdenProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/Generators.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$
oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/Colouring.mac")$


/* Boolean formal clause-sets, whose solutions are the partitionings of 
   {1,...,n} into two parts such that none of them contains an arithmetic 
   progression of size k. */
/* (We are using "trivially generalised partitionings here, where the
    parts can be empty.) */
vanderwaerden2_fcs(k,n) := tcol2sat_stdhg2stdfcs(ArithmeticProgressions(k,n))$

output_vanderwaerden2(k,n,filename) := 
  output_fcs(
    sconcat("Van der Waerden problem: 2 parts, arithmetic progressions of size ", k, ", ", n, " elements."), 
    vanderwaerden2_fcs(k,n),
    filename)$
output_vanderwaerden2_stdname(k,n) := output_vanderwaerden2(k,n,
  sconcat("VanDerWaerden_2_",k,"_",n,".cnf"))$

/* Boolean formal clause-sets, whose solutions are the partitionings of 
   the set of the first n prime numbers into two parts such that none of them 
   contains an arithmetic progression of size k. */
greentao2_fcs(k,n) := tcol2sat_stdhg2stdfcs(arithprog_primes_hg(k,n))$

output_greentao2(k,n,filename) := block(
 [FFGT : standardise_fcs(greentao2_fcs(k,n))],
  output_fcs_v(
    sconcat("Green-Tao problem: 2 parts, arithmetic progressions of size ", k, ", ", n, " prime numbers."), 
    FFGT[1],
    filename,
    FFGT[2]))$
output_greentao2_stdname(k,n) := output_greentao2(k,n,
  sconcat("GreenTao_2_",k,"_",n,".cnf"))$


/*!
\endhtmlonly
*/
