/* Oliver Kullmann, 6.7.2008 (Swansea) */
/* Copyright 2008, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/BasicExamples.mac
  \brief Basic examples for semigroups

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/BasicExamples.mac");

*/

/*!
\htmlonly
*/


/* ********************
   * Small semigroups *
   ********************
*/

/* The empty semigroup: */
empty_sgr : [{},lambda([x,y],unknown)]$

/* The (standardised) 1-element semigroup: */
singleton_sgr : [{1}, lambda([x,y],1)]$
singleton_mon : [{1}, lambda([x,y],1), 1]$


/* *******************
   * Null semigroups *
   *******************
*/

/* The constant semigroup (with x0 as null element): */
null_sgr(X,x0) := [X,buildq([x0],lambda([x,y],x0))]$

/* The left-zero and the right-zero semigroups: */
leftnull_compo : lambda([x,y],x)$
rightnull_compo : lambda([x,y],y)$
leftnull_sgr(X) := [X,leftnull_compo]$
rightnull_sgr(X) := [X,rightnull_compo]$


/* *********************
   * Cyclic semigroups *
   *********************
*/

/* Prerequisite: index, period natural numbers >= 1. */
cyclic_sgr(index,period) := block([n : index+period-1, V],
 V : setn(n),
 buildq([V,index,period],
        [V, lambda([a,b], block([s:a+b],
          if s <= index then s
          else index + mod(s - index, period)))]))$

/*!
\endhtmlonly
*/
