/* Oliver Kullmann, 28.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/BasicOperations.mac
  \brief Tests for the basic operations with clause-sets

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/BasicOperations.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$
oklib_include("Transitional/ComputerAlgebra/DataStructures/Lisp/HashMaps.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/Generators.mac")$

kill(f)$

/* **************************
   * Variables and literals *
   **************************
*/

okltest_var_l(f) := (
  for i : 1 thru 10 do (
    assert(f(i) = i),
    assert(f(-i) = i)
  ),
  true
)$


/* *****************************
   * Substitution and renaming *
   *****************************
*/

okltest_substitute_l(f) := block([h],
  h : sm2hm({[1,3],[2,-4],[3,-3]}),
  assert(f(1,h) = 3), assert(f(-1,h) = -3),
  assert(f(2,h) = -4), assert(f(-2,h) = 4),
  assert(f(3,h) = -3), assert(f(-3,h) = 3),
  assert(f(4,h) = false), assert(f(-4,h) = -false),
  true)$

okltest_substitute_c(f) := block([h],
  h : sm2hm({[1,3],[2,-4],[3,-3]}),
  assert(f({},h) = {}),
  assert(f({1},h) = {3}), assert(f({-1},h) = {-3}),
  assert(f({2},h) = {-4}), assert(f({-2},h) = {4}),
  assert(f({3},h) = {-3}), assert(f({-3},h) = {3}),
  assert(f({1,2,3},h) = {3,-4,-3}),
  assert(f({1,2,-3},h) = {3,-4}),
  assert(f({1,2,-3,4},h) = {3,-4,4}),
  assert(f({1,2,-3,-4},h) = {3,-4}),
  assert(f({1,2,-3,5},h) = {3,-4,5}),
  true)$

okltest_substitute_cs(f) := block([h],
  h : sm2hm({[1,3],[2,-4],[3,-3]}),
  assert(f({},h) = {}),
  assert(f({{}},h) = {{}}),
  assert(f({{},{4,5}},h) = {{},{4,5}}),
  assert(f({{1,2},{1,3},{-2,3}},h) = {{3,-4},{3,-3},{4,-3}}),
  true)$

okltest_standardise_fcs(f) := block([FF],
  assert(f([{},{}]) = [[{},{}],[]]),
  assert(f([{},{{}}]) = [[{},{{}}],[]]),
  assert(f([{1},{{}}]) = [[{1},{{}}],[1]]),
  assert(f([{2,3},{{}}]) = [[{1,2},{{}}],[2,3]]),
  assert(f([{4,5,6},{{},{-4,5,6},{5},{4,-5},{-5,-6}}]) = [[{1,2,3},{{},{-1,2,3},{2},{1,-2},{-2,-3}}],[4,5,6]]),
  true)$

okltest_make_vardisjoint_fcs(f) := (
  assert(f([]) = [[],0]),
  assert(f(map(cs_to_fcs,[{},{{}},{},{{}}])) = [map(cs_to_fcs,[{},{{}},{},{{}}]), 0]),
  assert(f(map(cs_to_fcs,[{{1}},{{}},{{1}},{{}}])) = [map(cs_to_fcs,[{{1}},{{}},{{2}},{{}}]), 2]),
  assert(f(map(cs_to_fcs,[{{4}},{{2}},{{2}},{{1}}])) = [map(cs_to_fcs,[{{1}},{{2}},{{3}},{{4}}]), 4]),
  true)$


/* ***********************************
   * Selecting parts of a clause-set *
   ***********************************
*/

okltest_scls_l(f) := (
  assert(f({},1) = {}),
  assert(f({{}},1) = {}),
  assert(f({{1}},1) = {{1}}),
  assert(f({{1}},-1) = {}),
  assert(f({{1}},2) = {}),
  assert(f({{1,2},{-1,2}},1) = {{1,2}}),
  assert(f({{1,2},{-1,2}},-1) = {{-1,2}}),
  assert(f({{1,2},{-1,2}},2) = {{1,2},{-1,2}}),
  true)$

okltest_scls_v(f) := (
  assert(f({},1) = {}),
  assert(f({{}},1) = {}),
  assert(f({{1}},1) = {{1}}),
  assert(f({{1}},-1) = {}),
  assert(f({{1}},2) = {}),
  assert(f({{1,2},{-1,2}},1) = {{1,2},{-1,2}}),
  assert(f({{1,2},{-1,2}},2) = {{1,2},{-1,2}}),
  assert(f({{1,2},{-1,2}},3) = {}),
  true)$


/* ***********************
   * Partial assignments *
   ***********************
*/

okltest_satisfyingpafp(f) := (
  assert(f({},[{},{}]) = true),
  assert(f({},[{1},{}]) = true),
  assert(f({},[{},{{}}]) = false),
  assert(f({1},[{1},{{1}}]) = true),
  assert(f({1},[{1},{{-1}}]) = false),
  true)$

okltest_all_pass(f) := (
  assert(f({}) = {{}}),
  assert(f({1}) = {{},{1},{-1}}),
  assert(f({1,2}) = {{},{-1},{1},{-2},{2},{-1,-2},{-1,2},{1,-2},{1,2}}),
  for n : 0 thru 3 do
    assert(length(f(setn(n))) = 3^n),
  true)$

okltest_all_pass_n(f) := block(
  assert(f({},-1) = {}),
  assert(f({1},-1) = {}),
  assert(f({},0) = {{}}),
  assert(f({1},0) = {{}}),
  assert(f({},1) = {}),
  assert(f({1},1) = {{-1},{1}}),
  for n : 0 thru 3 do
    assert(f(setn(n),n) = full_fcs(n)[2]),
  if oklib_test_level = 0 then return(true),
  block([oklib_test_level : oklib_test_level - 1],
    okltest_all_pass(buildq([f],lambda([V],apply(union,makelist(f(V,n),n,0,length(V))))))),
  true)$

/*!
\endhtmlonly
*/
