/* Oliver Kullmann, 5.5.2008 (Guangzhou) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Constructions.mac
  \brief Tests for the basic operations with clause-sets

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Constructions.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/BasicOperations.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/Generators.mac")$

kill(f)$


/* **************************
   * Syntactical operations *
   **************************
*/

okltest_comp_cs(f) := (
  assert(f({}) = {}),
  assert(f({{}}) = {{}}),
  assert(f({{1}}) = {{-1}}),
  assert(f({{1,2},{-2,-3}}) = {{-1,-2},{2,3}}),
  true)$

/* ****************************
   * Combinatorial operations *
   ****************************
*/

okltest_vardisjoint_sum_fcs(f) := (
  assert(f() = [{},{}]),
  okltest_standardise_fcs(buildq([f],lambda([FF],[f(FF),listify(FF[1])]))),
  assert(f([{3,4},{{-3},{4}}],[{1,3},{{1,3},{-1,-3}}]) = [{1,2,3,4},{{-1},{2},{3,4},{-3,-4}}]),
  true)$

okltest_vardisjoint_full_gluing(f) := (
  assert(f([{},{}],[{},{}]) = [{},{}]),
  assert(f([{},{}],[{},{{}}]) = [{1},{{-1}}]),
  assert(f([{},{{}}],[{},{{}}]) = [{1},{{1},{-1}}]),
  assert(f([{},{}],[{1},{{1},{-1}}]) = [{1,2},{{-2,1},{-2,-1}}]),
  assert(f([{1,2},{{1},{-1,2}}],full_fcs(2)) = [{1,2,3,4,5},{{5,1},{5,-1,2},{-5,3,4},{-5,-3,4},{-5,3,-4},{-5,-3,-4}}]),
  true)$

/*!
\endhtmlonly
*/
