/* Oliver Kullmann, 4.4.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Statistics.mac
  \brief Tests for the basic operations with clause-sets

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Statistics.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac");

kill(f)$

okltest_ordered_literal_degrees_cs(f) := block(
  assert(f({}) = []),
  assert(f({{}}) = []),
  assert(f({{1}}) = [[1,1]]),
  assert(f({{-1}}) = [[-1,1]]),
  assert(f({{1},{-1}}) = [[-1,1],[1,1]]),
  assert(f({{1},{-1},{}}) = [[-1,1],[1,1]]),
  /* assert(f({{1,2},{-1},{-2},{-1,2}}) = [[-1,2],[2,2],[-2,1],[1,1]]), */
  assert(f({{1,2},{1},{1,2,3}}) = [[1,3],[2,2],[3,1]]),
true)$

/*!
\endhtmlonly
*/
