/* Oliver Kullmann, 7.6.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/NumberTheory/Lisp/testobjects/Auxiliary.mac

Use by

oklib_load("Transitional/ComputerAlgebra/NumberTheory/Lisp/testobjects/Auxiliary.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/NumberTheory/Lisp/Auxiliary.mac")$
oklib_include("Transitional/ComputerAlgebra/NumberTheory/Lisp/tests/Auxiliary.mac")$

/* **************
   * Logarithms *
   **************
*/

okltest_fld(fld);
okltest_floorlog(floorlog);

/* ******************************
   * Representations of numbers *
   ******************************
*/

okltest_str2chrl(str2chrl);

okltest_digit2int(digit2int);
okltest_int2digit(int2digit);

okltest_polyadic2int(polyadic2int);
okltest_polyadicstr2int(polyadicstr2int);

okltest_int2polyadicstr(int2polyadicstr);
okltest_int2polyadic(int2polyadic);


okltest_ext_integer_partitions(ext_integer_partitions);

okltest_pow(pow);

/*!
\endhtmlonly
*/
