/* Oliver Kullmann, 7.6.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/NumberTheory/Lisp/testobjects/Auxiliary.mac

Use by

oklib_load("OKlib/ComputerAlgebra/NumberTheory/Lisp/testobjects/Auxiliary.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/Auxiliary.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/Auxiliary.mac")$

/* **************
   * Logarithms *
   **************
*/

okltest_ld(ld);
okltest_log10(log10);

okltest_fld(fld);
okltest_cld(cld);
okltest_floorlog(floorlog);

/* ******************************
   * Representations of numbers *
   ******************************
*/

okltest_str2chrl(str2chrl);

okltest_digit2int(digit2int);
okltest_int2digit(int2digit);

okltest_polyadic2int(polyadic2int);
okltest_polyadicstr2int(polyadicstr2int);

okltest_int2polyadic(int2polyadic);
okltest_int2polyadic_padd(int2polyadic_padd);
okltest_int2polyadicstr(int2polyadicstr);

okltest_hexstr2binv(hexstr2binv);
okltest_binv2hexstr(binv2hexstr);

okltest_factoradic2int(factoradic2int);
okltest_int2factoradic(int2factoradic);

/* ************
   * Rounding *
   ************
*/

okltest_round_fdd(round_fdd);
okltest_round_bfdd(round_bfdd);

/* **********************
   * Integer partitions *
   **********************
*/

okltest_ext_integer_partitions(ext_integer_partitions);
okltest_num_ext_integer_partitions(num_ext_integer_partitions);

okltest_uinteger_partitions(uinteger_partitions);
okltest_num_uinteger_partitions(num_uinteger_partitions);

/* ***********************
   * Corrected functions *
   ***********************
*/

okltest_pow(pow);

/*!
\endhtmlonly
*/
