/* Oliver Kullmann, 5.9.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/NumberTheory/Lisp/testobjects/CalkinWilf.mac

Use by

oklib_load("OKlib/ComputerAlgebra/NumberTheory/Lisp/testobjects/CalkinWilf.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/CalkinWilf.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/CalkinWilf.mac")$

/* **********
   * Basics *
   **********
*/

okltest_calkinwilf_expand(calkinwilf_expand);
okltest_calkinwilf_reduce(calkinwilf_reduce);

okltest_calkinwilfg_lrt(calkinwilfg_lrt);
okltest_calkinwilf_lrt(calkinwilf_lrt);
okltest_calkinwilf_path(calkinwilf_path);

okltest_calkinwilf_levels(calkinwilf_levels);

okltest_calkinwilf_recursion(calkinwilf_recursion);

/*!
\endhtmlonly
*/
