/* Oliver Kullmann, 20.9.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/NumberTheory/Lisp/testobjects/PrimeNumbers.mac

Use by

oklib_load("Transitional/ComputerAlgebra/NumberTheory/Lisp/testobjects/PrimeNumbers.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/NumberTheory/Lisp/PrimeNumbers.mac")$
oklib_include("Transitional/ComputerAlgebra/NumberTheory/Lisp/tests/PrimeNumbers.mac")$


okltest_primes_interval(primes_interval);

okltest_primes_first(primes_first);

/*!
\endhtmlonly
*/
