/* Oliver Kullmann, 20.9.2008 (Swansea) */
/* Copyright 2008, 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/NumberTheory/Lisp/testobjects/PrimeNumbers.mac

Use by

oklib_load("OKlib/ComputerAlgebra/NumberTheory/Lisp/testobjects/PrimeNumbers.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/PrimeNumbers.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/PrimeNumbers.mac")$

/* **********************************
   * Finding and enumerating primes *
   **********************************
*/

okltest_primes_interval(primes_interval);

okltest_primes_first(primes_first);

okltest_unrank_primes(unrank_primes);
okltest_rank_primes(rank_primes);
okltest_count_primes(count_primes);

okltest_product_primes(product_primes);

/* **********************************
   * The Prime Number Theorem (PNT) *
   **********************************
*/

okltest_Li(Li);

/* **************************
   * Additive number theory *
   **************************
*/

okltest_n_arithprog_primes_nc(n_arithprog_primes_nc);
okltest_n_arithprog_primes_c(n_arithprog_primes_c);
okltest_ln_arithprog_primes_c(ln_arithprog_primes_c);

okltest_first_arithprog_primes(first_arithprog_primes);

/*!
\endhtmlonly
*/
