/* Oliver Kullmann, 5.8.2009 (Swansea) */
/* Copyright 2009, 2016 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/NumberTheory/Lisp/testobjects/Quadratics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/NumberTheory/Lisp/testobjects/Quadratics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/Quadratics.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/Quadratics.mac")$

/* ******************************
   * Counting integer equations *
   ******************************
*/

okltest_count_quadintsol(count_quadintsol_bydef);

/* ******************
   * Square numbers *
   ******************
*/

okltest_isquarep(isquarep);

/* *******************
   * Sums of squares *
   *******************
*/

okltest_pythtripp(pythtripp);
okltest_pythtriptp(pythtriptp);

okltest_pythtrip_hypo_bydef(pythtrip_hypo_bydef);
okltest_pythtrip_le_bydef(pythtrip_le_bydef);

okltest_pythtrip_le_byDickson(pythtrip_le_byDickson);
okltest_pythtrip_le_byDickson_sorted(pythtrip_le_byDickson_sorted);
okltest_pythtripses_le_byDickson(pythtripses_le_byDickson);

okltest_count_pythtrip_hypo_bydef(count_pythtrip_hypo_bydef);
okltest_count_pythtrip_hypo(count_pythtrip_hypo);

okltest_count_pythtrip_le_bydef(count_pythtrip_le_bydef);
okltest_count_pythtrip_le_byfact(count_pythtrip_le_byfact);
okltest_count_pythtrip_le_byDickson(count_pythtrip_le_byDickson);

/*!
\endhtmlonly
*/
