/* Oliver Kullmann, 5.8.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/NumberTheory/Lisp/testobjects/Quadratics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/NumberTheory/Lisp/testobjects/Quadratics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/Quadratics.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/tests/Quadratics.mac")$

/* ******************************
   * Counting integer equations *
   ******************************
*/

okltest_count_quadintsol(count_quadintsol_bydef);

/*!
\endhtmlonly
*/
