/* Oliver Kullmann, 18.5.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/tests/BasicExamples.mac
  \brief Tests for monoids of partial assignments

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/tests/BasicExamples.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/BasicNotions.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/Order.mac")$


/* ********************
   * Small semigroups *
   ********************
*/



/* *******************
   * Null semigroups *
   *******************
*/



/* *********************
   * Cyclic semigroups *
   *********************
*/

okltest_cyclic_sgr(f) := (
  for i : 1 thru if oklib_test_level=0 then 3 else 5 do
    for p : 1 thru if oklib_test_level=0 then 3 else 5 do block([S : f(i,p)],
      assert(sgr_p(S)),
      assert(ipo_element_sgr(S[2], 1) = [i,p,i+p-1])
  ),
  true)$


/*!
\endhtmlonly
*/
