/* Oliver Kullmann, 10.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/tests/PartialAssignments.mac
  \brief Tests for monoids of partial assignments

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/tests/PartialAssignments.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/BasicNotions.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Commutativity.mac")$
oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$
oklib_include("Transitional/ComputerAlgebra/NumberTheory/Lisp/Auxiliary.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Operations/BasicNotions.mac")$

kill(f)$

/* *******************************
   * Boolean partial assignments *
   *******************************
*/

okltest_pass_mon(f) := (
  for n : 0 thru if oklib_test_level=0 then 2 else 3 do 
   block([V : f(setn(n))],
    assert(mon_p(V) = true),
    assert(length(V[1]) = pow(3,n)),
    assert(centre_grd(V) = {{}})
  ),
  true)$

okltest_pass_sgr(f) := block(
  for n : 0 thru if oklib_test_level=0 then 2 else 3 do 
   block([V : f(setn(n))],
    assert(sgr_p(V) = true),
    assert(length(V[1]) = pow(3,n)-1),
    assert(centre_grd(V) = {})
  ),
  if oklib_test_level=0 then return(true),
  okltest_pass_mon(buildq([f],lambda([V],
    block([P:f(V)],[adjoin({},P[1]),P[2],{}])))),
  true)$

okltest_natop_pass(f) := block([x,y],
  for n : 0 thru if oklib_test_level=0 then 2 else 3 do 
   block([V : pass_mon(setn(n)), opr : f(x,y), X : union(setn(n),{x,y})],
    assert(opr_ugrdset_p(opr,V,X) = true)),
  true)$

/*!
\endhtmlonly
*/
