#!/bin/bash
# Matthew Gwynne, 5.1.2011 (Swansea)
# Copyright 2011 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.

# Script which given the path to a full Dimacs CNF file "file"
# computes all minimum CNF representations of the input CNF,
# outputting them to $(basename file .cnf)_trans$i.cnf for 1 <= i <= N where
# n is the number of minimum representations.
# The user may optionally provide a second argument specifying a lower bound on the
# size of the minimum CNFs.

# The algorithm used is
# Combinatorics/Hypergraphs/Transversals/Bounded/BoundedTransversals_bv.cpp
# searching for transversals of size 0, 1, ... .
# This script should only be used for smaller examples, due to the potentially
# large number of minimum representations, and intermediate transversals generated.

set -o errexit
set -o nounset

script_name="all_minimum_cnf"
version="0.2.5"

# Error checking
err="ERROR[${script_name}]"
if [[ $# > 2 || $# < 1 ]]; then
  echo "${err}: Takes two arguments, the path to the full Dimacs CNF file of which the minimum CNF representations should be generated and optionally a lower bound on the size of the minimum CNF representations."
  exit 1;
fi

# Argument handling
input_file=$1
if [[ $# > 1 ]]; then
  lower_bound=$2
else
  lower_bound=0
fi

# Script for generating the subsumption hypergraph and then for 
# computing the minimum transversals of the subsumption hypergraph.
subsumption_hypergraph_computation=QuineMcCluskeySubsumptionHypergraph-n16-O3-DNDEBUG
transversal_computation=BoundedTransversals_bv-O3-DNDEBUG
# We assume that ${subsumption_hypergraph_computation} outputs also the prime
# implicates to ${input}_primes where ${input} is the file given to it as input.

echo "Starting with lower bound of ${lower_bound} ..."

# Compute subsumption hypergraph and prime implicates
echo "Computing subsumption hypergraph ..."
subsumption_hypergraph_file=$(mktemp)
prime_implicates_file=${input_file}_primes # Automatically created
${subsumption_hypergraph_computation} ${input_file} > ${subsumption_hypergraph_file}

# Compute transversals and then extract the CNFs from the prime clauses using the result.
echo "Computing bounded transversals ..."
transversal_file=$(mktemp)
transversals_file=$(mktemp)
${transversal_computation} ">=${lower_bound}" < ${subsumption_hypergraph_file}  | grep -v "^[pc]" > ${transversals_file}
num_transversals=$(wc -l ${transversals_file})
count=0; current_transversal=1
cat ${transversals_file} |  while read transversal; do
      echo "Translating assignment for transversal [${current_transversal}/${num_transversals}] ..."
      count=$(expr ${count} + 1)
      echo ${transversal} > ${transversal_file}
      cat ${prime_implicates_file} | FilterDimacs-O3-DNDEBUG ${transversal_file} > "$(basename ${input_file} .cnf)_trans${count}.cnf"
  done
temporary_files="${subsumption_hypergraph_file} ${prime_implicates_file} ${transversal_file} ${transversals_file}"
rm ${temporary_files}
