/* Matthew Gwynne, 17.1.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/tests/Basics.mac
  \brief Tests for boolean function translations

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/tests/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$


kill(f)$

/***********************************************
 * Random boolean functions                    *
 ***********************************************
*/


okltest_random_subset(f) := block(
  assert(f({}) = {}),
  set_random(1),
  assert(f({1}) = {1}),
  assert(f({1}) = {1}),
  assert(f({1}) = {}),
  assert(f({1,2,3}) = {2,3}),
  if oklib_test_level = 0 then return(true),
  for i : 0 thru 500 do
    assert(subsetp(f({1,2,3,4,5,6,7,8}),{1,2,3,4,5,6,7,8})),
  true)$

okltest_random_boolf_fcs(f) := block(
  set_random(1),
  assert(f(0) = [{},{{}}]),
  assert(f(1) = [{1},{{-1}}]),
  assert(f(2) = [{1,2},{{-2,1},{-1,2},{1,2}}]),
  assert(f(3) = [{1,2,3},{{-3,-2,-1},{-3,-2,1},{-2,-1,3},{-1,2,3},{1,2,3}}]),
  true)$

okltest_random_bal_boolf_fcs(f) := block(
  set_random(1),
  assert(f(1) = [{1},{{1}}]),
  assert(f(2) = [{1,2},{{-2,-1},{1,2}}]),
  assert(f(3) = [{1,2,3},{{-3,-2,-1},{-3,-1,2},{-3,1,2},{-2,-1,3}}]),
  if oklib_test_level = 0 then return(true),
  for i : 0 thru 500 do
    assert(length(f(3)[2]) = 4),
  for i : 0 thru 500 do
    assert(length(f(5)[2]) = 16),
  true)$

/*!
\endhtmlonly
*/
