/* Matthew Gwynne, 15.12.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
\file ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/tests/Permutations.mac
  \brief Tests for the analysis functions of permutations as boolean functions

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/tests/Permutations.mac");

*/

/*!
\htmlonly
*/

/* *************************************
   * Permutations as boolean functions *
   *************************************
*/

okltest_bv2c(f) := block(
  /* XXX */
  true)$

okltest_perm2dnffcl(f) := block(
  /* XXX */
  true)$

okltest_perm2dnffcs(f) := block(
  /* XXX */
  true)$

okltest_perm2cnffcs(f) := block(
  /* XXX */
  true)$

/*!
\endhtmlonly
*/