/* Oliver Kullmann, 24.12.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
\file ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/tests/TseitinTranslation.mac
  \brief Tests regarding the Tseitin translation

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/tests/TseitinTranslation.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$


kill(f)$


/* ****************************
   * Translating DNF into CNF *
   ****************************
*/

okltest_dualts_fcl(f) := (
  assert(f([[],[]]) = [[],[{}]]),
  assert(f([[3,1],[]]) = [[3,1],[{}]]),
  assert(f([[],[{}]]) = [[dts(1)],[{dts(1)},{dts(1)}]]),
  assert(f([[3,1],[{}]]) = [[3,1,dts(1)],[{dts(1)},{dts(1)}]]),
  assert(f([[3,1],[{},{1,3},{-3},{-1,-3}]]) = [
   [3,1,dts(1),dts(2),dts(3),dts(4)],
   [{dts(1)}, {-1,-3,dts(2)}, {3,dts(3)}, {1,3,dts(4)},
    {-dts(2),1}, {-dts(2),3}, {-dts(3),-3}, {-dts(4),-3},{-dts(4),-1},
    {dts(1),dts(2),dts(3),dts(4)}
   ]]),
  true)$

okltest_dualtsext_fcl(f) := block([x],
  assert(f([[],[]],x) = [[],[{}]]),
  assert(f([[3,1],[]],x) = [[3,1],[{}]]),
  assert(f([[],[{}]],x) = [[dts(1,x)],[{dts(1,x)},{dts(1,x)}]]),
  assert(f([[3,1],[{}]],x) = [[3,1,dts(1,x)],[{dts(1,x)},{dts(1,x)}]]),
  assert(f([[3,1],[{},{1,3},{-3},{-1,-3}]],1) = [
   [3,1,dts(1,1),dts(2,1),dts(3,1),dts(4,1)],
   [{dts(1,1)}, {-1,-3,dts(2,1)}, {3,dts(3,1)}, {1,3,dts(4,1)},
    {-dts(2,1),1}, {-dts(2,1),3}, {-dts(3,1),-3}, {-dts(4,1),-3},{-dts(4,1),-1},
    {dts(1,1),dts(2,1),dts(3,1),dts(4,1)}
   ]]),
  true)$

/*!
\endhtmlonly
*/
