/* Oliver Kullmann, 16.3.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/tests/Basics.mac
  \brief Tests for transversal-functions

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/CombinatorialMatrices/Lisp/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Generators.mac")$
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Generators.mac")$

kill(f)$

/* **************
   * Promotions *
   **************
*/

okltest_hg2ohg(f) := (
  assert(f([{},{}]) = [[],[]]),
  assert(f([{},{{}}]) = [[],[{}]]),
  assert(f([{1},{}]) = [[1],[]]),
  assert(f([{1},{{}}]) = [[1],[{}]]),
  assert(f([{1},{{},{1}}]) = [[1],[{},{1}]]),
  true)$


/* *************
   * Downcasts *
   *************
*/

okltest_ghg2hg(f) := (
  assert(f([{},{},identity]) = [{},{}]),
  assert(f([{1},{},identity]) = [{1},{}]),
  assert(f([{},{1},lambda([H],{})]) = [{},{{}}]),
  assert(f([{1,2},{1,2,3},lambda([e],if e<=2 then {1,2} else {2,3})]) = [{1,2},{{1,2},{2,3}}]),
  true)$


/* ************* **
   * Conversions *
   ***************
*/

okltest_setsystem2hg(f) := (
  assert(f({}) = [{},{}]),
  assert(f({{}}) = [{},{{}}]),
  assert(f({{1}}) = [{1},{{1}}]),
  assert(f({{},{1},{1,2}}) = [{1,2},{{},{1},{1,2}}]),
  true)$

okltest_listsets2hg(f) := (
  assert(f([]) = [{},{}]),
  assert(f([{}]) = [{},{{}}]),
  assert(f([{1}]) = [{1},{{1}}]),
  assert(f([{},{1},{1,2}]) = [{1,2},{{},{1},{1,2}}]),
  true)$

okltest_listsets2oghg(f) := (
  assert(f([]) = [[],[],identity]),
  assert(f([{}]) = [[],[{}],identity]),
  assert(f([{1}]) = [[1],[{1}],identity]),
  assert(f([{1,2},{-3,1},{3,2}]) = [[-3,1,2,3],[{1,2},{-3,1},{2,3}],identity]),
  true)$

okltest_edge_vertex_com_hyp(f) := (
  assert(comequalp(f([{},{}]), emptycom) = true),
  assert(comequalp(f([{},{{}}]), zerocom({{}},{})) = true),
  assert(comequalp(f([{1},{}]), zerocom({},{1})) = true),
  assert(comequalp(f([{1},{{}}]), zerocom({{}},{1})) = true),
  assert(comequalp(f([{1},{{1}}]), constantcom({{1}},{1},1)) = true),
  assert(comequalp(f([{1,2},{{1}}]), [{{1}},{1,2},lambda([H,v],if v=1 then 1 else 0)]) = true),
true)$

okltest_edge_int_com_hyp(f) := (
  assert(scomequalp(f([{},{}]), emptyscom) = true),
  assert(scomequalp(f([{},{{}}]), zeroscom({{}})) = true),
  assert(scomequalp(f([{1,2},{{}}]), zeroscom({{}})) = true),
  assert(scomequalp(f([{1},{{1}}]), constantscom({{1}},1)) = true),
  assert(scomequalp(f([{1},{{1},{}}]), [{{1},{}},lambda([H1,H2], if emptyp(H1) or emptyp(H2) then 0 else 1)]) = true),
  assert(scomequalp(f([{1,2},{{1},{2}}]), [{{1},{2}},lambda([H1,H2], if H1 = H2 then 1 else 0)]) = true),
  assert(scomequalp(f([{1,2},{{1},{1,2}}]), [{{1},{1,2}},lambda([H1,H2], if H1 = {1} or H2 = {1} then 1 else 2)]) = true),
  true)$

okltest_vertex_int_com_hyp(f) := (
  assert(scomequalp(f([{},{}]), emptyscom) = true),
  assert(scomequalp(f([{},{{}}]), emptyscom) = true),
  assert(scomequalp(f([{1,2},{{}}]), zeroscom({1,2})) = true),
  assert(scomequalp(f([{1},{{1}}]), constantscom({1},1)) = true),
  assert(scomequalp(f([{1},{{1},{}}]), constantscom({1},1)) = true),
  assert(scomequalp(f([{1,2},{{1},{2}}]), [{1,2},lambda([v1,v2], if v1 = v2 then 1 else 0)]) = true),
  assert(scomequalp(f([{1,2},{{1},{1,2}}]), [{1,2},lambda([v1,v2], if v1 = 1 and v2 = 1 then 2 else 1)]) = true),
  true)$


/* *****************
   * Constructions *
   *****************
*/

okltest_union_hg(f) := (
  assert(f() = [{},{}]),
  for n : 0 thru 3 do
    assert(apply(f,create_list([{},{}],i,1,n)) = [{},{}]),
  assert(f([{1,2,3},{{1,2},{2,3}}],[{2,3,4},{{2,4},{3}}]) = [{1,2,3,4},{{1,2},{2,3},{2,4},{3}}]),
  true)$

okltest_edge_k_hyp(f) := (
  for n : 0 thru 2 do
    assert(f([{},{}],n) = [{},{}]),
  for n : 0 thru 2 do
    assert(f([{},{{}}],n) = [{{}},{}]),
  for n : 0 thru 2 do
    assert(f([{1},{}],n) = [{}, if n=0 then {{}} else {}]),
  for n : 0 thru 2 do
    assert(f([{1},{{}}],n) = [{{}}, if n=0 then {{}} else {}]),
  /* XXX */
  true)$

okltest_edge_g_hyp(f) := (
  /* XXX */
  assert(f([{1,2,3,4},{{1},{2},{1,2},{2,3}}]) = [{{1},{2},{1,2},{2,3}}, {{{1},{1,2}},{{2},{1,2}},{{2},{2,3}},{{1,2},{2,3}}}]),
  true)$

okltest_anti_edge_k_hyp(f) := (
  assert(okltest_edge_k_hyp(buildq([f], lambda([G,k], block([E:f(G,k)], [E[1], setdifference(powerset(G[2],k),E[2])])))) = true),
  true)$

okltest_kneser_g_hyp(f) := (
  /* XXX */
  assert(okltest_kneser_g(buildq([f], lambda([n,m], kneser_g_hyp(complete_stdhg(n,m))))) = true),
  true)$


/* *****************
   * Connectedness *
   *****************
*/



/*!
\endhtmlonly
*/
