/* Oliver Kullmann, 22.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/tests/Colouring.mac
  \brief Tests for transversal-functions

Use by

oklib_load("Transitional/ComputerAlgebra/Hypergraphs/Lisp/tests/Colouring.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/Basics.mac")$


kill(f)$

/* ***********************
   * Translations to SAT *
   ***********************
*/

okltest_tcol2sat_hg2fcs(f) := (
  assert(f([{},{}]) = [{},{}]),
  assert(f([{},{{}}]) = [{},{{}}]),
  assert(f([{1},{{},{1}}]) = [{colv(1)},{{},{colv(1)},{-colv(1)}}]),
  assert(f([{1,2},{{1},{1,2}}]) = [{colv(1),colv(2)},{{colv(1)},{colv(1),colv(2)},{-colv(1)},{-colv(1),-colv(2)}}]),
  true)$

okltest_tcol2sat_stdhg2stdfcs(f) := (
  assert(f([{},{}]) = [{},{}]),
  assert(f([{},{{}}]) = [{},{{}}]),
  assert(f([{1},{{},{1}}]) = [{1},{{},{1},{-1}}]),
  assert(f([{1,2},{{1},{1,2}}]) = [{1,2},{{1},{1,2},{-1},{-1,-2}}]),
  true)$

okltest_tcol2sat_ohg2fcl(f) := (
  assert(f([[],[]]) = [[],[]]),
  assert(f([[],[{}]]) = [[],[{},{}]]),
  assert(f([[1],[{},{1}]]) = [[colv(1)],[{},{colv(1)},{},{-colv(1)}]]),
  assert(f([[2,1],[{1},{1,2}]]) = [[colv(2),colv(1)],[{colv(1)},{colv(1),colv(2)},{-colv(1)},{-colv(1),-colv(2)}]]),
  assert(okltest_tcol2sat_hg2fcs(buildq([f],lambda([G],fcl2fcs(f(hg2ohg(G))))))),
  true)$

okltest_tcol2sat_stdohg2stdfcl(f) := (
  assert(f([[],[]]) = [[],[]]),
  assert(f([[],[{}]]) = [[],[{},{}]]),
  assert(f([[2],[{2},{}]]) = [[2],[{2},{},{-2},{}]]),
  assert(f([[2,1],[{1},{1,2}]]) = [[2,1],[{1},{1,2},{-1},{-1,-2}]]),
  assert(okltest_tcol2sat_stdhg2stdfcs(buildq([f],lambda([G],fcl2fcs(f(hg2ohg(G))))))),
  true)$


/*!
\endhtmlonly
*/
