/* Oliver Kullmann, 2.11.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/tests/Homomorphisms.mac
  \brief Tests for homomorphisms-related functions

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/Homomorphisms.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$


kill(f)$


/* *****************
   * Basic notions *
   *****************
*/

okltest_homomorphism_bydef_hg(f) := (
  assert(f(identity,[{},{}],[{},{}]) = true),
  assert(f(identity,[{},{}],[{},{{}}]) = true),
  assert(f(identity,[{},{{}}],[{},{}]) = false),
  assert(f(identity,[{1},{}],[{},{}]) = false),
  assert(f(identity,[{1},{}],[{1},{}]) = true),
  assert(f(identity,[{1},{}],[{1,2},{{}}]) = true),
  assert(f(lambda([x],x-1), [{1,2,3},{{1},{2,3},{1,3}}],[{0,1,2},{{0},{1,2},{0,2}}]) = true),
  assert(f(lambda([x],x-1), [{1,2,3},{{1},{2,3},{1,3}}],[{0,1,2},{{0},{1,2},{0,1}}]) = false),
  true)$

okltest_transport_hg(f) := (
  assert(f(identity,[{},{}]) = [{},{}]),
  assert(f(identity,[{1,2},{{},{1},{2}}]) = [{1,2},{{},{1},{2}}]),
  assert(f(lambda([x],1), [{1,2,3},{{1,2},{2,3}}]) = [{1},{{1}}]),
  true)$


/* **************************
   * Special transport-maps *
   **************************
*/

okltest_colouring_blocks(f) := (
  /* XXX */
  true)$

okltest_random_colouring(f) := (
  /* XXX */
  true)$

okltest_random_projection_hg(f) := (
  /* XXX */
  true)$

okltest_modulo_projection_hg(f) := (
  assert(f([{},{}],1) = [{},{}]),
  assert(f([{1,3,5,6},{{1,3},{3,6},{1,6}}],2) = [{1,2},{{1},{1,2}}]),
  assert(f([{1,2,3,4},{{1,2},{1,3},{2,4},{1,3,4}}],3) = [{1,2,3},{{1,2},{1,3}}]),
  /* XXX */
  true)$

/*!
\endhtmlonly
*/
