/* Oliver Kullmann, 9.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/tests/IndependentSets.mac
  \brief Tests for independence-hypergraphs

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/IndependentSets.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac");
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/Transversals.mac");
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Basics.mac");
kill(f)$

/* Testing whether f computes the independence hypergraph */
okltest_independence_hyp(f) := block(
  assert(f([{},{}]) = [{},{{}}]),
  assert(f([{},{{}}]) = [{},{}]),
  assert(f([{1,2},{{1}}]) = [{1,2},{{2}}]),
  if oklib_test_level = 0 then return(true),
  block([oklib_test_level : min(oklib_test_level-1, 2)],
    okltest_transversal_hyp(buildq([f],lambda([G],ecomp_hyp(f(G)))))
  ),
true)$


/*!
\endhtmlonly
*/
