/* Oliver Kullmann, 27.3.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/tests/SetSystems.mac
  \brief Tests for transversal-functions

Use by

oklib_load("Transitional/ComputerAlgebra/Hypergraphs/Lisp/tests/SetSystems.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$


kill(f)$

/* **************
   * Singletons *
   **************
*/

okltest_singletonp(f) := (
  assert(f({}) = false),
  assert(f({1}) = true),
  assert(f({1,2}) = false),
  true)$

okltest_single_element(f) := (
  assert(f({1}) = 1),
  assert(f({{}}) = {}),
  true)$


/*!
\endhtmlonly
*/
