/* Oliver Kullmann, 27.3.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/tests/SetSystems.mac
  \brief Tests for transversal-functions

Use by

oklib_load("Transitional/ComputerAlgebra/Hypergraphs/Lisp/tests/SetSystems.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$


kill(f)$

/* **************
   * Singletons *
   **************
*/

okltest_singletonp(f) := (
  assert(f({}) = false),
  assert(f({1}) = true),
  assert(f({1,2}) = false),
  true)$

okltest_single_element(f) := (
  assert(f({1}) = 1),
  assert(f({{}}) = {}),
  true)$

okltest_choose_element(f) := (
  assert(f({1}) = 1),
  assert(elementp(f({1,2}),{1,2}) = true),
  true)$


/* *********************
   * Set constructions *
   *********************
*/

okltest_setn(f) := (
  assert(f(0) = {}),
  assert(f(1) = {1}),
  assert(f(2) = {1,2}),
  assert(f(-1) = {}),
  true)$

okltest_setmn(f) := (
  okltest_setn(buildq([f],lambda([n],f(1,n)))),
  assert(f(0,0) = {0}),
  assert(f(2,5) = {2,3,4,5}),
  assert(f(2,1) = {}),
  assert(f(-3,-4) = {}),
  assert(f(-4,-3) = {-4,-3}),
  true)$


/* **********************************
   * Constructions related to union *
   **********************************
*/

okltest_set_system_union(f) := (
  assert(f({}) = {}),
  assert(f({{}}) = {}),
  assert(f({{1,2},{2,3},{3,4}}) = {1,2,3,4}),
  true)$

okltest_list_sets_union(f) := (
  assert(f([]) = {}),
  assert(f([{}]) = {}),
  assert(f([{1,2},{2,3},{3,4}]) = {1,2,3,4}),
  true)$

okltest_cunion(f) := (
  assert(f({},{{1,2}}) = {}),
  assert(f({{}},{{1,2}}) = {{1,2}}),
  assert(f({{1,2},{2,3}},{{3,4},{4,5}}) = {{1,2,3,4},{1,2,4,5},{2,3,4},{2,3,4,5}}),
  true)$

okltest_add_element(f) := (
  assert(f(1,{}) = {}),
  assert(f(1,{{}}) = {{1}}),
  assert(f(1,{{1},{2,3}}) = {{1},{1,2,3}}),
  true)$


/* ********************************************
   * Constructions related to complementation *
   ********************************************
*/

okltest_ecomp(f) := (
  assert(f({},{}) = {}),
  assert(f({},{1}) = {}),
  assert(f({{}},{}) = {{}}),
  assert(f({{}},{1}) = {{1}}),
  assert(f({{1},{2}},{1,2,3}) = {{2,3},{1,3}}),
  true)$

okltest_setdifference2(f) := (
  assert(f({},{}) = {}),
  assert(f({{1},{}},{}) = {{1},{}}),
  assert(f({{1},{}},{2}) = {{1},{}}),
  assert(f({{1,2},{2,3}},{1}) = {{2},{2,3}}),
  assert(f({{1,2},{2,3}},{1,2,3}) = {{}}),
  assert(f([],{}) = []),
  assert(f([{1},{}],{}) = [{1},{}]),
  assert(f([{1},{}],{2}) = [{1},{}]),
  assert(f([{1,2},{2,3}],{1}) = [{2},{2,3}]),
  assert(f([{1,2},{2,3}],{1,2,3}) = [{},{}]),
  true)$


/* **************************************************
   * Constructions related to the cartesian product *
   **************************************************
*/

okltest_corr_cartesian_product(f) := (
  assert(f() = {[]}),
  assert(f({}) = {}),
  assert(f({1,3}) = {[1],[3]}),
  assert(f({-1,-2},{2}) = {[-1,2],[-2,2]}),
  true)$

okltest_cartesian_product_l(f) := (
  assert(f([]) = [[]]),
  assert(f([[]]) = []),
  assert(f([[1]]) = [[1]]),
  assert(f([[2,1]]) = [[2],[1]]),
  assert(f([[1],[]]) = []),
  assert(f([[1,2],[-3,-4]]) = [[1,-3],[1,-4],[2,-3],[2,-4]]),
  assert(okltest_corr_cartesian_product(buildq([f],lambda([[S]],setify(f(map(listify,S))))))),
  true)$

okltest_all_transformations_l(f) := (
  assert(f({}) = {[]}),
  assert(f({2}) = {[2]}),
  assert(f({-1,1}) = {[-1,-1],[-1,1],[1,-1],[1,1]}),
  assert(length(f({0,2,4})) = 27),
  true)$

okltest_all_transformations_l_l(f) := (
  assert(f([]) = [[]]),
  assert(f([2,1]) = [[2,2],[2,1],[1,2],[1,1]]),
  assert(okltest_all_transformations_l(buildq([f],lambda([X],setify(f(listify(X))))))),
  true)$


/* *****************************************
   * Constructions related to subsumption  *
   *****************************************
*/

okltest_min_elements(f) := (
  assert(f({}) = {}),
  assert(f({{}}) = {{}}),
  assert(f({{1},{2}}) = {{1},{2}}),
  assert(f({{1,2},{1,2,4},{3},{3,4},{5,6}}) = {{1,2},{3},{5,6}}),
  for n : 0 thru 3 do
    assert(f(powerset(setn(n))) = {{}}),
  true)$

okltest_max_elements(f) := (
  assert(f({}) = {}),
  assert(f({{}}) = {{}}),
  assert(f({{1},{2}}) = {{1},{2}}),
  assert(f({{1,2},{1,2,4},{3},{3,4},{5,6}}) = {{1,2,4},{3,4},{5,6}}),
  for n : 0 thru 3 do
    assert(f(powerset(setn(n))) = {setn(n)}),
  true)$

/*!
\endhtmlonly
*/
