/* Oliver Kullmann, 5.7.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/tests/Statistics.mac
  \brief Tests for hypergraph statistics functions

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/Statistics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$


kill(f)$

/* ******************
   * Basic measures *
   ******************
*/

okltest_nhyp_list_ohg(f) := (
  assert(f([[],[]]) = []),
  assert(f([[],[{}]]) = [[0,1]]),
  assert(f([[1,2,3],[{1},{},{1,2},{},{1,2,3},{2,3},{2}]]) = [[0,2],[1,2],[2,2],[3,1]]),
  true)$


/* ******************
   * Vertex degrees *
   ******************
*/


/*!
\endhtmlonly
*/
