/* Oliver Kullmann, 18.10.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/tests/Stratification.mac
  \brief Tests for functions related to stratification

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/Stratification.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$


kill(f)$


/* **********************************
   * Strata in monotone hypergraphs *
   **********************************
*/

okltest_sizes_strata_mon_ohg(f) := block([V],
  assert(f([V,[]]) = []),
  assert(f([V,[{1,2,3}]]) = [[3,1]]),
  assert(f([V,[{-1,-3,-5}]]) = [[-1,1]]),
  assert(f([V,[{3,4,5},{2,-1,5}]]) = [[5,2]]),
  assert(f([V,[{0,2,4},{2,4,6}]]) = [[4,1],[6,1]]),
  assert(f([V,[{0,2,4},{2,4,6},{-1,-2,6}]]) = [[4,1],[6,2]]),
  true)$

okltest_sizes_strata_indmon_ohg(f) := (
  assert(f([[],[]]) = []),
  assert(f([[1,2,3],[{1,2,3}]]) = [[3,1]]),
  assert(f([[-5,-3,-1],[{-1,-3,-5}]]) = [[3,1]]),
  assert(f([[-5,-3,-1,1],[{-1,-3,-5}]]) = [[3,1]]),
  assert(f([[-1,2,3,4,5],[{3,4,5},{2,-1,5}]]) = [[5,2]]),
  assert(f([[0,2,4,6],[{0,2,4},{2,4,6}]]) = [[3,1],[4,1]]),
  assert(f([[0,2,4,6],[{0,2,4},{2,4,6},{-1,-2,6}]]) = [[3,1],[4,2]]),
  true)$

okltest_accumulate_l(f) := block([x,y,a,b],
  assert(f([]) = []),
  assert(f([[x,y]]) = [[x,y]]),
  assert(f([[a,x],[b,y]]) = [[a,x],[b,x+y]]),
  true)$


/* *************************************
   * Stratifying arbitrary hypergraphs *
   *************************************
*/

okltest_strata_ses(f) := (
  /* XXX */
  true)$


/* **************
   * Heuristics *
   **************
*/



/*!
\endhtmlonly
*/
