/* Matthew Gwynne, 16.7.2009 (Swansea) */
/* Copyright 2009, 2010, 2018 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/PseudoBoolean/testobjects/CardinalityConstraints.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/PseudoBoolean/testobjects/CardinalityConstraints.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/PseudoBoolean/CardinalityConstraints.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/PseudoBoolean/tests/CardinalityConstraints.mac")$

/* ***************************************
   * Simplifying cardinality constraints *
   ***************************************
*/

okltest_crd2scrd(crd2scrd);
okltest_scrd2crd(scrd2crd);

okltest_remove_tautologies_scrd(remove_tautologies_scrd);

/* **********************
   * Direct translation *
   **********************
*/

okltest_direct_crd2cl(direct_crd2cl);
okltest_direct_crd2cl_lt(direct_crd2cl_lt);
okltest_direct_crd2cl_ge(direct_crd2cl_ge);

/* ************************
   * Using unary encoding *
   ************************
*/

okltest_unary_bb_totaliser_fcl(unary_bb_totaliser_fcl);
okltest_unary_bb_totaliser_r_fcl(unary_bb_totaliser_r_fcl);
okltest_unary_bb_comparator_fcl(unary_bb_comparator_fcl);
okltest_unary_bb_crd2fcl(unary_bb_crd2fcl);

/* ********************
   * AMO translations *
   ********************
*/

okltest_direct_amo2cl(direct_amo2cl);
okltest_direct_alo2cl(direct_alo2cl);
okltest_direct_eo2cl(direct_eo2cl);

okltest_represents_amo_p(represents_amo_p);
okltest_represents_eo_p(represents_eo_p);

okltest_amo_tass(amo_tass);
okltest_uep_amo_apply(uep_amo_apply);
okltest_uep_amo_p(uep_amo_p);

/*!
\endhtmlonly
*/
