/* Oliver Kullmann, 4.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Quasigroups/testobjects/Basics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Quasigroups/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Quasigroups/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Quasigroups/tests/Basics.mac")$

/* ***************
   * Conversions *
   ***************
*/

okltest_comls2qgrp(comls2qgrp);
okltest_ls2qgrp(ls2qgrp);
okltest_rls2uqgrp(rls2uqgrp);

/*!
\endhtmlonly
*/
