# Matthew Gwynne, 16.1.2011 (Swansea)
# Copyright 2011 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version.

# Required for add_constant_column in read_experiment_dirs
oklib_load("OKlib/Experimentation/ExperimentSystem/ControllingLocalSearch/DataCollection.R")

# #######################################################
# # Evaluation functions for series of experiment files #
# #######################################################

# Takes a directory prefix, a list of parameter names, and a filename
# exp_filename and returns a data.frame containing the data from
# exp_filename in every directory in the current working directory with the
# prefix followed by an arbitrary number of underscore separated parameters
# as the name.
#
# The parameters in the filename are added to the data.frame as a column
# with the name given by the associated element of the parameter name list.
read_experiment_dirs = function(prefix, param_names, exp_filename, ...) {
  prefix_dirs = dir(pattern=paste(prefix,".*",sep=""))
  prefix_dirs = Filter(function(d) file.info(d)["isdir"][[1]], prefix_dirs)
  result_df = NULL
  num_processed_dirs = 0
  for (dir in prefix_dirs) {
    if (file.info(dir)["isdir"][[1]]) {
      param_string = substring(dir, nchar(prefix)+2)
      parameters = unlist(strsplit(param_string, "_"))
      
      dir_df = tryCatch(
        read.table(paste(dir,"/",exp_filename,sep=""),...),
        error = function(e) NULL, warning=function(e) NULL)
      if (!is.null(dir_df)) {
        print(
              paste("[",num_processed_dirs,"/", length(prefix_dirs),
                    "]: Reading ", paste(dir,"/",exp_filename,".",sep="")))
        for (i in 1:length(parameters)) {
          dir_df = add_constant_column(dir_df, parameters[i], param_names[i])
        }
        num_processed_dirs = num_processed_dirs + 1
      } else {
        print(paste(
                    "WARNING[read_experiment_dirs]: Skipping '",
                    dir,"/",exp_filename,"' due to error.", sep=""))
      }
      
      result_df = rbind(result_df,dir_df)
    }
  }
  print(paste("Processed [",
              num_processed_dirs, "/", length(prefix_dirs),
              "] experiment directories.",sep=""))
  return(result_df)
}
# For example, if we have files generated by
#
# shell> ${OKlib}/Experimentation/Investigations/BooleanFunctions/analyse_random_permutations 2 1 5
#
# then run:
#
# R> E = read_experiment_dirs("random_perm", list("e","seed"), "Permutation_full.cnf_primes_stats", header=TRUE, skip=2)
#
# then we have:
#
# R> summary(E)
#      length      count   e      seed 
# Min.   :0   Min.   :0   2:25   1:5  
# 1st Qu.:1   1st Qu.:0          2:5  
# Median :2   Median :0          3:5  
# Mean   :2   Mean   :2          4:5  
# 3rd Qu.:3   3rd Qu.:2          5:5  
# Max.   :4   Max.   :8   
#
#
# Notice that each of the files we read contains header information and
# 2 lines at the top which we ignore. We therefore pass arguments "header"
# and "skip" to read_experiment_dirs which are then passed to each read.table
# call.
#
#
