#!/bin/bash
# Oliver Kullmann, 8.9.2011 (Swansea)
# Copyright 2011 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version.

# "Random" prints a ("true") random string of length 10, containing
# digits (0-9) and letters (a-z,A_Z).

# Optional arguments (positional):

# Random N pattern total

# N: number of characters; e.g. "Random 20" will print 20 random characters.

# pattern: the characters which are let through, default is "a-z0-9A-Z".
#   E.g. "Random 8 0-9" will print 8 random digits.

# total: the total number of random characters extracted from the random
# source, with default-value 500; needs to be set higher if N is larger,
# e.g., "Random 200 a-z0-9A-Z 1000".

set -o errexit
set -o nounset

script_name="Random"
version_number=0.0.6

N=${1:-10}
pattern=${2:-"a-z0-9A-Z"}
total=${3:-500}

result=$(head -c ${total} /dev/urandom | tr -dc "${pattern}" | head -c $N)
length=${#result}

if [[ ${length} -lt ${N} ]]; then
  echo -e "ERROR[${script_name}]: Only ${length} characters could be produced,\n"\
    " not ${N} as requested. Use the third argument."
  exit 1
fi

echo "${result}"

exit 0
