/* Oliver Kullmann, 30.12.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/testobjects/GreenTaoProblems.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/testobjects/GreenTaoProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/GreenTaoProblems.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/tests/GreenTaoProblems.mac")$

/* *****************************************
   * Arithmetic progressions in the primes *
   *****************************************
*/

okltest_greentao2_fcs(greentao2_fcs);
okltest_greentao2nd_fcs(greentao2nd_fcs);

okltest_greentao_nbfclud(greentao_nbfclud);
okltest_greentao_nbfcsud(greentao_nbfcsud);

okltest_greentaod_nbfclud(greentaod_nbfclud);
okltest_greentaod_nbfcsud(greentaod_nbfcsud);

/* ****************************************
   * Translation into boolean clause-sets *
   ****************************************
*/


/* *********************
   * Symmetry breaking *
   *********************
*/

okltest_greentao2_sb_fcs(greentao2_sb_fcs);

okltest_greentao_sb_fcs(greentao_sb_fcs);

okltest_greentaod_sb_nbfcsud(greentaod_sb_nbfcsud);


/* ************************
   * Statistics functions *
   ************************
*/


/* ********************
   * Output functions *
   ********************
*/


/*!
\endhtmlonly
*/
