/* Oliver Kullmann, 4.9.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/testobjects/RamseyProblems.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/testobjects/RamseyProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/RamseyProblems.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/tests/RamseyProblems.mac")$

okltest_ramsey2_ofcs(ramsey2_ofcs);
/*okltest_ramsey2_stdofcs(ramsey2_stdofcs);*/
okltest_ramsey_nbfclud(ramsey_nbfclud);
okltest_ramsey_stdnbfclud(ramsey_stdnbfclud);
okltest_ramsey_ofcs(ramsey_ofcs);
okltest_ramsey_stdofcs(ramsey_stdofcs);
okltest_ramsey2_symbr2_cs(ramsey2_symbr2_cs);
okltest_ramsey2_symbr2_stdcs(ramsey2_symbr2_stdcs);
okltest_ramsey_symbr2_nbfclud(ramsey_symbr2_nbfclud);
okltest_ramsey_symbr2_stdnbfclud(ramsey_symbr2_stdnbfclud);
okltest_ramsey_symbr2_fcl(ramsey_symbr2_fcl);
okltest_ramsey_symbr2_stdfcl(ramsey_symbr2_stdfcl);
okltest_ramsey_symbr2_eqs(ramsey_symbr2_eqs);
okltest_ramsey2_sym_break_rec(ramsey2_sym_break_rec);

/*!
\endhtmlonly
*/
