/* Oliver Kullmann, 19.4.2009 (Swansea) */
/* Copyright 2009, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/testobjects/SchurProblems.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/testobjects/SchurProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/SchurProblems.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/tests/SchurProblems.mac")$

/* *****************
   * Schur triples *
   *****************
*/

okltest_schur_nbfcsud(schur_nbfcsud);

okltest_nvar_schur_nbfcsud(nvar_schur_nbfcsud);
okltest_nval_schur_nbfcsud(nval_schur_nbfcsud);
okltest_ncl_list_schur_nbfcsud(ncl_list_schur_nbfcsud);
okltest_ncl_schur_nbfcsud(ncl_schur_nbfcsud);

/* *********************
   * Symmetry breaking *
   *********************
*/

okltest_schur_sb_nbfcsud(schur_sb_nbfcsud);

okltest_schur_fullsb_nbcl(schur_fullsb_nbcl);
okltest_wschur_fullsb_nbcl(wschur_fullsb_nbcl);

/* ****************************
   * Heuristical restrictions *
   ****************************
*/

okltest_schur_rm_nbfclud(schur_rm_nbfclud);

/* ****************************************
   * Translation into boolean clause-sets *
   ****************************************
*/
okltest_schur_aloamo_fcl(schur_aloamo_fcl);

okltest_nvar_schur_aloamo_fcl(nvar_schur_aloamo_fcl);
okltest_nvar_schur_aloamo_fcs(nvar_schur_aloamo_fcs);
okltest_ncl_list_schur_aloamo_fcl(ncl_list_schur_aloamo_fcl);
okltest_ncl_list_schur_aloamo_fcs(ncl_list_schur_aloamo_fcs);

okltest_nvar_pd_schur_nbfcsud(nvar_pd_schur_nbfcsud);

/* *******************
   * Standardisation *
   *******************
*/

okltest_schur_aloamo_stdfcl(schur_aloamo_stdfcl);

okltest_pd_schur_aloamo_stdfcl(pd_schur_aloamo_stdfcl);

okltest_schur_standnest_stdfcl(schur_standnest_stdfcl);

/*!
\endhtmlonly
*/
