/* Oliver Kullmann, 20.9.2008 (Swansea) */
/* Copyright 2008, 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/testobjects/VanderWaerdenProblems.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/testobjects/VanderWaerdenProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/VanderWaerdenProblems.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/tests/VanderWaerdenProblems.mac")$

/* **************************************************
   * Arithmetic progressions in the natural numbers *
   **************************************************
*/

okltest_vanderwaerden2_fcl(vanderwaerden2_fcl);
okltest_vanderwaerden2_fcs(vanderwaerden2_fcs);
okltest_vanderwaerden2nd_fcl(vanderwaerden2nd_fcl);
okltest_vanderwaerden2nd_fcs(vanderwaerden2nd_fcs);

okltest_pd_vanderwaerden2nd_fcl(pd_vanderwaerden2nd_fcl);
okltest_pd_vanderwaerden2nd_fcs(pd_vanderwaerden2nd_fcs);

okltest_vanderwaerden_nbfclud(vanderwaerden_nbfclud);
okltest_vanderwaerden_nbfcsud(vanderwaerden_nbfcsud);

/* ****************************************
   * Translation into boolean clause-sets *
   ****************************************
*/

okltest_vanderwaerden_aloamo_fcl(vanderwaerden_aloamo_fcl);
okltest_vanderwaerden_aloamo_fcs(vanderwaerden_aloamo_fcs);

okltest_vanderwaerden_aloamo_stdfcl(vanderwaerden_aloamo_stdfcl);
okltest_vanderwaerden_aloamo_stdfcs(vanderwaerden_aloamo_stdfcs);

okltest_standardise_vanderwaerden_aloamo(standardise_vanderwaerden_aloamo);
okltest_invstandardise_vanderwaerden_aloamo(invstandardise_vanderwaerden_aloamo);

/* ************************
   * Statistics functions *
   ************************
*/

okltest_nvar_vanderwaerden2(nvar_vanderwaerden2);
okltest_nvar_vanderwaerden2nd(nvar_vanderwaerden2nd);
okltest_nvar_vanderwaerden(nvar_vanderwaerden);
okltest_nvar_vanderwaerden_aloamo(nvar_vanderwaerden_aloamo);

okltest_ncl_vanderwaerden2_cs(ncl_vanderwaerden2_cs);
okltest_ncl_vanderwaerden2nd_cs(ncl_vanderwaerden2nd_cs);
okltest_ncl_vanderwaerden_cl(ncl_vanderwaerden_cl);
okltest_ncl_vanderwaerden_cs(ncl_vanderwaerden_cs);
okltest_ncl_vanderwaerden_aloamo_cl(ncl_vanderwaerden_aloamo_cl);
okltest_ncl_vanderwaerden_aloamo_cs(ncl_vanderwaerden_aloamo_cs);

/* ********************
   * Output functions *
   ********************
*/


/*!
\endhtmlonly
*/
