// Oliver Kullmann, 18.9.2008 (Swansea)
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/plans/Commutativity.hpp
  \brief Plans regarding notions associated to commutativity in general


  \todo Complexity of finding centralising elements
  <ul>
   <li> We have already centraliser_grd, bicentraliser_grd and
   centre. </li>
   <li> Given an implicit representation of a groupoid together with
   the guarantee that "short" representations always exists (a "black-box"
   groupoid), the problem of finding a centraliser of a subset is in NP. </li>
   <li> Is it NP-complete? </li>
   <li> In a monoid the problem of finding just one centralising element needs
   to exclude the neutral element, and for centralising just a single element
   we also need to exclude the subgroupoid generated by this single element.
   So perhaps the general problem is, given some subgroupoid, finding a
   centralising element not in this subgroupoid. </li>
   <li> Does there exist at this level of generality any other algorithm
   for finding centralising elements (one/all) other running through all
   elements? </li>
   <li> Also the task of sampling needs consideration. </li>
   <li> DONE Likely these functions should be renamed "centraliser_grd",
   "bicentraliser_grd" and "centre". </li>
  </ul>


*/

