/* Oliver Kullmann, 15.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Trees/tests/Generators.mac
  \brief Tests for basic graph functionality

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/Trees/tests/Generators.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

/* ****************
   * Random trees *
   ****************
*/

okltest_randomtree_pr1_og(f) := block(
  assert(f(1) = [[1],[]]),
  assert(f(2) = [[1,2],[{1,2}]]),
  set_random_state(make_random_state(0)),
  assert(f(3) = [[1,2,3],[{1,2},{2,3}]]),
  assert(f(3) = [[1,2,3],[{1,3},{1,2}]]),
  assert(f(5) = [[1,2,3,4,5],[{1,5},{3,5},{2,5},{2,4}]]),
  true)$

/*!
\endhtmlonly
*/
