/* Matthew Gwynne, 23.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Trees/tests/Representations.mac
  \brief Tests for tree representations and encodings

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/Trees/tests/Representations.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

/* *****************
   * Pruefer Codes *
   *****************
*/

okltest_tree2pruefercode_og(f) := block(
  assert(f([[1],[]]) = []),
  assert(f([[1,2], [{1,2}]]) = []),
  assert(f([[1,2,3],[{1,2},{2,3}]]) = [2]),
  assert(f([[1,2,3],[{2,1},{1,3}]]) = [1]),
  assert(f([[1,2,3,4,5,6],[{1,2},{3,2},{2,4},{4,5},{4,6}]]) = [2,2,4,4]),
  assert(f([[6,5,4,3,2,1],[{1,2},{3,2},{2,4},{4,5},{4,6}]]) = [4,4,2,2]),
  true)$

okltest_pruefercode2tree_og(f) := block(
  assert(f([1],[]) = [[1],[]]),
  assert(f([1,2], []) = [[1,2],[{1,2}]]),
  assert(f([1,2,3],[2]) = [[1,2,3],[{1,2},{2,3}]]),
  assert(f([1,2,3],[1]) = [[1,2,3],[{2,1},{1,3}]]),
  assert(f([1,2,3,4,5,6],[2,2,4,4]) =
    [[1,2,3,4,5,6],[{1,2},{3,2},{2,4},{4,5},{4,6}]]),
  assert(f([6,5,4,3,2,1],[4,4,2,2]) =
    [[6,5,4,3,2,1],[{4,6},{4,5},{2,4},{2,3},{1,2}]]),
  true)$

/*!
\endhtmlonly
*/
