/* Oliver Kullmann, 26.5.2019 (Swansea) */
/* Copyright 2019 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Quantification/tests/RandomQCNF.mac
  \brief Tests for generators of random QCNF

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Quantification/tests/RandomQCNF.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$


kill(f)$



/*!
\endhtmlonly
*/
