/* Oliver Kullmann, 23.12.2008 (Schwalbach) */
/* Copyright 2008, 2009, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Reductions/tests/UnitClausePropagation.mac
  \brief Tests for reductions by unit-clause-propagations

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/tests/UnitClausePropagation.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ConflictCombinatorics/HittingClauseSets.mac")$

kill(f)$

okltest_ucp_cs(f) := block(
  assert(f({}) = {}),
  assert(f({{}}) = {{}}),
  assert(f({{1}}) = {}),
  assert(f({{-1}}) = {}),
  assert(f({{-1},{1}}) = {{}}),
  assert(f({{-1},{1,2}}) = {}),
  assert(f({{-1},{1,2,3}}) = {{2,3}}),
  assert(f({{-1},{1,2},{-2,3},{-3}}) = {{}}),
  for n : 0 thru 5 do block([F : smusat_horn_cs(n)],
    assert(f(F) = {{}}),
    assert(f(union(F,{{1,2}})) = {{}})
  ),
  true)$

okltest_ucp_lpa_cs(f) := (
  assert(f({}) = [{},[]]),
  assert(f({{}}) = [{{}},[]]),
  assert(f({{},{1}}) = [{{},{1}},[]]),
  assert(f({{1}}) = [{},[{1}]]),
  assert(f({{-1}}) = [{},[{-1}]]),
  assert(f({{1},{-1}}) = [{{}},[{1}]]),
  assert(f({{1},{-2}}) = [{},[{1,-2}]]),
  assert(f({{1,2}}) = [{{1,2}},[]]),
  assert(f({{1},{-1,-2},{2,3}}) = [{},[{1},{-2},{3}]]),
  assert(f({{1},{-1,-2},{2,3},{-1,2,-3}}) = [{{}},[{1},{-2},{3}]]),
  assert(f({{1},{-1,-2},{2,3},{-1,2,-3},{-1,2,-3,4}}) = [{{},{4}},[{1},{-2},{3}]]),
  assert(f({{1},{2},{3},{4},{-1,-2},{-3,-4}}) = [{{}},[{1,2,3,4}]]),
  assert(f({{1},{-1},{2},{-2}}) = [{{},{1},{-1}},[{2}]]),
  true)$


/*!
\endhtmlonly
*/
