/* Oliver Kullmann, 21.4.2008 (Guangzhou) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

define_variable(testfile_okl,"m4_SHELL(OKL_MAXIMA_TEST_FILENAME)",any);
define_variable(test_output_okl,"m4_SHELL(OKL_MAXIMA_TEST_OUTPUT)",any);

oklib_automatic_test : true;
oklib_load_annotation : true;

test_level_okl : "m4_SHELL(test_level)";
oklib_test_level : if test_level_okl = "basic" then 0 
 elseif test_level_okl = "full" then 1
 else 2$

test_result : errcatch(oklib_batch(testfile_okl));
if test_result = [] then block([file_output_append : true],
  with_stdout(test_output_okl, print("The evaluation of some expression in the tests resulted in an error.")));

