/* Oliver Kullmann, 21.4.2008 (Guangzhou) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

testfile_okl : "m4_SHELL(OKL_MAXIMA_TEST_FILENAME)";
test_output_okl : "m4_SHELL(OKL_MAXIMA_TEST_OUTPUT)";

oklib_automatic_test : true;

test_level_okl : "m4_SHELL(test_level)";
oklib_test_level : if test_level_okl = "basic" then 0 
 elseif test_level_okl = "full" then 1
 else 2$

oklib_batch(testfile_okl);

