/* Oliver Kullmann, 16.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Ringframes/Rings/include.mac
  \brief Inclusion of functions regarding rings

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Ringframes/Rings/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Ringframes/Rings/ResidueClasses.mac")$

/*!
\endhtmlonly
*/
