/* Oliver Kullmann, 16.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Ringframes/Rings/ResidueClasses.mac
  \brief Providing implementations of rings of residue classes (modular arithmetic)

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Ringframes/Rings/ResidueClasses.mac");

*/

/*!
\htmlonly
*/

/* Prerequisite: n >= 1. */
mod_add(n) := buildq([n],lambda([x,y],mod(x+y,n)))$
mod_mul(n) := buildq([n],lambda([x,y],mod(x*y,n)))$

residues_rng(n) := [setmn(0,n-1), mod_add(n), mod_mul(n), [0], [mod(1,n)]]$

/*!
\endhtmlonly
*/

