/* Oliver Kullmann, 13.8.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/LinearAlgebra/Lisp/tests/QuadraticForms.mac
  \brief Tests for splitting trees

Use by

oklib_load("Transitional/ComputerAlgebra/LinearAlgebra/Lisp/tests/QuadraticForms.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/Basics.mac")$

kill(f)$

/* ***********************************************
   * Indices of positivity, negativity, nullity *
   ***********************************************
*/

okltest_pivot_d(f) := (

  true)$

/* Generic test function for the indices: */
okltest_pnn_indices(f) := (

  true)$

/* Generic test function for the hermitian rank: */
okltest_hermitian_rank(f) := (
  assert(f(matrix()) = 0),
  assert(f(matrix([0])) = 0),
  assert(f(matrix([1])) = 1),
  for n : 2 thru 5 do
    assert(f(scom2m(conststdscom(n,1)) - ident(n)) = n-1),
  true)$

/* Generic test function for the hermitian deficiency: */
okltest_hermitian_def(f) := (

  true)$

/*!
\endhtmlonly
*/
