/* Oliver Kullmann, 25.6.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Isomorphisms/tests/Homomorphisms.mac
  \brief Tests for basic graph functionality

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/Isomorphisms/tests/Homomorphisms.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

/* ***************************
   * Checking the properties *
   ***************************
*/



/* ****************************
   * Brute-force enumerations *
   ****************************
*/

okltest_all_pisomorphisms_bydef_stgl(f) := block(
  assert(f([{},{}]) = [[]]),
  assert(f([{1},{}]) = [[1]]),
  assert(f([{1,2},{}]) = [[1,2],[2,1]]),
  assert(f([{1,2},{{1,2}}]) = [[1,2],[2,1]]),
  assert(f([{1,2},{{1},{2}}]) = [[1,2],[2,1]]),
  assert(f([{1,2},{{1},{1,2}}]) = [[1,2]]),
  assert(f([{1,2,3},{{1},{1,2},{2,3},{1,3}}]) = [[1,2,3],[1,3,2]]),
  true)$


/*!
\endhtmlonly
*/
