/* Oliver Kullmann, 4.9.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/RamseyProblems.mac
  \brief %Generators for %Ramsey-problems

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/RamseyProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Ramsey.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Colouring.mac")$


/* The Ramsey-number ramsey_s^r(q_1, ..., q_s) is the smallest n >= 0 such
   that however the set of r-subsets of {1, ..., n} is divided into s
   (possibly empty) parts, there exists one part 1 <= i <= s containing
   all the possible r-subsets of some q-element subset of {1,...,n}.

   If q_1 = ... = q_s = q, then we have a hypergraph colouring problem, where
   the question is whether ramsey_ohg(q,r,n) is s-colourable (see
   ComputerAlgebra/Hypergraphs/Lisp/Generators/Generators.mac; this hypergraph
   has as vertices the r-subsets of {1,...,n}, while the hyperedges are the
   sets of all r-subset-vertices within all possible q-subsets of {1,...,n}).
*/

/* The boolean ordered formal clause-sets expressing that ramsey_2^r(q,q) > n; 
   a satisfying assignments yields a 2-colouring of the binom(q,r)-hypergraph
   with vertices all r-subsets of {1,...,n}, while the set of hyperedges is the
   set of the sets of all r-subsets obtained from the q-subsets of {1,...,n}.
   In other words, the clause-set is satisfiable iff one can assign 0 and
   1 to the r-element subsets (the "vertices") of {1,...,n} such that for 
   every q-element subset of {1,...,n} there are two such vertices which are
   subsets (of the q-element set) and which have different values assigned.
   For r=2 we have the interpretation, that the clause-set is satisfiable
   iff there exists an edge-labelling of the K_n with "colours" 1,2  such
   that no q-clique is monochromatic (w.r.t. the edges involved).
   For arbitrary r, instead of K_n^r one considers the K_n^r, the r-graph
   consisting of all r-element subsets of {1,...,n}; satisfying assignments
   are those labellings of the r-element subsets with "colours" 1,2 such
   that every q-element subset of {1,...,n} contains some r-element subset
   for each of the two colours.

   Variables are the colouring-variables colv(s) for the r-subsets of
   {1,...,n}, ordered lexicographically. The clause-list contains first
   the positive clauses, then the negative clauses, each sublist ordered
   lexicographically.
*/
ramsey2_ofcs(q,r,n) := tcol2sat_ohg2fcl(ramsey_ohg(q,r,n))$


/*!
\endhtmlonly
*/
