/* Oliver Kullmann, 21.5.2011 (London) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/MinVarDegrees.mac
  \brief Tests related to min-var-degrees of lean clause-sets

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/tests/MinVarDegrees.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Hypergraphs.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Statistics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/MinVarDegrees.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Autarkies/TableauAlgorithm.mac")$

kill(f)$

okltest_extremal_lean_mvdd_fcs(f) := (
  assert(f(1) = [{1},{{1},{-1}}]),
  assert(f(2) = [{1,2},{{1,2},{-1,2},{1,-2},{-1,-2}}]),
  for k : 3 thru if oklib_test_level=0 then 7 else 20 do
   block([F : f(k), N : nonmersenne_law(k)],
    assert(fcs_p(F) = true),
    assert(deficiency_fcs(F) = k),
    assert(min_variable_degree_fcs(F) = N),
    assert(lean_kernel_tableau_fs_cs(F[2])[1] = F[2])
  ),
  true)$


/*!
\endhtmlonly
*/
