/* Matthew Gwynne, 25.11.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/include.mac
  \brief Inclusion file for Maxima Ramsey theory functions

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/include.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Ramsey/include.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Schur/include.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/include.mac")$

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Sequences.mac")$

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/tests/Numbers.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/tests/Sequences.mac")$

/*!
\endhtmlonly
*/
