/* Oliver Kullmann, 16.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Ringframes/include.mac
  \brief Inclusion of functions regarding ringframes (rings, etc.)

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Ringframes/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Ringframes/Rings/include.mac")$

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Ringframes/BasicNotions.mac")$

/*!
\endhtmlonly
*/
