/* Oliver Kullmann, 15.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Trees/include.mac
  \brief Inclusion file for functions related to trees (as combinatorial objects)

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/Trees/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Trees/Generators.mac")$
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Trees/Representations.mac")$

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Trees/tests/Representations.mac")$

/*!
\endhtmlonly
*/
