/* Oliver Kullmann, 20.3.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/CryptoSystems/DataEncryptionStandard/RoundFunction.mac
  \brief The round function of DES

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/DataEncryptionStandard/RoundFunction.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/DataEncryptionStandard/Sboxes.mac")$

des_expansion : [
32,1,2,3,4,5,4,5,6,7,8,9,
8,9,10,11,12,13,12,13,14,15,16,17,
16,17,18,19,20,21,20,21,22,23,24,25,
24,25,26,27,28,29,28,29,30,31,32,1]$

des_pbox : [
16,7,20,21,29,12,28,17,1,15,23,26,5,18,31,10,
2,8,24,14,32,27,3,9,19,13,30,6,22,11,4,25]$

/* previous and current are boolean vectors of length 32, key is a boolean
   vector of length 48:
*/
des_round(previous,current,key) := block(
 [result : map(lambda([x],current[x]), des_expansion)],
  result : mod(result + key, 2),
  result : partition_elements(result, 6),
  result : lappend(create_list(des_sbox_bf(i)(result[i]),i,1,8)),
  result : map(lambda([x],result[x]), des_pbox),
  mod(result + previous, 2))$

/*!
\endhtmlonly
*/
