/* Matthew Gwynne, 22.3.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/include.mac
  \brief Inclusion of Maxima algebra functionality

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/include.mac")$

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/FiniteFields.mac")$

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/tests/FiniteFields.mac")$

/*!
\endhtmlonly
*/
