/* Oliver Kullmann, 25.12.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/tests/LatinSquares.mac
  \brief Tests regarding latin squares

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/LatinSquares.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$


/* *****************************************
   * Latin square problems as SAT problems *
   *****************************************
*/

okltest_ls_var(f) := (
  /* XXX */
  true)$

okltest_var_ls(f) := (
  /* XXX */
  true)$

okltest_ls_different_rows(f) := (
  /* XXX */
  true)$

okltest_ls_different_columns(f) := (
  /* XXX */
  true)$

okltest_ls_positions_box(f) := (
  /* XXX */
  true)$

okltest_ls_all_fields(f) := (
  /* XXX */
  true)$

okltest_weak_ls(f) := (
  /* XXX */
  true)$

okltest_ls_all_rows(f) := (
  /* XXX */
  true)$

okltest_ls_all_columns(f) := (
  /* XXX */
  true)$

okltest_ls_different_fields(f) := (
  /* XXX */
  true)$

okltest_dual_weak_ls(f) := (
  /* XXX */
  true)$

okltest_strong_ls(f) := (
  /* XXX */
  true)$


/* ****************************
   * Orthogonality conditions *
   ****************************
*/

okltest_orthogonality_cond_ls(f) := (
  /* XXX */
  true)$

okltest_orthogonality_dualcond_ls(f) := (
  /* XXX */
  true)$

okltest_orthogonality_strongcond_ls(f) := (
  /* XXX */
  true)$

okltest_row_symmetrybreaking_ls(f) := (
  /* XXX */
  true)$

okltest_exluding_solution_ls(f) := (
  /* XXX */
  true)$


/*!
\endhtmlonly
*/
