/* Oliver Kullmann, 11.5.2013 (Swansea) */
/* Copyright 2013 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/tests/LinearEquations.mac
  \brief Tests for clause-set-generators

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/LinearEquations.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$


/* *********************
   * Parity conditions *
   *********************
*/

okltest_even_parity_cl(f) := block(
  assert(f(0) = []),
  assert(f(1) = [{-1}]),
  assert(f(2) = [{-2,1},{-1,2}]),
  assert(f(3) = [{-3,-2,-1},{-3,2,1},{3,-2,1},{3,2,-1}]),
  true)$

okltest_odd_parity_cl(f) := block(
  assert(f(0) = [{}]),
  assert(f(1) = [{1}]),
  assert(f(2) = [{-1,-2},{2,1}]),
  assert(f(3) = [{-3,-2,1},{-3,2,-1},{3,-2,-1},{1,2,3}]),
  true)$

okltest_fullxoreqs_fcl(f) := block(
  assert(f(0,0) = [[],[]]),
  assert(f(1,1) = [[1,2],[{1,-2},{-1,2}]]),
  assert(f(2,2) = [[1,2,3,4], [{-3,-2,-1},{-3,1,2},{-2,1,3},{-1,2,3},{-4,-2,-1},{-4,1,2},{-2,1,4},{-1,2,4}]]),
  assert(f(1,3) = [[1,2,3,4], [{-4,-3,-2,1},{-4,-3,-1,2},{-4,-2,-1,3},{-4,1,2,3},{-3,-2,-1,4},{-3,1,2,4},{-2,1,3,4},{-1,2,3,4}]]),
  true)$

okltest_fullxoreqs_wv_fcl(f) := block(
  assert(okltest_fullxoreqs_fcl(buildq([f], lambda([m,n], f(m,n, create_list(i,i,1,m+n)))))),
  assert(f(2,2,[5,6,7,8]) = [[5,6,7,8],[{-7,-6,-5},{-7,5,6},{-6,5,7},{-5,6,7},{-8,-6,-5},{-8,5,6},{-6,5,8},{-5,6,8}]]),
  true)$

/*!
\endhtmlonly
*/
