/* Matthew Gwynne, 26.8.2011 (Swansea) */
/* Copyright 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/tests/Pigeonhole.mac
  \brief Tests for pigeonhole-generators

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/Pigeonhole.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/Pigeonhole.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Hypergraphs.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Statistics.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$

kill(f)$


/* ***********************
   * Pigeonhole formulas *
   ***********************
*/

/* Measures */

okltest_nvar_php(f) := block(
 for m : 0 thru 6 do
  for n : 0 thru 6 do
   assert(f(m,n) = nvar_fcs(weak_php_fcs(m,n))),
 true)$

okltest_ncl_list_weak_php(f) := block(
 for m : 0 thru 6 do
  for n : 0 thru 6 do
   assert(f(m,n) = ncl_list_fcs(weak_php_fcs(m,n))),
 true
)$

okltest_ncl_weak_php(f) := block(
 for m : 0 thru 6 do
  for n : 0 thru 6 do
   assert(f(m,n) = ncl_fcs(weak_php_fcs(m,n))),
 true
)$

okltest_deficiency_weak_php(f) := block(
 for m : 0 thru 6 do
  for n : 0 thru 6 do
   assert(f(m,n) = deficiency_fcs(weak_php_fcs(m,n))),
 true
)$

/* Extended Resolution */

okltest_php_induction_step_cl(f) := block(
  for i in [0,1] do
      assert(f(i) = []),
  assert(f(2) =
    [{php_ext(2,1,1),-php_ext(3,1,1)},{php_ext(2,1,1),-php_ext(3,1,2),
     -php_ext(3,3,1)},{-php_ext(2,1,1),php_ext(3,1,1),php_ext(3,1,2)},
     {-php_ext(2,1,1),php_ext(3,1,1),php_ext(3,3,1)},{php_ext(2,2,1),
     -php_ext(3,2,1)},{php_ext(2,2,1),-php_ext(3,2,2),-php_ext(3,3,1)},
     {-php_ext(2,2,1),php_ext(3,2,1),php_ext(3,2,2)},{-php_ext(2,2,1),
     php_ext(3,2,1),php_ext(3,3,1)}]),
  true)$

okltest_php_induction_cl(f) := block(
  for i in [0,1] do
    assert(f(i) = []),
  assert(f(2) =
    [{php_ext(2,1,1),-php(1,1)},{php_ext(2,1,1),-php(1,2),-php(3,1)},
     {-php_ext(2,1,1),php(1,1),php(1,2)},{-php_ext(2,1,1),php(1,1),php(3,1)},
     {php_ext(2,2,1),-php(2,1)},{php_ext(2,2,1),-php(2,2),-php(3,1)},
     {-php_ext(2,2,1),php(2,1),php(2,2)},{-php_ext(2,2,1),php(2,1),php(3,1)}]),
  true)$

okltest_weak_php_unsat_ext_fcs(f) := block(
  for i in [0,1] do
    assert(f(i) = weak_php_fcs(i+1,i)),
  assert(f(2) =
    [{php(1,1),php(1,2),php(2,1),php_ext(2,1,1),php(2,2),php_ext(2,2,1),
      php(3,1),php(3,2)},
     {{-php(1,1),-php(2,1)},{-php(1,1),php_ext(2,1,1)},{-php(1,1),-php(3,1)},
      {php(1,1),php(1,2)},{php(1,1),php(1,2),-php_ext(2,1,1)},
      {php(1,1),-php_ext(2,1,1),php(3,1)},{-php(1,2),php_ext(2,1,1),-php(3,1)},
      {-php(1,2),-php(2,2)},{-php(1,2),-php(3,2)},{-php(2,1),php_ext(2,2,1)},
      {-php(2,1),-php(3,1)},{php(2,1),php(2,2)},{php(2,1),php(2,2),
       -php_ext(2,2,1)}, {php(2,1),-php_ext(2,2,1),php(3,1)},{-php(2,2),
       php_ext(2,2,1),-php(3,1)},{-php(2,2),-php(3,2)},{php(3,1),php(3,2)}}]),
  true)$


/*!
\endhtmlonly
*/
