/* Oliver Kullmann, 4.9.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/tests/RamseyProblems.mac
  \brief Tests for clause-set-generators

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/RamseyProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

okltest_ramsey2_ofcs(f) := (
  assert(f(0,0,0) = [[colv({})], [{colv({})},{-colv({})}]]),
  assert(f(1,0,0) = [[colv({})], []]),
  assert(f(0,1,0) = [[], []]),
  assert(f(0,0,1) = [[colv({})], [{colv({})},{-colv({})}]]),
  assert(f(1,1,0) = [[], []]),
  assert(f(1,0,1) = [[colv({})], [{colv({})},{-colv({})}]]),
  assert(f(0,1,1) = [[colv({1})], []]),
  assert(f(1,1,1) = [[colv({1})], [{colv({1})},{-colv({1})}]]),
  true)$


/*!
\endhtmlonly
*/
