/* Oliver Kullmann, 4.9.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/tests/RamseyProblems.mac
  \brief Tests for clause-set-generators

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/RamseyProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

okltest_ramsey2_ofcs(f) := (
  assert(f(0,0,0) = [[colv({})], [{colv({})},{-colv({})}]]),
  assert(f(1,0,0) = [[colv({})], []]),
  assert(f(0,1,0) = [[], []]),
  assert(f(0,0,1) = [[colv({})], [{colv({})},{-colv({})}]]),
  assert(f(1,1,0) = [[], []]),
  assert(f(1,0,1) = [[colv({})], [{colv({})},{-colv({})}]]),
  assert(f(0,1,1) = [[colv({1})], []]),
  assert(f(1,1,1) = [[colv({1})], [{colv({1})},{-colv({1})}]]),
  true)$

okltest_ramsey2_sym_break_rec(f) := block(
  [vhm : sm2hm({}), vnhm : sm2hm({}), result],
  assert(f({}, sm2hm({}), sm2hm({})) = {}),
  set_hm(vnhm, 1, {1,2}),
  set_hm(vhm, {1,2}, 1),
  assert(f({1}, vhm, vnhm) = {}),
  assert(length(var_cs(f({1,2,3,4,5,6,7,8,9,10,11,12,13,14,15},
    sm2hm({[{1,2},1],[{1,3},2],[{2,3},3],[{1,4},4],[{2,4},5],
    [{3,4},6],[{1,5},7],[{2,5},8],[{3,5},9],[{4,5},10],[{1,6},11],[{2,6},12],
    [{3,6},13],[{4,6},14],[{5,6},15]}),sm2hm({[1,{1,2}],[2,{1,3}],[3,{2,3}],[4,{1,4}],
    [5,{2,4}],[6,{3,4}],[7,{1,5}],[8,{2,5}],[9,{3,5}],[10,{4,5}],[11,{1,6}],
    [12,{2,6}],[13,{3,6}],[14,{4,6}],[15,{5,6}]})))) = 3),
  true)$

/*!
\endhtmlonly
*/
