/* Oliver Kullmann, 4.9.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/tests/RamseyProblems.mac
  \brief Tests for clause-set-generators

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/RamseyProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

okltest_ramsey2_ofcs(f) := (
  assert(f(0,0,0) = [[colv({})], [{colv({})},{-colv({})}]]),
  assert(f(1,0,0) = [[colv({})], []]),
  assert(f(0,1,0) = [[], []]),
  assert(f(0,0,1) = [[colv({})], [{colv({})},{-colv({})}]]),
  assert(f(1,1,0) = [[], []]),
  assert(f(1,0,1) = [[colv({})], [{colv({})},{-colv({})}]]),
  assert(f(0,1,1) = [[colv({1})], []]),
  assert(f(1,1,1) = [[colv({1})], [{colv({1})},{-colv({1})}]]),
  true)$

okltest_ramsey_nbfclud(f) := (
  for i : 1 thru 5 do
    assert(f([],i,0) = [[],[],[]]),
  assert(f([2],2,2) = [[{1,2}],[{[{1,2},1]}],[1]]),
  assert(f([3,4],2,4) = [[{1,2},{1,3},{1,4},{2,3},{2,4},{3,4}],
          [{[{1,2},1],[{1,3},1],[{2,3},1]},{[{1,2},1],[{1,4},1],[{2,4},1]},
           {[{1,3},1],[{1,4},1],[{3,4},1]},{[{2,3},1],[{2,4},1],[{3,4},1]},
           {[{1,2},2],[{1,3},2],[{1,4},2],[{2,3},2],[{2,4},2],[{3,4},2]}],
          [1,2]]),
  true)$

okltest_ramsey2_symbr2_cs(f) := block(
  for i : 0 thru 5 do
    assert(f(i) = {}),
  for i : 0 thru 17 do 
    assert(length(f(i)) = 6 * floor(max((i - 3),0) / 3)),
  true)$

okltest_ramsey_symbr2_nbfclud(f) := block(
  assert(f(2,2,0) = [[],[],[1,2]]),
  assert(f(2,2,6) =
    [[{1,2},{1,3},{1,4},{1,5},{1,6},{2,3},{2,4},{2,5},{2,6},{3,4},{3,5},{3,6},
      {4,5},{4,6},{5,6}],[{nbv({1,3},1),nbv({2,3},2)},{nbv({1,3},2),
      nbv({2,3},1)},{nbv({1,2},1),nbv({2,3},2)},{nbv({1,2},2),nbv({2,3},1)},
      {nbv({1,2},1),nbv({1,3},2)},{nbv({1,2},2),nbv({1,3},1)}],[1,2]]),
  true)$

okltest_ramsey_symbr2_eqs(f) := block(
  for i : 0 thru 5 do 
    assert(f(2,2,i) = {}),
  for i : 0 thru 17 do
    assert(length(f(2,2,i)) = floor(max((i - 3),0) / 3)),
  true)$

okltest_ramsey2_sym_break_rec(f) := block(
  [vhm : sm2hm({}), vnhm : sm2hm({}), result],
  assert(f({}, lambda([a], false), lambda([a],false)) = {}),
  assert(f({1}, lambda([a],1), lambda([a],{1,2})) = {}),
  assert(length(var_cs(f({1,2,3,4,5,6,7,8,9,10,11,12,13,14,15},
    buildq([hm : sm2hm({[{1,2},1],[{1,3},2],[{2,3},3],[{1,4},4],[{2,4},5],
    [{3,4},6],[{1,5},7],[{2,5},8],[{3,5},9],[{4,5},10],[{1,6},11],[{2,6},12],
    [{3,6},13],[{4,6},14],[{5,6},15]})], lambda([a], ev_hm(hm,a))),
    buildq([hm : sm2hm({[1,{1,2}],[2,{1,3}],[3,{2,3}],[4,{1,4}],
    [5,{2,4}],[6,{3,4}],[7,{1,5}],[8,{2,5}],[9,{3,5}],[10,{4,5}],[11,{1,6}],
    [12,{2,6}],[13,{3,6}],[14,{4,6}],[15,{5,6}]})], lambda([a],ev_hm(hm,a)))))) = 3),
  true)$

/*!
\endhtmlonly
*/
