/* Oliver Kullmann, 20.9.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/tests/VanderWaerdenProblems.mac
  \brief Tests for clause-sets related to van der Waerden problems

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/VanderWaerdenProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$


/* **************************************************
   * Arithmetic progressions in the natural numbers *
   **************************************************
*/

okltest_vanderwaerden2_fcs(f) := (
  assert(f(0,0) = [{},{{}}]),
  assert(f(0,1) = [{1},{{}}]),
  assert(f(1,0) = [{},{}]),
  assert(f(1,1) = [{1},{{1},{-1}}]),
  assert(f(2,0) = [{},{}]),
  assert(f(2,1) = [{1},{}]),
  assert(f(2,2) = [{1,2},{{1,2},{-1,-2}}]),
  assert(f(2,3) = [{1,2,3},{{1,2},{1,3},{2,3},{-1,-2},{-1,-3},{-2,-3}}]),
  assert(f(3,0) = [{},{}]),
  assert(f(3,1) = [{1},{}]),
  assert(f(3,2) = [{1,2},{}]),
  assert(f(3,3) = [{1,2,3},{{1,2,3},{-1,-2,-3}}]),
  assert(f(3,4) = [{1,2,3,4},{{1,2,3},{2,3,4},{-1,-2,-3},{-2,-3,-4}}]),
  true)$

okltest_vanderwaerden2nd_fcs(f) := block(
  assert(okltest_vanderwaerden2_fcs(buildq([f], lambda([k,n],f(k,k,n))))),
  assert(f(3,4,4) = [{1,2,3,4},{{-1,-2,-3},{-2,-3,-4},{1,2,3,4}}]),
  true)$


/* *****************************************
   * Arithmetic progressions in the primes *
   *****************************************
*/

okltest_greentao2_fcs(f) := (
  assert(f(0,0) = [{},{{}}]),
  assertf((0,1) = [{2},{{}}]),
  assert(f(1,0) = [{},{}]),
  assert(f(1,1) = [{2},{{2},{-2}}]),
  assert(f(2,0) = [{},{}]),
  assert(f(2,1) = [{2},{}]),
  assert(f(2,2) = [{2,3},{{2,3},{-2,-3}}]),
  assert(f(2,3) = [{2,3,5},{{2,3},{2,5},{3,5},{-2,-3},{-2,-5},{-3,-5}}]),
  assert(f(3,0) = [{},{}]),
  assert(f(3,1) = [{2},{}]),
  assert(f(3,2) = [{2,3},{}]),
  assert(f(3,3) = [{2,3,5},{}]),
  assert(f(3,4) = [{2,3,5,7},{{3,5,7},{-3,-5,-7}}]),
  true)$

okltest_greentao2nd_fcs(f) := (
  okltest_greentao2_fcs(buildq([f], lambda([k,n], f(k,k,n)))),
  assert(f(3,4,5) = [{2,3,5,7,11}, {{3,5,7},{3,7,11}}]),
  assert(f(3,4,9) = [{2,3,5,7,11,13,17,19,23}, {{3,5,7},{3,7,11},{3,11,19},{3,13,23},{5,11,17},{7,13,19},{11,17,23},{-5,-11,-17,-23}}]),
  true)$



/*!
\endhtmlonly
*/
