/* Oliver Kullmann, 20.9.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/tests/VanderWaerdenProblems.mac
  \brief Tests for clause-sets related to van der Waerden problems

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/tests/VanderWaerdenProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$


okltest_vanderwaerden2_fcs(f) := (
  assert(f(0,0) = [{},{{}}]),
  assert(f(0,1) = [{1},{{}}]),
  assert(f(1,0) = [{},{}]),
  assert(f(1,1) = [{1},{{1},{-1}}]),
  assert(f(2,0) = [{},{}]),
  assert(f(2,1) = [{1},{}]),
  assert(f(2,2) = [{1,2},{{1,2},{-1,-2}}]),
  assert(f(2,3) = [{1,2,3},{{1,2},{1,3},{2,3},{-1,-2},{-1,-3},{-2,-3}}]),
  true)$


/*!
\endhtmlonly
*/
