#!/usr/bin/env bash
# Niyozbek Obidov, 20.6.2023 (Swansea)
# Copyright 2023 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# Counting qcnf-files in a directory, and how many of them have global variables

# USAGE:

# Bicliques> ./QCNFcount data
# 3 3
# (3 total .qcnf-files, of which 3 have global variables).


set -o errexit
set -o nounset

program="DirQCNFcount"
version="0.1.4"

directory="$1"
: ${filetype:=".qdimacs"}


total=0
count=0

shopt -s globstar
for path in ${directory}/**/*${filetype}; do
    ((++total))
    result=$(cat ${path} | ./QCNF2gCNF -trans +dp)
    if ((result != 0)); then ((++count)); fi
done

echo "${total} ${count}"
