#!/usr/bin/env bash
# Oliver Kullmann, 8.8.2023 (Swansea)
# Copyright 2023 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# Computing the sizes of conflict-graph and derived biclique-compatibility graph

# Extracting:
# i
# p
# n
# c
# E
# cE (possibly NA)



# USAGE:

# DirExtract QBF2BCC

# TODOS:


set -o errexit
set -o nounset

program="DirExtract"
errorm="ERROR[${program}]:"
version="0.0.8"

base_dir="$1"
base_dir="${base_dir%*/}"

: ${output:="${base_dir}.R"}
echo -e "Output: \"${output}\""

echo " i p n c E cE" > ${output}

count=0
shopt -s globstar
for dir in ${base_dir}/**/A_*; do
  ((++count))

  cat $dir/i >> ${output}
  echo -n " " >> ${output}
  cat $dir/p >> ${output}
  echo -n " " >> ${output}
  cat $dir/n >> ${output}
  echo -n " " >> ${output}
  cat $dir/c >> ${output}
  echo -n " " >> ${output}
  cat $dir/E >> ${output}
  echo -n " " >> ${output}
  if [[ -f ${dir}/cE ]]; then
    cat $dir/cE >> ${output}
  else
    echo "NA" >> ${output}
  fi
  echo        >> ${output}

done

echo $count
