#!/usr/bin/env bash
# Oliver Kullmann, 7.8.2023 (Swansea)
# Copyright 2023 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# Computing the size of conflict-graph



# USAGE:

# DirEcg QBF2BCC

# TODOS:

# 1. Perhaps if file E or cE already exists, skip directory?
#    - Perhaps that should be an option.

set -o errexit
set -o nounset

program="DirEcg"
errorm="ERROR[${program}]:"
version="0.1.4"

base_dir="$1"

: ${transprog:=~/oklibrary/Satisfiability/Transformers/Generators/Bicliques/CNF2cg}

count=0
shopt -s globstar
for dir in ${base_dir}/**/A_*; do

  if [[ -f ${dir}/E ]]; then continue; fi

  ((++count))

  index="$(cat ${dir}/i)"
  echo -n " ${index}"

  result="$(cat ${dir}/cnf | ${transprog} X)"
  E="${result#* }"

  echo -n ${E} > ${dir}/E

done

echo
echo "${count} done"
