#!/usr/bin/env bash
# Oliver Kullmann, 8.8.2023 (Swansea)
# Copyright 2023 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# Computing the sizes of conflict-graph and derived biclique-compatibility graph



# USAGE:

# DirExtract QBF2BCC

# TODOS:


set -o errexit
set -o nounset

program="DirExtract"
errorm="ERROR[${program}]:"
version="0.0.3"

base_dir="$1"

: ${output:="${base_dir}.R"}

echo " i n c E cE" > ${output}

shopt -s globstar
for dir in ${base_dir}/**/A_*; do

  cat $dir/i >> ${output}
  echo -n " " >> ${output}
  cat $dir/n >> ${output}
  echo -n " " >> ${output}
  cat $dir/c >> ${output}
  echo -n " " >> ${output}
  cat $dir/E >> ${output}
  echo -n " " >> ${output}
  cat $dir/cE >> ${output}
  echo        >> ${output}

done
