#!/usr/bin/env bash
# Oliver Kullmann, 23.6.2023 (Swansea)
# Copyright 2023 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# Creating the QBF2BCC corpus

# USAGE:

# ./DirQBF2BCC qdimacs.zip


# TODOS:
# 1. Should we remove the nested directory in QBF2BCC ?
# 2. Update the call of disprog to "global-only mode".


set -o errexit
set -o nounset

program="DirQBF2BCC"
errorm="ERROR[${program}]:"
version="0.1.0"

archive="$1"

: ${directory:="QBF2BCC"}
: ${filetype:="*.qdimacs.gz"}
: ${disprog:="~/oklibrary/Satisfiability/Transformers/Generators/Bicliques/Disassemble"}

patterna="*.zip"
if ! [[ $1 == $patterna ]]; then
  echo $errorm "Argument \"$1\" not a .zip-file."
  exit 1
fi

if [[ -e $directory ]]; then
  echo $errorm "Directory \"${directory}\" already exists."
  exit 1
fi


time1="$(date +%s)"
unzip -q -d QBF2BCC A.zip
time2="$(date +%s)"
echo "unzip:" $[ ${time2} - ${time1} ] "s"

shopt -s globstar # not removing files starting with "."
for file in ${directory}/**/*; do
  if ! [[ -f ${file} ]]; then continue; fi
  if ! [[ ${file} == ${filetype} ]]; then
    echo "rm ${file}"
    rm ${file}
  fi
done
time3="$(date +%s)"
echo "remove:" $[ ${time3} - ${time2} ] "s"

for file in ${directory}/**/${filetype}; do

  gunzip ${F}.qdimacs.gz
  ${disprog} ${F}.qdimacs
  rm ${F}.qdimacs

done

timefinal="$(date +%s)"
echo "total:" $[ ${timefinal} - ${time3} ] "s"
