#!/usr/bin/env bash
# Oliver Kullmann, 23.6.2023 (Swansea)
# Copyright 2023 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# Creating the QBF2BCC corpus

# USAGE:

# 


set -o errexit
set -o nounset

program="DirQBF2BCC"
errorm="ERROR[${program}]:"
version="0.0.2"

archive="$1"

: ${directory:="QBF2BCC"}


patterna="*.zip"
if ! [[ $1 == $patterna ]]; then
  echo $errorm "Argument \"$1\" not a .zip-file."
  exit 1
fi

if [[ -e $directory ]]; then
  echo $errorm "Directory \"${directory}\" already exists."
  exit 1
fi


# NEXT TODO unzip
