#!/usr/bin/env bash
# Oliver Kullmann, 23.10.2019 (Swansea)
# Copyright 2019, 2023 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# Fuzzing GSM

# REMARK: Currently after interrupt the files "SystemCalls_Popen_*"
# of the last call are not deleted.

# USAGE:

# EXAMPLE:

# ./Fuzzer "a10 10" "10*2,4" "" t

# See plans/general.txt for examples.


set -o errexit
set -o nounset

program="Fuzzer"
version="0.1.0"

: ${command1:="./GSM_debug"}
: ${argument1:=}
: ${argument2:=}
: ${command2:="./GCGeq_debug"}
: ${generator:="QBRG"}

fuzzdir="Fuzzing"
mkdir -p ${fuzzdir}

echo "${program}, PID=$$, directory ${fuzzdir}:"

genfile=${fuzzdir}/Generated_$$
rep1file=${fuzzdir}/Replaced1_$$
rep2file=${fuzzdir}/Replaced2_$$
rep3file=${fuzzdir}/Replaced3_$$
outfile=${fuzzdir}/Output_$$


handler() {
  echo "Aborting ${program}, PID=$$: no errors observed."
  pkill --signal SIGINT --parent $$
  rm -f ${genfile} ${rep1file} ${rep2file} ${rep3file} ${outfile}
  exit 0
}

trap handler SIGINT

counter=0
while [ 0 ]; do
  ((++counter)); printf "\r%d" ${counter}

  ${generator} "$@" -${genfile}

  cat ${genfile} | ${command1} "down,${argument1}" "${argument2}" "" "" > ${rep1file} &
  cat ${genfile} | ${command1} "up,${argument1}" "${argument2}" "" "" > ${rep2file} &
  cat ${genfile} | ${command1} "binsearch,${argument1}" "${argument2}" "" "" > ${rep3file} &
  wait

  cat ${genfile} ${rep1file} ${rep2file} ${rep3file} | ${command2} "+4" > ${outfile}

  rm ${genfile} ${rep1file} ${rep2file} ${rep3file} ${outfile}

done
