#!/usr/bin/env bash
# Oliver Kullmann, 23.10.2019 (Swansea)
# Copyright 2019, 2023 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# USAGE:

# EXAMPLE:

# ./Fuzzer "a10 10" "10*2,4" "" t


set -o errexit
set -o nounset

program="Fuzzer"
version="0.0.7"

: ${command1:="./GSM_debug"}
: ${command2:="./GCGeq_debug"}
: ${generator:="QBRG"}

fuzzdir="Fuzzing"
mkdir -p ${fuzzdir}

echo "${program}, PID=$$, directory ${fuzzdir}:"

genfile=${fuzzdir}/Generated_$$
repfile=${fuzzdir}/Replaced_$$
outfile=${fuzzdir}/Output$$

handler() {
  echo "Aborting ${program}, PID=$$: no errors observed."
  rm -f ${genfile} ${repfile} ${outfile}
  exit 0
}

trap handler SIGINT

counter=0
while [ 0 ]; do
  ((++counter)); printf "\r%d" ${counter}
  ${generator} "$@" -${genfile}
  cat ${genfile} | ${command1} "" "" "" "" > ${repfile}
  cat ${genfile} ${repfile} | ${command2} > ${outfile}
  rm ${genfile} ${repfile} ${outfile}
done
