/* Rui Wang, 6.10.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Trees/Lisp/tests/ReingoldTilford.mac
  \brief Tests related to Reingold-Tilford algorithm

Use by

oklib_load("OKlib/ComputerAlgebra/Trees/Lisp/tests/ReingoldTilford.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/ReingoldTilford.mac")$

kill(f)$

/* ******************************
   * Reingold-Tilford algorithm *
   ******************************
*/

okltest_reingold_tilford_rt(f) := block([x,y],
  assert(f([],x,y) = [[x,y]]),
  assert(f([[],[]],x,y) = [[x,y],[[x-1,y-1]],[[x+1,y-1]]]),
  assert(f([ [[]], [] ], x,y) = [[x,y],[[x-1,y-1],[[x-1,y-2]]],[[x+1,y-1]]]),
  assert(f([ [[]], [[],[]] ], x,y) = [[x,y],[[x-1,y-1],[[x-1,y-2]]],[[x+1,y-1],[[x,y-2]],[[x+2,y-2]]]]),
  assert(f([ [[],[]], [[],[]] ], x,y) = [[x,y], [[x-2,y-1],[[x-3,y-2]], [[x-1,y-2]]], [[x+2,y-1],[[x+1,y-2]],[[x+3,y-2]]]]),
  true)$
  

/*!
\endhtmlonly
*/
