/* Oliver Kullmann, 28.12.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/Basics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/tests/Basics.mac")$

/* *****************************
   * The notion of a reduction *
   *****************************
*/

okltest_weakest_reduction_cs(weakest_reduction_cs);
okltest_strongest_reduction_cs(strongest_reduction_cs);

/* ***************************
   * Subsumption elimination *
   ***************************
*/

okltest_subsumption_elimination_cs(subsumption_elimination_cs);

/*!
\endhtmlonly
*/
