/* Oliver Kullmann, 25.4.2008 (Guangzhou) */
/* Copyright 2008, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/DP-Reductions.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/DP-Reductions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/DP-Reductions.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/tests/DP-Reductions.mac")$

/* *************************
   * Singular DP-reduction *
   *************************
*/

okltest_sdp_reduction_cs(sdp_reduction_cs);
okltest_nonsingular_csp(nonsingular_csp);


/*!
\endhtmlonly
*/
