/* Oliver Kullmann, 31.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/GeneralisedUCP.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/GeneralisedUCP.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Reductions/GeneralisedUCP.mac");
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Reductions/tests/GeneralisedUCP.mac");

okltest_generalised_ucp(generalised_ucp);
okltest_generalised_ucp_pa(generalised_ucp_pa);

/*!
\endhtmlonly
*/
