/* Matthew Gwynne, 21.6.2011 (Swansea) */
/* Copyright 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/Hardness.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/Hardness.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/Hardness.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/tests/Hardness.mac")$


/* **********************
   * Computing hardness *
   **********************
*/

okltest_hardness_cs(hardness_cs);
okltest_hardness_u_cs(hardness_u_cs);

/* **********************************
   * Computing propagation-hardness *
   **********************************
*/

okltest_phardness_cs(phardness_cs);

/*!
\endhtmlonly
*/
