/* Oliver Kullmann, 28.12.2009 (Swansea) */
/* Copyright 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/RBases.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/RBases.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/RBases.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/tests/RBases.mac")$

/* ************
   * Sampling *
   ************
*/

okltest_rand_rbase_cs(rand_rbase_cs);

/*!
\endhtmlonly
*/
