/* Oliver Kullmann, 23.12.2008 (Schwalbach) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/UnitClausePropagation.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Reductions/testobjects/UnitClausePropagation.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Reductions/UnitClausePropagation.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Reductions/tests/UnitClausePropagation.mac")$

okltest_ucp_cs(ucp_cs_0);

/*!
\endhtmlonly
*/
