/* Oliver Kullmann, 16.6.2018 (Swansea) */
/* Copyright 2018 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/Binary.mac
  \brief Generators and analysis w.r.t. minimally unsatisfiable clause-sets containing only clauses of length at most 2

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/Binary.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/Auxiliary.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$


/* **********************
   * Cycle descriptions *
   **********************
*/

valid_triple_2mu(T) := listp(T) and length(T)=3 and naturalp(T[1])
 and naturalp(T[3]) and naturalzp(T[2])$
valid_cycledesc_2mu(T) := listp(T) and length(T) >= 2
 and every_s(valid_triple_2mu, T)$




/*!
\endhtmlonly
*/
