/* Oliver Kullmann, 31.5.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/Deficiency2.mac
  \brief Generators and analysis w.r.t. minimally unsatisfiable clause-sets of deficiency 2

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/Deficiency2.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$


/* *********************************************************************
   * The saturated minimally unsatisfiable clause-sets of deficiency 2 *
   *********************************************************************
*/

/* Standard clauses:*/
pos_c(n) := setn(n)$
neg_c(n) := comp_sl(setn(n))$
imp_c(i,n) := if i < n then {-i,i+1} else {-n,1}$

/* The standard MUSAT(def=2) formulas where every literal occurs at least twice,
   for n >= 2 */
musatd2(n) := [setn(n), union({pos_c(n),neg_c(n)}, setify(makelist(imp_c(i,n),i,1,n)))]$


/*!
\endhtmlonly
*/
