/* Oliver Kullmann, 31.5.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/Deficiency3.mac
  \brief Generators and analysis w.r.t. minimally unsatisfiable clause-sets of deficiency 3

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/Deficiency3.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/Deficiency2.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Constructions.mac")$

/* Sequence of elements of MU(3) (as formal clause-sets, with standardised
   variables) according to [OK, XSZ, 2008], which realises the min-var-degree
   of 5. n >= 2 is the number of variables. */
minvdegdef3(n) := block([FF : musatd2(n),F,V, P, N, C, S, F2, S2],
  V : FF[1],
  F : FF[2],
  P : pos_c(n),
  N : neg_c(n),
  C : imp_c(1,n),
  S : {P,N,C},
  F2 : adjoin({-1},setdifference(F,{N,C})),
  S2 : {P,{-1}},
  return(partial_gluing(FF,S,[V,F2],S2)))$

/*!
\endhtmlonly
*/
