/* Oliver Kullmann, 20.6.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Transversals/Minimal/testobjects/RecursiveSplitting.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/Minimal/testobjects/RecursiveSplitting.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/Minimal/RecursiveSplitting.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/Minimal/tests/RecursiveSplitting.mac")$


/* ************************************
   * Finding all minimal transversals *
   ************************************
*/

okltest_transversal_hyp(transversal_hyp_rs);

okltest_transversals_mongen(transversals_mongen_rs);
okltest_transversals_mongen_init(transversals_mongen_rs_init);


/*!
\endhtmlonly
*/
