/* Oliver Kullmann, 19.9.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Actions/include.mac
  \brief Inclusion of Maxima action-related functionality

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Actions/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Actions/BasicNotions.mac")$

oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Actions/tests/BasicNotions.mac")$

/*!
\endhtmlonly
*/
