/* Oliver Kullmann, 12.4.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/tests/Numbers.mac
  \brief Tests for clause-set-generators

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/VanderWaerden/tests/Numbers.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$


/* ***************************
   * Van der Waerden numbers *
   ***************************
*/

okltest_vanderwaerden(f) := (
  assert(f([]) = 1),
  for k : 1 thru 5 do
    assert(f([k]) = k),
  for k : 1 thru 5 do
    assert(f([1,k]) = k),
  assert(f([2,2]) = 3),
  assert(f([3,3]) = 9),
  assert(f([4,4]) = 35),
  assert(f([5,5]) = 178),
  assert(f([6,6]) = 1132),
  for k : 1 thru 6 do
    assert(f(sort([2,k])) = if oddp(k) then 2*k else 2*k-1),
  assert(f([2,2,3]) = 7),
  assert(f([3,7]) = 46),
  assert(f([4,7]) = 109),
  true)$

okltest_vanderwaerden_p(f) := (
  assert(f([]) = true),
  assert(f(1) = false),
  assert(f({1}) = false),
  assert(f([0]) = false),
  assert(f([1/2]) = false),
  assert(f([1,1]) = true),
  assert(f([2,1]) = false),
  true)$


/* *******************************************************
   * The formula from [Landman, Robertson, Culver, 2005] *
   *******************************************************
*/

okltest_lrc_j(f) := (
  for k : 1 thru 5 do
    assert(f(1,k) = 0),
  for r : 1 thru 5 do
    assert(f(r,1) = 0),
  true)$

okltest_lrc_l0p(f) := (
  for k : 1 thru 5 do
    assert(f(1,k) = true),
  for r : 1 thru 5 do
    assert(f(r,1) = if r = 1 then true else false)
  )$

okltest_lrc_l1p(f) := (
  for k : 1 thru 5 do
    assert(f(1,k) = true),
  for r : 1 thru 5 do
    assert(f(r,1) = if r <= 2 then true else false)
  )$


/*!
\endhtmlonly
*/
