/* Matthew Gwynne, 7.12.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/ConstraintTemplateGlobalPropagation.mac
  \brief Tests for the AES propagation functions

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/ConstraintTemplateGlobalPropagation.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/ConstraintTemplateGlobalPropagation.mac")$

kill(f)$

/********************************
 * Propagation functions            *
 ********************************
*/

okltest_prop_all_csttl(f) := block(
  assert(f([],[],[]) = [[],[]]),
  assert(f([],[],[lambda([a,b],[[1],[]])]) = [[1],[]]),
  assert(f([["test_cst",[1,2,3]]],[],
           [lambda([a,b],[[["new_test",[1,2,3,4]]],[]])]) =
         [[["new_test",[1,2,3,4]]],[]]),
  true)$


/****************************************
 * Standard functions                   *
 ****************************************
*/

okltest_prop_eq_vars_l(f) := block(
  assert(f([]) = []),
  assert(f([["eq_cst",[1,2,3,4]]]) = [veq(1,3),veq(2,4)]),
  assert(f([["eq_cst",[1,2,3,4]], ["test",[4,5,6]]]) = [veq(1,3),veq(2,4)]),
  true)$

okltest_prop_eq_csttl(f) := block(
  assert(f([],[]) = [[],[]]),
  assert(f([["eq_cst",[1,2,3,4]]],[1,2,3,4]) = [[],[veq(1,3),veq(2,4)]]),
  assert(f([["eq_cst",[1,2,3,4]], ["test",[4,5,6]]], [1,2,3,4,5,6]) =
    [[["test",[veq(2,4),5,6]]],[veq(1,3),veq(2,4),5,6]]),
  assert(f([["eq_cst",[1,2,3,4]], ["eq_cst",[3,4,5,6]], ["test",[4,5,6]]],
      [1,2,3,4,5,6]) =
    [[["test",[veq(veq(2,4),6),veq(veq(1,3),5),veq(veq(2,4),6)]]],
     [veq(veq(1,3),5),veq(veq(2,4),6)]]),
  true)$

okltest_prop_eq_lift_renaming_var(f) := block(
  for v in [1,2,3,4,5,6,7] do
   for fp in [lambda([a],a), lambda([a], a+1)] do
     assert(f(v,fp) = fp(v)),
  assert(f(veq(1,2), lambda([a],a)) = veq(1,2)),
  assert(f(veq(1,veq(2,3)), lambda([a],a)) = veq(1,veq(2,3))),
  assert(f(veq(1,2), lambda([a],a+1)) = veq(2,3)),
  assert(f(veq(1,veq(2,3)), lambda([a],a+1)) = veq(2,veq(3,4))),
  true)$

okltest_prop_eq_lift_renaming(f) := block(
  for fp in [lambda([a],a), lambda([a], a+1)] do
    assert(f([], fp) = []),
  assert(
    okltest_prop_eq_lift_renaming_var(
      buildq([f],lambda([v,fp], f([v],fp)[1])))),
  assert(f([1,2,3], lambda([a], a)) = [1,2,3]),
  assert(f([1,veq(2,3)], lambda([a], a)) = [1,veq(2,3)]),
  assert(f([1,2,3], lambda([a], a +1)) = [2,3,4]),
  assert(f([1,veq(2,3)], lambda([a], a +1)) = [2,veq(3,4)]),
  true)$

/*!
\endhtmlonly
*/
