/* Matthew Gwynne, 7.12.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/ConstraintTemplateTranslation.mac
  \brief Tests for the AES propagation functions

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/ConstraintTemplateTranslation.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/ConstraintTemplateTranslation.mac")$

kill(f)$

/********************************
 * Translation functions            *
 ********************************
*/

okltest_csttl2cl(f) := block(
  assert(f([],[]) = []),
  assert(f([["xor",[1,2]]],[["xor",[lambda([a],[{-a[2][1],-a[2][2]},{a[2][1],a[2][2]}]),lambda([a], [])]]]) = [{-1,-2},{1,2}]),
  true)$


/*!
\endhtmlonly
*/