/* Matthew Gwynne, 26.4.2008 (Swansea) */
/* Copyright 2008, 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/FieldOperationsAnalysis.mac
  \brief Tests for the analysis functions of the AES Field Operations

  Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/FieldOperationsAnalysis.mac");

  \bug What is the meaning of the part commented out? MG -- ACTION REQUIRED!
  <ul>
   <li>
   \verbatim
    inputList : create_list(-i,i,1,8),
      for i : 1 thru 7 do block(
        inputList = rotate(inputList,-1),
        assert(totaldisrep(apply_pa(setify(inputList), mulFullDNF[2])) =
          {setify(map(lambda([a], (a / abs(a)) * (8 + abs(a))),
            rotate(inputList,-1)))})
    \endverbatim
    </li>
    <li> MG : A very confused attempt at implementing the section of the tests
    now implemented and labelled "Test 2 * 2^i = 2^(i+1)". It was commented out
    as it wasn't working but I wanted to come back to it (should have gone to
    plans). </li>
   </ul>


  \bug DONE Tests take too much time for level basic. MG -- ACTION REQUIRED!
  <ul>
   <li> It seems this can be avoided, since oklib_test_level is yet
   not queried in the tests. </li>
   <li> ok_test_level introduced, although no tests will be possible at
   oklib_test_level = 0, due to the time the function to be tested takes. </li>
  </ul>


  \bug (DONE Tests now need expanding OK: what does this mean??? MG -- ACTION
  REQUIRED)
  Test functions only take ONE argument.
  <ul>
   <li> The above functions is only a HELPER function. </li>
  </ul>

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$

kill(f)$


/* ******************************************
   * Field Multiplication Analysis          *
   ******************************************
*/

/* Tests for AES GF(2^8) constant field multiplication dnf generator.
    
   The function to be tested takes a Rijndael GF(2^8) element as an integer
   and produces the DNF clause set representing multiplication by that element 
   in said finite field.
*/
/* OK: What does this mean?? MG -- ACTION REQUIRED */
okltest_rijnmult_fulldnf_fcs(f) := block(
  [mulFullDNF,inputList,outputList],
  if oklib_test_level = 0 then return(true),
  mulFullDNF : f(2),
  assert(length(mulFullDNF[2]) = 256),
  assert(length(mulFullDNF[1]) = 16),
  assert(elementp({-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1},
      mulFullDNF[2])),
  assert(elementp({-16,-15,-14,-13,-12,-11,-10,-8,-7,-6,-5,-4,-3,-1,2,9},
     mulFullDNF[2])),
  assert(elementp({-14,-13,-12,-9,-8,-7,-2,1,3,4,5,6,10,11,15,16},
     mulFullDNF[2])),
  assert(elementp({-15,-13,-12,-11,-9,-4,-2,1,3,5,6,7,8,10,14,16},
     mulFullDNF[2])),
  mulFullDNF : f(10),
  assert(length(mulFullDNF[2]) = 256),
  assert(length(mulFullDNF[1]) = 16),
  assert(elementp({-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1},
      mulFullDNF[2])),
  assert(elementp({-16,-14,-10,-9,-8,-7,-6,-5,1,2,3,4,11,12,13,15},
     mulFullDNF[2])),
  assert(elementp({-13,-11,-9,-5,-3,1,2,4,6,7,8,10,12,14,15,16},
     mulFullDNF[2])),
  assert(elementp({-12,-9,-7,-5,-1,2,3,4,6,8,10,11,13,14,15,16},
     mulFullDNF[2])),
  mulFullDNF : f(167),
  assert(length(mulFullDNF[2]) = 256),
  assert(length(mulFullDNF[1]) = 16),
  assert(elementp({-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-3,-2,-1},
      mulFullDNF[2])),
  assert(elementp({-12,-10,-9,-8,-5,-3,-1,2,4,6,7,11,13,14,15,16},
     mulFullDNF[2])),
  assert(elementp({-13,-12,-11,-10,-9,-6,-5,-4,1,2,3,7,8,14,15,16},
     mulFullDNF[2])),
  assert(elementp({-16,-15,-14,-13,-10,-8,-4,-3,-2,-1,5,6,7,9,11,12},
     mulFullDNF[2])),
  true)$


okltest_rijnmult_fullcnf_fcs(f) := block([FF],
  if oklib_test_level = 0 then return(true),
  FF : f(2),
  assert(length(FF[2]) = 2^16 - 256),
  assert(elementp({-6,-5,-3,-1,2,4,7,8,9,10,11,12,13,14,15,16},
    FF[2])),
  assert(elementp({-16,-15,-14,-13,-12,-11,-10,-9,-8,-7,-6,-5,-4,-2,-1,3},
    FF[2])),
  assert(elementp({-16,-15,-14,-12,-11,-7,-6,-3,1,2,4,5,8,9,10,13},
    FF[2])),
  true)$

okltest_rijnmult_cnfp(f) := block(
  if oklib_test_level = 0 then return(true),
  assert(f(1, [setn(16), lunion(create_list({{-i,i+8},{-(i+8),i}}, i,1,8))]) = true),
  assert(f(2,[{},{}]) = false),
  assert(f(3,[{},{}]) = false),
  assert(f(2,[setn(16),{{1,2},{4,-5,6},{-16}}]) = false),
  assert(f(3,[setn(16),{{1,2},{4,-5,6},{-16}}]) = false),
  if oklib_test_level = 1 then return(true),
  assert(f(2,rijnmult_fullcnf_fcs(2)) = true),
  true)$

/* *********************************************
   * Small Scale Field multiplication analysis *
   *********************************************
*/

okltest_ssmult_fulldnf_fcl(f) := block(
  assert(f(1,2,1,ss_polynomial_2_1) = [[1,2],[{-2,-1},{1,2}]]),
  assert(f(4,2,4,ss_polynomial_2_4) =
    [[1,2,3,4,5,6,7,8],
    [{-8,-7,-6,-5,-4,-3,-2,-1},{-8,-7,-5,-3,-2,-1,4,6},{-8,-7,-6,-4,-2,-1,3,5},
     {-8,-7,-2,-1,3,4,5,6},{-6,-5,-4,-3,-1,2,7,8},{-5,-3,-1,2,4,6,7,8},
     {-6,-4,-1,2,3,5,7,8},{-1,2,3,4,5,6,7,8},{-8,-5,-4,-3,-2,1,6,7},
     {-8,-6,-5,-3,-2,1,4,7},{-8,-4,-2,1,3,5,6,7},{-8,-6,-2,1,3,4,5,7},
     {-7,-5,-4,-3,1,2,6,8},{-7,-6,-5,-3,1,2,4,8},{-7,-4,1,2,3,5,6,8},
     {-7,-6,1,2,3,4,5,8}]]),
  if oklib_test_level = 0 then return(true),
  assert(f(3,2,8,ss_polynomial_2_8) = rijnmult_fulldnf_fcl(3)),
  true)$

okltest_ssmult_fullcnf_fcs(f) := block(
  assert(f(1,2,1,ss_polynomial_2_1) = [{1,2},{{-2,1},{-1,2}}]),
  if oklib_test_level = 0 then return(true),
  assert(f(3,2,8,ss_polynomial_2_8) = rijnmult_fullcnf_fcs(3)),
  true)$

okltest_ssmult_cnfp(f) := block(
  assert(f(1, [{1,2},{{-2,1},{-1,2}}],2,1,ss_polynomial_2_1)),
  assert(not(f(1,[{1,2},{{-2,1},{1,2}}],2,1,ss_polynomial_2_1))),
  if oklib_test_level = 0 then return(true),
  assert(f(3,rijnmult_fullcnf_fcs(3),2,8,ss_polynomial_2_8)),
  true)$

/* ******************************************
   * Representations by hitting clause-sets *
   ******************************************
*/

okltest_rijnmult2hittingcnf_fcs(f) := block([FF],
  if oklib_test_level = 0 then return(true),
  FF : f(2,dll_heuristics_first_formal),
  assert(hittingcsp(FF[2])),
  if oklib_test_level = 1 then return(true),
  assert(rijnmult_cnfp(2,cs_to_fcs(FF))),
  true)$

/*!
\endhtmlonly
*/
