/* Matthew Gwynne, 19.8.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/Translations.mac
  \brief Tests for the AES translation functions

Use by

oklib_load("Transitional/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/Translations.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac");

kill(f)$

okltest_aes_make_vars_int(f) := block(
  aes_reset_vars(),
  assert(f("p",1,128) = create_list(i,i,1,128)),
  assert(f("k",1,128) = create_list(i,i,128 + 1,2*128)),
  assert(f("c",1,128) = create_list(i,i,2*128 + 1,3*128)),
  for j : 1 thru 10 do 
    assert(f("x",1,128) = create_list(i,i,(j+2)*128 + 1,(j+3)*128)),
  true)$

okltest_aes_make_vars_named(f) := block(
  aes_reset_vars(),
  assert(f("p",1,1) = ['p1]),
  assert(f("p",1,2) = ['p2,'p3]),
  assert(f("c",10,15) = ['c10,'c11,'c12,'c13,'c14, 'c15]),
  assert(f("p",1,0) = []),
  /*assert(f("p",1,-1) = []),*/
  true)$

okltest_aes_round_constant(f) := block(
  for j : 1 thru 8 do
    assert(f([1,2,3,4,5,6,7,8],j) = 
      setify(create_list(if i = (9 - j) then {i} else {-i},i, 1, 8))),
  assert(f([1,2,3,4,5,6,7,8], 10) = {{-8},{-5},{-2},{-1},{3},{4},{6},{7}}),
  for j : 1 thru 8 do
    assert(f([32,31,30,29,28,27,26,25],j) = 
      setify(create_list(if i = 24 + j then {i} else {-i},i, 25, 32))),
  true)$

/*!
\endhtmlonly
*/
