/* Matthew Gwynne, 22.5.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/tests/GeneralisedConstraintTranslation.mac
  \brief Tests regarding constraint translations of DES.

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/tests/GeneralisedConstraintTranslation.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/tests/ConstraintTranslation.mac")$
oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$


/* ***********************
   * The complete system *
   ***********************
*/

okltest_des_plain2fcl_gen(f) := block(
  assert(
    okltest_des_plain2fcl(
      buildq([f],lambda([a],f(a,16))))),
  true)$

okltest_des_cipher2fcl_gen(f) := block(
  assert(
    okltest_des_cipher2fcl(
      buildq([f],lambda([a],f(a,16))))),
  true)$

okltest_des_key2fcl_gen(f) := block(
  assert(
    okltest_des_key2fcl(
      buildq([f],lambda([a],f(a,16))))),
  true)$

/*!
\endhtmlonly
*/
