/* Oliver Kullmann, 16.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Counting/tests/Degrees.mac
  \brief Tests for SAT-tests related to degrees

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Counting/tests/Degrees.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$


kill(f)$

okltest_locallemma_sattest_clausedeg(f) := block(
  assert(f({}) = true),
  assert(f({{}}) = false),
  assert(f({{1}}) = false),
  assert(f({{1},{-1}}) = false),
  assert(f({{1,2}}) = true),
  assert(f({{1,2},{-1,2}}) = false),
  assert(f({{1,2,3}}) = true),
  assert(f({{1,2,3},{-1,2,3}}) = true),
  assert(f({{1,2,3},{-1,2,3},{1,-2,3}}) = false),
  true)$

okltest_locallemma_sattest_vardeg(f) := block(
  assert(f({}) = true),
  assert(f({{}}) = false),
  assert(f({{1}}) = false),
  assert(f({{1},{-1}}) = false),
  assert(f({{1,2}}) = false),
  assert(f({{1,2},{-1,2}}) = false),
  assert(f({{1,2,3}}) = false),
  assert(f({{1,2,3},{-1,2,3}}) = false),
  assert(f({{1,2,3,4}}) = true),
  true)$

okltest_locallemma_sattest_asymmetric(f) := block(
  assert(f({}) = true),
  assert(f({{}}) = false),
  assert(f({{1}}) = true),
  assert(f({{1},{-1}}) = false),
  assert(f({{1,2}}) = true),
  assert(f({{1,2},{-1,2}}) = true),
  assert(f({{1,2},{-1,2},{1,-2}}) = false),
  assert(f({{1,2,3}}) = true),
  assert(f({{1,2,3},{-1,2,3}}) = true),
  assert(f({{1,2,3},{-1,2,3},{1,-2,3}}) = true),
  assert(f({{1,2,3},{-1,2,3},{1,-2,3},{1,2,-3}}) = false),
  true)$



/*!
\endhtmlonly
*/
