/* Oliver Kullmann, 3.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Counting/tests/InclusionExclusion.mac
  \brief Tests for counting via inclusion/exclusion

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Counting/tests/InclusionExclusion.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac");

kill(f)$

okltest_satprob_mcind(f) := block([F],
  assert(f({}) = 1),
  assert(f({{}}) = 0),
  assert(f({{1}}) = 1/2),
  assert(f({{1},{-1}}) = 0),
  assert(f({{1,2}}) = 3/4),
  assert(f({{1,2},{2,3}}) = 5/8),
  assert(f({{1,2},{-1,3}}) = 1/2),
  assert(f({{1,2},{3,4}}) = 9/16),
  assert(f({{1},{2,3},{-3,4}}) = 1/4),
  true)$


/*!
\endhtmlonly
*/
