/* Oliver Kullmann, 17.2.2008 (Swansea) */
/* Copyright 2008, 2013 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Counting/tests/RandomClauseSets.mac
  \brief Tests for SAT-tests related to degrees

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Counting/tests/RandomClauseSets.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/Pigeonhole.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Backtracking/DLL_solvers.mac")$


kill(f)$

okltest_probsatrand(f) := block(
  assert(f({}) = 1),
  assert(f({{}}) = 0),
  assert(f({{1}}) = 1/2),
  assert(f({{1},{-1}}) = 1/4),
  assert(f({{1},{2,3},{4,5,6}}) = 21/64),
  for m : 1 thru 3 do
   for n : 1 thru 3 do block([F : weak_php_fcs(m,n)],
    assert_float_equal(f(F), exp(logprobrand(F)))),
  true)$


/*!
\endhtmlonly
*/
