/* Oliver Kullmann, 16.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Bicliques/testobjects/BasicNotions.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/Bicliques/testobjects/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Bicliques/BasicNotions.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Bicliques/tests/BasicNotions.mac")$

/* ***********************
   * Fundamental notions *
   ***********************
*/

okltest_vbc_gl_p(vbc_gl_p);
okltest_vbc_mugl_p(vbc_mugl_p);
okltest_vbc_gg_p(vbc_gg_p);

okltest_vbc_dgl_p(vbc_dgl_p);

okltest_ebc_gg_p(ebc_gg_p);

/*!
\endhtmlonly
*/
