/* Oliver Kullmann, 5.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/include.mac
  \brief Central inclusion file for all Maxima functions

Use by

oklib_load("Transitional/ComputerAlgebra/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/Basics.mac")$
oklib_include("Transitional/ComputerAlgebra/Cryptology/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/DataStructures/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/LinearAlgebra/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Matroids/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/NumberTheory/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Numerical/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/TermSystems/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Trees/Lisp/include.mac")$

/*!
\endhtmlonly
*/
