/* Oliver Kullmann, 23.5.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/BicliquePartitions.mac
  \brief Functions regarding biclique partitions of multigraphs

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/BicliquePartitions.mac");

*/

/*!
\htmlonly
*/



/*!
\endhtmlonly
*/
