/* Oliver Kullmann, 23.1.2010 (Swansea) */
/* Copyright 2010, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/MaximaInternals/Auxiliary.mac
  \brief Various functions helping to handle Maxima specialities

Use by

oklib_load("OKlib/ComputerAlgebra/MaximaInternals/Auxiliary.mac");

*/

/*!
\htmlonly
*/

/* ***********************
   * Properties of terms *
   ***********************
*/

/* Testing whether term p contains some element in CRE-form: */
tcre_p(p) := not is(totaldisrep(p)=p)$


/* ***************************
   * Simplification of terms *
   ***************************
*/

/* Helper-function for simplification of "simple" terms: */
simplify_st(t) := block([simp:true, simpsum:true],
 factor(radcan(ratsimp(trigreduce(trigsimp(minfactorial(makefact(t))))))))$

/* Simplification of arbitrary terms: */
simplify_t(t) := if atom(t) then t else block([opr : op(t)],
 if opr = "=" then is(equal(simplify_st(first(t)-second(t)), 0))
 else simplify_st(t))$


/*!
\endhtmlonly
*/
