/* Oliver Kullmann, 23.1.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/MaximaInternals/include.mac
  \brief Central inclusion file for Maxima functions helping to handle Maxima specialities

Use by

oklib_load("OKlib/ComputerAlgebra/MaximaInternals/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/MaximaInternals/Auxiliary.mac")$
oklib_include("OKlib/ComputerAlgebra/MaximaInternals/MemoryManagement.mac")$


/*!
\endhtmlonly
*/
