/* Oliver Kullmann, 11.10.2010 (Swansea) */
/* Copyright 2010, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/MaximaInternals/MemoryManagement.mac
  \brief Handling memory limits

Use by

oklib_load("OKlib/ComputerAlgebra/MaximaInternals/MemoryManagement.mac");

*/

/*!
\htmlonly
*/

if maxima_lisp_name_okl = "ecl" then
 oklib_include("OKlib/ComputerAlgebra/MaximaInternals/MemoryManagement.lisp")$

/* Default values: */

show_memory_ecl() := (
 print("frame_stack_ecl:", get_frame_stack_ecl()),
 print("binding_stack_ecl:", get_binding_stack_ecl()),
 print("c_stack_ecl:", get_c_stack_ecl()),
 print("heap_size_ecl:", get_heap_size_ecl()),
 print("lisp_stack_ecl:", get_lisp_stack_ecl())
)$

default_memory_ecl() := (
  set_frame_stack_ecl(frame_stack_ecl),
  set_binding_stack_ecl(binding_stack_ecl),
  set_c_stack_ecl(c_stack_ecl),
  set_heap_size_ecl(heap_size_ecl),
  set_lisp_stack_ecl(lisp_stack_ecl)
)$

/*!
\endhtmlonly
*/
