/* Oliver Kullmann, 14.12.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/MaximaInternals/testobjects/Auxiliary.mac

Use by

oklib_load("OKlib/ComputerAlgebra/MaximaInternals/testobjects/Auxiliary.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/MaximaInternals/Auxiliary.mac")$
oklib_include("OKlib/ComputerAlgebra/MaximaInternals/tests/Auxiliary.mac")$

/* ***********************
   * Properties of terms *
   ***********************
*/

okltest_tcre_p(tcre_p);

/* ***************************
   * Simplification of terms *
   ***************************
*/

okltest_simplify_t(simplify_t);

/*!
\endhtmlonly
*/
