#!/bin/bash
# Oliver Kullmann, 13.12.2009 (Swansea)
# Copyright 2009 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.

# Run through all available cases for unit-clause propagation, and check the output.

# set -o errexit # currently "find" creates an error due to non-existing directories
set -o nounset

list_programs="${bin_dir}/UnitClausePropagation ${bin_dir}/UnitClausePropagation-O3-DNDEBUG"
app_test_dir=${OKlib}/Satisfiability/Reductions/UnitClausePropagation/app_tests

cd ${app_test_dir}

program_tested="UnitClausePropagation"

case ${test_level} in
basic) list_test_cases="$(find test_cases/basic -maxdepth 1 -name '*.cnf')"
    ;;
full) list_test_cases="$(find test_cases/basic -maxdepth 1 -name '*.cnf') $(find test_cases/full -maxdepth 1 -name '*.cnf')"
    ;;
extensive) list_test_cases="$(find test_cases/basic -maxdepth 1 -name '*.cnf') $(find test_cases/full -maxdepth 1 -name '*.cnf') $(find test_cases/extensive -maxdepth 1 -name '*.cnf')"
    ;;
esac

echo -e "\nTESTING ${program_tested}"
echo -e "\nTEST FORMULAS FOUND:"
echo "${list_test_cases}"

echo "Processing:"

for prog in ${list_programs}; do
  echo "${prog}"
  for P in ${list_test_cases}; do
    echo "Filename:" "${P}"
    directory=$(dirname ${P})
    filename=$(basename ${P})
    result_file="${directory}/dimacs_output/1/${filename}"

    output=$(cat ${P} | ${prog})
    echo "${output}" | diff - "${result_file}"
    if [[ $? != 0 ]]; then exit 1; fi

    output=$(cat ${P} | ${prog} set)
    echo "${output}" | diff - "${result_file}"
    if [[ $? != 0 ]]; then
      echo "Parameter: set"
      exit 1
    fi
  done
done

exit 0
