/* Oliver Kullmann, 23.12.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/CryptoSystems/testobjects/IteratedBlockCipher.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/testobjects/IteratedBlockCipher.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/IteratedBlockCipher.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/tests/IteratedBlockCipher.mac")$

/* *******************************************************************
   * Compositional iterated block ciphers with iterated key schedule *
   *******************************************************************
*/

okltest_key_schedule_0(key_schedule_0);

okltest_ibc_0(ibc_0);

/*!
\endhtmlonly
*/
