/* Oliver Kullmann, 11.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Operations/testobjectss/BasicNotions.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Operations/testobjects/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Operations/tests/BasicNotions.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Operations/BasicNotions.mac")$

/* ***********************************
   * Testing the defining properties *
   ***********************************
*/

okltest_opr_grdset_p(opr_grdset_p);

/*!
\endhtmlonly
*/

