#!/bin/bash
# Oliver Kullmann, 27.2.2010 (Swansea)
# Copyright 2010 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.

# Wrapper for satz215, using "time" for time measurement
# All parameters are transferred to satz215.

time m4_SHELL(satz215_call_okl) $*
