/* Oliver Kullmann, 19.8.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Categories/include.mac
  \brief Inclusion file for functions related to categories of clause-sets

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Categories/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Categories/ClauseSets.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Categories/LiteralStructures.mac")$

/*!
\endhtmlonly
*/
