/* Oliver Kullmann, 27.11.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Connectedness.mac
  \brief Functions regarding connectness in graphs

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/Connectedness.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Basic.mac")$

/*
  For tests regarding connectedness see connected_g_p and sconnected_dg_p
  (plus variations) in ComputerAlgebra/Graphs/Lisp/Basic.mac.
*/

/* Connected components of a graph: */
concom_g(G) := block([mg : g2mg(G)], setify(map(setify,
 map(lambda([C], map(lambda([v], get_vertex_label(v,mg)), C)), 
     connected_components(mg)))))$

/*!
\endhtmlonly
*/
