/* Oliver Kullmann, 23.12.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Drawing.mac
  \brief Functions for drawing graphs

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/Drawing.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Basic.mac")$

/* Draw standardised graph G, showing the vertices: */
draw_g(G) := draw_graph(g2mg(G),show_id=true,show_vertices=listify(G[1]));

/*!
\endhtmlonly
*/
