/* Oliver Kullmann, 5.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/include.mac
  \brief Inclusion file for Maxima graph functions

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Basic.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Colouring.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Generators.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/IndependentSets.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/InputOutput.mac")$

oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/tests/Basic.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/tests/Colouring.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/tests/IndependentSets.mac")$

/*!
\endhtmlonly
*/
