/* Oliver Kullmann, 27.12.2007 (Swansea) */
/* Copyright 2007 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/InputOutput.mac
  \brief Maxima graph input and output

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/InputOutput.mac");

*/

/*!
\htmlonly
*/

/* ***************************************
   * Printing graphs in dot-format       *
   ***************************************
*/

/* Functions for converting vertices into a string: */
element_label(i) := sconcat("e",i)$
string_vertex(v) := xreduce(sconcat, map(element_label, v))$
print_vertices(V) := for v in V do print(sconcat(string_vertex(v), ";"))$

/* Functions for converting set-edges into a string: */
print_edge(e) := block(
 [le : listify(e)], 
  print(sconcat(string_vertex(le[1]), " -- ", string_vertex(le[2]), ";")))$
print_edges(E) := for e in E do print_edge(e)$

/* Printing out a graph in the dot-format: */
print_graph_dot(G) := (
 print(sconcat("graph G {")), 
 print_vertices(G[1]), 
 print_edges(G[2]), 
 print("}")
)$
/* Output a graph g to file n: */
output_graph(g,n) := with_stdout(n, print_graph(g))$

/*!
\endhtmlonly
*/
