/* Oliver Kullmann, 30.12.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/CombinatorialMatrices/Lisp/LatinSquares/tests/BasicNotions.mac
  \brief Tests regarding basic notions for latin squares

Use by

oklib_load("OKlib/ComputerAlgebra/CombinatorialMatrices/Lisp/LatinSquares/tests/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/CombinatorialMatrices/Lisp/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Groups/CyclicGroups.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/BasicNotions.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Quasigroups/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Associativity.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$

kill(f)$

/* *****************************
   * Notions of "latin squares *
   *****************************
*/

okltest_comlso_p(f) := (
  /* XXX */
  true)$

/* Remark: The semantics of okltest_comls_p is identical with that of
   okltest_qgrp_p. Currently all tests are handled by okltest_comls_p.
*/
okltest_comls_p(f) := (
  assert(f(0) = false),
  assert(f([]) = false),
  assert(f([[],[]]) = false),
  assert(f([{},0]) = true),
  assert(f([{1},0]) = false),
  assert(f(scom_l([1])) = true),
  assert(f(scom_l([2])) = false),
  assert(f(scom_l([1,2],[2,1])) = true),
  assert(f(scom_l([2,1],[1,2])) = true),
  assert(f(scom_l([1,2],[2,2])) = false),
  for n : 1 thru 6 do
    assert(f(qgrp2comls(ugrp2grp(cyclic_ugrp(n)))) = true),
  true)$

okltest_ls_p(f) := (
  /* XXX */
  true)$

okltest_hrls_p(f) := (
  /* XXX */
  assert(f(matrix([2,1],[1,2])) = false),
  assert(f(matrix([1,2],[2,1])) = true),
  assert(f(matrix([1,3,2],[2,1,3],[3,2,1])) = true),
  true)$

okltest_rls_p(f) := (
  /* XXX */
  assert(f(matrix([2,1],[1,2])) = false),
  assert(f(matrix([1,2],[2,1])) = true),
  assert(f(matrix([1,2,3],[3,1,2],[2,3,1])) = false),
  assert(f(matrix([1,2,3],[2,3,1],[3,1,2])) = true),
  assert(f(matrix([1,3,2],[2,1,3],[3,2,1])) = false),
  for n : 1 thru 6 do
    assert(f(uqgrp2rls(cyclic_ugrp(n))) = true),
  true)$


/* *****************
   * Orthogonality *
   *****************
*/

okltest_ocomls_p(f) := (
  assert(f(scom_l([1]),scom_l([1])) = true),
  assert(f(scom_l([1,2],[2,1]), scom_l([1,2],[2,1])) = false),
  assert(f(scom_l([1,2],[2,1]), scom_l([2,1],[1,2])) = false),
  assert(f(m2scom(cyc3_rls), m2scom(cyc3_o_hrls)) = true),
  true)$

okltest_mocomls_p(f) := (
  assert(okltest_ocomls_p(buildq([f],lambda([A,B], f([A,B]))))),
  /* XXX */
  true)$


/* ************
   * Examples *
   ************
*/

okltest_cyc3_rls(f) := (
  assert(matrix_size(f) = [3,3]),
  assert(rls_p(f) = true),
  true)$

okltest_cyc3_o_hrls(f) := block([Q],
  assert(matrix_size(f) = [3,3]),
  assert(rls_p(f) = false),
  assert(hrls_p(f) = true),
  assert(ocomls_p(m2scom(f),m2scom(cyc3_rls)) = true),
  Q : ls2qgrp(f),
  assert(qgrp_p(Q) = true),
  assert(has_neutral_el_grd(Q) = false),
  assert(associative_bydef_grd(Q) = false),
  true)$

okltest_nassoc_rls(f) := block([Q],
  assert(matrix_size(f) = [5,5]),
  assert(rls_p(f) = true),
  Q : rls2uqgrp(f),
  assert(uqgrp_p(Q) = true),
  assert(associative_bydef_grd(ugrd2grd(Q)) = false),
  true)$

okltest_dk10_rls(f) := (
  assert(matrix_size(f) = [10,10]),
  assert(rls_p(f) = true),
  true)$

okltest_dk10_o_hrls(f) := (
  assert(matrix_size(f) = [10,10]),
  assert(rls_p(f) = false),
  assert(hrls_p(f) = true),
  assert(ocomls_p(m2scom(f),m2scom(dk10_rls)) = true),
  true)$


/* ***************
   * Conversions *
   ***************
*/

okltest_qgrp2comls(f) := (
  /* XXX */
  true)$

okltest_uqgrp2rls(f) := (
  assert(f([{77},lambda([x,y],77),77]) = matrix([1])),
  assert(f(rls2uqgrp(nassoc_rls)) = nassoc_rls),
  for n : 1 thru 5 do block(
   [M : f(cyclic_ugrp(n)),
    L : create_list(i,i,1,n)],
    assert(M = apply(matrix, create_list(rotate(L,-i),i,0,n-1)))
  ),
  /* XXX */
  true)$


/*!
\endhtmlonly
*/
