#!/usr/bin/env bash
# Oleg Zaikin, 9.7.2021 (Swansea)
# Copyright 2021 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# Usage:

# CallLSRG N m solver

# runs LSRG to generate a random Latin sqaure of order N with m filled cells, then a
# given solver is used to solve the Euler square completion problem for this square.

# TODO
#
# 1. Parse a result from solving program output (whether an orthogonal mate is found).
#
# 2. Calculate runtime of a solving program.

program="CallLSRG"
version="0.0.3"

if [[ $# == 1 && $1 == "-v" ]]; then
  echo $program
  echo "version" $version
  exit 0
elif [[ $# < 3 || [$# == 1 && $1 == "-h"] ]]; then
  echo "Usage: CallLSRG N m solver"
  exit 0
fi

N=$1
m=$2
solver=$3

i=0
while true; do
  LSRG $N,2 "-co" "1*0,0,$m;1*0,0,0" 1609092523835210350,1625864956250569213,0,0,$i | $solver
  i=$((i+1))
  echo $N $m
done
