#!/bin/bash
# Oleg Zaikin, 6.8.2020 (Swansea)
# Copyright 2021 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version.

# USAGE:

# ProcessRandomEulerExperiment N skipm solver

# creates a directory
# Random_Euler_${N}_${skipm}_${solver}_${timestamp}
# which contains a Makefile ready to perform the (continuous) experimentation.
#
# N - order of a partial Euler problem.
# skipm - the number of the first values of m (number of filled cells) to skip.
# solver - a solver of the partial Euler problem.

# Version 0.0.4

set -o errexit
set -o nounset

script_name="ProcessRandomEulerExperiment"
version_number=0.0.2

if [[ $# -ne 3 ]]; then
  echo "ERROR[${script_name}]: Exactly three parameters are needed:"
  echo "  order skipm solver"
  exit 1
fi

order=$1
skipm=$2
solver=$3

: ${timestamp=$(date +%s%N)}


SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

emakefile="${DIR}/ExpMakefile"
esymmetriser="${DIR}/symmetry-breaking-pair.py"

directory="Random_Euler_${order}_${skipm}_${solver}_${timestamp}"
mkdir ${directory}
echo -e "Created experiment-directory \"${directory}\""


cd ${directory}
cp ${emakefile} Makefile
mkdir experiments
cp ${esymmetriser} ./experiments/

echo -en "Run ${script_name}:\n  " > Log
date >> Log
echo "  in version ${version_number}" >> Log
echo -en "Machine:\n  " >> Log
uname -a >> Log
echo -e "This directory:\n  \"${directory}\"" >> Log
echo -e "order:\n  \"${order}\"" >> Log
echo -e "solver:\n  \"${solver}\"" >> Log

sed -i "s/ORDER/${order}/" Makefile
sed -i "s/SKIPM/${skipm}/" Makefile
sed -i "s/SOLVER/${solver}/" Makefile
