/* Oliver Kullmann, 4.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Quasigroups/tests/Basics.mac
  \brief Tests for the basic groupoid-notions

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Quasigroups/tests/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

/* ***************
   * Conversions *
   ***************
*/

okltest_ls2qgrp(f) := (
  /* XXX */
  true)$

okltest_stdls2qgrp(f) := (
  /* XXX */
  true)$

okltest_fstdls2uqgrp(f) := (
  /* XXX */
  true)$


/*!
\endhtmlonly
*/
