/* Oliver Kullmann, 2.6.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Combinatorics/Lisp/Enumeration/testobjects/Order.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/testobjects/Order.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/Order.mac")$
oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/tests/Order.mac")$

okltest_lex_lessp_l(lex_lessp_l);
okltest_lex_lessp_l(lex_lessp_l_bydef);
okltest_colex_lessp_l(colex_lessp_l);

/*!
\endhtmlonly
*/
