/* Oliver Kullmann, 22.8.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Combinatorics/Lisp/Enumeration/testobjects/Permutations.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/testobjects/Permutations.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/Permutations.mac")$
oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/tests/Permutations.mac")$

/* ************
   * Counting *
   ************
*/

/* ****************************
   * Lexicographical ordering *
   ****************************
*/

okltest_lex_permutations_l(lex_permutations_l);
okltest_rank_lex_permutations(rank_lex_permutations);
okltest_unrank_lex_permutations(unrank_lex_permutations);

/*!
\endhtmlonly
*/
