/* Matthew Gwynne, 21.1.2009 (Swansea) */
/* Copyright 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Combinatorics/Lisp/Enumeration/testobjects/Subsets.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/testobjects/Subsets.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/Subsets.mac")$
oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/tests/Subsets.mac")$

/* ************
   * Counting *
   ************
*/

okltest_count_ksubsets_s(count_ksubsets_s);
okltest_count_ksubsets(count_ksubsets);

/* ****************************
   * Lexicographical ordering *
   ****************************
*/

okltest_lex_subsets_l(lex_subsets_l);
okltest_lex_subsets_ll(lex_subsets_ll);
okltest_rank_lex_subsets(rank_lex_subsets);
okltest_unrank_lex_subsets(unrank_lex_subsets);

/* ******************************
   * Colexicographical ordering *
   ******************************
*/

okltest_colex_subsets_l(colex_subsets_l);
okltest_colex_subsets_ll(colex_subsets_ll);
okltest_rank_colex_subsets(rank_colex_subsets);
okltest_unrank_colex_subsets(unrank_colex_subsets);

/*!
\endhtmlonly
*/
