/* Oliver Kullmann, 21.7.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/TermSystems/Lisp/testobjects/Conversions.mac

Use by

oklib_load("OKlib/ComputerAlgebra/TermSystems/Lisp/testobjects/Conversions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TermSystems/Lisp/Conversions.mac")$
oklib_include("OKlib/ComputerAlgebra/TermSystems/Lisp/tests/Conversions.mac")$

/* ********************
   * Handling symbols *
   ********************
*/

okltest_indexed_symbol(indexed_symbol);

/* ********************************************
   * Auxiliary functions handling "equations" *
   ********************************************
*/

okltest_translate_vector_lincomb(translate_vector_lincomb);
okltest_translate_matrix_ineq(translate_matrix_ineq);

okltest_interprete_poscond(interprete_poscond);
okltest_interprete_negcond(interprete_negcond);
okltest_interprete_zerocond(interprete_zerocond);

/*!
\endhtmlonly
*/
