/* Oliver Kullmann, 21.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/TermSystems/Lisp/include.mac
  \brief Inclusion file for Maxima functions related to terms

Use by

oklib_load("OKlib/ComputerAlgebra/TermSystems/Lisp/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TermSystems/Lisp/Conversions.mac")$

oklib_include("OKlib/ComputerAlgebra/TermSystems/Lisp/tests/Conversions.mac")$

/*!
\endhtmlonly
*/
