/* Oliver Kullmann, 16.3.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/testobjects/Basics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/Basics.mac")$

/* **************
   * Promotions *
   **************
*/

okltest_hg2ohg(hg2ohg);


/* *************
   * Downcasts *
   *************
*/

okltest_ghg2hg(ghg2hg);

/* ************* **
   * Conversions *
   ***************
*/

okltest_setsystem2hg(setsystem2hg);
okltest_listsets2hg(listsets2hg);
okltest_listsets2oghg(listsets2oghg);

okltest_edge_vertex_com_hg(edge_vertex_com_hg);

okltest_edge_int_com_hg(edge_int_com_hg);
okltest_vertex_int_com_hg(vertex_int_com_hg);

/* *****************
   * Constructions *
   *****************
*/

okltest_union_hg(union_hg);

okltest_edge_k_hg(edge_k_hg);
okltest_edge_g_hg(edge_g_hg);
okltest_anti_edge_k_hg(anti_edge_k_hg);
okltest_kneser_g_hg(kneser_g_hg);

/* *****************
   * Connectedness *
   *****************
*/


/*!
\endhtmlonly
*/
