/* Oliver Kullmann, 16.3.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/testobjects/Basics.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Hypergraphs/Lisp/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/Basics.mac")$
oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/tests/Basics.mac")$

/* ************* **
   * Conversions *
   ***************
*/

okltest_setsystem2hg(setsystem2hg);
okltest_listsets2hg(listsets2hg);
okltest_listsets2oghg(listsets2oghg);

okltest_ghg2hg(ghg2hg);

okltest_edge_vertex_com_hyp(edge_vertex_com_hyp);

okltest_edge_int_com_hyp(edge_int_com_hyp);
okltest_vertex_int_com_hyp(vertex_int_com_hyp);

/*!
\endhtmlonly
*/
