/* Oliver Kullmann, 16.3.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011, 2016 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/testobjects/Basics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/Basics.mac")$

/* ************************************
   * Checking the defining properties *
   ************************************
*/

okltest_hg_p(hg_p);
okltest_ohg_p(ohg_p);
okltest_ghg_p(ghg_p);
okltest_oghg_p(oghg_p);

/* **************
   * Promotions *
   **************
*/

okltest_ses2hg(ses2hg);

okltest_hg2ohg(hg2ohg);

okltest_hg2ghg(hg2ghg);

okltest_ghg2oghg(ghg2oghg);

/* *************
   * Downcasts *
   *************
*/

okltest_ohg2hg(ohg2hg);

okltest_ghg2hg(ghg2hg);
okltest_oghg2ohg(oghg2ohg);

okltest_hg2ses(hg2ses);

/* ************* **
   * Conversions *
   ***************
*/

okltest_listsets2hg(listsets2hg);
okltest_listsets2oghg(listsets2oghg);

/* *******************
   * Standardisation *
   *******************
*/

/* ************
   * Matrices *
   ************
*/

okltest_hypver_hg2com(hypver_hg2com);
okltest_hypver_ghg2com(hypver_ghg2com);

okltest_edge_int_com_hg(edge_int_com_hg);
okltest_vertex_int_com_hg(vertex_int_com_hg);

/* *******************
   * Transformations *
   *******************
*/


/* *****************
   * Constructions *
   *****************
*/

okltest_union_hg(union_hg);

okltest_edge_k_hg(edge_k_hg);
okltest_edge_g_hg(edge_g_hg);
okltest_anti_edge_k_hg(anti_edge_k_hg);
okltest_kneser_g_hg(kneser_g_hg);

/* ************************************************
   * Constructions related to the subset-relation *
   ************************************************
*/

okltest_min_hg(min_hg);
okltest_max_hg(max_hg);

okltest_subsumption_ghg(subsumption_ghg);
okltest_subsumption_oghg(subsumption_oghg);
okltest_rsubsumption_hg(rsubsumption_hg);

/* *****************
   * Connectedness *
   *****************
*/

okltest_components_hg(components_hg);
okltest_components_ghg(components_ghg);

okltest_disjoint_union_rep_hg(disjoint_union_rep_hg);

okltest_is_connected_hg_p(is_connected_hg_p);

/*!
\endhtmlonly
*/
