/* Oliver Kullmann, 22.7.2008 (Swansea) */
/* Copyright 2008, 2009, 2012, 2016 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/testobjects/Colouring.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/testobjects/Colouring.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Colouring.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/Colouring.mac")$

/* *******************************
   * Translations to boolean SAT *
   *******************************
*/

okltest_colv_string(colv_string);
okltest_tcol2sat_hg2fcs(tcol2sat_hg2fcs);
okltest_tcol2sat_stdhg2stdfcs(tcol2sat_stdhg2stdfcs);
okltest_tcol2sat_ohg2fcl(tcol2sat_ohg2fcl);
okltest_tcol2sat_stdohg2stdfcl(tcol2sat_stdohg2stdfcl);

/* ***********************************
   * Translations to non-boolean SAT *
   ***********************************
*/

okltest_col2sat_ohg2nbfclud(col2sat_ohg2nbfclud);
okltest_col2sat_stdohg2stdnbfclud(col2sat_stdohg2stdnbfclud);
okltest_col2sat_stdhg2stdnbfcsud(col2sat_stdhg2stdnbfcsud);

okltest_gcol2sat_ohg2nbfclud(gcol2sat_ohg2nbfclud);
okltest_gcol2sat_stdohg2stdnbfclud(gcol2sat_stdohg2stdnbfclud);
okltest_gcol2sat_ohg2nbfclud_p(gcol2sat_ohg2nbfclud_p);

/* ***************************************************************
   * Determining all k-colourings via the transversal hypergraph *
   ***************************************************************
*/

okltest_allindkcov_hg(allindkcov_hyptrans_rs_hg);

/* **************
   * Reductions *
   **************
*/

okltest_reduce_isolates_ses(reduce_isolates_ses);
okltest_reduce_bounded_ses(reduce_bounded_ses);
okltest_reduce_bounded_hg(reduce_bounded_hg);

/*!
\endhtmlonly
*/
