/* Oliver Kullmann, 22.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/testobjects/Colouring.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Hypergraphs/Lisp/testobjects/Colouring.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/Colouring.mac")$
oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/tests/Colouring.mac")$

/* ***********************
   * Translations to SAT *
   ***********************
*/

okltest_tcol2sat_hg2fcs(tcol2sat_hg2fcs);
okltest_tcol2sat_stdhg2stdfcs(tcol2sat_stdhg2stdfcs);
okltest_tcol2sat_ohg2fcl(tcol2sat_ohg2fcl);
okltest_tcol2sat_stdohg2stdfcl(tcol2sat_stdohg2stdfcl);


/*!
\endhtmlonly
*/
