/* Oliver Kullmann, 26.6.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/testobjects/Generators.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Hypergraphs/Lisp/testobjects/Generators.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/Generators.mac")$
oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/tests/Generators.mac")$

/* *****************
   * Ramsey Theory *
   *****************
*/

okltest_ArithmeticProgressions(ArithmeticProgressions);

/*!
\endhtmlonly
*/
