/* Oliver Kullmann, 2.11.2011 (Swansea) */
/* Copyright 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/testobjects/Homomorphisms.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/testobjects/Homomorphisms.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Homomorphisms.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/Homomorphisms.mac")$

/* *****************
   * Basic notions *
   *****************
*/

okltest_homomorphism_bydef_hg(homomorphism_bydef_hg);
okltest_automorphism_bydef_hg(automorphism_bydef_hg);

okltest_suphomomorphism_bydef_hg(suphomomorphism_bydef_hg);

okltest_transport_hg(transport_hg);


/* **************************
   * Special transport-maps *
   **************************
*/

okltest_colouring_blocks(colouring_blocks);

okltest_random_colouring(random_colouring);

okltest_random_projection_hg(random_projection_hg);
okltest_random_projection_min_hg(random_projection_min_hg);

okltest_modulo_colouring(modulo_colouring);
okltest_modulo_projection_hg(modulo_projection_hg);

okltest_mirrorfold(mirrorfold);
okltest_mirrorexpand(mirrorexpand);

/*!
\endhtmlonly
*/
