/* Oliver Kullmann, 9.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/testobjects/IndependentSets.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/testobjects/IndependentSets.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/IndependentSets.mac");
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/IndependentSets.mac");

okltest_independence_hyp(independence_hyp_trrs);

/*!
\endhtmlonly
*/
