/* Oliver Kullmann, 27.3.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/testobjects/SetSystems.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/testobjects/SetSystems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/SetSystems.mac")$

/* **************
   * Singletons *
   **************
*/

okltest_singletonp(singletonp);
okltest_single_element(single_element);

okltest_choose_element(choose_element);
okltest_first_element(first_element);
okltest_last_element(last_element);

/* *********************
   * Set constructions *
   *********************
*/

okltest_setn(setn);
okltest_setmn(setmn);

okltest_singletons(singletons);

okltest_upairs(upairs);

/* **********************************
   * Constructions related to union *
   **********************************
*/

okltest_lunion(lunion);
okltest_family_sets_union(family_sets_union);

okltest_set_sum(set_sum);

okltest_cunion(cunion);
okltest_add_elements(add_elements);
okltest_add_element(add_element);
okltest_cunion_l(cunion_l);
okltest_add_elements_l(add_elements_l);
okltest_add_element_l(add_element_l);

/* ********************************************
   * Constructions related to complementation *
   ********************************************
*/

okltest_ecomp(ecomp);
okltest_setdifference2(setdifference2);
okltest_setdifference2e(setdifference2e);

/* **************************************************
   * Constructions related to the cartesian product *
   **************************************************
*/

okltest_cartesian_product_l(cartesian_product_l);

okltest_all_transformations_l(all_transformations_l);
okltest_all_transformations_l_l(all_transformations_l_l);

okltest_all_tuples(all_tuples);
okltest_all_tuples_l(all_tuples_l);

okltest_all_ord_tuples(all_ord_tuples);
okltest_all_ord_tuples_l(all_ord_tuples_l);

/* ************************************
   * Constructions related to subsets *
   ************************************
*/

okltest_kpermutations(kpermutations);

okltest_powerset_l(powerset_l);
okltest_powerlist2(powerlist2);

/* *******************************
   * Tests related to partitions *
   *******************************
*/

okltest_empty_element_p(empty_element_p);

okltest_non_disjoint_pair(non_disjoint_pair);
okltest_non_disjoint_pairs(non_disjoint_pairs);
okltest_disjoint_set_system_p(disjoint_set_system_p);

okltest_partitionp(partitionp);

/* ********************************
   * Tests related to subsumption *
   ********************************
*/

okltest_antichain_p(antichain_p);

okltest_subsumption_closed_p(subsumption_closed_p);

okltest_lr_subsetp(lr_subsetp);
okltest_rl_subsetp(rl_subsetp);

/* *****************************************
   * Constructions related to disjointness *
   *****************************************
*/

okltest_remove_with_element(remove_with_element);
okltest_remove_with_element_l(remove_with_element_l);
okltest_remove_non_disjoint(remove_non_disjoint);
okltest_unify_nondisjoint_elements(unify_nondisjoint_elements);


/* *****************************************
   * Constructions related to subsumption *
   *****************************************
*/

okltest_min_elements_l(min_elements_l_0);
okltest_min_elements_l(min_elements_l);

okltest_min_elements(min_elements_0);
okltest_min_elements(min_elements);

okltest_max_elements_l(max_elements_l);
okltest_max_elements(max_elements);

okltest_check_subsumption(check_subsumption);

/*!
\endhtmlonly
*/
