/* Oliver Kullmann, 27.3.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/testobjects/SetSystems.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Hypergraphs/Lisp/testobjects/SetSystems.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$
oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/tests/SetSystems.mac")$

/* **************
   * Singletons *
   **************
*/

okltest_singletonp(singletonp);
okltest_single_element(single_element);
okltest_choose_element(choose_element);

/* *********************
   * Set constructions *
   *********************
*/

okltest_setn(setn);
okltest_setmn(setmn);

/* **********************************
   * Constructions related to union *
   **********************************
*/

okltest_set_system_union(set_system_union);
okltest_list_sets_union(list_sets_union);

okltest_cunion(cunion);
okltest_add_element(add_element);

/* ********************************************
   * Constructions related to complementation *
   ********************************************
*/

okltest_ecomp(ecomp);
okltest_setdifference2(setdifference2);

/* **************************************************
   * Constructions related to the cartesian product *
   **************************************************
*/

okltest_corr_cartesian_product(corr_cartesian_product);
okltest_cartesian_product_l(cartesian_product_l);

okltest_all_transformations_l(all_transformations_l);
okltest_all_transformations_l_l(all_transformations_l_l);

/* *************************
   * Tests for set systems *
   *************************
*/

okltest_empty_element_p(empty_element_p);

okltest_non_disjoint_pair(non_disjoint_pair);
okltest_disjoint_set_system_p(disjoint_set_system_p);

okltest_antichain_p(antichain_p);

/* *****************************************
   * Constructions related to subsumption *
   *****************************************
*/

okltest_min_elements(min_elements);
okltest_max_elements(max_elements);

/*!
\endhtmlonly
*/
