/* Oliver Kullmann, 5.7.2012 (Swansea) */
/* Copyright 2012, 2016 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/testobjects/Statistics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/testobjects/Statistics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Statistics.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/tests/Statistics.mac")$

/* ******************
   * Basic measures *
   ******************
*/

okltest_nhyp_list_ohg(nhyp_list_ohg);


/* ******************
   * Vertex degrees *
   ******************
*/

okltest_vertex_degrees_nhyplist_hg(vertex_degrees_nhyplist_hg);

okltest_isolated_vertices_ses(isolated_vertices_ses);

/*!
\endhtmlonly
*/
