/* Oliver Kullmann, 7.8.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/IncidenceStructures/Lisp/include.mac
  \brief Inclusion file for Maxima functions related to incidence structures

Use by

oklib_load("OKlib/ComputerAlgebra/IncidenceStructures/Lisp/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/IncidenceStructures/Lisp/BasicNotions.mac")$
oklib_include("OKlib/ComputerAlgebra/IncidenceStructures/Lisp/ProjectivePlanes.mac")$

/*!
\endhtmlonly
*/
