/* Oliver Kullmann, 6.8.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/IncidenceStructures/Lisp/ProjectivePlanes.mac
  \brief Basic notions for incidence structures

Use by

oklib_load("Transitional/ComputerAlgebra/IncidenceStructures/Lisp/ProjectivePlanes.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/Basics.mac")$


/* ***************************************
   * Classification of degenerated cases *
   ***************************************
*/


/* ******************
   * The Fano plane *
   ******************
*/

/* The incidence matrix of the Fano plane, given as a
   symmetric matrix:
*/
fano_m : matrix(
    [0 , 1 , 1 , 0 , 0 , 1 , 0],
    [1 , 0 , 1 , 0 , 1 , 0 , 0],
    [1 , 1 , 0 , 1 , 0 , 0 , 0],
    [0 , 0 , 1 , 1 , 0 , 0 , 1],
    [0 , 1 , 0 , 0 , 1 , 0 , 1],
    [1 , 0 , 0 , 0 , 0 , 1 , 1],
    [0 , 0 , 0 , 1 , 1 , 1 , 0]
)$
fano_ics : com2ics(m2com(fano_m))$
fano_gl : scom2gl(m2scom(fano_m))$

/*!
\endhtmlonly
*/
