/* Oliver Kullmann, 13.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Matroids/Lisp/OrientedMatroids/include.mac
  \brief Inclusion file for Maxima functions related to oriented matroids

Use by

oklib_load("OKlib/ComputerAlgebra/Matroids/Lisp/OrientedMatroids/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Matroids/Lisp/OrientedMatroids/SignVectors.mac")$

/*!
\endhtmlonly
*/
