/* Oliver Kullmann, 29.6.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Trees/Lisp/testobjects/Basics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Trees/Lisp/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/tests/Basics.mac")$

/* ****************************
   * Unlabelled rooted trees  *
   ****************************
*/

okltest_rt_p(rt_p);

okltest_lvs(lvs);
okltest_nds(nds);

okltest_subtree(subtree);

okltest_dst(dst);

/* ****************************
   * Labelled rooted trees    *
   ****************************
*/

okltest_lrt_p(lrt_p);

okltest_l2ult(l2ult);

okltest_rt2lrt_il(rt2lrt_il);

/* ************
   * Measures *
   ************
*/

okltest_nnds_rt(nnds_rt);
okltest_nnds_lrt(nnds_lrt);

okltest_nlvs_rt(nlvs_rt);
okltest_nlvs_lrt(nlvs_lrt);

okltest_ninds_rt(ninds_rt);
okltest_ninds_lrt(ninds_lrt);

okltest_height_rt(height_rt);

okltest_levelled_height_rt(levelled_height_rt);



/* ****************
   * Transformers *
   ****************
*/

okltest_graph2tree(graph2tree);

/* **************
   * Generators *
   **************
*/

okltest_complete_rt(complete_rt);

okltest_random_ltree(random_ltree);

okltest_all2_rt(all2_rt);
okltest_num_all2_rt(num_all2_rt);
okltest_all2i_rt(all2i_rt);
okltest_num_all2i_rt(num_all2i_rt);
okltest_all2l_rt(all2l_rt);
okltest_num_all2l_rt(num_all2l_rt);

okltest_all_rt(all_rt);
okltest_num_all_rt(num_all_rt);


/* **************
   * Operations *
   **************
*/

okltest_mirror_rt(mirror_rt);


/*!
\endhtmlonly
*/
