/* Oliver Kullmann, 29.6.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Trees/Lisp/testobjects/Basics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Trees/Lisp/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/tests/Basics.mac")$

/* ****************************
   * Unlabelled rooted trees  *
   ****************************
*/

okltest_rt_p(rt_p);

okltest_nnds(nnds);
okltest_nlvs(nlvs);

okltest_lvs(lvs);
okltest_nds(nds);

okltest_subtree(subtree);

okltest_dst(dst);

okltest_height(height);

okltest_levelled_height(levelled_height);

/* ****************************
   * Labelled rooted trees    *
   ****************************
*/

okltest_l2ult(l2ult);

okltest_nnds_l(nnds_l);
okltest_nlvs_l(nlvs_l);

/* ****************
   * Transformers *
   ****************
*/

okltest_graph2tree(graph2tree);

/*!
\endhtmlonly
*/
