/* Rui Wang, 28.9.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Trees/Lisp/ReingoldTilford.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Trees/Lisp/testobjets/ReingoldTilford.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/ReingoldTilford.mac")$
oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/tests/ReingoldTilford.mac")$


/* ******************************
   * Reingold-Tilford algorithm *
   ******************************
*/

okltest_reingold_tilford_rt(reingold_tilford_rt);


/*!
\endhtmlonly
*/
