/* Rui Wang, 31.10.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Trees/Lisp/testobjects/Visualisation.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Trees/Lisp/testobjects/Visualisation.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/Visualisation.mac")$
oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/tests/Visualisation.mac")$


/* ******************************
   * Tree drawing *
   ******************************
*/

okltest_tdlrt2points(tdlrt2points);

okltest_tdlrt2edges(tdlrt2edges);

okltest_draw_rt(draw_rt);


/*!
\endhtmlonly
*/
