/* Oliver Kullmann, 27.3.2008 (Swansea) */
/* Copyright 2008, 2010, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Resolution/testobjects/Basics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/tests/Basics.mac")$

/* ***************************
   * Single resolution steps *
   ***************************
*/

okltest_resolvable(resolvable);

okltest_resolution_literal(resolution_literal);

okltest_resolvable_p(resolvable_p);

okltest_two_subsumption_resolvent_p(two_subsumption_resolvent_p);

/* *************************
   * Adding all resolvents *
   *************************
*/

okltest_resolvable_cs(resolvable_cs);
okltest_two_subsumption_resolvable_cs(two_subsumption_resolvable_cs);

okltest_two_subsumption_resolvents_rem_cs(two_subsumption_resolvents_rem_cs);

/* *****************
   * DP resolution *
   *****************
*/

okltest_dp_operator(dp_operator);
okltest_dp_operator_fcs(dp_operator_fcs);

okltest_distribution_min_dp(distribution_min_dp);


/* *******************
   * Blocked clauses *
   *******************
*/

okltest_blocking_literal_p(blocking_literal_p);
okltest_blocked_cs_p(blocked_cs_p);
okltest_okltest_elim_blocked_cs(elim_blocked_cs);
okltest_blocked_extension_cs_p(blocked_extension_cs_p);

/*!
\endhtmlonly
*/
