/* Oliver Kullmann, 27.11.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Resolution/testobjects/Graphs.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/testobjects/Graphs.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/Graphs.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/tests/Graphs.mac")$

okltest_resolutiongraph_cs2g(resolutiongraph_cs2g);
okltest_cc_resolutiongraph_cs(cc_resolutiongraph_cs);

okltest_subresolutiongraph_cs2g(subresolutiongraph_cs2g);
okltest_cc_subresolutiongraph_cs(cc_subresolutiongraph_cs);


/*!
\endhtmlonly
*/
