/* Matthew Gwynne, 23.9.2011 (Swansea) */
/* Copyright 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Resolution/testobjects/Proofs.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/testobjects/Proofs.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/Proofs.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/tests/Proofs.mac")$


/* ******************
   * Basic concepts *
   ******************
*/

okltest_resl_p(resl_p);
okltest_resl_ref_p(resl_ref_p);
okltest_reslrt_p(reslrt_p);

/* ************************************
   * Extraction                       *
   ************************************
*/


okltest_axioms_resl2cl(axioms_resl2cl);
okltest_resolvents_resl2cl(resolvents_resl2cl);
okltest_ncl_php_ext_uni_resl(ncl_php_ext_uni_resl);


/*!
\endhtmlonly
*/
