/* Oliver Kullmann, 7.10.2011 (Swansea) */
/* Copyright 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Resolution/testobjects/Search.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/testobjects/Search.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/Search.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/tests/Search.mac")$

/* *******************
   * Tree resolution *
   *******************
*/

okltest_resolution_closure_treecomp_cs(resolution_closure_treecomp_cs);
okltest_treecomp_refutation_cs(treecomp_refutation_cs);

/* ***********************************
   * Short resolution proofs via SAT *
   ***********************************
*/

okltest_shortresref_fcl2snbfclfd(shortresref_fcl2snbfclfd);

okltest_shortresref_aloamo_fcl(shortresref_aloamo_fcl);

okltest_shortresref_setfirstresolvent_snbcl(shortresref_setfirstresolvent_snbcl);

/*!
\endhtmlonly
*/
