#!/bin/bash
# Oliver Kullmann, 23.4.2011 (Guangzhou)
# Copyright 2011, 2012, 2016, 2020 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.

# Split a SAT-problem into sub-problems, using the OKsolver

# Usage:
#   SplittingViaOKsolver parameters File
# where File is the CNF in DIMACS format, and parameters are for
# the OKsolver-2002.

# For example
#   SplittingViaOKsolver -D20 File
# which cuts off a branch once 20 variables have been eliminated.

# Creates a directory "SplitViaOKsolver_parameters_timestamp" (in the current
# directory), containing the following files:
# - Log : some general logging information
# - Parameters : the parameters passed over to the OKsolver
# - Version : information on this script and the OKsolver
# - Environment : information on the computer environment
# - File : a copy of the instance
# - F : containing the value of File (note that File is a string-variable)
# - Result : output of the OKsolver, after creating the instances
# - N : the number of sub-instances
# - Data : a header-line " i n d" (for "index", "variables", "depth"),
#   followed per line, for indices 1 <= i <= N, by the number n of variables
#   in the partial assignment for the i-th sub-instance and the number d of
#   decision assignments, sorted by descending n (otherwise by increasing i);
#   at the beginning of the line a running counter is added.
# - Statistics : basic evaluation of Data
# - Md5sum : a combined md5sum-hash-value of all files in Instances
# And in the directory Instances we have files with names 1, ..., N,
# each containing a partial assignment in DIMACS format (one line, starting
# with v, followed by literals set to true, concluded by "0") yielding the
# corresponding sub-instance.

set -o errexit
set -o nounset

script_name="SplittingViaOKsolver"
version_number=0.1.15

timestamp=$(date +"%Y-%m-%d-%H%M%S")

directory=SplitViaOKsolver_$(echo $* | tr -d " -./")_${timestamp}

solver=${solver:=OKsolver2002_NTP}
data_preprocessing=PreprocessSplitting-O3-DNDEBUG

echo "${script_name} in version ${version_number} started."

mkdir ${directory}
echo -e "Created directory\n  ${directory}."
cd ${directory}

echo -n "Begin: " > Log
date >> Log
echo "Process id = $$" >> Log

echo "${script_name} ${version_number}" > Version
echo >> Version
${solver} --version >> Version

uname -a > Environment
echo >> Environment
cat /proc/cpuinfo >> Environment
echo >> Environment
free -m >> Environment

parameters="$*"
filename="${!#}"
length=$(($#-1))
other_param=${@:1:$length}
new_param="${other_param} -S=${directory}/Instances ${filename}"
echo ${new_param} > Parameters

cp ../${filename} .
echo $(basename ${filename}) > F

mkdir Instances

echo -e "$(date): Running ${solver},\n  creating partial assignments in subdirectory \"Instances\"."
echo "$(date): Started ${solver}." >> Log
cd ..
set +e
${solver} ${new_param} >${directory}/Result 2>&1
estatus=$?
set -e
cd ${directory}
echo "$(date): Completed run of ${solver}." | tee -a Log

if [[ $estatus != 0 && $estatus != 10 && $estatus != 20 ]]; then
  echo -n "ERROR: " >> Log
  date >> Log
  echo -e "UNEXPECTED RETURN VALUE ${estatus}.\n" | tee -a Log
  exit 1
else
  echo "Return value of OKsolver: ${estatus}" >> Log
fi
echo "Splitting successfully completed. " >> Log

N=$(awk '/splitting_cases/ {print $3}' Result)
echo $N > N

cd Instances
echo "Extracting data from partial assignments."
echo " i n d" > ../Data
${data_preprocessing} $N >> ../Data
cd ..

echo "Extracting statistics."
echo -e "E=read.table(\"Data\")\nsummary(E\$n)\ntable(E\$n)\nsummary(E\$d)\ntable(E\$d)" | R --quiet --vanilla | tail -n +3 > Statistics

echo "$(date): Started computing md5sum." | tee -a Log
cd Instances
current_md5sum=0
for F in *; do
  current_md5sum=$(echo ${current_md5sum} | cat ${F} - | md5sum | awk '{print $1}')
done
cd ..
echo ${current_md5sum} > Md5sum
echo "$(date): Completed computation of md5sum." | tee -a Log
# Remark: the file Instances/decisions is last in the order.

echo -n "Completed: " >> Log
date >> Log
ps p $$ k time S >> Log

exit 0
