/* Matthew Gwynne, 17.1.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/testobjects/Basics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/testobjects/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/tests/Basics.mac")$

/* *******************
   * Boolean vectors *
   *******************
*/

okltest_lex_bv_l(lex_bv_l);
okltest_unrank_lex_bv(unrank_lex_bv);
okltest_rank_lex_bv(rank_lex_bv);

okltest_bv2c(bv2c);
okltest_bv2c_wv(bv2c_wv);


/* *****************
   * Constructions *
   *****************
*/

okltest_bfnm2n1(bfnm2n1);

/*!
\endhtmlonly
*/
