/* Matthew Gwynne, 15.12.2009 (Swansea) */
/* Copyright 2009, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/testobjects/Permutations.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/testobjects/Permutations.mac");

*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/Permutations.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/tests/Permutations.mac")$

/*!
\htmlonly
*/

/* *************************************
   * Permutations as boolean functions *
   *************************************
*/

okltest_lex_bv_l(lex_bv_l);
okltest_unrank_lex_bv(unrank_lex_bv);
okltest_rank_lex_bv(rank_lex_bv);

okltest_bv2c(bv2c);
okltest_bv2c_wv(bv2c_wv);

okltest_perm2dnffcl(perm2dnffcl);
okltest_perm2dnffcs(perm2dnffcs);
okltest_perm2cnffcs(perm2cnffcs);

okltest_m2dnffcl(m2dnffcl);
okltest_m2dnffcs(m2dnffcs);
okltest_m2cnffcs(m2cnffcs);

/*!
\endhtmlonly
*/
