/* Oliver Kullmann, 29.1.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/testobjects/RandomBooleanFunctions.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/testobjects/RandomBooleanFunctions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/RandomBooleanFunctions.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/tests/RandomBooleanFunctions.mac")$


okltest_random_subset(random_subset);
okltest_random_bf_fcs(random_bf_fcs);
okltest_random_bal_bf_fcs(random_bal_bf_fcs);

/*!
\endhtmlonly
*/
