/* Oliver Kullmann, 24.12.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/testobjects/TseitinTranslation.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/testobjects/TseitinTranslation.mac");

*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/TseitinTranslation.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/tests/TseitinTranslation.mac")$

/*!
\htmlonly
*/

/* ****************************
   * Translating DNF into CNF *
   ****************************
*/

okltest_dualts_fcl(dualts_fcl);
okltest_dualtsext_fcl(dualtsext_fcl);


/*!
\endhtmlonly
*/
