/* Oliver Kullmann, 24.12.2010 (Swansea) */
/* Copyright 2010, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/testobjects/TseitinTranslation.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/testobjects/TseitinTranslation.mac");

*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/TseitinTranslation.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/tests/TseitinTranslation.mac")$

/*!
\htmlonly
*/

/* ****************************
   * Translating DNF into CNF *
   ****************************
*/

okltest_dualts_fcl(dualts_fcl);
okltest_dualts_cs(dualts_cs);

okltest_dualtsplus_fcl(dualtsplus_fcl);
okltest_dualtsext_fcl(dualtsext_fcl);

/* Measures */
okltest_nvar_dualts(nvar_dualts);
okltest_nvar_full_dualts(nvar_full_dualts);
okltest_ncl_dualts(ncl_dualts);
okltest_ncl_full_dualts(ncl_full_dualts);
okltest_ncl_list_dualts(ncl_list_dualts);
okltest_ncl_list_full_dualts(ncl_list_full_dualts);


/*!
\endhtmlonly
*/
