#!/usr/bin/env bash
# Oliver Kullmann, 2.4.2020 (Swansea)
# Copyright 2020 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# USAGE:

# A1Reduction file SATWrapper

# #########################

set -o errexit
set -o nounset

program="A1Reduction"
version="0.0.1"

if (( $# != 2 )); then
  echo "Exactly two parameters needed: file, SAT-wrapper" >> /dev/stderr
  exit 1
fi

file="$1"
filename="$(basename ${file})"

satwrapper="$2"
satwrappername="$(basename ${satwrapper})"

timestamp="$(date +%s%N)"

: ${directory:="${program}_${filename}_${satwrappername}_${timestamp}"}
echo ${directory}
mkdir ${directory}

clauseselectors="${directory}/cs_selectors"
tail -1 ${file} > ${clauseselectors}
numclauses=$(cat ${clauseselectors} | awk '{print $(NF-1)}')

resultclauses="${directory}/result_clauses"
touch ${resultclauses}
resultnumber="${directory}/result_number"
echo "0" > ${resultnumber}

solverdirectory="${directory}/SAT1"
inputfile="${file}" outputdirectory="${solverdirectory}" outputfile="/dev/null" ${satwrapper}

if [ -s ${solverdirectory}/err ]; then
  echo "[${program}]: ERROR with solver" >> /dev/stderr
  exit 1
fi

cleanup() {
  rm ${clauseselectors}
  rm -r ${solverdirectory}
}

if [ -s ${solverdirectory}/pass ]; then
  echo "XXX"
else
  cleanup
  exit 0
fi
