#!/usr/bin/env bash
# Oliver Kullmann, 2.4.2020 (Swansea)
# Copyright 2020 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# USAGE:

# EXAMPLE:


set -o errexit
set -o nounset

program="SATWrap_minisat"
version="0.0.2"

: ${minisatcall:="minisat-2.2.0"}

: ${inputfile:="/dev/stdin"}
inputfilename="$(basename ${inputfile})"

: ${outputfile:="/dev/stdout"}

timestamp="$(date +%s%N)"

: ${outputdirectory:="${program}_${inputfilename}_${timestamp}"}

mkdir ${outputdirectory}

: ${assignmentfile:="${outputdirectory}/Pass"}
: ${logfile:="${outputdirectory}/Log"}
: ${errfile:="${outputdirectory}/Err"}
: ${statusfile:="${outputdirectory}/Status"}

if [ ${inputfile} == "/dev/stdin" ]; then
  if [ ${assignmentfile} == "/dev/null" ]; then
    set +e
    cat ${inputfile} | ${minisatcall} "$@" 1> ${logfile} 2> ${errfile}
    exitstatus=$?
    set -e
    echo ${exitstatus} > ${statusfile}
  fi
fi




echo ${outputdirectory} >> ${outputfile}

exit 0

cat ${inputfile} > ${outputfile}
