#!/bin/bash
# Oliver Kullmann, 25.8.2007 (Swansea)
# Copyright 2007 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.

# One input parameter is expected, a filename.
# If the first line matches the regular expression (BRE)
# ^// .*\([12][09][09][0-9]\).*(.+) *$
# then Header.h is inserted right after the first line,
# where XXXX is replaced either by "\1-2007" in case
# \1 is not 2007, or otherwise just by "2007".
# If the first lines doesn't match, then the filename
# is printed out.

set -o errexit -o nounset # -o xtrace
shopt -s extglob

licence_text_file=${OKPLATFORM}/OKsystem/OKlib/System/LegalIssues/Header.h

if [ $# != 1 ]; then
  echo "ERROR[AddLicence1]: Exactly one input parameter is expected, the name of the file where the licence is to be inserted!"
  exit 1
fi

first_line=$(head --lines=1 $1)

if [[ "${first_line}" =~ "^// .*([12][09][09][0-9]).*\(.+\) *$" ]]; then
  year=${BASH_REMATCH[1]}
  if [ "${year}" == "2007" ]; then
    replacement="2007"
  else
    replacement="${year} - 2007"
  fi

  echo ${first_line} > $$
  sed -e "s;XXXX;${replacement};" ${licence_text_file} >> $$
  tail --lines=+2 $1 >> $$

  mv $$ $1

else

  echo $1

fi

