/* Oliver Kullmann, 12.1.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Trees/Lisp/include.mac
  \brief Inclusion file for Maxima trees-related functions

Use by

oklib_load("OKlib/ComputerAlgebra/Trees/Lisp/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/ReingoldTilford.mac")$
oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/Visualisation.mac")$

oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/tests/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Trees/Lisp/tests/ReingoldTilford.mac")$

/*!
\endhtmlonly
*/
