// Oliver Kullmann, 17.1.2010 (Swansea)
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file Experimentation/Investigations/RamseyTheory/GreenTaoProblems/plans/GreenTao_te_m-3-3-3.hpp
  \brief Investigations regarding the "transversal extension" numbers greentao_{m+2}([2,...,2,3,3,3])

  The aloamo-translation is generated by
  output_greentao_stdname(append(create_list(2,i,1,m),[3,3,3]),n)
  and output_greentao_sb_stdname(append(create_list(2,i,1,m),[3,3,3]),n) at
  Maxima-level, and by "GTSat 2 ... 2 3 3 3 n" at C++ level.

  The nested translation is generated by
  output_greentao_standnest_stdname(append(create_list(2,i,1,m),[3,3,3]),n) and
  output_greentao_standnest_strong_stdname(append(create_list(2,i,1,m),[3,3,3]),n).

  The logarithmic translation is generated by
  output_greentao_logarithmic_stdname(append(create_list(2,i,1,m),[3,3,3]),n).

  The reduced translation is created by
  output_greentao_reduced_stdname(append(create_list(2,i,1,m),[3,3,3]),n) resp.
  output_greentao_reduced_strong_stdname(append(create_list(2,i,1,m),[3,3,3]),n).


  \todo greentao_4(2,3,3,3) >= 151
  <ul>
   <li> Let's start with adaptnovelty+ and the logarithmic translation (seems
   best here). </li>
   <li> n=150 easy (with cutoff=10^5; 3 solutions in 100 runs). </li>
   <li> n=151: 100 runs with cutoff=10^6 didn't find a solution (98 times
   min=1, twice min=2). </li>
   <li> OKsolver_2002 for n=151
    <ol>
     <li> For the logarithmic translation, without symmetry breaking and
     without preprocessing, it seems that it will take several hundred days.
     </li>
     <li> With minisat2-preprocessing while otherwise the same it doesn't look
     much different. </li>
     <li> Weak nested standard translation, without symmetry breaking and
     without preprocessing: </li>
    </ol>
   </li>
   <li> minisat2: aborted after 34 restarts (182314933 conflicts, 133210 s).
   </li>
  </ul>


  \todo greentao_5(2,2,3,3,3) >= 154
  <ul>
   <li> The conjecture is greentao_5(2,2,3,3,3) = 154. </li>
   <li> Likely the simple logarithmic translation isn't best here anymore.
   </li>
   <li> n=152: easily found satisfiable by sapsnr and weak nested standard
   translation (cutoff=10^5). </li>
   <li> n=153, weak nested standard translation, rnovelty, cutoff=10^6: In run
   477 a solution was found (seed=105677245, osteps=141802):
   \verbatim
  0   1   2   3
  1 184 290   2
477
   \endverbatim
   </li>
   <li> n=154
    <ol>
     <li> Weak standard nested translation, rnovelty, cutoff=10^6:
     \verbatim
  1   2   3   4
228 761   8   3
1000
     \endverbatim
     </li>
     <li> rnovelty+, cutoff=10^6:
     \verbatim
   1    2    3
 677 1318    5
2000
     \endverbatim
     </li>
     <li> rnovelty, cutoff=2*10^6:
     \verbatim
  1   2   3   4
249 747   3   1
1000
     \endverbatim
     </li>
     <li> rnovelty, cutoff=4*10^6:
     \verbatim
  1   2   3
265 729   6
1000
     \endverbatim
     </li>
     <li> rnovelty, cutoff=8*10^6:
     \verbatim
  1   2   3
267 731   2
1000
> summary(EN2$osteps[EN2$min==1])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
  14340  160400  341700  718500  676100 7094000
> summary(EN2$osteps[EN2$min==2])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.
   1733   34550   69400  109400  125800 2773000
     \endverbatim
     </li>
     <li> rnovelty+, cutoff=8*10^6:
     \verbatim
  1   2
822 178
1000
     \endverbatim
     So rnovelty+ is definitely better than rnovelty. </li>
    </ol>
   </li>
   <li> Best local search algorithm from Ubcsat-suite for the weak nested
   standard translation:
   \verbatim
> E = eval_ubcsat("GreenTao_N_5-2-2-3-3-3_155.cnf")
   \endverbatim
   evaluated by plot(E$alg,E$best) and eval_ubcsat_dataframe(E):
   \verbatim
rnovelty :
 1  2  3
 4 53 43
rnoveltyp :
 1  2  3  4
 3 49 46  2
walksat_tabu :
 1  2  3  4
 3 39 52  6
walksat_tabu_nonull :
 1  2  3  4
 2 37 49 12
sapsnr :
 1  2  3  4  5
 2 21 48 24  5
saps :
 1  2  3  4  5
 2 17 43 31  7
noveltyp :
 1  2  3  4
 1 24 66  9
adaptnoveltyp :
 1  2  3  4  5
 1 13 52 33  1
gwsat :
 1  2  3  4  5  6
 1  8 35 39 14  3
rsaps :
 1  2  3  4  5  6  7
 1  2 10 31 26 26  4
novelty :
 2  3  4
17 65 18
irots :
 2  3  4  5
11 47 38  4
rots :
 2  3  4  5  6
 7 35 44 13  1
hwsat :
 2  3  4  5  6  7  8  9
 4 13 31 30 17  3  1  1
walksat :
 2  3  4  5  6  7  8  9
 2 11 17 20 21 18  9  2
hsat :
 3  4  5  6  7  8  9 10 11 12
 2  1 10 20 24 15 11  7  5  5
samd :
 3  4  5  6  7  8  9 10 11 12 13
 1  5  8 16 26 16 13  8  3  3  1
gsat_tabu :
 3  4  5  6  7  8  9 10 11 12
 1  3  9 16 21 13 20 12  4  1
gsat :
 4  5  6  7  8  9 10 12
 2 10 11 26 26 17  7  1
gsat_simple :
 5  6  7  8  9 10 11 12 13 14
 6 14 23 16 17  6 13  2  2  1
   \endverbatim
   </li>
   <li> Weak nested standard translation, rnovelty, cutoff=10^6:
   \verbatim
 1  2  3
14 83  3
100
   \endverbatim
   </li>
   <li> Weak nested standard translation, sapsnr, cutoff=10^6:
   \verbatim
  1   2   3
183 736  81
1000
   \endverbatim
   So actually sapsnr might be better. </li>
  </ul>

*/

