// Oliver Kullmann, 11.2.2010 (Swansea)
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file Experimentation/Investigations/RamseyTheory/GreenTaoProblems/plans/GreenTao_te_m-3-3-4.hpp
  \brief Investigations regarding the "transversal extension" numbers greentao_{m+2}([2,...,2,3,3,4])

  The aloamo-translation is generated by
  output_greentao_stdname(append(create_list(2,i,1,m),[3,3,4]),n)
  and output_greentao_sb_stdname(append(create_list(2,i,1,m),[3,3,4]),n) at
  Maxima-level, and by "GTSat 2 ... 2 3 3 4 n" at C++ level.

  The nested translation is generated by
  output_greentao_standnest_stdname(append(create_list(2,i,1,m),[3,3,4]),n) and
  output_greentao_standnest_strong_stdname(append(create_list(2,i,1,m),[3,3,4]),n).

  The logarithmic translation is generated by
  output_greentao_logarithmic_stdname(append(create_list(2,i,1,m),[3,3,4]),n).

  The reduced translation is created by
  output_greentao_reduced_stdname(append(create_list(2,i,1,m),[3,3,4]),n) resp.
  output_greentao_reduced_strong_stdname(append(create_list(2,i,1,m),[3,3,4]),n).


  \todo greentao_4(2,3,3,4) > 446
  <ul>
   <li> First considering the weak standard nested translation with rnovelty+.
   </li>
   <li> n=442, cutoff=10^6: finds one solution in 15 runs (seed=2776413455,
   osteps=327557). </li>
   <li> n=443
    <ol>
     <li> cutoff=10^6: in 100 runs no solutions was found. </li>
     <li> cutoff=2*10^6: finds in run 78 one solution (seed=3773007564,
     osteps=1936809). </li>
    </ol>
   </li>
   <li> n=444, cutoff=4*10^6: finds a solution in run 10 (seed=2050602575,
   osteps=2112736). </li>
   <li> n=445, cutoff=4*10^6: finds a solution in run 7 (seed=4168291728,
   osteps=2670307). </li>
   <li> n=446, cutoff=4*10^6: finds a solution in run 2 (seed=3913893840,
   osteps=3235502). </li>
  </ul>

*/

