// Oliver Kullmann, 12.4.2010 (Swansea)
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file Experimentation/Investigations/RamseyTheory/GreenTaoProblems/plans/GreenTao_3-4-4-k.hpp
  \brief On investigations into Green-Tao numbers greentao_3(4,4,k)

  Aloamo-translations are generated by output_greentao_stdname([4,4,k],n) at
  Maxima-level, and by "GTSat 4 4 k n" at C++ level.

  Standard nested translations are generated by
  output_greentao_standnest_stdname([4,4,k],n) resp.
  output_greentao_standnest_strong_stdname([4,4,k],n).


  \todo greentao_3(4) > 3500
  <ul>
   <li> Let's start with the weak standard nested translation and with
   rnovelty+. </li>
   <li> greentao_2(4) = 512. </li>
   <li> n=1000 is satisfiable in 205 steps. </li>
   <li> n=1500 is satisfiable in 404 steps. </li>
   <li> n=2000 is satisfiable in 1050 steps. </li>
   <li> n=2500 is satisfiable in 1339 steps. </li>
   <li> n=3000 is satisfiable in 2831 steps. </li>
   <li> n=3500 is satisfiable in 6780 steps (seems hard for OKsolver_2002,
   and also for minisat2). </li>
  </ul>
  
*/
