// Oliver Kullmann, 7.11.2009 (Swansea)
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file Experimentation/Investigations/RamseyTheory/GreenTaoProblems/plans/GreenTao_te_m-3-4.hpp
  \brief Investigations regarding the "transversal extension" numbers greentao_{m+2}([2,...,2,3,4])

  Generated by output_greentao_stdname(append(create_list(2,i,1,m),[3,4]),n)
  and output_greentao_sb_stdname(append(create_list(2,i,1,m),[3,4]),n).


  \todo greentao_3(2,3,4) = 117
  <ul>
   <li> Easy for OKsolver_2002:
   \verbatim
> OKsolver_2002-O3-DNDEBUG GreenTao_3-2-3-4_116.cnf
s SATISFIABLE
c sat_status                            1
c initial_maximal_clause_length         4
c initial_number_of_variables           348
c initial_number_of_clauses             8061
c initial_number_of_literal_occurrences 17337
c number_of_initial_unit-eliminations   0
c reddiff_maximal_clause_length         0
c reddiff_number_of_variables           0
c reddiff_number_of_clauses             0
c reddiff_number_of_literal_occurrences 0
c number_of_2-clauses_after_reduction   7018
c running_time(sec)                     2.0
c number_of_nodes                       2384
c number_of_single_nodes                0
c number_of_quasi_single_nodes          0
c number_of_2-reductions                11743
c number_of_pure_literals               0
c number_of_autarkies                   21
c number_of_missed_single_nodes         3
c max_tree_depth                        76
c number_of_table_enlargements          0
c number_of_1-autarkies                 46284
c number_of_new_2-clauses               0
c maximal_number_of_added_2-clauses     0
c file_name                             GreenTao_3-2-3-4_116.cnf
> OKsolver_2002-O3-DNDEBUG GreenTao_3-2-3-4_117.cnf
s UNSATISFIABLE
c sat_status                            0
c initial_maximal_clause_length         4
c initial_number_of_variables           351
c initial_number_of_clauses             8198
c initial_number_of_literal_occurrences 17633
c number_of_initial_unit-eliminations   0
c reddiff_maximal_clause_length         0
c reddiff_number_of_variables           0
c reddiff_number_of_clauses             0
c reddiff_number_of_literal_occurrences 0
c number_of_2-clauses_after_reduction   7137
c running_time(sec)                     2.4
c number_of_nodes                       2703
c number_of_single_nodes                0
c number_of_quasi_single_nodes          0
c number_of_2-reductions                14339
c number_of_pure_literals               0
c number_of_autarkies                   24
c number_of_missed_single_nodes         11
c max_tree_depth                        77
c number_of_table_enlargements          0
c number_of_1-autarkies                 57409
c number_of_new_2-clauses               0
c maximal_number_of_added_2-clauses     0
c file_name                             GreenTao_3-2-3-4_117.cnf
   \endverbatim
   </li>
  </ul>


  \todo greentao_4(2,2,3,4) = 120
  <ul>
   <li> n=117,118: minisat2 determines satisfiability in 13 restarts. </li>
   <li> n=119: minisat2 determines satisfiability in 15 restarts. </li>
   <li> n=120: minisat2 determines unsatisfiability in 13 restarts. </li>
   <li> n=130
    <ol>
     <li> OKsolver_2002 without symmetry breaking and without preprocessing
     apparently falls into a deep whole:
     \verbatim
> OKsolver_2002-O3-DNDEBUG -M -D30 GreenTao_4-2-2-3-4_130.cnf
227528557:    113      0.00  2.24E+04     0.80s     0.00s     0y   0d  0h  1m 15s     0     1   85

s UNKNOWN
c sat_status                            2
c initial_maximal_clause_length         4
c initial_number_of_variables           520
c initial_number_of_clauses             18821
c initial_number_of_literal_occurrences 39254
c number_of_initial_unit-eliminations   0
c reddiff_maximal_clause_length         0
c reddiff_number_of_variables           0
c reddiff_number_of_clauses             0
c reddiff_number_of_literal_occurrences 0
c number_of_2-clauses_after_reduction   17550
c running_time(sec)                     253.6
c number_of_nodes                       44429
c number_of_single_nodes                37
c number_of_quasi_single_nodes          0
c number_of_2-reductions                344658
c number_of_pure_literals               0
c number_of_autarkies                   519
c number_of_missed_single_nodes         5154
c max_tree_depth                        126
c number_of_table_enlargements          0
c number_of_1-autarkies                 5648488
c number_of_new_2-clauses               0
c maximal_number_of_added_2-clauses     0
c file_name                             GreenTao_4-2-2-3-4_130.cnf
     \endverbatim
     </li>
     <li> OKsolver_2002 without symmetry breaking and with preprocessing seems
     to be able to solve it in 2 days (csltok), so preprocessing seems to
     help. </li>
     <li> minisat2 determines unsatisfiability in 18 restarts (261912
     conflicts) without symmetry breaking, and behaves *identical* on the
     symmetry-breaking instance. </li>
     <li> picosat913 needs 4 times longer without minisat2 preprocessing and
     still twice as long with minisat2 preprocessing. </li>
     <li> So likely again minisat2 is best here (and the conflict-driven
     approach achieves something). </li>
    </ol>
   </li>
  </ul>


  \todo greentao_5(2,2,2,3,4) = 128
  <ul>
   <li> Best local search solver:
   \verbatim
> E = eval_ubcsat("GreenTao_5-2-2-2-3-4_125.cnf")
   \endverbatim
   evaluated by plot(E$alg,E$best): hard to say, since many algorithms
   determined satisfiability, but saps is best, followed perhaps by gwsat,
   adaptnovelty+ and sapsnr. </li>
   <li> n=125: minisat2 determines satisfiability in 17 restarts. </li>
   <li> n=127: minisat2 determines satisfiability in 20 restarts. </li>
   <li> n=128: minisat2 determines unsatisfiability in 21 restarts. </li>
   <li> n=130: minisat2 determines unsatisfiability in 20 restarts</li>
   <li> n=140: minisat2 determines unsatisfiability in 24 restarts (20m
   on csltok; there seems to be the pattern, that short before the search-end
   the average length of learned clauses jumps (over 100)). </li>
  </ul>


  \todo greentao_6(2,...,2,3,4) = 136
  <ul>
   <li> Best local search solver:
   \verbatim
> E = eval_ubcsat("GreenTao_6-2-2-2-2-3-4_135.cnf")
   \endverbatim
   evaluated by plot(E$alg,E$best): the following four solvers seem best:
   \verbatim
> table(E$best[E$alg=="gwsat"])
 0  1  2  3
 2 21 69  8
> table(E$best[E$alg=="rnovelty"])
 0  1  2  3
 2 20 71  7
> table(E$best[E$alg=="sapsnr"])
 0  1  2  3
 1 32 66  1
> table(E$best[E$alg=="rnoveltyp"])
 0  1  2  3
 1 17 70 12
> table(E$best[E$alg=="saps"])
 1  2
49 51
   \endverbatim
   </li>
   <li> Repeated the evaluation for n=140: for cutoff=100000 no solver could
   find a satisfying assignment, while 8 found min=1; sapsnr looks best,
   followed by saps. Using cutoff=10^6: Now saps looks clearly best. </li>
   <li> n=130: minisat2 determines satisfiability in 13 restarts. </li>
   <li> n=135: minisat2 determines satisfiability in 24 restarts; so perhaps
   unsatisfiability can still be determined here, but for satisfiable cases
   ubcsat is to be used. </li>
   <li> n=136:
    <ol>
     <li> cutoff=10^6 with saps: 97 times min=1, 3 times min=2. </li>
     <li> cutoff=10^6 with sapsnr: 68 times min=1, 32 times min=2. </li>
     <li> cutoff=10^6 with gwsat: 93 times min=1, 7 times min=2. </li>
     <li> cutoff=10^6 with rnovelty: 78 times min=1, 21 times min=2, once
     min=3. </li>
     <li> minisat2: determined unsatisfiability in 31 restarts (55800700
     conflicts, 106321 s (csltok)). </li>
   </li>
   <li> n=140:
    <ol>
     <li> None of the ubcsat-algorithms found a solution in 100 runs and with
     cutoff=10^6. </li>
    </ol>
   </li>
  </ul>


  \todo greentao_7(2,...,2,3,4) >= 142
  <ul>
   <li> n=140: cutoff=10^5 using saps found 3 solutions in 100 runs (e.g.,
   seed=4007050970, osteps=26801). </li>
   <li> n=141
    <ol>
     <li> cutoff=10^6 using saps:
     \verbatim
 0  1  2
 9 78 13
100
     \endverbatim
     (best solution: seed=414927092, osteps=73582).
     </li>
    </ol>
   </li>
   <li> n=142
    <ol>
     <li> cutoff=10^6 using saps:
     \verbatim
 1  2
77 23
100
     \endverbatim
     </li>
     <li> cutoff=10^7 using saps:
     \verbatim

     \endverbatim
     </li>
    </ol>
   </li>
   <li> n=145
    <ol>
     <li> cutoff=10^6 using saps:
     \verbatim
 1  2
39 61
100
     \endverbatim
     </li>
    </ol>
   </li>
   <li> n=150:
    <ol>
     <li> cutoff=10^5 using saps:
     \verbatim
 1  2  3  4
 8 52 38  2
100
     \endverbatim
     </li>
     <li> cutoff=10^6 using saps:
     \verbatim
 1  2
44 56
100
     \endverbatim
     </li>
    </ol>
   </li>
  </ul>

*/

