/* Oliver Kullmann, 11.7.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/BicliquePartitions/tests/BasicNotions.mac
  \brief Tests for biclique-notions

Use by

oklib_load("OKlib/ComputerAlgebra/Graphs/Lisp/BicliquePartitions/tests/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Graphs/Lisp/Basic.mac")$

kill(f)$


/* ***********************
   * Fundamental notions *
   ***********************
*/

okltest_ebcp_gg_p(f) := block([G,edgef],
  assert(f({},[{},{},edgef]) = true),
  assert(f({},[{1},{},edgef]) = true),
  assert(f({{1},{}},[{1,2},{1},lambda([e],{1,2})]) = false),
  assert(f({{1},{}},[{1},{1},lambda([e],{1})]) = false),
  assert(f({{1},{}},[{1,2},{1},lambda([e],{1,2})]) = false),
  assert(f({{1},{2}},[{1,2},{1,2},lambda([e],if e=1 then {1} else {1,2})]) = false),
  assert(f({{1,2}},[{1,2},{1,2},lambda([e],if e=1 then {1} else {1,2})]) = false),
  assert(f({{1},{2}},[{1,2},{1,2},lambda([e],{1,2})]) = true),
  assert(f({{1},{2}},[{1,2,3},{1,2},lambda([e],if e=1 then {1,2} else {2,3})]) = true),
  assert(f({{1},{2}},[{1,2},{1,2},lambda([e],{1,2})]) = true),
  assert(f({{1},{2}},[{1,2},{1,2,3},lambda([e],{1,2})]) = false),
  assert(f({{1,2},{2}},[{1,2},{1,2},lambda([e],{1,2})]) = false),
  true)$

okl_test_greedy_bcp_gl(f) := block(
  assert(setify(f([{1,2},{{1,2}}])) = {[{1},{2}]}),
  assert(setify(f([{1,2,3,4},{{1,3},{2,4}}]))={[{1},{3}],[{2},{4}]}),
  assert(setify(f([{1,2,3,4},{{1,3},{2,4},{1,4},{2,3}}]))={[{1,2},{3,4}]}),
  assert(setify(f([{1,2,3,4,5,6},{{1,3},{2,4},{1,4},{2,3},{5,6},{1,6},{4,5}}]))={[{1,2},{3,4}],[{1,5},{6}],[{4},{5}]}),
  assert(setify(f([{1,2,3,4,5,6,7},{{1,3},{2,4},{1,4},{2,3},{5,6},{1,6},{4,5},{2,7}}]))={[{1,2},{3,4}],[{1,5},{6}],[{2},{7}],[{4},{5}]}),
  true) $

/*!
\endhtmlonly
*/
