/* Oliver Kullmann, 11.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/BicliquePartitions/tests/Bicliques.mac
  \brief Tests for biclique-notions

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/BicliquePartitions/tests/Bicliques.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$


/* ***********************
   * Fundamental notions *
   ***********************
*/

okltest_vbc_gl_p(f) := block([G],
  assert(f(0,G) = false),
  assert(f([],G) = false),
  assert(f([0,0],G) = false),
  assert(f([{1},{1}], G) = false),
  assert(f([{},{}], [{},{}]) = true),
  assert(f([{1},{}], [{},{}]) = false),
  assert(f([{1},{}], [{1},{}]) = true),
  assert(f([{},{1,2}], [{1,2,3},{{1,2}}]) = true),
  assert(f([{1,2},{3,4}], [{1,2,3,4},{{1,3},{1,4},{2,3},{2,4}}]) = true),
  assert(f([{1,2},{3,4}], [{1,2,3,4},{{1,3},{1,4},{2,3},{2,4},{1}}]) = true),
  assert(f([{1,2},{3,4}], [{1,2,3,4},{{1,3},{1,4},{2,3},{3,4}}]) = false),
  true)$


/*!
\endhtmlonly
*/
