/* Oliver Kullmann, 23.1.2008 (Swansea) */
/* Copyright 2008, 2011, 2020 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Numerical/Lisp/include.mac
  \brief Inclusion file for Maxima functions related to numerical computations

Use by

oklib_load("OKlib/ComputerAlgebra/Numerical/Lisp/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Numerical/Lisp/LinearProgramming.mac")$
oklib_include("OKlib/ComputerAlgebra/Numerical/Lisp/Minimisation.mac")$
oklib_include("OKlib/ComputerAlgebra/Numerical/Lisp/Norms.mac")$
oklib_include("OKlib/ComputerAlgebra/Numerical/Lisp/Zeros.mac")$

oklib_include("OKlib/ComputerAlgebra/Numerical/Lisp/tests/LinearProgramming.mac")$
oklib_include("OKlib/ComputerAlgebra/Numerical/Lisp/tests/Norms.mac")$

/*!
\endhtmlonly
*/
