/* Oliver Kullmann, 3.2.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Transversals/tests/Basics.mac
  \brief Tests for basic transversal-functions

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/tests/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$

kill(f)$


okltest_transversal_p(f) := (
  assert(f({},{}) = true),
  assert(f({},{{}}) = false),
  assert(f({},{{1}}) = false),
  assert(f({1,2},{{1,3},{2,4},{1,2,3,4}}) = true),
  assert(f({1,2,9},{{1,3},{2,4},{1,2,3,4}}) = true),
  true)$

okltest_etransversal_p(f) := (
  assert(f({},{}) = true),
  assert(f({},{{}}) = false),
  assert(f({},{{1}}) = false),
  assert(f({1,2},{{1,3},{2,4},{1,2,3,4}}) = false),
  assert(f({1,2},{{1,3},{2,4},{2,3,4}}) = true),
  assert(f({1,2,9},{{1,3},{2,4},{1,2,3,4}}) = false),
  assert(f({1,2,9},{{1,3},{2,4},{1,3,4}}) = true),
  assert(f({{2},{2,1},{2,3},{2,4}}, {{{1},{2},{3,4}},{{1},{2,3},{4}},{{1},{3},{2,4}},{{1,2},{3},{4}},{{1,3},{2},{4}},{{1,4},{2},{3}}}) = true),
  true)$


/* ************************
   * Greedy approximation *
   ************************
*/

okltest_greedy_transversal_ohg(f) := (
  assert(f([{},{}]) = {}),
  assert(f([{},{{}}]) = false),
  /* XXX */
  true)$

okltest_greedy_transversal_(f) := (
  assert(f([]) = {}),
  for n : 0 thru 5 do block([N : setn(n)],
    assert(f(listify(singletons(N))) = N)),
  assert(f([{1,2},{1,3},{2,4},{1,5},{2,3}]) = {1,2}),
  /* XXX */
  true)$


/*!
\endhtmlonly
*/
