/* Oliver Kullmann, 11.2.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Gasarch.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Gasarch.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Gasarch.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Gasarch.mac")$

/* *****************************************************
   * Hypergraphs of sub-square-vertices in a rectangle *
   *****************************************************
*/

okltest_gasarch_hg(gasarch_hg);

okltest_standardise_gasarch(standardise_gasarch);

/* **************
   * Statistics *
   **************
*/

okltest_nver_gasarch_ohg(nver_gasarch_ohg);
okltest_nver_gasarch_hg(nver_gasarch_hg);
okltest_nhyp_gasarch_ohg(nhyp_gasarch_ohg);
okltest_nhyp_gasarch_hg(nhyp_gasarch_hg);


/*!
\endhtmlonly
*/
