/* Oliver Kullmann, 26.6.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Generators.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Generators.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Generators.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Generators.mac")$

/* ************************
   * Complete hypergraphs *
   ************************
*/

okltest_complete_hg(complete_hg);
okltest_complete_stdhg(complete_stdhg);
okltest_complete_ohg(complete_ohg);
okltest_complete_stdohg(complete_stdohg);

okltest_nver_complete_hg(nver_complete_hg);
okltest_nhyp_complete_hg(nhyp_complete_hg);

/* ******************************
   * Schur's and Rado's theorem *
   ******************************
*/

okltest_schurtriples_ohg(schurtriples_ohg);
okltest_schurtriples_hg(schurtriples_hg);

okltest_schurtriples_me_ohg(schurtriples_me_ohg);
okltest_schurtriples_me_hg(schurtriples_me_hg);

okltest_nhyp_list_schurtriples_ohg(nhyp_list_schurtriples_ohg);
okltest_nhyp_list_schurtriples_me_ohg(nhyp_list_schurtriples_me_ohg);
okltest_nhyp_schurtriples_ohg(nhyp_schurtriples_ohg);
okltest_nhyp_schurtriples_me_ohg(nhyp_schurtriples_me_ohg);

/* ********************
   * Ramsey's theorem *
   ********************
*/

okltest_ramsey_hg(ramsey_hg);
okltest_ramsey_ohg(ramsey_ohg);

okltest_rv_var(rv_var);
okltest_set_rv(set_rv);
okltest_ramseyrv_ohg(ramseyrv_ohg);

okltest_nver_ramsey_hg(nver_ramsey_hg);
okltest_nver_ramsey_ohg(nver_ramsey_ohg);
okltest_nhyp_ramsey_hg(nhyp_ramsey_hg);
okltest_nhyp_ramsey_ohg(nhyp_ramsey_ohg);

/* ***************************
   * Generalised Tic-tac-toe *
   ***************************
*/

okltest_gttt_tlbr(gttt_tlbr);
okltest_gttt_bltr(gttt_bltr);

okltest_gttt_lines(gttt_lines);
okltest_gttt_length(gttt_length);
okltest_gttt_slope(gttt_slope);
okltest_gttt_startpoints(gttt_startpoints);
okltest_gttt_lines_k(gttt_lines_k);

okltest_gttt_ohg(gttt_ohg);

/*!
\endhtmlonly
*/
