/* Oliver Kullmann, 26.6.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Generators.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Generators.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Generators.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Generators.mac")$

/* ************************
   * Complete hypergraphs *
   ************************
*/

okltest_complete_stdhg(complete_stdhg);

okltest_nver_complete_hg(nver_complete_hg);
okltest_nhyp_complete_hg(nhyp_complete_hg);

/* *****************************
   * Van der Waerden's theorem *
   *****************************
*/

okltest_arpr(arpr);

okltest_arithprog_finish(arithprog_finish);
okltest_arithprog_ohg(arithprog_ohg);
okltest_arithprog_hg(arithprog_hg);

okltest_nver_arithprog_hg(nver_arithprog_hg);
okltest_nver_arithprog_ohg(nver_arithprog_ohg);
okltest_nhyp_arithprog_hg(nhyp_arithprog_hg);
okltest_nhyp_arithprog_ohg(nhyp_arithprog_ohg);

okltest_arithmetic_progression_p(arithmetic_progression_p);
okltest_arithmetic_progression_d_p(arithmetic_progression_d_p);

okltest_arithmetic_progressions(arithmetic_progressions);
okltest_arithprog_list_ohg(arithprog_list_ohg);

/* ******************************
   * Schur's and Rado's theorem *
   ******************************
*/

okltest_schurtriples_ohg(schurtriples_ohg);
okltest_schurtriples_hg(schurtriples_hg);

/* ********************
   * Ramsey's theorem *
   ********************
*/

okltest_ramsey_hg(ramsey_hg);
okltest_ramsey_ohg(ramsey_ohg);

okltest_rv_var(rv_var);
okltest_set_rv(set_rv);
okltest_ramseyrv_ohg(ramseyrv_ohg);

okltest_nver_ramsey_hg(nver_ramsey_hg);
okltest_nver_ramsey_ohg(nver_ramsey_ohg);
okltest_nhyp_ramsey_hg(nhyp_ramsey_hg);
okltest_nhyp_ramsey_ohg(nhyp_ramsey_ohg);

/*!
\endhtmlonly
*/
