/* Oliver Kullmann, 26.6.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Generators.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Generators.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Generators.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Generators.mac")$

/* ************************
   * Complete hypergraphs *
   ************************
*/

okltest_complete_hg(complete_hg);
okltest_complete_stdhg(complete_stdhg);
okltest_complete_ohg(complete_ohg);
okltest_complete_stdohg(complete_stdohg);

okltest_nver_complete_hg(nver_complete_hg);
okltest_nhyp_complete_hg(nhyp_complete_hg);

okltest_nver_colouring_hg(nver_colouring_hg);
okltest_nhyp_colouring_hg(nhyp_colouring_hg);

/* ***************************
   * Generalised Tic-tac-toe *
   ***************************
*/

okltest_gttt_tlbr(gttt_tlbr);
okltest_gttt_bltr(gttt_bltr);

okltest_gttt_lines(gttt_lines);
okltest_gttt_length(gttt_length);
okltest_gttt_slope(gttt_slope);
okltest_gttt_startpoints(gttt_startpoints);
okltest_gttt_lines_k(gttt_lines_k);

okltest_gttt_ohg(gttt_ohg);

/*!
\endhtmlonly
*/
