/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Hindman.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Hindman.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Hindman.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Hindman.mac")$

/* *****************
   * Hindman quads *
   *****************
*/

okltest_hindman_a1k2_ohg(hindman_a1k2_ohg);
okltest_nver_hindman_a1k2_ohg(nver_hindman_a1k2_ohg);
okltest_nhyp_hindman_a1k2_ohg(nhyp_hindman_a1k2_ohg);

okltest_hindmani_a1k2_ohg(hindmani_a1k2_ohg);
okltest_nver_hindmani_a1k2_ohg(nver_hindmani_a1k2_ohg);
okltest_nhyp_hindmani_a1k2_ohg(nhyp_hindmani_a1k2_ohg);

okltest_hindmanquadsgen_degenerated_ohg(hindmanquadsgen_degenerated_ohg);
okltest_hindmanquadsgen_ohg(hindmanquadsgen_ohg);

/* ********************
   * The general case *
   ********************
*/

okltest_hindman_ohg(hindman_ohg_0);
okltest_hindmani_ohg(hindmani_ohg_0);

/*!
\endhtmlonly
*/
