/* Oliver Kullmann, 15.7.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Schur.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/testobjects/Schur.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/Schur.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Generators/tests/Schur.mac")$

/* *******************
   * Schur's theorem *
   *******************
*/

okltest_schurtriples_ohg(schurtriples_ohg);
okltest_schurtriples_hg(schurtriples_hg);

okltest_schurtriples_me_ohg(schurtriples_me_ohg);
okltest_schurtriples_me_hg(schurtriples_me_hg);

okltest_wschurtriples_ohg(wschurtriples_ohg);

okltest_nhyp_list_schurtriples_ohg(nhyp_list_schurtriples_ohg);
okltest_nhyp_list_schurtriples_me_ohg(nhyp_list_schurtriples_me_ohg);
okltest_nhyp_list_wschurtriples_ohg(nhyp_list_wschurtriples_ohg);
okltest_nhyp_schurtriples_ohg(nhyp_schurtriples_ohg);
okltest_nhyp_schurtriples_me_ohg(nhyp_schurtriples_me_ohg);
okltest_nhyp_wschurtriples_ohg(nhyp_wschurtriples_ohg);

okltest_has_schurtriple(has_schurtriple);
okltest_has_wschurtriple(has_wschurtriple);

/* ************
   * Symmetry *
   ************
*/

okltest_schurtriples_pd_ohg(schurtriples_pd_ohg);
okltest_wschurtriples_pd_ohg(wschurtriples_pd_ohg);

okltest_nver_schurtriples_pd_ohg(nver_schurtriples_pd_ohg);
okltest_nver_wschurtriples_pd_ohg(nver_wschurtriples_pd_ohg);

/* *****************
   * Group triples *
   *****************
*/

okltest_grouptriples_ougrp2ohg(grouptriples_ougrp2ohg);
okltest_grouptriples_ugrp2hg(grouptriples_ugrp2hg);
okltest_grouptriples_me_ougrp2ohg(grouptriples_me_ougrp2ohg);
okltest_grouptriples_me_ugrp2hg(grouptriples_me_ugrp2hg);
okltest_wgrouptriples_ougrp2ohg(wgrouptriples_ougrp2ohg);
okltest_wgrouptriples_ugrp2hg(wgrouptriples_ugrp2hg);

okltest_nver_grouptriples_ougrp2ohg(nver_grouptriples_ougrp2ohg);
okltest_nver_grouptriples_ugrp2hg(nver_grouptriples_ugrp2hg);
okltest_nver_grouptriples_me_ougrp2ohg(nver_grouptriples_me_ougrp2ohg);
okltest_nver_grouptriples_me_ugrp2hg(nver_grouptriples_me_ugrp2hg);
okltest_nver_wgrouptriples_ougrp2ohg(nver_wgrouptriples_ougrp2ohg);
okltest_nver_wgrouptriples_ugrp2hg(nver_wgrouptriples_ugrp2hg);

okltest_nhyp_grouptriples_ougrp2ohg(nhyp_grouptriples_ougrp2ohg);
okltest_nhyp_wgrouptriples_ougrp2ohg(nhyp_wgrouptriples_ougrp2ohg);

okltest_mschurtriples_ohg(mschurtriples_ohg);
okltest_mschurtriples_hg(mschurtriples_hg);
okltest_mschurtriples_me_ohg(mschurtriples_me_ohg);
okltest_mschurtriples_me_hg(mschurtriples_me_hg);
okltest_wmschurtriples_ohg(wmschurtriples_ohg);
okltest_wmschurtriples_hg(wmschurtriples_hg);

okltest_nver_mschurtriples_ohg(nver_mschurtriples_ohg);
okltest_nver_mschurtriples_hg(nver_mschurtriples_hg);
okltest_nver_mschurtriples_me_ohg(nver_mschurtriples_me_ohg);
okltest_nver_mschurtriples_me_hg(nver_mschurtriples_me_hg);
okltest_nver_wmschurtriples_ohg(nver_wmschurtriples_ohg);
okltest_nver_wmschurtriples_hg(nver_wmschurtriples_hg);

okltest_nhyp_mschurtriples_ohg(nhyp_mschurtriples_ohg);
/* okltest_nhyp_mschurtriples_hg(nhyp_mschurtriples_hg); */
/* okltest_nhyp_mschurtriples_me_ohg(nhyp_mschurtriples_me_ohg); */
/* okltest_nhyp_mschurtriples_me_hg(nhyp_mschurtriples_me_hg); */
okltest_nhyp_wmschurtriples_ohg(nhyp_wmschurtriples_ohg);
/* okltest_nhyp_wmschurtriples_hg(nhyp_wmschurtriples_hg); */

okltest_symmetrictriples_ohg(symmetrictriples_ohg);
okltest_symmetrictriples_hg(symmetrictriples_hg);
okltest_symmetrictriples_me_ohg(symmetrictriples_me_ohg);
okltest_symmetrictriples_me_hg(symmetrictriples_me_hg);
okltest_wsymmetrictriples_ohg(wsymmetrictriples_ohg);
okltest_wsymmetrictriples_hg(wsymmetrictriples_hg);

okltest_nver_symmetrictriples_ohg(nver_symmetrictriples_ohg);
okltest_nver_symmetrictriples_hg(nver_symmetrictriples_hg);
okltest_nver_symmetrictriples_me_ohg(nver_symmetrictriples_me_ohg);
okltest_nver_symmetrictriples_me_hg(nver_symmetrictriples_me_hg);
okltest_nver_wsymmetrictriples_ohg(nver_wsymmetrictriples_ohg);
okltest_nver_wsymmetrictriples_hg(nver_wsymmetrictriples_hg);

okltest_nhyp_symmetrictriples_ohg(nhyp_symmetrictriples_ohg);
okltest_nhyp_wsymmetrictriples_ohg(nhyp_wsymmetrictriples_ohg);

/*!
\endhtmlonly
*/
