/* Oliver Kullmann, 25.6.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Isomorphisms/testobjects/Homomorphisms.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/Isomorphisms/testobjects/Homomorphisms.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Isomorphisms/Homomorphisms.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Isomorphisms/tests/Homomorphisms.mac")$

/* ***************************
   * Checking the properties *
   ***************************
*/



/* ****************************
   * Brute-force enumerations *
   ****************************
*/

okltest_all_pisomorphisms_bydef_stgl(all_pisomorphisms_bydef_stgl);


/*!
\endhtmlonly
*/
