/* Oliver Kullmann, 6.7.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/BasicNotions.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/BasicNotions.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/BasicNotions.mac")$

/* ************************************
   * Checking the defining properties *
   ************************************
*/

okltest_compo_p(compo_p);

okltest_grd_p(grd_p);
okltest_ugrd_p(ugrd_p);
okltest_cgrd_p(cgrd_p);
okltest_cugrd_p(cugrd_p);

okltest_sgr_p(sgr_p);
okltest_csgr_p(csgr_p);
okltest_mon_p(mon_p);
okltest_cmon_p(cmon_p);

okltest_qgrp_p(qgrp_p);
okltest_cqgrp_p(cqgrp_p);
okltest_uqgrp_p(uqgrp_p);
okltest_cuqgrp_p(cuqgrp_p);

okltest_grp_p(grp_p);
okltest_cgrp_p(cgrp_p);
okltest_grpn_p(grpn_p);
okltest_cgrpn_p(cgrpn_p);
okltest_grpni_p(grpni_p);
okltest_cgrpni_p(cgrpni_p);


/* *********************
   * Checking equality *
   *********************
*/

okltest_grd_equalp(grd_equalp);
okltest_ugrd_equalp(ugrd_equalp);

/* *************
   * Downcasts *
   *************
*/

okltest_ugrd2grd(ugrd2grd);

okltest_grpni2grpn(grpni2grpn);
okltest_grpni2grp(grpni2grp);
okltest_grpn2grp(grpn2grp);

/* **************
   * Promotions *
   **************
*/

/*!
\endhtmlonly
*/
