/* Oliver Kullmann, 7.7.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/Constructions.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/Constructions.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Constructions.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Constructions.mac")$

/* ***********************
   * Complex composition *
   ***********************
*/

okltest_complex_compo(complex_compo);

okltest_complex_grd(complex_grd);

/* *********************
   * Product groupoids *
   *********************
*/

okltest_product_compo(product_compo);

okltest_product_grd(product_grd);

/* *****************
   * Transposition *
   *****************
*/

okltest_transposed_compo(transposed_compo);

okltest_transposed_grd(transposed_grd);
okltest_transposed_ugrd(transposed_ugrd);

/*!
\endhtmlonly
*/
