/* Oliver Kullmann, 14.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/Enumeration.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/Enumeration.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Enumeration.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Enumeration.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Commutativity.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/NeutralElements.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Idempotency.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/NullElements.mac")$


/* *********************
   * Basic enumeration *
   *********************
*/

okltest_all_grd2m(all_grd2m);
okltest_all_grd(all_grd);

/* ************
   * Counting *
   ************
*/

okltest_counting_groupoids([
 [number_grd, []], 
 [number_cgrd, [commutative_bydef_grd]],
 [number_ugrd, [has_neutral_el_grd]],
 [number_cugrd, [commutative_bydef_grd,has_neutral_el_grd]],
 [number_igrd, [idempotent_bydef_grd]],
 [number_iugrd, [idempotent_bydef_grd,has_neutral_el_grd]],
 [number_cigrd, [commutative_bydef_grd,idempotent_bydef_grd]],
 [number_ciugrd, [commutative_bydef_grd,idempotent_bydef_grd,has_neutral_el_grd]],
 [number_ngrd, [has_null_el_grd]],
 [number_cngrd, [commutative_bydef_grd,has_null_el_grd]],
 [number_ingrd, [idempotent_bydef_grd,has_null_el_grd]],
 [number_nugrd, [has_null_el_grd,has_neutral_el_grd]],
 [number_cingrd, [commutative_bydef_grd,idempotent_bydef_grd,has_null_el_grd]],
 [number_cnugrd, [commutative_bydef_grd,has_null_el_grd,has_neutral_el_grd]],
 [number_inugrd, [idempotent_bydef_grd,has_null_el_grd,has_neutral_el_grd]],
 [number_cinugrd, [commutative_bydef_grd,idempotent_bydef_grd,has_null_el_grd,has_neutral_el_grd]]
]);

/* ***********************************
   * Enumerating isomorphism classes *
   ***********************************
*/

okltest_all_isomorphism_classes_grd(all_isomorphism_classes_bydef_grd);
okltest_all_isomorphism_classes_grd(all_isomorphism_classes_actively_grd);

okltest_all_isomorphism_classes_actively_sm_grd(all_isomorphism_classes_actively_sm_grd);

/* *********************************
   * Enumerating isotopism classes *
   *********************************
*/

okltest_all_isotopism_classes_grd(all_isotopism_classes_actively_grd);

okltest_all_isotopismisomorphism_classes_grd(all_isotopismisomorphism_classes_actively_grd);

/*!
\endhtmlonly
*/
