/* Oliver Kullmann, 14.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/Enumeration.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/Enumeration.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Enumeration.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Enumeration.mac")$

/* ***********************************
   * Enumerating isomorphism classes *
   ***********************************
*/

okltest_all_isomorphisms_classes_grd(all_isomorphisms_classes_bydef_grd);
okltest_all_isomorphisms_classes_grd(all_isomorphisms_classes_actively_grd);

okltest_all_isomorphisms_classes_actively_sm_grd(all_isomorphisms_classes_actively_sm_grd);

/* *********************************
   * Enumerating isotopism classes *
   *********************************
*/

okltest_all_isotopism_classes_grd(all_isotopism_classes_actively_grd);

okltest_all_isotopismisomorphism_classes_grd(all_isotopismisomorphism_classes_actively_grd);

/*!
\endhtmlonly
*/
