/* Oliver Kullmann, 12.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/Homomorphisms.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/Homomorphisms.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Homomorphisms.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/Homomorphisms.mac")$

/* ***********************
   * Fundamental notions *
   ***********************
*/

okltest_homomorphism_bydef_grd(homomorphism_bydef_grd);
okltest_homomorphism_bydef_ugrd(homomorphism_bydef_ugrd);

okltest_induced_congruence_grd(induced_congruence_grd);

/* ***********************
   * Isomorphism testing *
   ***********************
*/

okltest_is_isomorphic_bydef_grd(is_isomorphic_bydef_grd);

okltest_transport_grd(transport_grd);
okltest_transport3_grd(transport3_grd);

/* *************************
   * Enumerating groupoids *
   *************************
*/

okltest_all_isomorphisms_classes_grd(all_isomorphisms_classes_bydef_grd);
okltest_all_isomorphisms_classes_grd(all_isomorphisms_classes_actively_grd);

okltest_all_isomorphisms_classes_actively_sm_grd(all_isomorphisms_classes_actively_sm_grd);

okltest_all_isotopism_classes_grd(all_isotopism_classes_actively_grd);

okltest_all_isotopismisomorphism_classes_grd(all_isotopismisomorphism_classes_actively_grd);

/*!
\endhtmlonly
*/
