/* Oliver Kullmann, 14.1.2009 (Swansea) */
/* Copyright 2009, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/InvertibleElements.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/InvertibleElements.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/InvertibleElements.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/InvertibleElements.mac")$

/* **********
   * Basics *
   **********
*/

okltest_leftinvertible_el_ugrd(leftinvertible_el_ugrd);
okltest_rightinvertible_el_ugrd(rightinvertible_el_ugrd);
okltest_invertible_el_ugrd(invertible_el_ugrd);

okltest_leftinversion_ugrd(leftinversion_ugrd);
okltest_rightinversion_ugrd(rightinversion_ugrd);
okltest_inversion_ugrd(inversion_ugrd);

/* ***************
   * Involutions *
   ***************
*/

okltest_involutions_ugrd(involutions_ugrd);

/*!
\endhtmlonly
*/
