/* Oliver Kullmann, 4.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/NeutralElements.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/NeutralElements.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/NeutralElements.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/NeutralElements.mac")$

okltest_leftneutral_el_grd(leftneutral_el_grd);
okltest_rightneutral_el_grd(rightneutral_el_grd);
okltest_neutral_el_grd(neutral_el_grd);

okltest_has_leftneutral_el_grd(has_leftneutral_el_grd);
okltest_has_rightneutral_el_grd(has_rightneutral_el_grd);
okltest_has_neutral_el_grd(has_neutral_el_grd);

/*!
\endhtmlonly
*/
