/* Oliver Kullmann, 14.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/NullElements.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/testobjects/NullElements.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/NullElements.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/tests/NullElements.mac")$

okltest_leftnull_el_grd(leftnull_el_grd);
okltest_rightnull_el_grd(rightnull_el_grd);
okltest_null_el_grd(null_el_grd);

okltest_has_leftnull_el_grd(has_leftnull_el_grd);
okltest_has_rightnull_el_grd(has_rightnull_el_grd);
okltest_has_null_el_grd(has_null_el_grd);

/*!
\endhtmlonly
*/
