/* Oliver Kullmann, 11.7.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Operations/tests/BasicNotions.mac
  \brief Tests for monoids of partial assignments

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Operations/tests/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/BasicExamples.mac")$

kill(f)$

/* ***********************************
   * Testing the defining properties *
   ***********************************
*/

okltest_opr_grdset_p(f) := block([op],
  assert(f(op,[{},op],{}) = true),
  assert(f(op,[{1},op],{}) = true),
  assert(f(op,[{},op],{1}) = true),
  assert(f(lambda([g,x],1), [{1},lambda([x,y],1)], {1}) = true),
  assert(f(lambda([x,y],2), singleton_mon, {1,2}) = true),
  /* XXX */
  true)$

okltest_opr_ugrdset_p(f) := (
  assert(f(singleton_mon[2], singleton_mon, singleton_mon[1]) = true),
  assert(f(lambda([x,y],2), singleton_mon, {1,2}) = false),
  /* XXX */
  true)$


/*!
\endhtmlonly
*/
