/* Oliver Kullmann, 5.1.2008 (Swansea) */
/* Copyright 2008, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/DataStructures/Lisp/include.mac
  \brief Inclusion file for Maxima data-structure functions

Use by

oklib_load("OKlib/ComputerAlgebra/DataStructures/Lisp/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/HashMaps.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lambda.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Strings.mac")$

oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/tests/HashMaps.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/tests/Lists.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/tests/Strings.mac")$

/*!
\endhtmlonly
*/
