/* Oliver Kullmann, 30.10.2011 (Swansea) */
/* Copyright 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/DataStructures/Lisp/Strings.mac
  \brief Functions for string handling and printing

Use by

oklib_load("OKlib/ComputerAlgebra/DataStructures/Lisp/Strings.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$

/* Print a string on one line, with exactly one line-break: */
print_nlb(s) := printf(true,"~a~a",s,newline)$


/* Concatening the string-arguments, separating them with new-lines: */
sconcatnl([L]) := uaapply(sconcat, lappend(map(lambda([x],[x,newline]),L)))$
/* Separating them with spaces: */
sconcats([L]) := uaapply(sconcat, lappend(map(lambda([x],[x,space]),L)))$


/* Evaluate term t, and concatenate all print-output into one string: */
print2string('t) := block([S : make_string_output_stream()],
 with_stdout(S,ev(t)),
 get_output_stream_string(S))$


/* String with standard creation-statement: */
created_by_OKlib() := sconcat("Produced by OKlibrary (", oklibrary_domain, ", ID=", git_id_oklib, ") at ", timedate(), ".")$


/*!
\endhtmlonly
*/
