/* Oliver Kullmann, 25.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Categories/Lisp/BasicNotions.mac
  \brief Basic notions (like test-predicates and conversions) for categories

Use by

oklib_load("Transitional/ComputerAlgebra/Categories/Lisp/BasicNotions.mac");

*/

/*!
\htmlonly
*/

/* ***********************
   * Fundamental notions *
   ***********************
*/



/*!
\endhtmlonly
*/

