/* Oliver Kullmann, 10.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/testobjects/PartialAssignments.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/testobjects/PartialAssignments.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/PartialAssignments.mac")$
oklib_include("Transitional/ComputerAlgebra/Algebra/Lisp/Groupoids/Semigroups/tests/PartialAssignments.mac")$

/* *******************************
   * Boolean partial assignments *
   *******************************
*/

okltest_pass_mon(pass_mon);
okltest_pass_sgr(pass_sgr);

okltest_natop_pass(natop_pass);

/*!
\endhtmlonly
*/
