/* Oliver Kullmann, 24.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Conflicts.mac
  \brief Functions related tot the conflict-combinatorics of clause-sets

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Conflicts.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac");
oklib_include("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/Basics.mac");
oklib_include("Transitional/ComputerAlgebra/LinearAlgebra/Lisp/QuadraticForms.mac");

/* The clause-variable matrix of a formal clause-set (as a combinatorial
   matrix) */
cvcom(FF) := [FF[2], FF[1], lambda([C,v],
 block([i : intersection(C, {v,-v})],
  if emptyp(i) then return(0)
  elseif i = {v} then return(+1)
  else return(-1)))]$

/* The conflict-matrix (as a square combinatorial matrix) of a clause-set */
cm_cs(F) := [F, lambda([C,D], length(intersection(C,comp_sl(D))))]$

/* The hermitean rank of a boolean clause-set F */
hermitean_rank_cs(F) := hermitean_rank(scom2m(cm_cs(F)))$

/* The hermitean defect of a boolean clause-set F */
hermitean_defect_cs(F) := ncl_cs(F) - hermitean_rank_cs(F)$

/*!
\endhtmlonly
*/
