/* Oliver Kullmann, 31.12.2007 (Swansea) */
/* Copyright 2007 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Hypergraphs.mac
  \brief Functions related to the various transformation to graphs and hypergraphs

Use by

load("$OKPLATFORM/OKsystem/Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Hypergraphs.mac");

where $OKPLATFORM has to be replaced by the path to the OKplatform directory.

Needs 

 - ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac
 - ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac.

*/

/*!
\htmlonly
*/

/* the clause-variable graph of a formal clause-set */
cl_var_graph(FF) := [union(FF[1], FF[2]),
  family_sets_union(FF[2], lambda([C], setify(makelist({C,var_l(x)},x,listify(C)))))]$

/* the deficiency of a formal clause-set */
deficiency_fcs(FF) := length(FF[2]) - length(FF[1])$

/* the maximal deficiency of a formal clause-set */
max_deficiency_fcs(FF) := length(FF[2]) - length(max_matching(g2mg(cl_var_graph(FF))))$

/*!
\endhtmlonly
*/
