/* Oliver Kullmann, 12.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ConflictCombinatorics/testobjects/Conflicts.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/ConflictCombinatorics/testobjects/Conflicts.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ConflictCombinatorics/Conflicts.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ConflictCombinatorics/tests/Conflicts.mac")$
oklib_include("OKlib/ComputerAlgebra/LinearAlgebra/Lisp/QuadraticForms.mac")$

okltest_cm_cs(cm_cs);
okltest_cg_cs(cg_cs);

okltest_nconflicts(nconflicts);
okltest_rnconflicts(rnconflicts);

okltest_hermitian_rank_cs(hermitian_rank_cs);
okltest_hermitian_rank_cs_h(hermitian_rank_cs_h);

okltest_charpoly_cs(charpoly_cs);

okltest_partition_number_cs(partition_number_m_cs);

okltest_graphiccsp(graphiccsp);

okltest_alon_saks_cs(alon_saks_cs);

/*!
\endhtmlonly
*/
