/* Oliver Kullmann, 12.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ConflictCombinatorics/testobjects/HittingClauseSets.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ConflictCombinatorics/testobjects/HittingClauseSets.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ConflictCombinatorics/HittingClauseSets.mac");
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ConflictCombinatorics/tests/HittingClauseSets.mac");

okltest_hitting_cls_rep_st(hitting_cls_rep_st);

okltest_sasg2000(sasg2000);
okltest_brouwer1999(brouwer1999);

okltest_sat_decision_hitting_cs(sat_decision_hitting_cs);

okltest_hittingcsp(hittingcsp);
okltest_treehittingcsp(treehittingcsp);

/* ****************************************************
   * Representing clause-sets via hitting clause-sets *
   ****************************************************
*/

okltest_hitting_decomposition_m_cs(hitting_decomposition_m_cs);


/*!
\endhtmlonly
*/
