/* Matthew Gwynne, 17.1.2011 (Swansea) */
/* Copyright 2011, 2018 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/Basics.mac
  \brief Basic tools for handling boolean and finite functions

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/FiniteFunctions/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$
oklib_include("OKlib/ComputerAlgebra/NumberTheory/Lisp/Auxiliary.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/HashMaps.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/Generators.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$


/* *******************
   * Boolean vectors *
   *******************
*/

/*
  A "boolean value" is either 0 or 1.
*/

boolval_p(v) := v=0 or v=1$

/* Translating Maxima-truth-values into boolean values: */
tv2boolval(t) := if t then 1 else 0$

/*
  A "boolean vector" ("bv") of length k (k in NN_0) is a list v of length k
  with entries 0, 1.
*/

bv_p(v) := listp(v) and every_s(boolval_p,v)$

/* The set of all boolean vectors of length k: */
all_bv(k) := apply(cartesian_product, create_list({0,1},i,1,k))$

/* The 2^k boolean vectors of length k in lexicographical order: */
lex_bv_l(k) := cartesian_product_l(create_list([0,1],i,1,k))$
/* Unranking for 1 <= i <= 2^k: */
unrank_lex_bv(i,k) := if k=0 then [] else int2polyadic_padd(i-1,2,k)$
/* Ranking of boolean vectors: */
rank_lex_bv(x) := polyadic2int(x,2) + 1$


/* Translating boolean vectors into (standardised) DNF-clauses (using the
   positions as variables):
*/
bv2c(v) := bv2c_wv(v,create_list(i,i,1,length(v)))$
/* More generally, supplying a vector V of boolean variables (of the same
   length as v):
*/
bv2c_wv(v,V) := setify((2*v - 1) * V)$

/* Translating boolean vectors into hyperedges consisting of the indices
   of the position where the vector is true:
*/
bv2he(v) := setify(sublist_indices(v,lambda([x],x=1)))$


/* *********************
   * Boolean functions *
   *********************
*/

/*

  The basic idea is that a "boolean function" is just some function f,
  which can be applied to boolean vectors b, and such that f(b) is
  a boolean vector.

  A "boolean function" ("bf") is a function with the following properties:

   - implicitly a size-domain S <= NN_0 is given
   - for every n in S there is an m_n in NN_0 such that for all boolean vectors
     x of length n the term f(x) is a boolean vector of length m_n.

  f is an "n x m bf" if n in S and m_n = m.
*/

/* Testing whether f is a n x m boolean function: */
bf_nm_p(f,n,m) :=
 every_s(lambda([x], 
           block([y:f(x)], listp(y) and is(length(y)=m) and bv_p(y))),
         all_bv(n))$


/* ********************************
   * Some basic boolean functions *
   ********************************
*/

/* Functions with size-domain NN_0 and m=1: */

zero_bf : lambda([x], [0])$
one_bf : lambda([x], [1])$

and_bf : lambda([x], [lmin(x)])$
or_bf : lambda([x], [lmax(x)])$

xor_bf : lambda([x], [mod(apply("+", x),2)])$

/* Functions with size-domain NN_0 and m=n: */

id_bf : identity$
neg_bf : lambda([x], 1-x)$

/* Integer representations: */

and_ibo(x,y):=?boole(?boole\-and,x,y)$
or_ibo(x,y):=?boole(?boole\-ior,x,y)$
xor_ibo(x,y):=?boole(?boole\-xor,x,y)$
/* These functions are also in the Maxima-package "functs" (however with
   defective definitions), with names "logand, logor, logxor".
   "ibo" for "integer boolean operation".
*/


/* ***************
   * Conversions *
   ***************
*/

/* The "bit-vector presentation" of an n x 1 boolean function f is the boolean
   vector of length 2^n containing all values of f, applied to the 
   lexicographical ordering of inputs:
*/
bf2bv(f_, n) := map(lambda([x], first(f_(x))), lex_bv_l(n))$
bv2bf(fv) := buildq([a : il2ary(fv)], lambda([x], [a[rank_lex_bv(x)]]))$

/* Boolean functions as full DNF resp. DNF (the clause-order follows the
   lexicographical order of the boolean vectors):
*/
bf2fulldnf_fcl(f,n) := [create_list(i,i,1,n), map(bv2c, sublist(lex_bv_l(n), lambda([x],is(f(x)=[1]))))]$
bf2fullcnf_fcl(f,n) := [create_list(i,i,1,n), map(bv2c, 1 - sublist(lex_bv_l(n), lambda([x],is(f(x)=[0]))))]$
/* Converting a boolean function as full DNF into into a boolean function: */
fulldnf2bf_cs(F) := buildq([F], lambda([x], tv2boolval(elementp(bv2c(x),F))))$


/* The "DNF hypergraph representation" of an n x 1 boolean function f
   is obtained from its full DNF by taking the variable as vertices and
   converting the clauses into hyperedges by removing the negative literals.
*/
/* Converting a boolean function given as a full DNF into its DNF hypergraph
   representation:
*/
fulldnf2dnfhg_ofcs2ohg(FF) :=
 [ FF[1], map(lambda([C],subset(C,lambda([x],is(x>0)))), FF[2]) ]$
/* Translating a boolean function as set-system into a boolean function: */
dnfhg2bf_ses(S) := buildq([S], lambda([x], tv2boolval(elementp(bv2he(x), S))))$


/* *****************
   * Constructions *
   *****************
*/

/* The component-wise negation of a boolean function: */
negation_bf(f) := buildq([f], lambda([x],1-f(x)))$

/* The composition of boolean functions (first f, then g): */
composition_bf(g,f) := buildq([f,g], lambda([x], g(f(x))))$
square_bf(f) := composition_bf(f,f)$

/* A boolean n x m function f as a boolean (n+m) x 1 function: */
bf2relation_bf(f,n) := buildq([f,n], lambda([x], tv2boolval(is(f(take_l(n,x))=rest(x,n)))))$
bf2relation_fulldnf_cl(f,n) :=
 map(bv2c, map(lambda([x],append(x,f(x))), lex_bv_l(n)))$
bf2relation_fullcnf_fcs(f,n) := block(
 [F : map(comp_sl,bf2relation_fulldnf_cl(f,n))],
  if emptyp(F) then [{},{{}}]
  else block([N : length(first(F))],
    [setn(N), setdifference(full_cs(N), setify(F))]))$

/* The boolean n x 1 function giving the i-th output bit of the boolean n x m
   function f: */
bfnm2n1(f,i) := buildq([f,n,i], lambda([x], [f(x)[i]]))$

/*!
\endhtmlonly
*/
