/* Oliver Kullmann, 26.5.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Hypergraphs/Lisp/Transversals/include.mac
  \brief Inclusion file for hypergraph transversal functions

Use by

oklib_load("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/Bounded/include.mac");
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/Minimal/include.mac");

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/Basics.mac")$

oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/Transversals/tests/Basics.mac")$


/*!
\endhtmlonly
*/
