/* Matthew Gwynne, 28.4.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software$ you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library$ either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/data/FieldMul2CNF.mac
  \brief Example CNF for the Rijndael byte field multiplication by 02 or "x".

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/data/FieldMul2CNF.mac")$

*/

/*!
\htmlonly
*/

FieldMul2CNF : [{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16},{{-8,15,16},{-7,14},{-6,13,16},{-5,12,16},{-4,11},{-3,10},{-2,9},{-1,5,12},{-1,6,13},{-1,8,15},{-16,1},{-16,-15,-8},{-15,8,16},{-14,7},{-13,-6,-1},{-13,6,16},{-12,-5,-1},{-12,5,16},{-11,4},{-10,3},{-9,2}}]$

/*!
\endhtmlonly
*/
