/* Matthew Gwynne, 16.12.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software$ you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library$ either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/data/SmallScaleSboxCNF.mac
  \brief Example CNF for the Rijndael byte field multiplication by 02 or "x".

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/data/SmallScaleSboxCNF.mac")$

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/SboxAnalysis.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/data/SboxCNF.mac")$



/* Takes the exponent and the element in the field to multiply with */
ss_sbox_cnfs : sm2hm({})$

set_hm(ss_sbox_cnfs, 4, fcs2fcl(ss_sbox_fullcnf_fcs(2,4,ss_polynomial_2_4)))$
set_hm(ss_sbox_cnfs, 8, Sbox44ICCNF)$
/* Need 4 also. */

/*!
\endhtmlonly
*/
