#!/bin/bash
# Oliver Kullmann, 23.8.2011 (Swansea)
# Copyright 2011 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute 
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the 
# License, or any later version.

set -o errexit
set -o nounset

script_name="ProcessSplitViaOKsolver"
version_number=0.0.3

timestamp=$(date +"%Y-%m-%d-%H%M%S")

if [[ $# -ne 1 ]]; then
  echo "ERROR[${script_name}]: Exactly one parameter is needed, the directory to be processed."
  exit 1
fi

directory=$1

directory=ProcessSplitViaOKsolver_${directory}_${timestamp}

exit 0
