/* Oliver Kullmann, 8.6.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Backtracking/tests/Learning.mac
  \brief Tests for (pure) learning algorithms

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Backtracking/tests/Learning.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Backtracking/tests/DLL_solvers.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Backtracking/DLL_solvers.mac")$

kill(f)$


okltest_basic_learning(f) := block(
  okltest_SATsolver(f(generalised_ucp1,dll_heuristics_first_formal)),
  if oklib_test_level = 0 then return(true),
  okltest_SATsolver(f(generalised_ucp2,johnson_heuristic)),
  true)$


/*!
\endhtmlonly
*/
