/* Oliver Kullmann, 27.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/Ramsey/Hypergraphs.mac
  \brief Basic functions for investigating Ramsey hypergraphs

Use by

oklib_load("Transitional/ComputerAlgebra/RamseyTheory/Lisp/Ramsey/Hypergraphs.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Hypergraphs/Lisp/Generators.mac")$

/* Ramsey hypergraphs are computed by ramsey_(o)hg(q,r,n) (from
   Hypergraphs/Lisp/Generators.mac).
*/

/* S_n acts by automorphisms on the vertex set of ramsey_hg(q,r,n): */


/*!
\endhtmlonly
*/
