/* Matthew Gwynne, 25.11.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/Ramsey/include.mac
  \brief Inclusion file for Maxima Ramsey functions

Use by

oklib_load("Transitional/ComputerAlgebra/RamseyTheory/Lisp/Ramsey/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/RamseyTheory/Lisp/Ramsey/Numbers.mac")$

oklib_include("Transitional/ComputerAlgebra/RamseyTheory/Lisp/Ramsey/tests/Numbers.mac")$

/*!
\endhtmlonly
*/
