/* Oliver Kullmann, 24.12.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/testobjects/ByteField.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/testobjects/ByteField.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/ByteField.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/tests/ByteField.mac")$

okltest_rijn_polynomial(rijn_polynomial);

okltest_rijn_stand(rijn_stand);

okltest_nat2polybin(nat2polybin);
okltest_polybin2nat(polybin2nat);

okltest_rijn_add(rijn_add);
okltest_rijn_mul(rijn_mul);
okltest_rijn_matmul(rijn_matmul);
okltest_rijn_inv(rijn_inv);

okltest_rijn_natadd(rijn_natadd);
okltest_rijn_natadd(rijn_nataddl);
okltest_rijn_natmul(rijn_natmul);
okltest_rijn_natinv(rijn_natinv);

/*!
\endhtmlonly
*/
