/* Matthew Gwynne, 28.1.2010 (Swansea) */
/* Copyright 2010, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/testobjects/SmallScaleAdvancedEncryptionStandard.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/testobjects/SmallScaleAdvancedEncryptionStandard.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/SmallScaleAdvancedEncryptionStandard.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/tests/SmallScaleAdvancedEncryptionStandard.mac")$


/* **************************************
   * Special bit-linear byte operations *
   **************************************
*/

okltest_ss_sbox_linmap_gen(ss_sbox_linmap_gen);
okltest_ss_mul_w_sbox_linmap_gen(ss_mul_w_sbox_linmap_gen);

/* *********
   * S box *
   *********
*/

okltest_ss_sbox_gen(ss_sbox_gen);
okltest_ss_inv_sbox_gen(ss_inv_sbox_gen);

okltest_ss_sbox_bf(ss_sbox_bf);
okltest_ss_sbox_w_add_bf(ss_sbox_w_add_bf);

/* *************
   * Sub-bytes *
   *************
*/

okltest_ss_subbytes(ss_subbytes);
okltest_ss_inv_subbytes(ss_inv_subbytes);

/* **************
   * Shift rows *
   **************
*/

okltest_ss_shiftrows(ss_shiftrows);
okltest_ss_inv_shiftrows(ss_inv_shiftrows);


/* ***************
   * Mix columns *
   ***************
*/

okltest_ss_mixcolumn_gen(ss_mixcolumn_gen);
okltest_ss_mixcolumn_gen_bf(ss_mixcolumn_gen_bf);
okltest_ss_inv_mixcolumn_gen(ss_inv_mixcolumn_gen);


okltest_ss_mixcolumns_gen(ss_mixcolumns_gen);
okltest_ss_inv_mixcolumns_gen(ss_inv_mixcolumns_gen);


/* *****************
   * Key expansion *
   *****************
*/

okltest_ss_key_expansion_gen(ss_key_expansion_gen); 

/* *********************************
   * AES encryption and decryption *
   *********************************
*/

okltest_ss_round_gen(ss_round_gen);
okltest_ss_inv_round_gen(ss_inv_round_gen);
okltest_ss_encrypt_wf_gen(ss_encrypt_wf_gen);
okltest_ss_decrypt_wf_gen(ss_decrypt_wf_gen);
okltest_ss_encrypt_gen(ss_encrypt_gen);
okltest_ss_decrypt_gen(ss_decrypt_gen);

/* **********************************************************
   * Small scale AES encryption as an iterated block cipher *
   **********************************************************
*/

okltest_ss_encrypt_gen(ss_encrypt_ibc_gen);

/* **********************************************************
   * Small scale AES instantiations                         *
   **********************************************************
*/

okltest_ss_encrypt(ss_encrypt);
okltest_ss_encrypt(ss_encrypt_ibc);
okltest_ss_encrypt_wf(ss_encrypt_wf);
okltest_ss_decrypt(ss_decrypt);
okltest_ss_decrypt_wf(ss_decrypt_wf);

/*!
\endhtmlonly
*/
