/* Oliver Kullmann, 3.4.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Counting/testobjects/Backtracking.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Counting/testobjects/Backtracking.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Counting/Backtracking.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Counting/tests/InclusionExclusion.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$

okltest_satprob(lambda([F],satprob_dll_simplest_trivial1(cs_to_fcs(F))));

/*!
\endhtmlonly
*/
