/* Oliver Kullmann, 17.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Counting/testobjects/RandomClauseSets.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Counting/testobjects/RandomClauseSets.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Counting/RandomClauseSets.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Counting/tests/RandomClauseSets.mac")$

okltest_probsatrand(probsatrand);

/*!
\endhtmlonly
*/
