/* Oliver Kullmann, 23.4.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/testobjects/Sequences.mac

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/testobjects/Sequences.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Sequences.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/tests/Sequences.mac")$

/* ****************
   * Transformers *
   ****************
*/

okltest_transform_threshold_l(transform_threshold_l);
okltest_transform_steps_l(transform_steps_l);
okltest_alphastep2tau(alphastep2tau);
okltest_tau2alphastep(tau2alphastep);

/* ************
   * Analysis *
   ************
*/


/*!
\endhtmlonly
*/
