/* Oliver Kullmann, 24.12.2009 (Swansea) */
/* Copyright 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/tests/ByteField.mac
  \brief Tests for Advanced Encryption Standard

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/tests/ByteField.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/ByteField.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/FiniteFields.mac")$

kill(f)$

/* ******************
   * Representation *
   ******************
*/

okltest_rijn_polynomial(f) := block([x, GF_IRREDUCIBILITY_CHECK : true],
  assert(hipow(f,x) = 8),
  assert(gf_set(2,8,f) = true),
  for i : 0 thru 7 do
    assert(elementp(coeff(f,x,i),{0,1}) = true),
  true)$

okltest_rijn_stand(f) := block([x],
  assert(f(0) = 0),
  assert(f(1) = 1),
  assert(f(x^8) = x^4+x^3+x+1),
  assert(f(x^8 + x^4 + x^3 + x + 1) = 0),
  true)$

okltest_nat2polybin(f) := block([x],
  assert(f(0) = 0),
  assert(f(1) = 1),
  assert(f(2) = x),
  assert(f(3) = x+1),
  assert(f(4) = x^2),
  for e : 0 thru 5 do
    assert(f(2^e) = x^e),
  true)$

okltest_polybin2nat(f) := block([x],
  assert(f(0) = 0),
  assert(f(1) = 1),
  assert(f(x) = 2),
  assert(f(x+1) = 3),
  assert(f(x^2) = 4),
  for e : 0 thru 5 do
    assert(f(x^e) = 2^e),
  true)$

okltest_rijn_stand_vec(f) := (

  true)$

okltest_nat2vecbin(f) := (

  true)$

okltest_nat2vecbin_rijn(f) := (

  true)$

okltest_vecbin2nat(f) := (

  true)$

okltest_polybin2vecbin(f) := (

  true)$

okltest_polybin2vecbin_rijn(f) := (

  true)$

okltest_vecbin2polybin(f) := (

  true)$


/* **************
   * Operations *
   **************
*/

okltest_rijn_add(f) := block([x],
  assert(f(0,0) = 0),
  assert(f(x,x) = 0),
  assert(f(x,x^4+x^2+x+3) = x^4+x^2+1),
  true)$

okltest_rijn_mul(f) := block([x],
  assert(f(0,0) = 0),
  assert(f(0,x^2) = 0),
  assert(f(1,x^3+x^2+3) = x^3+x^2+1),
  assert(f(x^4,x^4) = x^4+x^3+x+1),
  assert(f(rijn_polynomial-1,rijn_polynomial-1) = 1),
  true)$

okltest_rijn_matmul(f) := block([x],
  assert(f(matrix(),matrix()) = matrix()),
  assert(f(matrix([0]),matrix([0])) = matrix([0])),
  assert(f(matrix([x,0],[0,x]),matrix([x,0],[0,x])) = matrix([x^2,0],[0,x^2])),
  assert(f(matrix([x,1],[x,x^2]),matrix([1,x^3],[x,0])) = matrix([0,x^4],[x^3+x,x^4])),
  assert(f(matrix([x^4,0],[0,x^4]),matrix([x^4,0],[0,x^4])) = matrix([x^4+x^3+x+1,0],[0,x^4+x^3+x+1])),
  true)$

okltest_rijn_inv(f) := block([x],
  assert(f(1) = 1),
  assert(f(x) = x^7+x^3+x^2+1),
  true)$

okltest_rijn_natadd(f) := (
  assert(f(0,0) = 0),
  assert(okltest_rijn_add(buildq([f], lambda([a,b], nat2polybin(f(polybin2nat(rijn_stand(a)),polybin2nat(rijn_stand(b))))))) = true),
  true)$

okltest_rijn_natmul(f) := (
  assert(f(0,0) = 0),
  assert(f(0,1) = 0),
  assert(f(1,1) = 1),
  assert(f(2,141) = 1),
  true)$

okltest_rijn_natinv(f) := (
  assert(f(1) = 1),
  assert(f(2) = 141),
  assert(f(polybin2nat(rijn_stand(-1))) = polybin2nat(rijn_stand(-1))),
  true)$

okltest_rijn_vecadd(f) := (

  true)$

okltest_rijn_vecmul(f) := (

  true)$

okltest_rijn_vecinv(f) := (
  assert(f([1]) = [0,0,0,0,0,0,0,1]),
  /* XXX */
  true)$


/*!
\endhtmlonly
*/
