/* Matthew Gwynne, 22.5.2011 (Swansea) */
/* Copyright 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/testobjects/ConstraintTranslation.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/testobjects/GeneralisedConstraintTranslation.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/GeneralisedConstraintTranslation.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/tests/GeneralisedConstraintTranslation.mac")$


/* ***********************
   * The complete system *
   ***********************
*/

okltest_des_sbox_output2inputs(des_sbox_output2inputs);
okltest_des_sbox_outputs2inputs(des_sbox_outputs2inputs);

okltest_des_plain2fcl_gen(des_plain2fcl_gen);
okltest_des_cipher2fcl_gen(des_cipher2fcl_gen);
okltest_des_key2fcl_gen(des_key2fcl_gen);

/*!
\endhtmlonly
*/
