/* Matthew Gwynne, 22.5.2011 (Swansea) */
/* Copyright 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/testobjects/ConstraintTranslation.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/testobjects/GeneralisedConstraintTranslation.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/GeneralisedConstraintTranslation.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/tests/ConstraintTranslation.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/DataEncryptionStandard/tests/GeneralisedConstraintTranslation.mac")$


/* ***********************
   * The complete system *
   ***********************
*/

okltest_des_sbox_output2inputs(des_sbox_output2inputs);
okltest_des_sbox_outputs2inputs(des_sbox_outputs2inputs);


/* **************************************************************
   * Assignments to plaintext, key and ciphertext variables     *
   **************************************************************
*/

okltest_des_plain2pa(des_plain2pa_gen);
okltest_des_plain2fcl(des_plain2fcl_gen);
okltest_des_cipher2pa_gen(des_cipher2pa_gen);
okltest_des_cipher2fcl_gen(des_cipher2fcl_gen);
okltest_des_key2pa(des_key2pa_gen);
okltest_des_key2fcl(des_key2fcl_gen);

okltest_des_random_pkctriple(des_random_pkctriple);
okltest_des_random_pkctriple_pa(des_random_pkctriple_pa);
okltest_des_random_pkctriple_pa_std(des_random_pkctriple_pa_std);
okltest_des_random_pcpair_pa(des_random_pcpair_pa);
okltest_des_random_pcpair_pa_std(des_random_pcpair_pa_std);
okltest_des_random_pkpair_pa(des_random_pkpair_pa);
okltest_des_random_pkpair_pa_std(des_random_pkpair_pa_std);
okltest_des_random_kcpair_pa(des_random_kcpair_pa);
okltest_des_random_kcpair_pa_std(des_random_kcpair_pa_std);

/*!
\endhtmlonly
*/
