/* Oliver Kullmann, 4.5.2008 (Guangzhou) */
/* Copyright 2008, 2009, 2018 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/DataStructures/Lisp/testobjects/HashMaps.mac

Use by

oklib_load("OKlib/ComputerAlgebra/DataStructures/Lisp/testobjects/HashMaps.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/HashMaps.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/tests/HashMaps.mac")$

/* ************************
   * Set-theoretical maps *
   ************************
*/

okltest_sm_p(sm_p);
okltest_osm_p(osm_p);

okltest_define_set_map(define_set_map);

okltest_evaluate_set_map(evaluate_set_map);
okltest_evaluate_set_map_d(evaluate_set_map_d);

okltest_l2sm(l2sm);
okltest_ll2sm(ll2sm);
okltest_l2osm_inv(l2osm_inv);

okltest_allbij_sm(allbij_sm);
okltest_allperm_sm(allperm_sm);
okltest_allinj_sm(allinj_sm);

/* *********************************
   * Hash maps as provided by Lisp *
   *********************************
*/

okltest_eq_ohmsm_p(eq_ohmsm_p);
okltest_create_hash_map(create_hash_map);
okltest_create_set_map(create_set_map);

okltest_eq_hmsm_p(eq_hmsm_p);
okltest_set_hm(set_hm);
okltest_ev_hm(ev_hm);
okltest_ev_hm_d(ev_hm_d);
okltest_del_hm(del_hm);
okltest_sm2hm(sm2hm);
okltest_osm2hm(osm2hm);
okltest_hm2sm(hm2sm);
okltest_compose_hm_sm(compose_hm_sm);
okltest_lambda_hm(lambda_hm);

/* ***********************
   * Arrays as hash-maps *
   ***********************
*/

okltest_okl_make_array(okl_make_array);
okltest_okl_listarray(okl_listarray);
okltest_okl_fillarray_l(okl_fillarray_l);

okltest_l2array(l2array);
okltest_il2array(il2array);
okltest_fl2array(fl2array);

okltest_sm2array(sm2array);
okltest_array2osm(array2osm);
okltest_lambda_array(lambda_array);
okltest_extract_array(extract_array);
okltest_extract_arraylist(extract_arraylist);

/* *********************
   * Frequency counter *
   *********************
*/

okltest_list_distribution(list_distribution);
okltest_multi_list_distribution2list_distribution(multi_list_distribution2list_distribution);
okltest_num_distribution(num_distribution);

/*!
\endhtmlonly
*/
