/* Oliver Kullmann, 20.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/DataStructures/Lisp/testobjects/Lists.mac

Use by

oklib_load("Transitional/ComputerAlgebra/DataStructures/Lisp/testobjects/Lists.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$
oklib_include("Transitional/ComputerAlgebra/DataStructures/Lisp/tests/Lists.mac")$

okltest_take_elements(take_elements);
okltest_remove_element(remove_element);

okltest_partition_elements(partition_elements);

okltest_rotate(rotate);

okltest_sublist_indicator(sublist_indicator);

okltest_matrix2list(matrix2list);
okltest_matrixcolumns(matrixcolumns);
okltest_columns2matrix(columns2matrix);

/*!
\endhtmlonly
*/
