/* Oliver Kullmann, 20.2.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011, 2012, 2013 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/DataStructures/Lisp/testobjects/Lists.mac

Use by

oklib_load("OKlib/ComputerAlgebra/DataStructures/Lisp/testobjects/Lists.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/tests/Lists.mac")$

/* ***************
   * List access *
   ***************
*/

okltest_firste(firste);
okltest_seconde(seconde);
okltest_thirde(thirde);
okltest_fourthe(fourthe);

/* ***********************
   * Apply-functionality *
   ***********************
*/

okltest_uaapply(uaapply);

okltest_lappend(lappend);

/* *********************
   * Map-functionality *
   *********************
*/

okltest_map2(map2);

/* *******************************
   * Testing properties of lists *
   *******************************
*/

okltest_every_s(every_s);
okltest_everynary_s(everynary_s);
okltest_some_s(some_s);
okltest_somenary_s(somenary_s);

okltest_listnorep_p(listnorep_p);
okltest_lconstant_p(lconstant_p);

okltest_strictascending_p(strictascending_p);
okltest_strictdescending_p(strictdescending_p);
okltest_ascending_p(ascending_p);
okltest_descending_p(descending_p);

okltest_prefix_p(prefix_p);

/* *******************************************
   * Summations and products over lists/sets *
   *******************************************
*/

okltest_sum_l(sum_l);
okltest_sum_s(sum_s);
okltest_gsum_l(gsum_l);
okltest_gsum_s(gsum_s);
okltest_prod_l(prod_l);
okltest_prod_s(prod_s);
okltest_gprod_l(gprod_l);
okltest_gprod_s(gprod_s);

/* *************************************
   * Finding special elements in lists *
   *************************************
*/

okltest_first_smallest_l(first_smallest_l);
okltest_first_smallest_lb_l(first_smallest_lb_l);

okltest_first_smallest_f_l(first_smallest_f_l);
okltest_first_largest_f_l(first_largest_f_l);

okltest_smallest_f_l(smallest_f_l);
okltest_largest_f_l(largest_f_l);

okltest_find_first_l(find_first_l);
okltest_find_firste_l(find_firste_l);
okltest_find_last_l(find_last_l);
okltest_find_laste_l(find_laste_l);

okltest_elementp_l(elementp_l);

/* **************************
   * Sublist constructions *
   **************************
*/

okltest_take_elements(take_elements);

okltest_sublist_indices_el(sublist_indices_el);

okltest_remove_element(remove_element);
okltest_remove_elements(remove_elements);

okltest_sublist_indicator(sublist_indicator);

okltest_remove_consrep(remove_consrep);

/* *********************
   * List partitioning *
   *********************
*/

okltest_partition_elements(partition_elements);
okltest_partition_list(partition_list);
okltest_partition_list(partition_list_epo);
okltest_partition_list_eq(partition_list_eq);
okltest_split_list(split_list);
okltest_split_list_epo(split_list_epo);

/* **********************
   * List constructions *
   **********************
*/

okltest_rotate(rotate);

okltest_stable_unique(stable_unique);

okltest_interleave_l(interleave_l);

okltest_paddingfront_l(paddingfront_l);
okltest_paddingback_l(paddingback_l);

/* *************************
   * Random parts of lists *
   *************************
*/

/* ************************
   * Numerical operations *
   ************************
*/

okltest_count_l(count_l);
okltest_countgt_l(countgt_l);
okltest_countlt_l(countlt_l);
okltest_countpred_l(countpred_l);

okltest_countntconst_l(countntconst_l);

okltest_size_constintervals_l(size_constintervals_l);

okltest_Delta_l(Delta_l);

okltest_count_extremals_l(count_extremals_l);

okltest_m2l_r(m2l_r);
okltest_transpose_l(transpose_l);
okltest_matrixcolumns(matrixcolumns);
okltest_columns2matrix(columns2matrix);

/* ***********
   * Sorting *
   ***********
*/

okltest_sort_length(sort_length);
okltest_sort_length_desc(sort_length_desc);
okltest_sort_length_part(sort_length_part);
okltest_sort_length_desc_part(sort_length_desc_part);
okltest_l2order_p(l2order_p);


/*!
\endhtmlonly
*/
