/* Oliver Kullmann, 30.10.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/DataStructures/Lisp/testobjects/Strings.mac

Use by

oklib_load("OKlib/ComputerAlgebra/DataStructures/Lisp/testobjects/Strings.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/Strings.mac")$
oklib_include("OKlib/ComputerAlgebra/DataStructures/Lisp/tests/Strings.mac")$

okltest_print_nlb(print_nlb);

okltest_sconcatnl(sconcatnl);
okltest_sconcats(sconcats);

okltest_print2string(print2string);

/*!
\endhtmlonly
*/
