/* Oliver Kullmann, 19.9.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Algebra/Lisp/Groupoids/Actions/testobjects/BasicNotions.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Actions/testobjects/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Actions/BasicNotions.mac")$
oklib_include("OKlib/ComputerAlgebra/Algebra/Lisp/Groupoids/Actions/tests/BasicNotions.mac")$

/* *****************
   * Basic notions *
   *****************
*/

okltest_ecompo_p(ecompo_p);
okltest_recompo_p(recompo_p);

okltest_act_set_p(act_set_p);
okltest_ract_set_p(ract_set_p);

okltest_act_grd_p(act_grd_p);
okltest_ract_grd_p(ract_grd_p);

okltest_act_ugrd_p(act_ugrd_p);
okltest_ract_ugrd_p(ract_ugrd_p);

/* ***************
   * Conversions *
   ***************
*/

/* ********************
   * Basic operations *
   ********************
*/

/*!
\endhtmlonly
*/
