/* Oliver Kullmann, 30.4.2008 (Guangzhou) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Symmetries/testobjects/Symmetries.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Symmetries/testobjects/Symmetries.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Symmetries/Symmetries.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Symmetries/tests/Symmetries.mac")$

okltest_is_isomorphic_fcs(is_isomorphic_fcs);

okltest_representatives_fcs(representatives_fcs);

okltest_manage_repository_isomorphism_types(manage_repository_isomorphism_types);

/*!
\endhtmlonly
*/
