/* Oliver Kullmann, 30.4.2008 (Guangzhou) */
/* Copyright 2008, 2018 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Symmetries/testobjects/Symmetries.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Symmetries/testobjects/Symmetries.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Symmetries/Symmetries.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Symmetries/tests/Symmetries.mac")$

/* *****************
   * Automorphisms *
   *****************
*/

okltest_num_varauto_fcs(num_varauto_fcs);
okltest_num_flipauto_fcs(num_flipauto_fcs);
okltest_num_auto_fcs(num_auto_fcs);

/* ****************************************
   * Isomorphism testing via backtracking *
   ****************************************
*/

okltest_is_isomorphic_fcs(is_isomorphic_btr_fcs);

/* **********************************************
   * Isomorphism testing via graph isomorphisms *
   **********************************************
*/

okltest_is_isomorphic_fcs(is_isomorphic_fcs);

/* **********************************************
   * Isomorphism testing via matrix isomorphism *
   **********************************************
*/

okltest_is_varisomorphic_fcs_p(is_varisomorphic_com_fcs_p);

/* **********************************
   * Isomorphism classes management *
   **********************************
*/

okltest_representatives_fcs(representatives_fcs);

okltest_manage_repository_isomorphism_types(manage_repository_isomorphism_types);

/* *******************************
   * Analysing hash-repositories *
   *******************************
*/

okltest_analyse_isorepo_def(analyse_isorepo_def);
okltest_analyse_isorepo_set(analyse_isorepo_set);
okltest_analyse_isorepo_defset(okltest_analyse_isorepo_defset_reference_implementation);
okltest_analyse_isorepo_defset(analyse_isorepo_defset);

/*!
\endhtmlonly
*/
