/* Oliver Kullmann, 24.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/CombinatorialMatrices/Lisp/Basics.mac
  \brief Basic functionality for combinatorial matrices

Use by

oklib_load("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/Basics.mac");

*/

/*!
\htmlonly
*/

/* Converts a square combinatorial matrix into a combinatorial matrix */
scom2com(M) := [M[1],M[1],M[2]]$

/* Transforms a combinatorial matrix into a Maxima matrix */
com2m(M) := block([rows : listify(M[1]), cols : listify(M[2]), f : M[3]],
  apply(matrix, makelist(makelist(f(i,j),j,cols),i,rows)))$

/* Transforms a square combinatorial matrix into a Maxima matrix */
scom2m(M) := com2m(scom2com(M))$


/*!
\endhtmlonly
*/
