/* Oliver Kullmann, 25.4.2008 (Guangzhou) */
/* Copyright 2008, 2009, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Reductions/DP-Reductions.mac
  \brief Special cases of applications of the DP-operator which yield reductions

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/DP-Reductions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Statistics.mac")$
oklib_include("OKlib/ComputerAlgebra/Hypergraphs/Lisp/SetSystems.mac")$


/* *************************
   * Singular DP-reduction *
   *************************
*/

/* Applying elimination of singular literals as long as possible: */
sdp_reduction_cs(F) := block([S : singular_variables_cs(F)],
  if emptyp(S) then return(F) else
  return(sdp_reduction_cs(dp_operator(F,choose_element(S)))))$

/* Predicate for testing whether clause-set F is reduced w.r.t.
   singular DP-reduction: */
nonsingular_csp(F) := emptyp(singular_variables_cs(F))$


/*!
\endhtmlonly
*/
