/* Oliver Kullmann, 15.7.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/Schur/testobjects/Certificates.mac

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Schur/testobjects/Certificates.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Schur/Certificates.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Schur/tests/Certificates.mac")$

/* *****************
   * Basic notions *
   *****************
*/

okltest_certificate_schur_p(certificate_schur_p);
okltest_certificate_pdschur_p(certificate_pdschur_p);

/* *******************
   * Transformations *
   *******************
*/

okltest_uncompresss_schurpalindromic_subsets(uncompresss_schurpalindromic_subsets);

/*!
\endhtmlonly
*/
