/* Oliver Kullmann, 6.8.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/Schur/testobjects/Homomorphisms.mac

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Schur/testobjects/Homomorphisms.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Schur/Homomorphisms.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/Schur/tests/Homomorphisms.mac")$

/* ***********************************
   * Relations to Ramsey-hypergraphs *
   ***********************************
*/

okltest_hom_ramsey_schur(hom_ramsey_schur);

/* *****************
   * Automorphisms *
   *****************
*/

okltest_auto_pdschur(auto_pdschur);
okltest_auto_pdwschur(auto_pdwschur);

/*!
\endhtmlonly
*/
