/* Matthew Gwynne, 7.12.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/testobjects/ConstraintTemplateGlobalPropagation.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/testobjects/ConstraintTemplateGlobalPropagation.mac");

*/


/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/ConstraintTemplateGlobalPropagation.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/ConstraintTemplateGlobalPropagation.mac")$

/********************************
 * Propagation functions            *
 ********************************
*/

okltest_prop_all_csttl(prop_all_csttl);


/****************************************
 * Standard functions                   *
 ****************************************
*/

okltest_prop_eq_vars_l(prop_eq_vars_l);
okltest_prop_eq_csttl(prop_eq_csttl);

okltest_prop_eq_lift_renaming_var(prop_eq_lift_renaming_var);
okltest_prop_eq_lift_renaming(prop_eq_lift_renaming);

/*!
\endhtmlonly
*/
