/* Matthew Gwynne, 28.9.2008 (Swansea) */
/* Copyright 2008, 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/testobjects/ConstraintTemplateRewriteSystem.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/testobjects/ConstraintTemplateRewriteSystem.mac");

*/


/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/ConstraintTemplateRewriteSystem.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/ConstraintTemplateRewriteSystem.mac")$


/* ********************************************
   * Rewrite system functions                 *
   ********************************************
*/

okltest_cstt_namespace_new(cstt_namespace_new);
okltest_cstt_namespace_replace(cstt_namespace_replace);

/****************************
 * Constraints              *
 ****************************
*/

okltest_cstt_new(cstt_new);
okltest_cstt_name(cstt_name);
okltest_cstt_vars_l(cstt_vars_l);
okltest_cstt_args_l(cstt_args_l);
okltest_cstt_namespace_f(cstt_namespace_f);
okltest_cstt_p(cstt_p);
okltest_cstt_named_p(cstt_named_p);

/********************************
 * Rewrite functions            *
 ********************************
*/

okltest_rewrite_all_csttl(rewrite_all_csttl);
okltest_rewrite_all_cstt_vars_l(rewrite_all_cstt_vars_l);


/*!
\endhtmlonly
*/
