/* Matthew Gwynne, 28.9.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/testobjects/ConstraintTemplateSmallScaleRewriteRules.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/testobjects/ConstraintTemplateSmallScaleRewriteRules.mac");

*/


/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/Translations.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/ConstraintTemplateSmallScaleRewriteRules.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/ConstraintTemplateSmallScaleRewriteRules.mac")$


/* ***********************************************
   * Constraint template rewrite translation     *
   ***********************************************
*/

oktest_generate_ss_constraint_vars(generate_ss_constraint_vars);


/* ***********************************************
   * Constraint template rewrite functions       *
   ***********************************************
*/

okltest_ss_ns_var_l(ss_ns_var_l);
okltest_ss_cstr_cstl(ss_cstr_cstl);

okltest_ss_round_ns_var_l(ss_round_ns_var_l);
okltest_ss_round_cstr_cstl(ss_round_cstr_cstl);

okltest_ss_round_core_box_ns_var_l(ss_round_core_box_ns_var_l);
okltest_ss_round_core_box_cstr_cstl(ss_round_core_box_cstr_cstl);

okltest_ss_final_round_ns_var_l(ss_final_round_ns_var_l);
okltest_ss_final_round_cstr_cstl(ss_final_round_cstr_cstl);

okltest_ss_subbytes_ns_var_l(ss_subbytes_ns_var_l);
okltest_ss_subbytes_cstr_cstl(ss_subbytes_cstr_cstl);

okltest_ss_shiftrows_ns_var_l(ss_shiftrows_ns_var_l);
okltest_ss_shiftrows_cstr_cstl(ss_shiftrows_cstr_cstl);

okltest_ss_mixcolumns_ns_var_l(ss_mixcolumns_ns_var_l);
okltest_ss_mixcolumns_cstr_cstl(ss_mixcolumns_cstr_cstl);


okltest_ss_bi_mixcolumn_ns_var_l(ss_bi_mixcolumn_ns_var_l);
okltest_ss_bi_mixcolumn_cstr_cstl(ss_bi_mixcolumn_cstr_cstl);
okltest_ss_mixcolumn_ns_var_l(ss_mixcolumn_ns_var_l);
okltest_ss_mixcolumn_cstr_cstl(ss_mixcolumn_cstr_cstl);
okltest_ss_mixcolumn_boolm_ns_var_l(ss_mixcolumn_boolm_ns_var_l);
okltest_ss_mixcolumn_boolm_cstr_cstl(ss_mixcolumn_boolm_cstr_cstl);
okltest_ss_inv_mixcolumn_ns_var_l(ss_inv_mixcolumn_ns_var_l);
okltest_ss_inv_mixcolumn_cstr_cstl(ss_inv_mixcolumn_cstr_cstl);

okltest_ss_key_expansion_ns_var_l(ss_key_expansion_ns_var_l);
okltest_ss_key_expansion_cstr_cstl(ss_key_expansion_cstr_cstl);


/* ****************************************
   * Translation functions                *
   ****************************************
*/

okltest_ss_mul_ts_gen(ss_mul_ts_gen);
okltest_ss_sbox_ts_gen(ss_sbox_ts_gen);
okltest_ss_sbox_w_mul_ts_gen(ss_sbox_w_mul_ts_gen);
okltest_ss_mixcolumn_ts_gen(ss_mixcolumn_ts_gen);
okltest_ss_round_column_ts_gen(ss_round_column_ts_gen);
/* okltest_ss_sbox_pi_cst_cl(ss_sbox_pi_cst_cl); TEST FAILURE */
okltest_ss_sbox_ts_var_l(ss_sbox_ts_var_l);
okltest_ss_sbox_ts_cst_cl(ss_sbox_ts_cst_cl);
okltest_ss_sbox_w_mul_ts_var_l(ss_sbox_w_mul_ts_var_l);
okltest_ss_sbox_w_mul_ts_cst_cl(ss_sbox_w_mul_ts_cst_cl);
okltest_ss_mul_pi_cst_cl(ss_mul_pi_cst_cl);
okltest_ss_mul_ts_var_l(ss_mul_ts_var_l);
okltest_ss_mul_ts_cst_cl(ss_mul_ts_cst_cl);
okltest_ss_mixcolumn_ts_var_l(ss_mixcolumn_ts_var_l);
okltest_ss_mixcolumn_ts_cst_cl(ss_mixcolumn_ts_cst_cl);
okltest_ss_round_column_ts_var_l(ss_round_column_ts_var_l);
okltest_ss_round_column_ts_cst_cl(ss_round_column_ts_cst_cl);

/*!
\endhtmlonly
*/
