/* Matthew Gwynne, 28.4.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/testobjects/FieldOperationsAnalysis.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/testobjects/FieldOperationsAnalysis.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/FieldOperationsAnalysis.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/FieldOperationsAnalysis.mac")$


/* ************************************************************
   * General small scale field analysis                       *
   ************************************************************
*/

okltest_ss_field_op_fulldnf_gen_fcl(ss_field_op_fulldnf_gen_fcl);
okltest_ss_field_op_fullcnf_gen_fcs(ss_field_op_fullcnf_gen_fcs);
okltest_ss_field_op_gen_cnfp(ss_field_op_gen_cnfp);

/* ******************************************
   * Field Multiplication Analysis          *
   ******************************************
*/

okltest_rijnmult_fulldnf_fcs(rijnmult_fulldnf_fcs);
okltest_rijnmult_fullcnf_fcs(rijnmult_fullcnf_fcs);
okltest_rijnmult_cnfp(rijnmult_cnfp);

/* *********************************************
   * Small Scale Field multiplication analysis *
   *********************************************
*/

okltest_ssmult_fulldnf_fcl(ssmult_fulldnf_fcl);
okltest_ssmult_fullcnf_fcs(ssmult_fullcnf_fcs);
okltest_ssmult_gen_cnfp(ssmult_gen_cnfp);

/* *********************************************
   * Small Scale Field inversion analysis *
   *********************************************
*/

okltest_ssinv_fulldnf_fcl(ssinv_fulldnf_fcl);
okltest_ssinv_fullcnf_fcs(ssinv_fullcnf_fcs);
okltest_ssinv_cnfp(ssinv_cnfp);


/* ******************************************
   * Representations by hitting clause-sets *
   ******************************************
*/

okltest_rijnmult2hittingcnf_fcs(rijnmult2hittingcnf_fcs);

/*!
\endhtmlonly
*/
