/* Matthew Gwynne, 19.8.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/testobjects/Translations.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/testobjects/Translations.mac");

*/


/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/Translations.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/tests/Translations.mac")$

/* ***************************************
   * Sets of Conditions                  *
   ***************************************
*/

okltest_aes_sbox_ts_gen(aes_sbox_ts_gen);
okltest_aes_mul_ts_gen(aes_mul_ts_gen);
okltest_nadd_ss_sm(nadd_ss_sm);
okltest_nadd_ss(nadd_ss);

/******************************************************************
 * Statistics                                                     *
 ******************************************************************
*/

okltest_nsbox_ss(nsbox_ss)$
okltest_nmul_ss_gen(nmul_ss_gen)$
okltest_nvar_ss(nvar_ss)$
okltest_ncl_ss(ncl_ss)$

/******************************************************************
 * Data translation                                               *
 ******************************************************************
*/

okltest_aes_hex2pa(aes_hex2pa);
okltest_ss_random_matrix(ss_random_matrix);
okltest_ss_matrix2pa(ss_matrix2pa);
okltest_ss_pa2matrix(ss_pa2matrix);

/*!
\endhtmlonly
*/
