/* Matthew Gwynne, 26.3.2011 (Swansea) */
/* Copyright 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/CryptoSystems/DataEncryptionStandard/testobjects/Sboxes.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/DataEncryptionStandard/testobjects/Sboxes.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/DataEncryptionStandard/Sboxes.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/DataEncryptionStandard/tests/Sboxes.mac")$

okltest_desmatrix2bf(desmatrix2bf);
okltest_des_sbox_bf(des_sbox_bf);
okltest_des_6t1_sbox_bf(des_6t1_sbox_bf);
okltest_des_comb_sbox_bf(des_comb_sbox_bf);


/*!
\endhtmlonly
*/
