/* Oliver Kullmann, 30.12.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/CombinatorialMatrices/Lisp/LatinSquares/testobjects/BasicNotions.mac

Use by

oklib_load("OKlib/ComputerAlgebra/CombinatorialMatrices/Lisp/LatinSquares/testobjects/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/CombinatorialMatrices/Lisp/LatinSquares/BasicNotions.mac")$
oklib_include("OKlib/ComputerAlgebra/CombinatorialMatrices/Lisp/LatinSquares/tests/BasicNotions.mac")$

/* *****************************
   * Notions of "latin squares *
   *****************************
*/

okltest_comlso_p(comlso_p);
okltest_comls_p(comls_p);
okltest_ls_p(ls_p);
okltest_hrls_p(hrls_p);
okltest_rls_p(rls_p);

/* *****************
   * Orthogonality *
   *****************
*/

okltest_ocomls_p(ocomls_p);
okltest_mocomls_p(mocomls_p);

/* ************
   * Examples *
   ************
*/

okltest_cyc3_rls(cyc3_rls);
okltest_cyc3_o_hrls(cyc3_o_hrls);
okltest_nassoc_rls(nassoc_rls);
okltest_dk10_rls(dk10_rls);
okltest_dk10_o_hrls(dk10_o_hrls);

/* ***************
   * Conversions *
   ***************
*/

okltest_qgrp2comls(qgrp2comls);
okltest_uqgrp2rls(uqgrp2rls);

/*!
\endhtmlonly
*/
