/* Oliver Kullmann, 30.12.2008 (Swansea) */
/* Copyright 2008, 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/CombinatorialMatrices/Lisp/LatinSquares/testobjects/BasicNotions.mac

Use by

oklib_load("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/LatinSquares/testobjects/BasicNotions.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/LatinSquares/BasicNotions.mac")$
oklib_include("Transitional/ComputerAlgebra/CombinatorialMatrices/Lisp/LatinSquares/tests/BasicNotions.mac")$

/* *****************
   * Basic notions *
   *****************
*/

okltest_lso_p(lso_p);
okltest_ls_p(ls_p);
okltest_stdls_p(stdls_p);
okltest_fstdls_p(fstdls_p);

okltest_ols_p(ols_p);
okltest_mols_p(mols_p);

/* ************
   * Examples *
   ************
*/

okltest_cyc3_fstdls(cyc3_fstdls);
okltest_cyc3_o_stdls(cyc3_o_stdls);
okltest_dk10_fstdls(dk10_fstdls);
okltest_dk10_o_stdls(dk10_o_stdls);

/*!
\endhtmlonly
*/
