/* Oliver Kullmann, 4.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

define_variable(OKplatform,"m4_SHELL(OKplatform)",any);
define_variable(OKsystem,"m4_SHELL(OKsystem)",any);

showtime : true;
linel : 100;

define_variable(oklib_monitor,false,boolean);
define_variable(oklib_monitor_level,0,any); /* may take value inf */

define_variable(oklib_test_level,0,any); /* may take value inf */
define_variable(oklib_test_demos,false,boolean);
define_variable(oklib_test_demos_level,0,any); /* may take value inf */

define_variable(oklib_load_round,0,fixnum);
oklib_loaded_files["maxima-init.mac"] : 0;

oklib_load(name) := block([full_name : sconcat(OKsystem,"/",name)],
 oklib_load_round : oklib_load_round+1,
 oklib_loaded_files[full_name] : oklib_load_round,
 load(full_name));

oklib_include(name) := block([full_name : sconcat(OKsystem,"/",name)],
 if oklib_loaded_files[full_name] # oklib_load_round then
  (oklib_loaded_files[full_name] : oklib_load_round, load(full_name))
);

oklib_load_all() := oklib_load("Transitional/ComputerAlgebra/include.mac");

oklib_batch(name) := block([full_name : sconcat(OKsystem,"/",name)],
 oklib_load_round : oklib_load_round+1,
 oklib_loaded_files[full_name] : oklib_load_round,
 batch(full_name));
oklib_demo(name) := block([full_name : sconcat(OKsystem,"/",name)],
 oklib_load_round : oklib_load_round+1,
 oklib_loaded_files[full_name] : oklib_load_round,
 demo(full_name));

define_variable(oklib_automatic_test,false,boolean);

