/* Oliver Kullmann, 18.7.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Numerical/Lisp/testobjects/LinearProgramming.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Numerical/Lisp/testobjects/LinearProgramming.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Numerical/Lisp/LinearProgramming.mac")$
oklib_include("Transitional/ComputerAlgebra/Numerical/Lisp/tests/LinearProgramming.mac")$

/* ********************************************
   * Auxiliary functions handling "equations" *
   ********************************************
*/

okltest_translate_vector_lincomb(translate_vector_lincomb);
okltest_translate_matrix_ineq(translate_matrix_ineq);

okltest_interprete_poscond(interprete_poscond);
okltest_interprete_negcond(interprete_negcond);
okltest_interprete_zerocond(interprete_zerocond);

/* ******************************************
   * Solving systems of linear inequalities *
   ******************************************
*/

okltest_solve_lineq(solve_lineq);

/*!
\endhtmlonly
*/
