/* Oliver Kullmann, 26.11.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Numerical/Lisp/testobjects/Norms.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Numerical/Lisp/testobjects/Norms.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Numerical/Lisp/Norms.mac")$
oklib_include("OKlib/ComputerAlgebra/Numerical/Lisp/tests/Norms.mac")$

okltest_norm_vec(norm_vec);
okltest_dist_vec(dist_vec);

/*!
\endhtmlonly
*/
