/* Matthew Gwynne, 5.4.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/tests/Conversions.mac
  \brief Tests for the Cryptology conversion functions.

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/tests/Conversions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

okltest_lpad(f) := block(
  for n : 0 thru 3 do
    assert(f("","",n) = ""),
  for n : -3 thru 4 do
    assert(f("test","c",n) = "test"),
  assert(f("","-",1) = "-"),
  assert(f("","-",2) = "--"),
  assert(f("abc","d",4) = "dabc"),
  true)$


okltest_int2poly(f) := block([x],
  for n : 1 thru 3 do
    assert(f(0,n) = 0),
  /*for n : -12 thru 12 do
    assert(f(n,abs(n)+1) = n),*/
  for n : 2 thru 10 do
    assert(f(n,n) = x),
  assert(f(275,2) = x^8+x^4+x+1),
  assert(f(423423,15) = 8*x^4+5*x^3+6*x^2+13*x+3),
  true)$

okltest_poly2int(f) := block([x],
  for n : 1 thru 3 do
    assert(f(0,n,x) = 0),
  for n : -12 thru 12 do
    assert(f(n,abs(n)+1,x) = n),
  for n : 2 thru 10 do
    assert(f(x,n,x) = n),
  assert(f(x^8+x^4+x+1,2,x) = 275),
  assert(f(a^8+a^4+a+1,2,a) = 275),
  assert(f(8*x^4+5*x^3+6*x^2+13*x+3,15,x) = 423423),
  true)$

okltest_binl2dnf_l_std(f) := block(
  assert(f([]) = []),
  assert(f([0,0,0]) = [-1,-2,-3]),
  assert(f([0,1,0]) = [-1,2,-3]),
  assert(f([1,0,0]) = [1,-2,-3]),
  assert(f([1,1,1]) = [1,2,3]),
  assert(f([1,0,0,1,1,0,0,1]) = [1,-2,-3,4,5,-6,-7,8]),
  true)$

okltest_binl2dnf_l(f) := block(
  okltest_binl2dnf_l(lambda([a],f(a,makelist(i,i,1,length(a))))),
  true)$

okltest_hex2il(f) := block(
  assert(f("") = []),
  assert(f("00") = [0]),
  assert(f("32488853038D31734198AA2E0370D450") =
  [50,72,136,83,3,141,49,115,65,152,170,46,3,112,212,80]), 
  true)$

okltest_il2hex(f) := block(
  assert(f([]) = ""),
  assert(f([0]) = "00"),
  assert(f([50,72,136,83,3,141,49,115,65,152,170,46,3,112,212,80])
  = "32488853038D31734198AA2E0370D450"), 
  true)$

/*!
\endhtmlonly
*/
