/* Oliver Kullmann, 27.11.2011 (Swansea) */
/* Copyright 2011 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Resolution/tests/Graphs.mac
  \brief Tests regarding resolution graphs

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Resolution/tests/Graphs.mac");

*/

/*!
\htmlonly
*/

kill(f)$

okltest_resolutiongraph_cs2g(f) := (
  assert(f({}) = [{},{}]),
  assert(f({{}}) = [{{}},{}]),
  assert(f({{1}}) = [{{1}},{}]),
  assert(f({{1},{-1}}) = [{{1},{-1}},{{{1},{-1}}}]),
  assert(f({{1,2},{-1,-2}}) = [{{1,2},{-1,-2}},{}]),
  assert(f({{1,2},{-1,2},{1,-2},{-1,-2}}) = [{{1,2},{-1,2},{1,-2},{-1,-2}}, {{{1,2},{-1,2}},{{1,2},{1,-2}},{{-1,-2},{1,-2}},{{-1,-2},{-1,2}}}]),
  true)$

okltest_cc_resolutiongraph_cs(f) := (
  assert(f({}) = {}),
  assert(f({{}}) = {{{}}}),
  assert(f({{1},{2},{-1},{-2}}) = {{{1},{-1}},{{2},{-2}}}),
  assert(f({{1,2},{-1,2},{1,-2},{-1,-2}}) = {{{1,2},{-1,2},{1,-2},{-1,-2}}}),
  assert(f({{1,2},{-1,-2}}) = {{{1,2}},{{-1,-2}}}),
  true)$

okltest_subresolutiongraph_cs2g(f) := (
  assert(f({}) = [{},{}]),
  assert(f({{}}) = [{{}},{}]),
  assert(f({{1}}) = [{{1}},{}]),
  assert(f({{1},{-1}}) = [{{1},{-1}},{{{1},{-1}}}]),
  assert(f({{1,2},{-1,-2}}) = [{{1,2},{-1,-2}},{}]),
  assert(f({{1,2},{-1,2},{1,-2},{-1,-2}}) = [{{1,2},{-1,2},{1,-2},{-1,-2}}, {{{1,2},{-1,2}},{{1,2},{1,-2}},{{-1,-2},{1,-2}},{{-1,-2},{-1,2}}}]),
  assert(f({{1,2},{-2,3},{1,3}}) = [{{1,2},{-2,3},{1,3}}, {}]),
  assert(f({{1,2},{-2,3},{1,3},{-3,2}}) = [{{1,2},{-2,3},{1,3},{-3,2}}, {}]),
  true)$

okltest_cc_subresolutiongraph_cs(f) := (
  assert(f({}) = {}),
  assert(f({{}}) = {{{}}}),
  assert(f({{1},{2},{-1},{-2}}) = {{{1},{-1}},{{2},{-2}}}),
  assert(f({{1,2},{-1,2},{1,-2},{-1,-2}}) = {{{1,2},{-1,2},{1,-2},{-1,-2}}}),
  assert(f({{1,2},{-1,-2}}) = {{{1,2}},{{-1,-2}}}),
  assert(f({{1,2},{-2,3},{1,3},{-3,2}}) = {{{1,2}},{{-2,3}},{{1,3}},{{-3,2}}}),
  true)$


/*!
\endhtmlonly
*/
