#!/usr/bin/env bash
# Oliver Kullmann, 7.5.2023 (Swansea)
# Copyright 2023 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

set -o errexit
set -o nounset

program="F2"
version="0.0.1"

source tests/Fbasis

 ./Fuzzer "a30 40" "100*2,6;100*2,10;10*2,3" "" t &
argument1="+sba"  ./Fuzzer "a30 40" "100*2,6;100*2,10;10*2,3" "" t &
argument1="+sbm"  ./Fuzzer "a30 40" "100*2,6;100*2,10;10*2,3" "" t &

wait
