#!/usr/bin/env bash
# Oliver Kullmann, 7.5.2023 (Swansea)
# Copyright 2023 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

set -o errexit
set -o nounset

program="F4"
version="0.0.2"

source tests/Fbasis

./Fuzzer "a100 100" "100*2,4" u,m t &
argument1="+sba" ./Fuzzer "a100 100" "100*2,4" u,m t &
argument1="+sbm" ./Fuzzer "a100 100" "100*2,4" u,m t &
argument1="+sbi" ./Fuzzer "a100 100" "100*2,4" u,m t &

wait
