/* Oliver Kullmann, 21.5.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Primality/tests/Basics.mac
  \brief Tests for basic components related to prime clauses

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Primality/tests/Basics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

okltest_prime_clause_p(f) := (
  assert(f({},{}) = false),
  assert(f({},{{}}) = true),
  assert(f({},{{1}}) = false),
  assert(f({},{{1},{-1}}) = true),
  assert(f({1},{{1}}) = true),
  assert(f({1,3},{{1,2},{-2,3}}) = true),
  assert(f({1,2,3},{{1,2},{-2,3}}) = false),
  true)$

okltest_dual_prime_clause_p(f) := (
  assert(f({},{}) = true),
  assert(f({},{{}}) = false),
  assert(f({},{{1}}) = false),
  assert(f({},{{1},{-1}}) = false),
  assert(f({1},{{1}}) = true),
  assert(f({1,3},{{1,2},{-2,3}}) = true),
  assert(f({1,2,3},{{1,2},{-2,3}}) = false),
  true)$

okltest_prime_cs_p(f) := (
  assert(f({}) = true),
  assert(f({{}}) = true),
  assert(f({{1}}) = true),
  assert(f({{},{1}}) = false),
  assert(f({{1,2},{-2,3},{1,3}}) = true),
  assert(f({{1,2},{-2,3}}) = true),
  true)$

okltest_maximal_prime_cs_p(f) := (
  assert(f({}) = true),
  assert(f({{}}) = true),
  assert(f({{1}}) = true),
  assert(f({{},{1}}) = false),
  assert(f({{1,2},{-2,3},{1,3}}) = true),
  assert(f({{1,2},{-2,3}}) = false),
  true)$

/*!
\endhtmlonly
*/
