/* Oliver Kullmann, 28.12.2009 (Swansea) */
/* Copyright 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Primality/tests/RBases.mac
  \brief Tests for components related to r-bases

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Primality/tests/RBases.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/UnitClausePropagation.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/tests/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Reductions/GeneralisedUCP.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/Backtracking/DLL_solvers.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/tests/Cores.mac")$


/* ************
   * Sampling *
   ************
*/

okltest_rand_rbase_cs(f) := block([S, R, fr],
  assert(f({},ucp_0_cs) = {}),
  assert(f({{}},ucp_0_cs) = {{}}),
  for n : 0 thru 5 do block([F : setify(create_list({i},i,1,n))],
    assert(f(F,ucp_0_cs) = F)),
  assert(f({{},{1}},ucp_0_cs) = {{}}),
  assert(f({{1},{-1},{2}},ucp_0_cs) = {{1},{-1}}),
  assert(elementp(f({{1},{-1},{2}},ucp_0_cs), {{{1},{-1}},{{2},{-2}}}) = true),
  assert(f({{1,2,3},{-1,3,4},{2,3,4}},ucp_0_cs) = {{1,2,3},{-1,3,4}}),
  assert(f({{1,2,3},{-1,3,4},{2,3,4},{3,-4,5},{2,3,5}},ucp_0_cs) = {{1,2,3},{-1,3,4},{3,-4,5}}),
  assert(f({{1,2,3},{2,-3,4},{1,2,4},{5,-6,7},{-4,5,6},{-4,5,7},{1,2,5,7}},ucp_0_cs) = {{1,2,3},{2,-3,4},{5,-6,7},{-4,5,6}}),
  assert(okltest_subsumption_elimination_cs(buildq([f], lambda([F], f(F,weakest_reduction_cs)))) = true),
  assert(okltest_subsumption_elimination_cs(buildq([f], lambda([F], f(F,generalised_ucp0_cs)))) = true),
  S : dll_simplest_first_shortest_clause,
  R : buildq([S],lambda([F], strongest_reduction_cs(F,S))),
  fr : buildq([f,R],lambda([F], f(F,R))),
  assert(okltest_some_irr_cs(fr) = true),
  /* XXX */
  true)$

/*!
\endhtmlonly
*/
