/* Matthew Gwynne, 21.1.2009 (Swansea) */
/* Copyright 2009, 2010, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Combinatorics/Lisp/Enumeration/include.mac
  \brief Inclusion file for Maxima combinatorics enumeration-related functions

Use by

oklib_load("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/include.mac");
*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/Basics.mac")$
oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/Order.mac")$
oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/Permutations.mac")$
oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/Subsets.mac")$

oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/Order.mac")$
oklib_include("OKlib/ComputerAlgebra/Combinatorics/Lisp/Enumeration/tests/Subsets.mac")$


/*!
\endhtmlonly
*/
