/* Oliver Kullmann, 30.12.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/tests/GreenTaoProblems.mac
  \brief Tests for clause-sets related to Green-Tao problems

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/tests/GreenTaoProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$

/* *****************************************
   * Arithmetic progressions in the primes *
   *****************************************
*/

okltest_greentao2_fcl(f) := (
  assert(f(0,0) = [[],[{},{}]]),
  assert(f(0,1) = [[2],[{},{}]]),
  assert(f(1,0) = [[],[]]),
  assert(f(3,5) = [[2,3,5,7,11],[{3,5,7},{3,7,11},{-3,-5,-7},{-3,-7,-11}]]),
  assert(okltest_greentao2_fcs(buildq([f],lambda([k,n],fcl2fcs(f(k,n))))) = true),
  true)$

okltest_greentao2_fcs(f) := (
  assert(f(0,0) = [{},{{}}]),
  assertf((0,1) = [{2},{{}}]),
  assert(f(1,0) = [{},{}]),
  assert(f(1,1) = [{2},{{2},{-2}}]),
  assert(f(2,0) = [{},{}]),
  assert(f(2,1) = [{2},{}]),
  assert(f(2,2) = [{2,3},{{2,3},{-2,-3}}]),
  assert(f(2,3) = [{2,3,5},{{2,3},{2,5},{3,5},{-2,-3},{-2,-5},{-3,-5}}]),
  assert(f(3,0) = [{},{}]),
  assert(f(3,1) = [{2},{}]),
  assert(f(3,2) = [{2,3},{}]),
  assert(f(3,3) = [{2,3,5},{}]),
  assert(f(3,4) = [{2,3,5,7},{{3,5,7},{-3,-5,-7}}]),
  true)$

okltest_greentao2nd_fcl(f) := (
  assert(f(0,0,0) = [[],[{},{}]]),
  assert(f(0,1,2) = [[2,3],[{},{-2},{-3}]]),
  assert(okltest_greentao2nd_fcs(buildq([f],lambda([k1,k2,n],fcl2fcs(f(k1,k2,n))))) = true),
  assert(okltest_greentao2_fcl(buildq([f],lambda([k,n],f(k,k,n)))) = true),
  true)$

okltest_greentao2nd_fcs(f) := (
  okltest_greentao2_fcs(buildq([f], lambda([k,n], f(k,k,n)))),
  assert(okltest_greentao2_fcs(buildq([f],lambda([k,n],f(k,k,n)))) = true),
  assert(f(3,4,5) = [{2,3,5,7,11}, {{3,5,7},{3,7,11}}]),
  assert(f(3,4,9) = [{2,3,5,7,11,13,17,19,23}, {{3,5,7},{3,7,11},{3,11,19},{3,13,23},{5,11,17},{7,13,19},{11,17,23},{-5,-11,-17,-23}}]),
  true)$

okltest_greentao_nbfclud(f) := (
  assert(f([],0) = [[],[],[]]),
  assert(f([],1) = [[2],[],[]]),
  assert(f([],2) = [[2,3],[],[]]),
  assert(f([0],0) = [[],[{}],[1]]),
  assert(f([0,0],0) = [[],[{},{}],[1,2]]),
  assert(f([0,0,0,1],1) = [[2],[{},{},{},{[2,4]}],[1,2,3,4]]),
  assert(f([2,3],5) = [[2,3,5,7,11], [{[2,1],[3,1]},{[2,1],[5,1]},{[2,1],[7,1]},{[2,1],[11,1]},{[3,1],[5,1]},{[3,1],[7,1]},{[3,1],[11,1]},{[5,1],[7,1]},{[5,1],[11,1]},{[7,1],[11,1]},{[3,2],[5,2],[7,2]},{[3,2],[7,2],[11,2]}],[1,2]]),
  assert(okltest_greentao_nbfcsud(buildq([f],lambda([L,n], nbfclud2nbfcsud(f(L,n))))) = true),
  true)$

okltest_greentao_nbfcsud(f) := (
  assert(f([],0) = [{},{},{}]),
  assert(f([],1) = [{2},{},{}]),
  assert(f([],2) = [{2,3},{},{}]),
  assert(f([1],0) = [{},{},{1}]),
  assert(f([1],1) = [{2},{{[2,1]}},{1}]),
  assert(f([1],2) = [{2,3},{{[2,1]},{[3,1]}},{1}]),
  assert(f([1,1],0) = [{},{},{1,2}]),
  assert(f([1,1],1) = [{2},{{[2,1]},{[2,2]}},{1,2}]),
  assert(f([1,1],2) = [{2,3},{{[2,1]},{[2,2]},{[3,1]},{[3,2]}},{1,2}]),
  assert(f([2],0) = [{},{},{1}]),
  assert(f([2],1) = [{2},{},{1}]),
  assert(f([2],2) = [{2,3},{{[2,1],[3,1]}},{1}]),
  assert(f([1,2,3],3) = [{2,3,5}, {
   {[2,1]},{[3,1]},{[5,1]},
   {[2,2],[3,2]},{[2,2],[5,2]},{[3,2],[5,2]}}, {1,2,3}]),
  assert(f([1,1,2,2,3,3],4) = [{2,3,5,7}, {
   {[2,1]},{[3,1]},{[5,1]},{[7,1]},
   {[2,2]},{[3,2]},{[5,2]},{[7,2]},
   {[2,3],[3,3]},{[2,3],[5,3]},{[2,3],[7,3]},{[3,3],[5,3]},{[3,3],[7,3]},{[5,3],[7,3]},
   {[2,4],[3,4]},{[2,4],[5,4]},{[2,4],[7,4]},{[3,4],[5,4]},{[3,4],[7,4]},{[5,4],[7,4]},
   {[3,5],[5,5],[7,5]},
   {[3,6],[5,6],[7,6]}
  }, {1,2,3,4,5,6}]),
  /* XXX */
  true)$

okltest_greentaod_nbfclud(f) := (
  assert(f(0,0,0) = [[],[],[]]),
  assert(f(0,2,2) = [[2,3],[],[]]),
  assert(f(3,3,4) = [[2,3,5,7],[{[3,1],[5,1],[7,1]},{[3,2],[5,2],[7,2]},{[3,3],[5,3],[7,3]}],[1,2,3]]),
  assert(okltest_greentaod_nbfcsud(buildq([f],lambda([m,k,n],nbfclud2nbfcsud(f(m,k,n))))) = true),
  true)$

okltest_greentaod_nbfcsud(f) := (
  assert(f(0,0,0) = [{},{},{}]),
  assert(f(0,1,2) = [{2,3},{},{}]),
  assert(f(1,2,3) = [{2,3,5},{{[2,1],[3,1]},{[2,1],[5,1]},{[3,1],[5,1]}},{1}]),
  assert(f(2,3,5) = [{2,3,5,7,11},{{[3,1],[5,1],[7,1]},{[3,1],[7,1],[11,1]},{[3,2],[5,2],[7,2]},{[3,2],[7,2],[11,2]}},{1,2}]),
  /* XXX */
  true)$


/* ****************************************
   * Translation into boolean clause-sets *
   ****************************************
*/


/* *********************
   * Symmetry breaking *
   *********************
*/

okltest_greentao2_sb_fcs(f) := (
  /* XXX */
  true)$

okltest_greentao_sb_fcs(f) := (
  assert(f([],2) = [{},{{}}]),
  assert(f([],3) = [{},{{}}]),
  assert(f([1],2) = [{nbv(2,1),nbv(3,1)},{{-nbv(2,1)},{-nbv(3,1)},{nbv(2,1)},{nbv(3,1)}}]),
  assert(f([1,1],2) = [
 {nbv(2,1),nbv(3,1),nbv(2,2),nbv(3,2)},
 {{-nbv(2,1)},{-nbv(3,1)}, {-nbv(2,2)},{-nbv(3,2)},
  {nbv(2,1),nbv(2,2)},{nbv(3,1),nbv(3,2)},
  {-nbv(2,1),-nbv(2,2)},{-nbv(3,1),-nbv(3,2)}, 
  {nbv(3,1)}}]),
  assert(f([1,1,2,2],2) = [
 {nbv(2,1),nbv(3,1),nbv(2,2),nbv(3,2),nbv(2,3),nbv(3,3),nbv(2,4),nbv(3,4)},
 {{-nbv(2,1)},{-nbv(3,1)}, {-nbv(2,2)},{-nbv(3,2)},
  {-nbv(2,3),-nbv(3,3)}, {-nbv(2,4),-nbv(3,4)},
  {nbv(2,1),nbv(2,2),nbv(2,3),nbv(2,4)},{nbv(3,1),nbv(3,2),nbv(3,3),nbv(3,4)},
 {-nbv(2,1),-nbv(2,2)},{-nbv(2,1),-nbv(2,3)},{-nbv(2,1),-nbv(2,4)},{-nbv(2,2),-nbv(2,3)},{-nbv(2,2),-nbv(2,4)},{-nbv(2,3),-nbv(2,4)},
 {-nbv(3,1),-nbv(3,2)},{-nbv(3,1),-nbv(3,3)},{-nbv(3,1),-nbv(3,4)},{-nbv(3,2),-nbv(3,3)},{-nbv(3,2),-nbv(3,4)},{-nbv(3,3),-nbv(3,4)},
 {nbv(3,1),nbv(3,3)}}]),
  /* XXX */
  true)$

okltest_greentaod_sb_nbfcsud(f) := (
  /* XXX */
  true)$


/* ************************
   * Statistics functions *
   ************************
*/


/* ********************
   * Output functions *
   ********************
*/


/*!
\endhtmlonly
*/
