/* Oliver Kullmann, 8.8.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/tests/HindmanProblems.mac
  \brief Tests for clause-set-generators

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/tests/HindmanProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$


/* ********************
   * Hindman problems *
   ********************
*/

okltest_hindmani_a1k2_nbfcsud(f) := (
  assert(f(0,0) = [{},{},{}]),
  assert(f(1,2) = [{1,2},{},{1}]),
  /* XXX */
  true)$

okltest_hindman_a1k2_nbfcsud(f) := (
  assert(f(0,0) = [{},{},{}]),
  assert(f(1,2) = [{1,2},{{[1,1],[2,1]}},{1}]),
  /* XXX */
  true)$

okltest_hindmani_r2k2_ofcs(f) := (
  assert(f(1,0) = [[],[]]),
  assert(f(1,2) = [[1,2],[]]),
  /* XXX */
  true)$

okltest_hindman_r2k2_ofcs(f) := (
  assert(f(1,0) = [[],[]]),
  assert(f(1,2) = [[1,2],[{1,2},{-1,-2}]]),
  /* XXX */
  true)$


/*!
\endhtmlonly
*/
