/* Oliver Kullmann, 19.4.2009 (Swansea) */
/* Copyright 2009, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/tests/SchurProblems.mac
  \brief Tests for clause-sets related to Schur problems

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Generators/RamseyTheory/tests/SchurProblems.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Statistics.mac")$

kill(f)$


okltest_schur_nbfcsud(f) := (
  assert(f(0,0) = [{},{},{}]),
  assert(f(0,1) = [{1},{},{}]),
  assert(f(0,2) = [{1,2},{},{}]),
  assert(f(0,3) = [{1,2,3},{},{}]),
  assert(f(1,0) = [{},{},{1}]),
  assert(f(1,1) = [{1},{},{1}]),
  assert(f(1,2) = [{1,2},{{[1,1],[2,1]}},{1}]),
  assert(f(1,3) = [{1,2,3},{{[1,1],[2,1]},{[1,1],[2,1],[3,1]}},{1}]),
  assert(f(2,0) = [{},{},{1,2}]),
  assert(f(2,1) = [{1},{},{1,2}]),
  assert(f(2,2) = [{1,2},{{[1,1],[2,1]},{[1,2],[2,2]}},{1,2}]),
  assert(f(2,3) = [{1,2,3},{{[1,1],[2,1]},{[1,1],[2,1],[3,1]},{[1,2],[2,2]},{[1,2],[2,2],[3,2]}},{1,2}]),
  assert(f(3,0) = [{},{},{1,2,3}]),
  assert(f(3,1) = [{1},{},{1,2,3}]),
  assert(f(3,2) = [{1,2},{{[1,1],[2,1]},{[1,2],[2,2]},{[1,3],[2,3]}},{1,2,3}]),
  assert(f(3,3) = [{1,2,3},{{[1,1],[2,1]},{[1,1],[2,1],[3,1]},{[1,2],[2,2]},{[1,2],[2,2],[3,2]},{[1,3],[2,3]},{[1,3],[2,3],[3,3]}},{1,2,3}]),
  true)$

okltest_nvar_schur_nbfcsud(f) := (
  for r : 0 thru 5 do
   for n : 0 thru 5 do block([F : schur_nbfcsud(r,n)],
    assert(f(r,n) = length(F[1]))
  ),
  true)$

okltest_nval_schur_nbfcsud(f) := (
  for r : 0 thru 5 do
   for n : 0 thru 5 do block([F : schur_nbfcsud(r,n)],
    assert(f(r,n) = length(F[3]))
  ),
  true)$

okltest_ncl_list_schur_nbfcsud(f) := (
  for r : 0 thru 5 do
   for n : 0 thru 5 do block([F : schur_nbfcsud(r,n)],
    assert(f(r,n) = ncl_list_fcs(F))
  ),
  true)$

okltest_ncl_schur_nbfcsud(f) := (
  for r : 0 thru 5 do
   for n : 0 thru 5 do block([F : schur_nbfcsud(r,n)],
    assert(f(r,n) = ncl_fcs(F))
  ),
  true)$

okltest_schur_sb_nbfcsud(f) := (
  /* XXX */
  true)$

okltest_nvar_schur_aloamo_fcl(f) := (
  for r : 0 thru 5 do
   for n : 0 thru 5 do block([F : schur_aloamo_fcl(r,n)],
    assert(f(r,n) = nvar_fcl(F))
  ),
  true)$

okltest_nvar_schur_aloamo_fcs(f) := (
  for r : 0 thru 5 do
   for n : 0 thru 5 do block([F : schur_aloamo_fcs(r,n)],
    assert(f(r,n) = nvar_fcs(F))
  ),
  true)$

okltest_ncl_list_schur_aloamo_fcl(f) := (
  for r : 0 thru 6 do
   for n : 0 thru 6 do block([F : schur_aloamo_fcl(r,n)],
    assert(f(r,n) = ncl_list_fcl(F))
  ),
  true)$

okltest_ncl_list_schur_aloamo_fcs(f) := (
  for r : 0 thru 6 do
   for n : 0 thru 6 do block([F : schur_aloamo_fcs(r,n)],
    assert(f(r,n) = ncl_list_fcs(F))
  ),
  true)$

/*!
\endhtmlonly
*/
