/* Matthew Gwynne, 21.1.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Combinatorics/Lisp/include.mac
  \brief Inclusion file for Maxima combinatorics-related functions

Use by

oklib_load("Transitional/ComputerAlgebra/Combinatorics/Lisp/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Combinatorics/Lisp/Enumeration/include.mac")$

/*!
\endhtmlonly
*/
