#!/bin/bash
boundnds=${2:-25000}
cd ../../..
# Optimise nds:
cat $1 | ./laMols  7 data/SpecsCollection/3MOLS/diag "" count dom enu wdL "" "" 1 10 cin "nds,${boundnds}" | awk 'FNR == 2 {print $16 " " $15}'
