/* Oliver Kullmann, 3.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Counting/include.mac
  \brief Inclusion file for Maxima SAT-counting functions

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/Counting/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Counting/Backtracking.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Counting/Degrees.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Counting/InclusionExclusion.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Counting/RandomClauseSets.mac")$

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Counting/tests/Degrees.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Counting/tests/InclusionExclusion.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Counting/tests/RandomClauseSets.mac")$

/*!
\endhtmlonly
*/
