/* Oliver Kullmann, 17.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/Counting/RandomClauseSets.mac
  \brief Functions related to thresholds from SAT to UNSAT related to clause- or variable degrees

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/Counting/RandomClauseSets.mac");

*/

/*!
\htmlonly
*/

/* The probability that a random assignment over the 
   variables in the given clause-set satisfies a random clause-set 
   drawn with the same number of clauses of the same lengths as the
   given clause-set. */
/* Compare with logprobrand in
ComputerAlgebra/Satisfiability/Lisp/Backtracking/DLL_solvers.mac. */
probsatrand(F) :=
  block([L : listify(F)], product(1 - 2^(-length(L[i])),i,1,length(L)))$


/*!
\endhtmlonly
*/
