/* Oliver Kullmann, 28.1.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011, 2012, 2013 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/BasicOperations.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/BasicOperations.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/BasicOperations.mac")$

/* **************************
   * Variables and literals *
   **************************
*/

okltest_v_p(v_p);
okltest_l_p(l_p);

okltest_var_l(var_l);

okltest_sign_l(sign_l);
okltest_pos_l(pos_l);
okltest_neg_l(neg_l);

okltest_literals_v(literals_v);

okltest_gv(gv);

/* ***********
   * Clauses *
   ***********
*/

okltest_comp_sl(comp_sl);

okltest_c_p(c_p);

okltest_clashp(clashp);

okltest_var_sl(var_sl);
okltest_var_sl(var_c);

okltest_pospart_c(pospart_c);
okltest_negpart_c(negpart_c);
okltest_posp_c(posp_c);
okltest_negp_c(negp_c);

/* ***************
   * Clause-sets *
   ***************
*/

okltest_cs_p(cs_p);
okltest_ocs_p(ocs_p);
okltest_cl_p(cl_p);
okltest_fcs_p(fcs_p);
okltest_ofcs_p(ofcs_p);
okltest_fcl_p(fcl_p);

okltest_var_cs(var_cs);
okltest_var_cl(var_cl);
okltest_var_ocs(var_ocs);
okltest_var_fcs(var_fcs);
okltest_var_fcl(var_fcl);
okltest_var_ofcs(var_ofcs);

okltest_ovar_cl(ovar_cl);

okltest_olit_cs(olit_cs);
okltest_flit_cs(flit_cs);

okltest_cs2fcs(cs2fcs);
okltest_cl2fcl(cl2fcl);
okltest_ocs2ofcs(ocs2ofcs);

okltest_cs2ocs(cs2ocs);
okltest_fcs2ofcs(fcs2ofcs);
okltest_fcs2fcl(fcs2fcl);

okltest_cs2fcl(cs2fcl);

okltest_ocs2cs(ocs2cs);
okltest_cl2cs(cl2cs);

okltest_fcs2cs(fcs2cs);
okltest_ofcs2ocs(ofcs2ocs);
okltest_fcl2cl(fcl2cl);
okltest_fcl2cs(fcl2cs);

/* ***********************************
   * Selecting parts of a clause-set *
   ***********************************
*/

okltest_scs_k(scs_k);
okltest_scs_l(scs_l);
okltest_scs_v(scs_v);
okltest_scs_V(scs_V);

/* **************************
   * Crossing out variables *
   **************************
*/

okltest_apply_sv_c(apply_sv_c);
okltest_apply_sv_cs(apply_sv_cs);
okltest_apply_sv_cl(apply_sv_cl);
okltest_apply_sv_ip_cl(apply_sv_ip_cl);

okltest_restrict_V_cs(restrict_V_cs);
okltest_restrict_V_cl(restrict_V_cl);

/* *****************************************
   * Printing clause-sets in Dimacs-format *
   *****************************************
*/

okltest_dimacs_l_string(dimacs_l_string);
okltest_dimacs_c_string(dimacs_c_string);
okltest_dimacs_c_stringext(dimacs_c_stringext);

okltest_print_fcs_v(print_fcs_v);
okltest_print_fcl_v(print_fcl_v);

okltest_standard_statistics_fcs(standard_statistics_fcs);

/* *****************************************
   * Printing clause-sets in PLA-format    *
   *****************************************
*/

okltest_print_fcl2pla(print_fcl2pla);

/*!
\endhtmlonly
*/
