/* Oliver Kullmann, 28.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/BasicOperations.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/BasicOperations.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/BasicOperations.mac")$

/* **************************
   * Variables and literals *
   **************************
*/

okltest_v_p(v_p);
okltest_l_p(l_p);

okltest_var_l(var_l);

/* ***********
   * Clauses *
   ***********
*/

okltest_comp_sl(comp_sl);

okltest_c_p(c_p);

/* ***************
   * Clause-sets *
   ***************
*/

okltest_cs_p(cs_p);
okltest_fcs_p(fcs_p);

/* *****************************
   * Substitution and renaming *
   *****************************
*/

okltest_substitute_l(substitute_l);
okltest_substitute_c(substitute_c);
okltest_substitute_cs(substitute_cs);

okltest_rename_fcs(rename_fcs);

okltest_standardise_fcs(standardise_fcs);
okltest_make_vardisjoint_fcs(make_vardisjoint_fcs);

/* ***********************************
   * Selecting parts of a clause-set *
   ***********************************
*/

okltest_scls_l(scls_l);
okltest_scls_v(scls_v);
okltest_scls_V(scls_V);

/*!
\endhtmlonly
*/
