/* Oliver Kullmann, 5.5.2008 (Guangzhou) */
/* Copyright 2008, 2009, 2010, 2012, 2013, 2019 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Constructions.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Constructions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Constructions.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Constructions.mac")$

/* **********************
   * Logical operations *
   **********************
*/

okltest_c2cl_expand(c2cl_expand);
okltest_c2cs_expand(c2cs_expand);
okltest_expand_fcs(expand_fcs);
okltest_expand_cs(expand_cs);

okltest_or_cs2(or_cs2);
okltest_or_cs(or_cs);

okltest_dual_cs(dual_cs);

okltest_comp_cs(comp_cs);
okltest_comp_fcs(comp_fcs);

okltest_neg_cs(neg_cs);

okltest_add_neg_cl_cs(add_neg_cl_cs);

/* ****************************
   * Combinatorial operations *
   ****************************
*/

okltest_vardisjoint_sum_fcs(vardisjoint_sum_fcs);

okltest_vardisjoint_full_gluing(vardisjoint_full_gluing);
okltest_full_gluing(full_gluing);
okltest_partial_gluing(partial_gluing);

okltest_twisting_cs(twisting_cs);
okltest_twisting_var_disjoint_cs(twisting_var_disjoint_cs);

/*!
\endhtmlonly
*/
