/* Oliver Kullmann, 1.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Generators.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Generators.mac");

*/

/*!
\htmlonly
*/

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Generators.mac");
oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Generators.mac");


okltest_nvar_php(nvar_php);
okltest_ncl_list_weak_php(ncl_list_weak_php);

/*!
\endhtmlonly
*/
