/* Oliver Kullmann, 2.2.2008 (Swansea) */
/* Copyright 2008, 2009, 2010, 2011, 2018 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Hypergraphs.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Hypergraphs.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Hypergraphs.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Hypergraphs.mac")$


/* *******************************************
   * Clause-variable matrices and variations *
   *******************************************
*/

okltest_clvar_g(clvar_g);

okltest_var_fcs2hg(var_fcs2hg);
okltest_var_fcs2ghg(var_fcs2ghg);

okltest_cvg_cs(cvg_cs);

okltest_cl_var_com_fcs(cl_var_com_fcs);
okltest_clvar_com2fcs(clvar_com2fcs);
okltest_clvar_ocom2fcl(clvar_ocom2fcl);
okltest_clvar_m2fcs(clvar_m2fcs);
okltest_clvar_w_com2fcs(clvar_w_com2fcs);
okltest_clvar_w_ocom2fcl(clvar_w_ocom2fcl);

okltest_cl_int_scom_cs(cl_int_scom_cs);
okltest_var_int_scom_fcs(var_int_scom_fcs);

okltest_var_lit_clause_digraph(var_lit_clause_digraph);

/* ***************************************
   * Implication graphs (and variations) *
   ***************************************
*/

okltest_implication_dg_fcs(implication_dg_fcs);
okltest_imp_cs2dg(imp_cs2dg);

/* ************
   * Measures *
   ************
*/

okltest_min_degree_cvg_cs(min_degree_cvg_cs);
okltest_max_degree_cvg_cs(max_degree_cvg_cs);

okltest_deficiency_fcs(deficiency_fcs);
okltest_deficiency_cs(deficiency_cs);

okltest_max_deficiency_fcs(max_deficiency_fcs);

okltest_surplus_bydef_fcs(surplus_bydef_fcs);
okltest_surplus_bydef_cs(surplus_bydef_cs);

/* ************
   * Analysis *
   ************
*/

okltest_var_disjointfcsp(var_disjointfcsp);

okltest_accumulation_variables_cs(accumulation_variables_cs);

okltest_full_variables_fcs(full_variables_fcs);

/*!
\endhtmlonly
*/
