/* Oliver Kullmann, 2.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Hypergraphs.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Hypergraphs.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Hypergraphs.mac");
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Hypergraphs.mac");


okltest_cvg_cs(cvg_cs);

okltest_min_degree_cvg_cs(min_degree_cvg_cs);
okltest_max_degree_cvg_cs(max_degree_cvg_cs);

okltest_deficiency_fcs(deficiency_fcs);
okltest_max_deficiency_fcs(max_deficiency_fcs);


/*!
\endhtmlonly
*/
