/* Oliver Kullmann, 2.2.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Hypergraphs.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Hypergraphs.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Hypergraphs.mac");
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Hypergraphs.mac");


/* *******************
   * Transformations *
   *******************
*/

okltest_cvg_cs(cvg_cs);

okltest_cl_var_com_fcs(cl_var_com_fcs);

okltest_cl_int_scom_cs(cl_int_scom_cs);
okltest_var_int_scom_fcs(var_int_scom_fcs);

okltest_var_lit_clause_digraph(var_lit_clause_digraph);

/* ************
   * Measures *
   ************
*/

okltest_min_degree_cvg_cs(min_degree_cvg_cs);
okltest_max_degree_cvg_cs(max_degree_cvg_cs);

okltest_deficiency_fcs(deficiency_fcs);
okltest_max_deficiency_fcs(max_deficiency_fcs);

/* ************
   * Analysis *
   ************
*/

okltest_var_disjointp(var_disjointp);

okltest_accumulation_variables_fcs(accumulation_variables_fcs);

/*!
\endhtmlonly
*/
