/* Oliver Kullmann, 4.4.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Statistics.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Statistics.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Statistics.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Statistics.mac")$

/* *******************
   * Literal degrees *
   *******************
*/

okltest_literal_degrees_cs(literal_degrees_cs);
okltest_all_literal_degrees_fcs(all_literal_degrees_fcs);
okltest_ordered_literal_degrees_cs(ordered_literal_degrees_cs);
okltest_min_literal_degree_cs(min_literal_degree_cs);
okltest_max_literal_degree_cs(max_literal_degree_cs);
okltest_min_literal_degree_l_cs(min_literal_degree_l_cs);
okltest_max_literal_degree_l_cs(max_literal_degree_l_cs);
okltest_literal_degrees_list_fcs(literal_degrees_list_fcs);

/* ********************
   * Variable degrees *
   ********************
*/

okltest_variable_degree_cs(variable_degree_cs);
okltest_variable_degrees_cs(variable_degrees_cs);
okltest_min_variable_degree_cs(min_variable_degree_cs);
okltest_max_variable_degree_cs(max_variable_degree_cs);
okltest_max_variable_degree_v_cs(max_variable_degree_v_cs);
okltest_variable_degrees_list_cs(variable_degrees_list_cs);

/* *******************************
   * Weighted numbers of clauses *
   *******************************
*/

okltest_weighted_ncl_2n_cs(weighted_ncl_2n_cs);

/*!
\endhtmlonly
*/
