/* Oliver Kullmann, 4.4.2008 (Swansea) */
/* Copyright 2008, 2009, 2011, 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Statistics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Statistics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Statistics.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Statistics.mac")$

/* ******************
   * Basic measures *
   ******************
*/

okltest_nvar_cs(nvar_cs);
okltest_nvar_ocs(nvar_ocs);
okltest_nvar_cl(nvar_cl);
okltest_nvar_fcs(nvar_fcs);
okltest_nvar_fcl(nvar_fcl);
okltest_nvar_ofcs(nvar_ofcs);

okltest_ncl_fcs(ncl_fcs);
okltest_ncl_fcl(ncl_fcl);
okltest_ncl_cs(ncl_cs);
okltest_ncl_cl(ncl_cl);

okltest_nlitocc_cl(nlitocc_cl);
okltest_nlitocc_cs(nlitocc_cs);
okltest_nlitocc_fcl(nlitocc_fcl);
okltest_nlitocc_fcs(nlitocc_fcs);

okltest_ncl_list_fcl(ncl_list_fcl);
okltest_ncl_list_fcs(ncl_list_fcs);
okltest_ncl_list_cl(ncl_list_cl);
okltest_ncl_list_cs(ncl_list_cs);

okltest_max_rank_cs(max_rank_cs);
okltest_max_rank_fcs(max_rank_fcs);
okltest_min_rank_cs(min_rank_cs);
okltest_min_rank_fcs(min_rank_fcs);

okltest_uniformcsp(uniformcsp);

/* *******************
   * Literal degrees *
   *******************
*/

okltest_literal_degree_cs(literal_degree_cs);

okltest_literal_degrees_cs(literal_degrees_cs);
okltest_literal_degrees_cl(literal_degrees_cl);
okltest_literal_degrees_fcs(literal_degrees_fcs);

okltest_ordered_literal_degrees_cs(ordered_literal_degrees_cs);
okltest_ordered_literal_degrees_fcs(ordered_literal_degrees_fcs);

okltest_min_literal_degree_cs(min_literal_degree_cs);
okltest_min_literal_degree_fcs(min_literal_degree_fcs);
okltest_max_literal_degree_cs(max_literal_degree_cs);
okltest_max_literal_degree_fcs(max_literal_degree_cs);

okltest_min_literal_degree_l_cs(min_literal_degree_l_cs);
okltest_max_literal_degree_l_cs(max_literal_degree_l_cs);
okltest_max_literal_degree_l_cl(max_literal_degree_l_cl);

okltest_literalregularcsp(literalregularcsp);

okltest_mean_literal_degree_fcs(mean_literal_degree_fcs);

okltest_min_literal_frequency_cs(min_literal_frequency_cs);
okltest_max_literal_frequency_cs(max_literal_frequency_cs);
okltest_max_literal_frequency_cs(max_literal_frequency_cs);

okltest_literal_degrees_list_fcs(literal_degrees_list_fcs);

okltest_max_literal_degree_tb(max_literal_degree_tb);
okltest_max_literal_degree_tb_l_cs(max_literal_degree_tb_l_cs);

/* ********************
   * Variable degrees *
   ********************
*/

okltest_variable_degree_cs(variable_degree_cs);
okltest_variable_degrees_cs(variable_degrees_cs);

okltest_min_variable_degree_cs(min_variable_degree_cs);
okltest_min_variable_degree_fcs(min_variable_degree_fcs);
okltest_max_min_var_deg_cs(max_min_var_deg_cs);
okltest_max_variable_degree_fcs(max_variable_degree_fcs);
okltest_max_variable_degree_cs(max_variable_degree_cs);
okltest_max_variable_degree_v_cs(max_variable_degree_v_cs);
okltest_min_max_var_deg_cs(min_max_var_deg_cs);

okltest_variableregularcsp(variableregularcsp);

okltest_mean_variable_degree_cs(mean_variable_degree_cs);

okltest_min_variable_frequency_cs(min_variable_frequency_cs);
okltest_max_variable_frequency_cs(max_variable_frequency_cs);
okltest_mean_variable_frequency_cs(mean_variable_frequency_cs);

okltest_variable_degrees_list_cs(variable_degrees_list_cs);

okltest_full_variables_cs(full_variables_cs);
okltest_full_variables_fcs(full_variables_fcs);
okltest_full_var_csp(full_var_csp);
okltest_full_var_fcsp(full_var_fcsp);

okltest_singularpure_variables_cs(singularpure_variables_cs);
okltest_singular_variables_cs(singular_variables_cs);
okltest_singular_variables_fcs(singular_variables_fcs);
okltest_onesingular_variables_fcs(onesingular_variables_fcs);
okltest_onesingular_variables_cs(onesingular_variables_cs);

okltest_sortvar_prodocc_cs(sortvar_prodocc_cs);

/* **********************
   * Numbers of clauses *
   **********************
*/

okltest_nfcl_fcl(nfcl_fcl);
okltest_nfcl_cs(nfcl_cs);

okltest_weighted_ncl_2n_cs(weighted_ncl_2n_cs);
okltest_weighted_ncl_2n_fcs(weighted_ncl_2n_fcs);

/* **************************
   * Summarising statistics *
   **************************
*/

okltest_statistics_cs(statistics_cs);
okltest_statistics_fcs(statistics_fcs);
okltest_extended_statistics_fcs(extended_statistics_fcs);


/*!
\endhtmlonly
*/
