/* Oliver Kullmann, 27.7.2007 (Swansea) */
/* Copyright 2008, 2009, 2013 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Substitutions.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/Substitutions.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/Substitutions.mac")$
oklib_include("OKlib/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/Substitutions.mac")$

/* ********************************************
   * Substitutions for variables and literals *
   ********************************************
*/

okltest_substitute_l(substitute_l);

/* *****************************
   * Substitutions for clauses *
   *****************************
*/

okltest_substitute_c(substitute_c);

/* *********************************
   * Substitutions for clause-sets *
   *********************************
*/

okltest_substitute_cs(substitute_cs);

okltest_rename_fcs(rename_fcs);
okltest_rename_cs(rename_cs);

okltest_all_var_renamings_fcs(all_var_renamings_fcs);
okltest_all_sign_flippings_fcs(all_sign_flippings_fcs);
okltest_all_renamings_fcs(all_renamings_fcs);

okltest_standardise_fcs(standardise_fcs);
okltest_make_vardisjoint_fcs(make_vardisjoint_fcs);
okltest_make_vardisjoint_vl_fcs(make_vardisjoint_vl_fcs);

/*!
\endhtmlonly
*/
