/* Oliver Kullmann, 27.7.2007 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/BasicOperations.mac

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/testobjects/BasicOperations.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/BasicOperations.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/tests/BasicOperations.mac")$

/* ********************************************
   * Substitutions for variables and literals *
   ********************************************
*/

okltest_substitute_l(substitute_l);

/* *****************************
   * Substitutions for clauses *
   *****************************
*/

okltest_substitute_c(substitute_c);

/* *********************************
   * Substitutions for clause-sets *
   *********************************
*/

okltest_substitute_cs(substitute_cs);

okltest_rename_fcs(rename_fcs);

okltest_standardise_fcs(standardise_fcs);
okltest_make_vardisjoint_fcs(make_vardisjoint_fcs);

/*!
\endhtmlonly
*/
