/* Oliver Kullmann, 5.1.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/include.mac
  \brief Inclusion file for Maxima satisfiability-related functions

Use by

oklib_load("Transitional/ComputerAlgebra/Satisfiability/Lisp/include.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Autarkies/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Backtracking/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/BranchingTuples/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ClauseSets/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ConflictCombinatorics/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ConstraintProblems/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Counting/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Generators/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/MinimalUnsatisfiability/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/PropositionalLogic/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Reductions/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Resolution/include.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/Symmetries/include.mac")$

/*!
\endhtmlonly
*/
