/* Matthew Gwynne, 27.2.2012 (Swansea) */
/* Copyright 2012 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/CryptoSystems/KeeLoq/testobjects/Cipher.mac

Use by

oklib_load("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/KeeLoq/testobjects/Cipher.mac");

*/

/*!
\htmlonly
*/


oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/KeeLoq/Cipher.mac")$
oklib_include("OKlib/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/KeeLoq/tests/Cipher.mac")$


/* *****************
   * KeeLoq cipher *
   *****************
*/

okltest_keeloq_nlf(keeloq_nlf);
okltest_keeloq_round(keeloq_round_8t1_bf);
okltest_keeloq_round_bf(keeloq_round_9t1_bf);
okltest_keeloq_encryption_gen(keeloq_encryption_gen);
okltest_keeloq_encryption(keeloq_encryption);

/*!
\endhtmlonly
*/
