#!/usr/bin/env bash
# Oleg Zaikin, 28.12.2020 (Swansea)
# Copyright 2020 Oliver Kullmann
# This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation and included in this library; either version 3 of the
# License, or any later version. */

# USAGE:

# Call_LSRG

# runs LSRG with parameters '10 1 3,2,1 out_lsrg' k times

# For changing k=1000 (the default), use e.g.
# k=5 ./Call_LSRG


program="Call_LSRG"
version="0.0.1"

: ${k:=1000}
: ${progr:="./LSRG"}
: ${progargs:="10 1 3,2,1 -out_lsrg"}
: ${progargs2:="10 1 3,2,1"}

for ((i=0; i < k-1; ++i)); do
  $progr $progargs;
done
$progr $progargs2
