/* Matthew Lewsey, 11.2.2009 (Swansea) */
/* Copyright 2009 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Graphs/Lisp/Bicliques/tests/BasicNotions.mac
  \brief Tests for biclique-notions

Use by

oklib_load("Transitional/ComputerAlgebra/Graphs/Lisp/Bicliques/tests/Consenus.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$
oklib_include("Transitional/ComputerAlgebra/Graphs/Lisp/Bicliques/Consensus.mac")$

kill(f)$


/* ***********************
   * Fundamental notions *
   ***********************
*/

okltest_bc_absorbs_bc_gl_p(f) := block([G],
  assert(f([{},{}],[{},{}]) = true),
  assert(f([{},{}],[{1},{}]) = false),
  assert(f([{1},{}],[{},{}]) = true),
  assert(f([{},{1}],[{1},{}]) = true),
  assert(f([{1,3},{4,6}],[{2,3},{4,5}]) = false),
  assert(f([{1,2,3,4},{5,6}],[{1,3},{4,6}]) = false),
  true)$

okltest_con_adj_gl_b1_1_b2_1_p(f) := block([G],
  assert(f([{},{}],[{},{}],[]) = false),
  assert(f([{1},{}],[{1},{}],[]) = true),
  assert(f([{1,2},{}],[{1},{}],[]) = true),
  assert(f([{1,2},{}],[{},{1}],[]) = false),
  assert(f([{1},{}],[{2},{}],[]) = false),
  assert(f([{1,2},{}],[{1},{}],[[{1},{3}]]) = false),
  true)$
  
okltest_con_adj_gl_b1_1_b2_2_p(f) := block([G],
  assert(f([{},{}],[{},{}],[]) = false),
  assert(f([{1},{}],[{},{1}],[]) = true),
  assert(f([{1,2},{}],[{},{1}],[]) = true),
  assert(f([{1,2},{}],[{1},{}],[]) = false),
  assert(f([{1},{}],[{},{2}],[]) = false),
  assert(f([{1,2},{}],[{},{1}],[[{3},{1}]]) = false),
  true)$

okltest_con_adj_gl_b1_2_b2_1_p(f) := block([G],
  assert(f([{},{}],[{},{}],[]) = false),
  assert(f([{},{1}],[{1},{}],[]) = true),
  assert(f([{},{1,2}],[{1},{}],[]) = true),
  assert(f([{},{1,2}],[{},{1}],[]) = false),
  assert(f([{},{1}],[{2},{}],[]) = false),
  assert(f([{},{1,2}],[{1},{}],[[{1},{3}]]) = false),
  true)$

okltest_con_adj_gl_b1_2_b2_2_p(f) := block([G],
  assert(f([{},{}],[{},{}],[]) = false),
  assert(f([{},{1}],[{},{1}],[]) = true),
  assert(f([{},{1,2}],[{},{1}],[]) = true),
  assert(f([{},{1,2}],[{1},{}],[]) = false),
  assert(f([{},{1}],[{},{2}],[]) = false),
  assert(f([{},{1,2}],[{},{1}],[[{3},{1}]]) = false),
  true)$

okltest_maximal_bc_gl(f) := block([G],
  assert(f([{},{}],[{},{}]) = [{},{}]),
  /* XXX */
  assert(f([{},{}],[{1,2},{{1,2}}]) = [{1},{2}]),
  assert(f([{1},{2,3}],[{1,2,3,4},{{1,2},{1,3},{1,4}}]) = [{1},{2,3,4}]),
  true)$

okltest_con_adj_gl_b1_1_b2_1(f) := block([G],
  assert(f([{1},{}],[{1},{}]) = [{1},{}]),
  assert(f([{1,2},{}],[{1},{}]) = [{1},{}]),
  assert(f([{1,2},{}],[{2,3},{}]) = [{2},{}]),
  assert(f([{1,2,3},{7}],[{3,4,5},{6}]) = [{3},{6,7}]),
  true)$

okltest_con_adj_gl_b1_1_b2_2(f) := block([G],
  assert(f([{1},{}],[{},{1}]) = [{1},{}]),
  assert(f([{1,2},{}],[{},{1}]) = [{1},{}]),
  assert(f([{1,2},{}],[{},{2,3}]) = [{2},{}]),
  assert(f([{1,2,3},{7}],[{6},{3,4,5}]) = [{3},{6,7}]),
  true)$

okltest_con_adj_gl_b1_2_b2_1(f) := block([G],
  assert(f([{},{1}],[{1},{}]) = [{1},{}]),
  assert(f([{},{1,2}],[{1},{}]) = [{1},{}]),
  assert(f([{},{1,2}],[{2,3},{}]) = [{2},{}]),
  assert(f([{7},{1,2,3}],[{3,4,5},{6}]) = [{3},{6,7}]),
  true)$

okltest_con_adj_gl_b1_2_b2_2(f) := block([G],
  assert(f([{},{1}],[{},{1}]) = [{1},{}]),
  assert(f([{},{1,2}],[{},{1}]) = [{1},{}]),
  assert(f([{},{1,2}],[{},{2,3}]) = [{2},{}]),
  assert(f([{7},{1,2,3}],[{6},{3,4,5}]) = [{3},{6,7}]),
  true)$

okltest_con_adj_gl_bc(f) := block([G],
  assert(f([{},{}],[{},{}],[]) = []),
  assert(f([{1},{2}],[{1},{3}],[]) = [[{1},{2,3}]]),
  assert(f([{1},{2}],[{1},{3}],[[{2,3},{1}]]) = [[{2,3},{1}]]),
  true)$

okltest_con_ext_gl_bc(f) := block([G],
  assert(f([{},{}],[{},{}],[],[{},{}]) = []),
  assert(f([{1},{2}],[{1},{3}],[],[{1,2,3},{{1,2},{1,3}}]) = [[{1},{2,3}]]),
  assert(f([{1},{2}],[{1},{3}],[[{2,3},{1}]],[{1,2,3},{{1,2},{1,3}}]) = [[{2,3},{1}]]),
  assert(f([{1},{2}],[{1},{3}],[],[{1,2,3,4},{{1,2},{1,3},{1,4}}]) = [[{1},{2,3,4}]]),
  assert(f([{1},{2}],[{1},{3}],[],[{1,2,3,4,5},{{1,2},{1,3},{1,4},{5,2},{5,3},{5,4}}]) = [[{1,5},{2,3,4}]]),
  assert(f([{1},{2}],[{1},{3}],[[{1},{4}]],[{1,2,3,4,5},{{1,2},{1,3},{1,4},{5,2},{5,3}}]) = [[{1},{2,3,4}],[{1},{4}]]),
  true)$

okltest_aux_con_alg1_abs(f) := block([G],
  assert(f([[{1},{2}],[{3},{4}],[{1},{}]]) = [[{1},{2}],[{3},{4}]]),
  assert(f([[{2},{1}],[{2},{1}],[{1,3},{2,4}]]) = [[{2},{1}],[{1,3},{2,4}]]),
  true)$

okltest_aux_con_alg1_con(f) := block([G],
  assert(f([[{1},{2}],[{1},{4}]]) = [[{1},{2,4}],[{1},{2}],[{1},{4}]]),
  assert(f([[{1},{2,3}],[{1},{3,4}]]) = [[{1},{2,3,4}],[{1},{2,3}],[{1},{3,4}]]),
  true)$

okltest_aux_con_alg2_ext(f) := block([G],
  assert(f([[{1,2},{3,4}],[{1,5},{6}]],[{1,2,3,4,5,6},{{1,3},{1,4},{2,3},{2,4},{1,6},{5,6}}]) = [[{1},{3,4,6}],[{1,2},{3,4}],[{1,5},{6}]]),
  assert(f([[{1,2},{3,4}],[{5,6},{7,8}],[{1,5},{4,7}]],[{1,2,3,4,5,6,7,8},{{1,3},{1,4},{2,3},{2,4},{5,7},{5,8},{6,7},{6,8},{1,4},{1,7},{5,4},{5,7}}]) = [[{1},{3,4,7}],[{1,2},{3,4}],[{5,6},{7,8}],[{1,5},{4,7}]]),
  true)$

okltest_con_alg1(f) := block([G],
  assert(f([[{1},{2}]],[{1,2},{{1,2}}]) = [[{1},{2}]]),
  assert(f([[{1},{2}],[{3},{4}]],[{1,2,3,4},{{1,2},{3,4}}]) = [[{1},{2}],[{3},{4}]]),
  assert(f([[{1,2},{3,4}],[{5,6},{7,8}],[{1,5},{4,7}]],[{1,2,3,4,5,6,7,8},{{1,3},{1,4},{2,3},{2,4},{5,7},{5,8},{6,7},{6,8},{1,4},{1,7},{5,4},{5,7}}]) = [[{5},{4,7,8}],[{4},{1,2,5}],[{7},{1,5,6}],[{1},{3,4,7}],[{1,2},{3,4}],[{5,6},{7,8}],[{1,5},{4,7}]]),
  true)$

okltest_con_alg2(f) := block([G],
  assert(f([[{1},{2}]],[{1,2},{{1,2}}]) = [[{1},{2}]]),
  assert(f([[{1},{2}],[{3},{4}]],[{1,2,3,4},{{1,2},{3,4}}]) = [[{1},{2}],[{3},{4}]]),
  assert(f([[{1,2},{3,4}],[{5,6},{7,8}],[{1,5},{4,7}]],[{1,2,3,4,5,6,7,8},{{1,3},{1,4},{2,3},{2,4},{5,7},{5,8},{6,7},{6,8},{1,4},{1,7},{5,4},{5,7}}]) = [[{5},{4,7,8}],[{4},{1,2,5}],[{7},{1,5,6}],[{1},{3,4,7}],[{1,2},{3,4}],[{5,6},{7,8}],[{1,5},{4,7}]]),
  true) $


/*!
\endhtmlonly
*/
