/* Matthew Gwynne, 26.3.2008 (Swansea) */
/* Copyright 2008 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/SboxAnalysis.mac
  \brief Cryptanalysis functions and tools regarding AES/Rijndael Sbox.

Use by

oklib_load("Transitional/ComputerAlgebra/Cryptology/Lisp/Cryptanalysis/Rijndael/SboxAnalysis.mac");

*/

/*!
\htmlonly
*/

oklib_include("Transitional/ComputerAlgebra/DataStructures/Lisp/Lists.mac")$
oklib_include("Transitional/ComputerAlgebra/Cryptology/Lisp/Conversions.mac")$
oklib_include("Transitional/ComputerAlgebra/Cryptology/Lisp/CryptoSystems/Rijndael/AdvancedEncryptionStandard.mac")$
oklib_include("Transitional/ComputerAlgebra/Satisfiability/Lisp/ConflictCombinatorics/HittingClauseSets.mac")$


/* ******************************************
   * Sbox Analysis                          *
   ******************************************
*/

/* Transforms an integer into a big endian binary list representation
   padded with 0s to the left up to length "n" */
int2binlist(int,n) := polynomial2list(intToPoly(int,2),n)$

/* Generation of the full DNF clause-set representing the AES sbox */
generate_full_aes_sbox_dnf_fcs() :=  
  cs_to_fcs(map(lambda([ce],binary_list_to_dnf_c(
    append(polynomial2list(ce,8),polynomial2list(
      intToGF2t8Poly(lookup_sbox(GF2t8PolyToInt(ce))),8)))),
    map(lambda([se], xreduce(lambda([a,b],a+b),se,0)), 
      powerset(setify(makelist(x^i,i,0,7))))))$

/* Generation of the full CNF clause-set representing the AES sbox */
generate_full_aes_sbox_cnf_fcs() := block(
  [full16cs : clauses_f(full_fcs(16)), aes_sbox_cs :
  clauses_f(generate_full_aes_sbox_dnf_fcs())],
  cs_to_fcs(setdifference(full16cs, map(comp_sl,aes_sbox_cs))))$

/* Tests whether a full CNF clause-set represents the AES sbox */
test_CNF_aes_sbox(FF) := 
 is(cs_to_fcs(dualtreehittingcls_fcs(FF,dll_heuristics_first_real)) = generate_full_aes_sbox_dnf_fcs())$

/* Generation of a CNF hitting clause-set, given a heuristics h for
   a backtracking solver (without reduction) */
hitting_cnf_aes_sbox(h) := dualtreehittingcls_condensed_fcs(generate_full_aes_sbox_dnf_fcs(),h)$

/* Generate the full DNF form of a given permutation of an integer set. The 
   permutation (mapping) is given as a list "perm", where it is assumed the 
   mapping is from elements of the list "perm" after sorting, given the 
   natural order, to the corresponding elements in "perm" */
generate_full_int_perm_dnf_fcs(perm) := block(
  elements : sort(perm),
  /* MG : Is there already a library function for this (binary length of an
     integer)? */
  binLength : apply(max,map(
    lambda([a],if abs(a) = 0 then 1 else ceiling(log(a+1)/log(2))),perm)),
  cs_to_fcs(setify(map(
    lambda([a,b], binary_list_to_dnf_c(
      append(int2binlist(a,binLength),int2binlist(b,binLength)))),elements,
      perm)))
)$

/* Generate the full CNF form of a given permutation of an integer set. The 
   permutation (mapping) is given as a list "perm", where it is assumed the 
   mapping is from elements of the list "perm" after sorting, given the 
   natural order, to the corresponding elements in "perm" */
generate_full_int_perm_cnf_fcs(perm) := block(
  [fullncs, int_perm_dnf : generate_full_int_perm_dnf_fcs(perm)],
  fullncs : full_fcs(length(int_perm_dnf[1])),
  [int_perm_dnf[1],setdifference(clauses_f(fullncs),
    map(comp_sl,clauses_f(int_perm_dnf)))]
)$

/*!
\endhtmlonly
*/
