/* Oliver Kullmann, 8.5.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/GreenTao/testobjects/Asymptotics.mac

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/testobjects/Asymptotics.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/Asymptotics.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/tests/Asymptotics.mac")$

/* *********************************************
   * The formula from [Grosswald. Hagis, 1979] *
   *********************************************
*/

okltest_C_gh_fin(C_gh_fin);
okltest_C_gh_inf(C_gh_inf);
okltest_C_gh_inf_hp(C_gh_inf_hp);

/*!
\endhtmlonly
*/
