/* Oliver Kullmann, 22.4.2010 (Swansea) */
/* Copyright 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/RamseyTheory/Lisp/GreenTao/testobjects/Numbers.mac

Use by

oklib_load("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/testobjects/Numbers.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/Numbers.mac")$
oklib_include("OKlib/ComputerAlgebra/RamseyTheory/Lisp/GreenTao/tests/Numbers.mac")$

/* *********************
   * Green-Tao numbers *
   *********************
*/

okltest_greentao(greentao);

/*!
\endhtmlonly
*/
