/* Oliver Kullmann, 21.11.2009 (Swansea) */
/* Copyright 2009, 2010 Oliver Kullmann
This file is part of the OKlibrary. OKlibrary is free software; you can redistribute
it and/or modify it under the terms of the GNU General Public License as published by
the Free Software Foundation and included in this library; either version 3 of the
License, or any later version. */

/*!
  \file ComputerAlgebra/Satisfiability/Lisp/ConstraintProblems/tests/Domains.mac
  \brief Tests related to handling domains

Use by

oklib_load("OKlib/ComputerAlgebra/Satisfiability/Lisp/ConstraintProblems/tests/Domains.mac");

*/

/*!
\htmlonly
*/

oklib_include("OKlib/ComputerAlgebra/TestSystem/Lisp/Asserts.mac")$

kill(f)$


/* ********************
   * Helper functions *
   ********************
*/

okltest_dom_lengths(f) := (
  assert(f([{}]) = [0]),
  assert(f([{1}]) = [1]),
  assert(f([{2}]) = [1]),
  assert(f([{2,3},{},{1}]) = [2,0,1]),
  true)$

okltest_log_dom_lengths(f) := (
  assert(f([{1}]) = [0.0]),
  assert(f([{1},{1}]) = [0.0, 0.0]),
  /* XXX */
  true)$


/* ***************************
   * Heuristical evaluations *
   ***************************
*/

okltest_log_prod_dom_size(f) := (
  assert(f([]) = 0),
  assert(f([{1},{1}]) = 0),
  assert(f([{1,2},{1,2},{1}]) = log(4)),
  true)$


/*!
\endhtmlonly
*/
